unpackaged/main/default/objects/NCP_Credits__c/NCP_Credits__c.object-meta.xml
<CustomObject>
    <label>NCP Credit</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>NCP_Credit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCP Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NCP_Credits__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>FON_Credits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/FON_Session_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Session_Date__c</fullName>
    <label>Session Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending for Approval</fullName>
                <default>true</default>
                <label>Pending for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Audited - Approved</fullName>
            </value>
            <value>
                <fullName>Audited - Rejected</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
                <isActive>false</isActive>
                <label>Manual</label>
            </value>
            <value>
                <fullName>Not Considered</fullName>
                <isActive>false</isActive>
                <label>Not Considered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/FON_Session_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Session_Date__c</fullName>
    <label>Session Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reserved for future use.</description>
    <inlineHelpText>Reserved for future use.</inlineHelpText>
    <label>RESERVED</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>OrderApi__Contact__r.FirstName&amp;&#39; &#39;&amp;OrderApi__Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</description>
    <inlineHelpText>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Is_Closed__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>**SYSTEM FIELD - Identifies Sales Orders as ready for payment with a status of Unpaid and identifies Invoices with a status of Draft until it is posted and ready for payment.</description>
    <inlineHelpText>**System Calculated/Override** Checked when the Sales Order is closed. Sales Orders close automatically when paid in full by the customer, when a contract expires, or when a contract/recurring Sales Order is cancelled.</inlineHelpText>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Is_Proforma__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Proforma__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this field is checked, this sales order will be displayed in the community.</description>
    <inlineHelpText>When this field is checked, this sales order will be displayed in the community.</inlineHelpText>
    <label>Is Proforma</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Proforma_Invoice_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Proforma_Invoice_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>** SYSTEM FIELD ** Automatically checked when a proforma invoice email has been sent from this sales order.</description>
    <inlineHelpText>** SYSTEM FIELD ** Automatically checked when a proforma invoice email has been sent from this sales order.</inlineHelpText>
    <label>Proforma Invoice Email Sent</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Sales_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order_Status__c</fullName>
    <description>Status of the Sales Order</description>
    <formula>IF(ISPICKVAL(OrderApi__Posting_Entity__c,&#39;Invoice&#39;),
            IF(AND((OrderApi__Is_Cancelled__c), NOT(OrderApi__Is_Voided__c)),
            &#39;Cancelled&#39;,
            IF(AND(NOT(OrderApi__Is_Posted__c), NOT(OrderApi__Is_Voided__c)),
            &#39;Draft&#39;,
            IF(AND(OrderApi__Is_Closed__c, OrderApi__Is_Posted__c, NOT(OrderApi__Is_Voided__c),  TODAY() &gt; OrderApi__Due_Date__c, OrderApi__Balance_Due__c &gt; 0),
            &#39;Overdue&#39;,
            IF(AND( OrderApi__Balance_Due__c &gt; 0,OrderApi__Is_Closed__c, OrderApi__Is_Posted__c, NOT(OrderApi__Is_Voided__c)),
            &#39;Unpaid&#39;,
            IF(AND(OrderApi__Balance_Due__c &lt;= 0, NOT(OrderApi__Is_Voided__c),OrderApi__Is_Closed__c,OrderApi__Is_Posted__c),
            &#39;Paid&#39;,
            IF(OrderApi__Is_Voided__c,
            &#39;Voided&#39;,
            /*Default Value for Invoice*/
            &#39;&#39;)))))),
            /* Receipt Changes goes here */
            IF(ISPICKVAL(OrderApi__Posting_Entity__c,&#39;Receipt&#39;),
            IF(AND(NOT(OrderApi__Is_Closed__c), NOT(OrderApi__Is_Posted__c), NOT(OrderApi__Is_Voided__c)),
            &#39;Draft&#39;,
            IF(AND(OrderApi__Is_Closed__c, NOT(OrderApi__Is_Posted__c), NOT(OrderApi__Is_Voided__c),  TODAY() &gt; OrderApi__Due_Date__c, OrderApi__Balance_Due__c &gt; 0),
            &#39;Overdue&#39;,
            IF(AND(OrderApi__Is_Closed__c, NOT(OrderApi__Is_Posted__c), NOT(OrderApi__Is_Voided__c)),
            &#39;Unpaid&#39;,
            IF(AND(OrderApi__Balance_Due__c &lt;= 0, NOT(OrderApi__Is_Voided__c),OrderApi__Is_Closed__c,OrderApi__Is_Posted__c),
            &#39;Paid&#39;,
            IF(OrderApi__Is_Voided__c,
            &#39;Voided&#39;,
            /*Default Value for Receipt*/
            &#39;&#39;))))),
            &#39;&#39;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the item related to the sales order.</description>
    <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
    <label>Item</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/classes/FON_NewYearBatchJob.cls
/**
 * Created by nkopparthi on 11/16/20.
 */

global class FON_NewYearBatchJob implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        // collect the batches of records or objects to be passed to execute

        Integer year = system.today().year();
        String query = 'SELECT Id, Status__c, Contact_Name__c FROM NCP_Credits__c WHERE Contact_Name__c != null AND CALENDAR_YEAR(FON_Session_Date__c) < ' + year + ' AND Status__c = \'Pending for Approval\'';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<NCP_Credits__c> ncpList) {

        Set<Id> conIds = new Set<Id>();
        List<OrderApi__Sales_Order__c> lstSoIns = new List<OrderApi__Sales_Order__c>();
        List<OrderApi__Sales_Order_Line__c> lstSolIns = new List<OrderApi__Sales_Order_Line__c>();
        Id ItemID = [SELECT Id FROM OrderApi__Item__c WHERE Name = 'CE Credit Filing Fee' LIMIT 1].Id;
        
        List<OrderApi__Sales_Order_Line__c> currentSOLS = [Select Id, OrderApi__Item__c,OrderApi__Contact__c FROM OrderApi__Sales_Order_Line__c WHERE OrderApi__Item__r.Name = 'CE Credit Filing Fee' AND OrderApi__Sales_Order__r.OrderApi__Sales_Order_Status__c != 'Paid' AND OrderApi__Contact__c=:conIds];
        Map<String,Boolean> mapCONxSOL = new Map<String,Boolean>();
        
        if(currentSOLS.size()>0){
            for(OrderApi__Sales_Order_Line__c cSOL : currentSOLS){
                mapCONxSOL.put(cSOL.OrderApi__Contact__c,true);
            }
        }
        // process each batch of records default size is 200
            
            for(NCP_Credits__c ncp : ncpList) {
                conIds.add(ncp.Contact_Name__c);
            }
    
            for(Id cId : conIds){
                Boolean hasSOL = mapCONxSOL.get(cId);
                if(hasSOL != true){
                    OrderApi__Sales_Order__c so = new OrderApi__Sales_Order__c();
                    so.OrderApi__Contact__c = cId;
                    so.OrderApi__Is_Closed__c = true;
                    so.OrderApi__Is_Proforma__c = true;
                    so.OrderApi__Proforma_Invoice_Email_Sent__c = true;
                    lstSoIns.add(so);
                }
            }
    
            try {
    
                if(!lstSoIns.isEmpty()){
                    insert lstSoIns;
    
                    for(OrderApi__Sales_Order__c so : lstSoIns){
                        OrderApi__Sales_Order_Line__c sol = new OrderApi__Sales_Order_Line__c();
                        sol.OrderApi__Item__c = ItemID;
                        sol.OrderApi__Sales_Order__c = so.Id;
                        lstSolIns.add(sol);
                    }
    
                    if(!lstSolIns.isEmpty()){
                        insert lstSolIns;
                    }
                }
    
            } catch(Exception e) {
                System.debug(e);
            }
            

    }

    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations like sending email
    }
}