unpackaged/main/default/objects/NCP_Credits__c/NCP_Credits__c.object-meta.xml
<CustomObject>
    <label>NCP Credit</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>NCP_Credit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCP Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NCP_Credits__c/fields/FON_Total_Credits__c.field-meta.xml
<CustomField>
    <fullName>FON_Total_Credits__c</fullName>
    <formula>Credit_Value__c +  FON_Speaker_Credits__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Credits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Program_Term__c.field-meta.xml
<CustomField>
    <fullName>Program_Term__c</fullName>
    <label>Program Term</label>
    <referenceTo>ProgramApi__Program_Term__c</referenceTo>
    <relationshipLabel>NCP Credits</relationshipLabel>
    <relationshipName>NCP_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <label>Session Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person Training</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Workshop</fullName>
            </value>
            <value>
                <fullName>Conference Call</fullName>
            </value>
            <value>
                <fullName>e-Publication</fullName>
            </value>
            <value>
                <fullName>ECCHO Business Committee Meeting</fullName>
            </value>
            <value>
                <fullName>ECCHO Hosted Session</fullName>
            </value>
            <value>
                <fullName>ECCHO NCP Editorial Board</fullName>
            </value>
            <value>
                <fullName>ECCHO OPS Chairman</fullName>
            </value>
            <value>
                <fullName>ECCHO OPS Committee Meeting</fullName>
            </value>
            <value>
                <fullName>General Session</fullName>
            </value>
            <value>
                <fullName>In-Person Meeting</fullName>
            </value>
            <value>
                <fullName>Lunch-N-Learn</fullName>
            </value>
            <value>
                <fullName>NCP CE Workshop</fullName>
            </value>
            <value>
                <fullName>NCP Evaluation of Pilot Items</fullName>
            </value>
            <value>
                <fullName>NCP Guide Program</fullName>
            </value>
            <value>
                <fullName>NCP Partner Training</fullName>
            </value>
            <value>
                <fullName>OnDemand</fullName>
            </value>
            <value>
                <fullName>Roundtable</fullName>
            </value>
            <value>
                <fullName>Seminar</fullName>
            </value>
            <value>
                <fullName>User Group</fullName>
            </value>
            <value>
                <fullName>Web Based Training</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Series</fullName>
            </value>
            <value>
                <fullName>Publication</fullName>
            </value>
            <value>
                <fullName>CD Rom</fullName>
            </value>
            <value>
                <fullName>Teleconference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending for Approval</fullName>
                <default>true</default>
                <label>Pending for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Audited - Approved</fullName>
            </value>
            <value>
                <fullName>Audited - Rejected</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
                <isActive>false</isActive>
                <label>Manual</label>
            </value>
            <value>
                <fullName>Not Considered</fullName>
                <isActive>false</isActive>
                <label>Not Considered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/ProgramApi__Program_Profile__c.object-meta.xml
<CustomObject>
    <description>This object maintains a single persona for each participant in a given program.</description>
    <label>Program Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Program Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/Allowed_Credits__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Credits__c</fullName>
    <label>Allowed Credits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/Allowed_Workshops__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Workshops__c</fullName>
    <label>Allowed Workshops</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_End_Date__c</fullName>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_Start_Date__c</fullName>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Total_Credits__c.field-meta.xml
<CustomField>
    <fullName>FON_Total_Credits__c</fullName>
    <label>Total Credits (Full)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Contact to program profile; a Contact has only one profile for a program</description>
    <inlineHelpText>Identifies Contact to program profile; a Contact has only one profile for a program</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Status__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Status__c</fullName>
    <description>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</description>
    <inlineHelpText>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Track</fullName>
                <default>true</default>
                <label>On Track</label>
            </value>
            <value>
                <fullName>Cautionary</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending Revocation</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/ProgramApi__Program_Term__c.object-meta.xml
<CustomObject>
    <description>This object establishes the length of time given to complete tasks.</description>
    <label>Program Term</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Program Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/FON_Allowed_Credits__c.field-meta.xml
<CustomField>
    <fullName>FON_Allowed_Credits__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Allowed Credits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/FON_Allowed_Workshops__c.field-meta.xml
<CustomField>
    <fullName>FON_Allowed_Workshops__c</fullName>
    <defaultValue>2</defaultValue>
    <label>Allowed Workshops</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/FON_Credits_Acquired__c.field-meta.xml
<CustomField>
    <fullName>FON_Credits_Acquired__c</fullName>
    <inlineHelpText>Approved Credits</inlineHelpText>
    <label>Approved Credits</label>
    <summarizedField>NCP_Credits__c.FON_Total_Credits__c</summarizedField>
    <summaryFilterItems>
        <field>NCP_Credits__c.Status__c</field>
        <operation>equals</operation>
        <value>Approved, Audited - Approved</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>NCP_Credits__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Audited - Rejected</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>NCP_Credits__c.Session_Type__c</field>
        <operation>notEqual</operation>
        <value>NCP CE Workshop</value>
    </summaryFilterItems>
    <summaryForeignKey>NCP_Credits__c.Program_Term__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/FON_Workshops_Attended2__c.field-meta.xml
<CustomField>
    <fullName>FON_Workshops_Attended2__c</fullName>
    <label>Workshops Attended</label>
    <summaryFilterItems>
        <field>NCP_Credits__c.Session_Type__c</field>
        <operation>equals</operation>
        <value>NCP CE Workshop</value>
    </summaryFilterItems>
    <summaryForeignKey>NCP_Credits__c.Program_Term__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/FON_Workshops_Attended__c.field-meta.xml
<CustomField>
    <fullName>FON_Workshops_Attended__c</fullName>
    <label>Workshops Attended</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__End_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__End_Date__c</fullName>
    <description>Identifies the term end date; Date all goals must be completed to successfully complete program</description>
    <inlineHelpText>Identifies the term end date; Date all goals must be completed to successfully complete program</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Profile__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SYSTEM. Relates the program profile to the term</description>
    <inlineHelpText>SYSTEM. Relates the program profile to the term</inlineHelpText>
    <label>Program Profile</label>
    <referenceTo>ProgramApi__Program_Profile__c</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Start_Date__c</fullName>
    <description>Identifies the term start date</description>
    <inlineHelpText>Identifies the term start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/Total_Credits__c.field-meta.xml
<CustomField>
    <fullName>Total_Credits__c</fullName>
    <inlineHelpText>All Entered Credits Regardless of Status</inlineHelpText>
    <label>Total Credits Entered</label>
    <summarizedField>NCP_Credits__c.FON_Total_Credits__c</summarizedField>
    <summaryFilterItems>
        <field>NCP_Credits__c.Session_Type__c</field>
        <operation>notEqual</operation>
        <value>NCP CE Workshop</value>
    </summaryFilterItems>
    <summaryForeignKey>NCP_Credits__c.Program_Term__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/Workshops_Approved__c.field-meta.xml
<CustomField>
    <fullName>Workshops_Approved__c</fullName>
    <label>Workshops Approved</label>
    <summaryFilterItems>
        <field>NCP_Credits__c.Session_Type__c</field>
        <operation>equals</operation>
        <value>NCP CE Workshop</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>NCP_Credits__c.Status__c</field>
        <operation>equals</operation>
        <value>Approved, Audited</value>
    </summaryFilterItems>
    <summaryForeignKey>NCP_Credits__c.Program_Term__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/classes/Fon_Creditstatus.cls
Public without sharing Class Fon_Creditstatus{    
    
    /*
     * Name : fetchCurrentlogged
     * Des  : this method will be used to current login user contact id
     **/
    private static User fetchCurrentlogged(){        
        List<User> userList = [SELECT Id,
                                        FirstName, 
                                        LastName, 
                                        contactId 
                                    FROM User 
                                    WHERE Id =:UserInfo.getUserId()];
        return userList[0];
    }
    
    
    // this method will be used to found Program term record id based on login user contact.
    private static List<ProgramApi__Program_Profile__c> fetchProgramProfile(){
        string loginUserContactId = fetchCurrentlogged().contactId; 
        return [SELECT Id,
                        FON_Program_Start_Date__c,
                        FON_Program_End_Date__c,
                        ProgramApi__Status__c,                        
                        Allowed_Credits__c,
                        Allowed_Workshops__c,
                        (SELECT Id,FON_Credits_Acquired__c,
                                FON_Workshops_Attended2__c,
                                FON_Allowed_Credits__c,
                                FON_Allowed_Workshops__c,
                                ProgramApi__Start_Date__c,
                                ProgramApi__End_Date__c,
                                Workshops_Approved__c,
                                FON_Workshops_Attended__c,
                                Total_Credits__c
                            FROM ProgramApi__Program_Terms__r)
                    FROM ProgramApi__Program_Profile__c
                    WHERE ProgramApi__Contact__c =: loginUserContactId
                    order by FON_Program_End_Date__c desc];
        
    }
    
    
    private static map<id,List<NCP_Credits__c>> fetchCredits(set<id> setProgramTermIds){        
        // this will store the if of the program term and its related crdits
        map<id,List<NCP_Credits__c>> mapTermCredit = new map<id,List<NCP_Credits__c>>();
        
        // for each credits
        for(NCP_Credits__c credits : [SELECT Id,
                                              Status__c,
                                              FON_Total_Credits__c,
                                              Program_Term__r.FON_Workshops_Attended2__c,
                                              Session_Type__c,
                                              Program_Term__c,
                                              Credit_Value__c,
                                      		  FON_Audit_Adjusted_Value__c
                                          FROM NCP_Credits__c
                                          WHERE Program_Term__c IN :setProgramTermIds
                                          //AND (Status__c = 'Approved' 
                                          //  OR Status__c = 'Pending for Approval' 
                                          //  OR Session_Type__c = 'Workshop')
                                     ]){
            
            // saving the credits
            List<NCP_Credits__c> lstCredits = new List<NCP_Credits__c>{credits};
            
            // checking if the program term is already present and update the list
            if(mapTermCredit.containsKey(credits.Program_Term__c)){
                lstCredits.addAll(mapTermCredit.get(credits.Program_Term__c));
            }
            
            // update the map
            mapTermCredit.put(credits.Program_Term__c,lstCredits);
        }  
        return mapTermCredit;        
    }
    
    public static List<ProgramApi__Program_Profile__c> currentProfProfile(string loginUserContactId){
        return  [SELECT Id,
                        FON_Program_Start_Date__c,
                        FON_Program_End_Date__c,
                        ProgramApi__Status__c,
                        Allowed_Credits__c,
                        Allowed_Workshops__c
                 FROM ProgramApi__Program_Profile__c
                 WHERE ProgramApi__Contact__c =: loginUserContactId                     
                 AND ProgramApi__Status__c = 'On Track'
                 order by createdDate desc LIMIT 1];
    }
    
    @AuraEnabled
    public static OnLoadWrapper fetchonLoadWrapper(){
        
        Integer allCredits = Integer.valueOf(System.Label.Allowed_Credits_for_1_year_NCP);
        Integer allWorkshop = Integer.valueOf(System.Label.Allowed_Workshops_in_1_year_NCP);
        
        // making instance return wrapper
        OnLoadWrapper onloadObj = new OnLoadWrapper();
        
        // getting user record
        onloadObj.userDetails = fetchCurrentlogged();
        
        // this will save the ids of the program term ids to get the NCP credits
        set<id> setPrgTermIds = new set<id>();
        
        // getting program profile
        List<ProgramApi__Program_Profile__c> lstProgProfile = fetchProgramProfile();
        system.debug('\n--lstProgProfile--'+lstProgProfile);
        
        // getting the current prof profile for table 1
        List<ProgramApi__Program_Profile__c> currentProgProfile = currentProfProfile(onloadObj.userDetails.ContactId);
        system.debug('\n--currentProgProfile--'+currentProgProfile);
        
        if(currentProgProfile.isEmpty()
            && !lstProgProfile.isEmpty()){
            currentProgProfile.add(lstProgProfile[0]);
        }
        
        
        // if current progprom profile is present
        if(!currentProgProfile.isEmpty()){
            // details for the first table in the component
            if(currentProgProfile[0].FON_Program_Start_Date__c != null){
                onloadObj.startYear = currentProgProfile[0].FON_Program_Start_Date__c.year();
            }
            
            if(currentProgProfile[0].FON_Program_End_Date__c != null){
                onloadObj.endYear = currentProgProfile[0].FON_Program_End_Date__c.year();
            }
            
            
            if(currentProgProfile[0].Allowed_Workshops__c != null){
                onloadObj.WCreditsRequired = currentProgProfile[0].Allowed_Workshops__c;
            }
            
            if(currentProgProfile[0].Allowed_Credits__c != null){
                onloadObj.CreditsRequired = currentProgProfile[0].Allowed_Credits__c;
            }
        }
         
        
        // for each proggram profile
        for(ProgramApi__Program_Profile__c progProfile : lstProgProfile){
            
            // checking if the program term is present
            if(progProfile.ProgramApi__Program_Terms__r != null){
                
                // for reach program term save the ids
                for(ProgramApi__Program_Term__c progTerm : progProfile.ProgramApi__Program_Terms__r){
                    setPrgTermIds.add(progTerm.Id);
                }
            }
        }
        system.debug('\n--setPrgTermIds--'+setPrgTermIds);
        
        // code to get the credits for the program term
        //map<id,List<NCP_Credits__c>> mapTermCredit = fetchCredits(setPrgTermIds); 
        
        Fon_CEInfoCntrl.NCPCreditDetails creditRec = Fon_CEInfoCntrl.fetchNCPCredit();
        system.debug('\n--creditRec--'+creditRec);
        
        
        // setitng the terms Ids
        set<string> setTermIdsNew = new set<string>();
        
        // getting the credits based upon logged in user
        Fon_CEInfoCntrl.NCPCreditDetails creditRec1 = Fon_CEInfoCntrl.fetchNCPCredit();
        
        // for approved non workshop
        for(NCP_Credits__c credit : creditRec1.lstApprovedNCPCredits){            
            setTermIdsNew.add(credit.Program_Term__c);
        }
        
        // for pending non workshop
        for(NCP_Credits__c credit : creditRec1.lstNonApprovedNCPCredits){
            setTermIdsNew.add(credit.Program_Term__c);
        }
        
        
        // for workshop
        for(NCP_Credits__c credit : creditRec1.lstNonApprovedNCPCredits){
            setTermIdsNew.add(credit.Program_Term__c);            
        }
        system.debug('\n--setTermIdsNew--'+setTermIdsNew);
        map<id,List<NCP_Credits__c>> mapTermCredit = fetchCredits(setPrgTermIds); 
        
        // if prog profile is present
        if(!lstProgProfile.isEmpty()){
            
            // initaize the prog profile details
            onloadObj.lstProfileWrapper = new List<ProfWrapper>();
            
            // for each program profile
            for(ProgramApi__Program_Profile__c progProfile : lstProgProfile){
                
                // creatng the instance of prog profile wrapper
                ProfWrapper progProfileObj = new ProfWrapper();
                progProfileObj.progProfile = progProfile;
                progProfileObj.progTerms = new List<programTermWrapper>();
                
                // this will save the credits for the prog profile
                List<NCP_Credits__c> lstCredits = new List<NCP_Credits__c>();
                
                // getting related Program Term
                if(progProfile.ProgramApi__Program_Terms__r != null){
                    
                    // for reach program term 
                    for(ProgramApi__Program_Term__c progTerm : progProfile.ProgramApi__Program_Terms__r){
                        
                        // saving the list of credits
                        List<NCP_Credits__c> lstTemp = new List<NCP_Credits__c>();
                        
                        // checking if the have the credits
                        if(mapTermCredit.containsKey(progTerm.Id)){
                            //lstTemp = mapTermCredit.get(progTerm.Id);
                            List<NCP_Credits__c> cr = mapTermCredit.get(progTerm.Id);
                            if(cr.size()>0){
                                for(NCP_Credits__c credit : cr){
                                    if(credit.Status__c == 'Approved' &&  credit.Session_Type__c != 'NCP CE Workshop'){
                                    //if(credit.Session_Type__c != 'NCP CE Workshop'){
                                    	lstTemp.add(credit);
                                    }
                                }
                            }
                            lstCredits.addAll(lstTemp);
                        }
                        
                        
                        
                        // making wrapper list
                        progProfileObj.progTerms.add(new programTermWrapper(progTerm,lstTemp));
                        
                    }
                }
                system.debug('\n--lstCredits--'+lstCredits);                     
                
                
                // for each term get the attended workshop
                for(programTermWrapper progTerm : progProfileObj.progTerms){   
                    if(progTerm.progTerm.Workshops_Approved__c != null){
                        progProfileObj.approvedWorkCredits += progTerm.progTerm.Workshops_Approved__c;
                        if(allWorkshop > progTerm.progTerm.Workshops_Approved__c){
                        	progProfileObj.calculatedWorkCredits += progTerm.progTerm.Workshops_Approved__c;
                        }else{
                            progProfileObj.calculatedWorkCredits += allWorkshop;
                        }
                    }
                    
                    if(progTerm.progTerm.FON_Workshops_Attended2__c != null){
                        progProfileObj.AllWorkCredits += progTerm.progTerm.FON_Workshops_Attended2__c;
                    }
                }

                for(programTermWrapper progTerm : progProfileObj.progTerms){

                    if(progTerm.progTerm.FON_Credits_Acquired__c != null){
                        // this is the original approved Credits as of july 2024
                        progProfileObj.approvedCredits += progTerm.progTerm.FON_Credits_Acquired__c;
                        
                        if(allCredits > progTerm.progTerm.FON_Credits_Acquired__c){
                        	progProfileObj.calculatedCredits += progTerm.progTerm.FON_Credits_Acquired__c;
                        }else{
                            progProfileObj.calculatedCredits += allCredits;
                        }
                        
                    }

                    if(progTerm.progTerm.Total_Credits__c != null)
                        progProfileObj.AllCredits += progTerm.progTerm.Total_Credits__c;
                }
                
               
                // iteration for each credits
                for(NCP_Credits__c credit : lstCredits){
                    
                    // if the record is approved and non workshop
                    //if(credit.Session_Type__c != 'NCP CE Workshop'){
                            if (credit.FON_Audit_Adjusted_Value__c != null && !String.isEmpty(String.valueOf(credit.FON_Audit_Adjusted_Value__c).trim())) {
                                progProfileObj.adjustedCredits += credit.FON_Audit_Adjusted_Value__c;
                            } else {
                                progProfileObj.adjustedCredits += credit.Credit_Value__c;
                            }
                    //   }

                }
                
                
                // adding obj to list
                system.debug('\n--progProfileObj--'+progProfileObj);
                onloadObj.lstProfileWrapper.add(progProfileObj);
                system.debug('\n--onloadObj--'+onloadObj);
            }
                      
        }
        return onloadObj;  
    }
        
    
    // wrapper classes
    public class OnLoadWrapper{
        @AuraEnabled public User userDetails {get;set;}
        @AuraEnabled public integer startYear {get;set;}
        @AuraEnabled public integer endYear {get;set;}
        @AuraEnabled public decimal CreditsRequired {get;set;}
        @AuraEnabled public decimal WCreditsRequired {get;set;}
        @AuraEnabled public ProgramApi__Program_Profile__c lastestProgProfile {get;set;}        
        @AuraEnabled public List<ProfWrapper> lstProfileWrapper {get;set;}        
    }
    
    public Class ProfWrapper{
        @AuraEnabled public ProgramApi__Program_Profile__c progProfile {get;set;}
        @AuraEnabled public List<programTermWrapper> progTerms {get;set;}
        @AuraEnabled public integer startYear {get;set;}
        @AuraEnabled public integer endYear {get;set;}
        
        @AuraEnabled public Decimal approvedCredits {get;set;}
        @AuraEnabled public Decimal adjustedCredits {get;set;}
         @AuraEnabled public Decimal calculatedCredits {get;set;}
        @AuraEnabled public Decimal approvedWorkCredits {get;set;}
        @AuraEnabled public Decimal calculatedWorkCredits {get;set;}
        @AuraEnabled public Decimal AllCredits {get;set;}
        @AuraEnabled public Decimal AllWorkCredits {get;set;}  
        
        // constructor
        public ProfWrapper(){
            this.approvedCredits = 0;
            this.adjustedCredits = 0;
            this.approvedWorkCredits = 0;
            this.calculatedCredits = 0;
            this.calculatedWorkCredits = 0;
            this.AllCredits = 0;
            this.AllWorkCredits = 0;
            this.progProfile = new ProgramApi__Program_Profile__c();
        }
        
    }
    
    public class programTermWrapper{
        @AuraEnabled public ProgramApi__Program_Term__c progTerm {get;set;}
        @AuraEnabled public Decimal approvedCredits {get;set;}
        @AuraEnabled public Decimal adjCredits {get;set;}
        @AuraEnabled public Decimal approvedWorkCredits {get;set;}
        @AuraEnabled public Decimal AllCredits {get;set;}
        @AuraEnabled public Decimal AllWorkCredits {get;set;}  
        
        // constructor
        public programTermWrapper(ProgramApi__Program_Term__c progTerm, List<NCP_Credits__c> lstCredits){
            this.progTerm = progTerm;
            this.approvedCredits = 0;
            this.adjCredits = 0;
            this.approvedWorkCredits = 0;
            this.AllCredits = 0;
            this.AllWorkCredits = 0;
            
            // code for making total for each prg profile            
            for(NCP_Credits__c credit : lstCredits){
                
                // if the record is approved and non workshop
                if(credit.Status__c == 'Approved'
                   &&  credit.Session_Type__c != 'NCP CE Workshop'){
                       if(credit.Credit_Value__c != null)
                           this.approvedCredits += credit.Credit_Value__c;
                       if (credit.FON_Audit_Adjusted_Value__c != null && !String.isEmpty(String.valueOf(credit.FON_Audit_Adjusted_Value__c).trim())) {
                            this.adjCredits += credit.FON_Audit_Adjusted_Value__c;
                        } else {
                            this.adjCredits += credit.Credit_Value__c;
                        }
                }



                
                // saving the credtis for all
                if(credit.Status__c == 'Pending for Approval'
                   &&  credit.Session_Type__c != 'NCP CE Workshop'){
                       if(credit.Credit_Value__c != null)
                           this.AllCredits += credit.Credit_Value__c;
                }
                
                // saving the workshop for all
                if(credit.Status__c == 'Approved'
                   &&  credit.Session_Type__c == 'NCP CE Workshop'){
                       if(credit.Credit_Value__c != null)
                           this.approvedWorkCredits += credit.Credit_Value__c;
                }
                
                // saving the workshop for all
                if(credit.Status__c == 'Pending for Approval'
                    && credit.Session_Type__c == 'NCP CE Workshop'){
                       if(credit.Credit_Value__c != null)
                           this.AllWorkCredits += credit.Credit_Value__c;
                }                
            }
        }
    }
     
}