unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label># Application</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>Contact__r.FirstName&amp;&#39; &#39;&amp;Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/NCP_Credits__c.object-meta.xml
<CustomObject>
    <label>NCP Credit</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>NCP_Credit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCP Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NCP_Credits__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>FON_Credits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/FON_Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>FON_Provider_Name__c</fullName>
    <label>Provider Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/NCP_Session__c.field-meta.xml
<CustomField>
    <fullName>NCP_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCP Session</label>
    <referenceTo>NCP_Sessions__c</referenceTo>
    <relationshipLabel>NCP Credits</relationshipLabel>
    <relationshipName>NCP_Credits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Program_Term__c.field-meta.xml
<CustomField>
    <fullName>Program_Term__c</fullName>
    <label>Program Term</label>
    <referenceTo>ProgramApi__Program_Term__c</referenceTo>
    <relationshipLabel>NCP Credits</relationshipLabel>
    <relationshipName>NCP_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending for Approval</fullName>
                <default>true</default>
                <label>Pending for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Audited - Approved</fullName>
            </value>
            <value>
                <fullName>Audited - Rejected</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
                <isActive>false</isActive>
                <label>Manual</label>
            </value>
            <value>
                <fullName>Not Considered</fullName>
                <isActive>false</isActive>
                <label>Not Considered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/NCP_Sessions__c.object-meta.xml
<CustomObject>
    <label>NCP Session</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCP Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NCP Sessions</relationshipLabel>
    <relationshipName>NCP_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>NCP Sessions</relationshipLabel>
    <relationshipName>NCP_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>NCP Sessions</relationshipLabel>
    <relationshipName>NCP_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Minutes_EDU_Submitting__c.field-meta.xml
<CustomField>
    <fullName>Minutes_EDU_Submitting__c</fullName>
    <label>Minutes EDU (Submitting)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/ProgramApi__Program_Profile__c.object-meta.xml
<CustomObject>
    <description>This object maintains a single persona for each participant in a given program.</description>
    <label>Program Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Program Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Account__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</description>
    <inlineHelpText>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Contact to program profile; a Contact has only one profile for a program</description>
    <inlineHelpText>Identifies Contact to program profile; a Contact has only one profile for a program</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/ProgramApi__Program_Term__c.object-meta.xml
<CustomObject>
    <description>This object establishes the length of time given to complete tasks.</description>
    <label>Program Term</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Program Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Active__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifies active term; Term end date is in the future</description>
    <inlineHelpText>Identifies active term; Term end date is in the future</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__End_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__End_Date__c</fullName>
    <description>Identifies the term end date; Date all goals must be completed to successfully complete program</description>
    <inlineHelpText>Identifies the term end date; Date all goals must be completed to successfully complete program</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Profile__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SYSTEM. Relates the program profile to the term</description>
    <inlineHelpText>SYSTEM. Relates the program profile to the term</inlineHelpText>
    <label>Program Profile</label>
    <referenceTo>ProgramApi__Program_Profile__c</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Start_Date__c</fullName>
    <description>Identifies the term start date</description>
    <inlineHelpText>Identifies the term start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/Fon_CEInfoCntrl_Test.cls
@isTest
public class Fon_CEInfoCntrl_Test {
    
    @testSetup static void setupmt() {
        
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('ECCHO Account').getRecordTypeId();
        
        Account acc = new Account(recordtypeId = devRecordTypeId,Name = 'Test Acc');
        insert acc;
        
        Contact con = new contact(LastName='Test Con',AccountId = acc.Id);
        insert con;
         
       
        
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Fonteva Chatter Manager Community Login User'].Id,
            LastName = 'last',
            Email = 'puser000@amamama.com',
            Username = 'puser000@amamama.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ContactId = con.Id
        );
        
        insert u;
        
        ProgramApi__Program_Profile__c ppp = new ProgramApi__Program_Profile__c();
        ppp.ProgramApi__Account__c = acc.Id;
        ppp.ProgramApi__Contact__c = con.Id;
        insert ppp;
        
        
        ProgramApi__Program_Term__c ppt = new ProgramApi__Program_Term__c();
        ppt.ProgramApi__Profile__c = ppp.Id;
        ppt.ProgramApi__Start_Date__c = System.today();
        ppt.ProgramApi__End_Date__c = System.today().addMonths(5);
        ppt.ProgramApi__Active__c = true;
        ppt.Contact__c = con.Id;
        insert ppt;
        
        NCP_Credits__c ncp = new NCP_Credits__c();
        ncp.Program_Term__c = ppt.Id;
        ncp.Contact_Name__c = con.Id;
        ncp.Status__c = 'Pending for Approval';
        insert ncp;
        
        
        
        Application__c app = new Application__c();
        app.Account__c = acc.Id;
        app.Contact__c = con.Id;
        insert app;
        
        NCP_Sessions__c ncs = new NCP_Sessions__c();
        ncs.Name = 'Test session';
        ncs.Account__c = acc.Id;
        ncs.Contact__c = con.Id;
        ncs.Application__c = app.Id;
        ncs.Status__c = 'Approved';
        ncs.Session_Date__c = System.today();
        ncs.Minutes_EDU_Submitting__c = '2500';
        insert ncs;
        
        NCP_Credits__c ncpc = new NCP_Credits__c();
        ncpc.Program_Term__c = ppt.Id;
        ncpc.Contact_Name__c = con.Id;
        ncpc.NCP_Session__c = ncs.Id;
        ncpc.Status__c = 'Approved';
        insert ncpc;
        
        Blob b = Blob.valueOf('Test Data');
    	
    	Attachment attachment = new Attachment();
    	attachment.ParentId = ncs.Id;
    	attachment.Name = 'Test Attachment for Parent';
    	attachment.Body = b;
        insert attachment;
    }
    
    @isTest
    public static void fetchCurrentlogged_Test(){
        User u = [SELECT Id FROM User WHERE Email = 'puser000@amamama.com'];
        NCP_Sessions__c ncoSess = [SELECT id,Contact__c FROM NCP_Sessions__c WHERE Name='Test session'];
        Attachment att = [SELECT Id from Attachment];
        NCP_Credits__c ncp = [SELECT Id,FON_Provider_Name__c,NCP_Session__c,
                              NCP_Session__r.Session_Date__c,NCP_Session__r.Description__c
                              FROM NCP_Credits__c 
                              WHERE Status__c = 'Approved'
                              LIMIT 1];
        System.runAs(u) {
            Fon_CEInfoCntrl.fetchCurrentlogged();
            Fon_CEInfoCntrl.fetchNCPCredit();
            Fon_CEInfoCntrl.fecthApprovedSession();
            Fon_CEInfoCntrl.createNCP_CreditRec(ncoSess.Id,'serialtext',/* System.today(),*/System.today(),false,'Test provider',System.today());
            Fon_CEInfoCntrl.getPickListValuesIntoList('NCP_Sessions__c','Status__c');
            Fon_CEInfoCntrl.saveChunk(ncoSess.Id,'test','tt','testing','');
             Fon_CEInfoCntrl.saveChunk(ncoSess.Id,'test','tt','testing',att.Id);
            
            Fon_CEInfoCntrl.manaualCreditRecDetails wrap = new Fon_CEInfoCntrl.manaualCreditRecDetails();
            wrap.audityear = '2020';
            wrap.entryDate = system.today();
            wrap.instructor = 'ty';
            wrap.instructortitle = 'rg';
            wrap.minuteofEDU = 20;
            wrap.providerName = 'Test';
            wrap.sessionDate = System.today();
            wrap.proiderphORemail = 'test@testing.com';
            wrap.speakerCheckbox = false;
            String ncpJson = JSON.serialize(ncp);
            try{
                Fon_CEInfoCntrl.createNCPCreditManaulRec(wrap);
            }catch(exception ex){
                
            }
            
            Fon_CEInfoCntrl.updateNCPRecords(ncpJson);
            Fon_CEInfoCntrl.deleteNCPRec(ncp.Id);
        }
    }
    
    @isTest
    static void createNotes() {
        Test.startTest();
        User u = [SELECT Id FROM User WHERE Email = 'puser000@amamama.com'];
        System.runAs(u){
        Fon_CEInfoCntrl.createNotes('TEST' ,'test');
        }
        Test.stopTest();
    }
    
}