unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label># Application</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>Contact__r.FirstName&amp;&#39; &#39;&amp;Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CandidateId__c/CandidateId__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Candidate Id</label>
</CustomObject>

unpackaged/main/default/objects/CandidateId__c/fields/Candidate_Id_Number__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Id_Number__c</fullName>
    <label>Candidate Id Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CandidateId__c/fields/Candidate_Id_Text__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Id_Text__c</fullName>
    <label>Candidate Id Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FON_Candidate_Id_Generated_On__c.field-meta.xml
<CustomField>
    <fullName>FON_Candidate_Id_Generated_On__c</fullName>
    <label>Candidate Id Generated On</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FON_NCP_Candidate_ID__c.field-meta.xml
<CustomField>
    <fullName>FON_NCP_Candidate_ID__c</fullName>
    <inlineHelpText>*System Generated* Candidate ID for exam registration. Always 11 digits long. Infromation coming from the Attendee record</inlineHelpText>
    <label>NCP Candidate ID</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/NCP_Credits__c.object-meta.xml
<CustomObject>
    <label>NCP Credit</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>NCP_Credit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCP Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NCP_Credits__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>FON_Credits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/FON_Session_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Session_Date__c</fullName>
    <label>Session Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <label>Session Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person Training</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Workshop</fullName>
            </value>
            <value>
                <fullName>Conference Call</fullName>
            </value>
            <value>
                <fullName>e-Publication</fullName>
            </value>
            <value>
                <fullName>ECCHO Business Committee Meeting</fullName>
            </value>
            <value>
                <fullName>ECCHO Hosted Session</fullName>
            </value>
            <value>
                <fullName>ECCHO NCP Editorial Board</fullName>
            </value>
            <value>
                <fullName>ECCHO OPS Chairman</fullName>
            </value>
            <value>
                <fullName>ECCHO OPS Committee Meeting</fullName>
            </value>
            <value>
                <fullName>General Session</fullName>
            </value>
            <value>
                <fullName>In-Person Meeting</fullName>
            </value>
            <value>
                <fullName>Lunch-N-Learn</fullName>
            </value>
            <value>
                <fullName>NCP CE Workshop</fullName>
            </value>
            <value>
                <fullName>NCP Evaluation of Pilot Items</fullName>
            </value>
            <value>
                <fullName>NCP Guide Program</fullName>
            </value>
            <value>
                <fullName>NCP Partner Training</fullName>
            </value>
            <value>
                <fullName>OnDemand</fullName>
            </value>
            <value>
                <fullName>Roundtable</fullName>
            </value>
            <value>
                <fullName>Seminar</fullName>
            </value>
            <value>
                <fullName>User Group</fullName>
            </value>
            <value>
                <fullName>Web Based Training</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Series</fullName>
            </value>
            <value>
                <fullName>Publication</fullName>
            </value>
            <value>
                <fullName>CD Rom</fullName>
            </value>
            <value>
                <fullName>Teleconference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending for Approval</fullName>
                <default>true</default>
                <label>Pending for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Audited - Approved</fullName>
            </value>
            <value>
                <fullName>Audited - Rejected</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
                <isActive>false</isActive>
                <label>Manual</label>
            </value>
            <value>
                <fullName>Not Considered</fullName>
                <isActive>false</isActive>
                <label>Not Considered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/FON_Session_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Session_Date__c</fullName>
    <label>Session Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reserved for future use.</description>
    <inlineHelpText>Reserved for future use.</inlineHelpText>
    <label>RESERVED</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>OrderApi__Contact__r.FirstName&amp;&#39; &#39;&amp;OrderApi__Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</description>
    <inlineHelpText>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Is_Posted__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Posted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked all Invoices related to the Sales Order will post an receivable transaction to the GL.</description>
    <inlineHelpText>When checked all Invoices related to the Sales Order will post an receivable transaction to the GL.</inlineHelpText>
    <label>Is Posted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/Event_Is_NCP_Exam__c.field-meta.xml
<CustomField>
    <fullName>Event_Is_NCP_Exam__c</fullName>
    <formula>EventApi__Event__r.Is_NCP_Exam__c</formula>
    <label>Event Is NCP Exam</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <formula>EventApi__Event__r.Name</formula>
    <label>Event Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Is_Posted__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Posted__c</fullName>
    <description>When checked all Invoices related to the Sales Order will post an receivable transaction to the GL.</description>
    <formula>OrderApi__Sales_Order__r.OrderApi__Is_Posted__c</formula>
    <inlineHelpText>When checked all Invoices related to the Sales Order will post an receivable transaction to the GL.</inlineHelpText>
    <label>Is Posted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the item related to the sales order.</description>
    <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
    <label>Item</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/classes/FON_SalesOrderService.cls
/**
* Created by nkopparthi on 11/16/20.
*/

public without sharing class FON_SalesOrderService {
    
    public static void approveOldCredits(List<OrderApi__Sales_Order__c> records, Map<Id,OrderApi__Sales_Order__c> oldRecords) {
        
        Set<Id> conIds = new Set<Id>();
        List<Id> soIds = new List<Id>();
        List<OrderApi__Sales_Order__c> soList = new List<OrderApi__Sales_Order__c>();
        List<NCP_Credits__c> ncpCredits = new List<NCP_Credits__c>();
        List<NCP_Credits__c> ncpCreditsUpd = new List<NCP_Credits__c>();
        Id ItemID = [SELECT Id FROM OrderApi__Item__c WHERE Name = 'CE Credit Filing Fee' LIMIT 1].Id;
        
        for(OrderApi__Sales_Order__c so :records){
            if(so.OrderApi__Is_Posted__c == TRUE && oldRecords.get(so.Id).OrderApi__Is_Posted__c == FALSE){
                soIds.add(so.Id);
            }
        }
        
        soList = [
            SELECT  Id,
            OrderApi__Contact__c,
            (SELECT Id,
             OrderApi__Item__c
             FROM OrderApi__Sales_Order_Lines__r)
            FROM OrderApi__Sales_Order__c
            WHERE Id IN :soIds
        ];
        
        for(OrderApi__Sales_Order__c so : soList){
            for(OrderApi__Sales_Order_Line__c sol : so.OrderApi__Sales_Order_Lines__r){
                if(sol.OrderApi__Item__c == ItemID){
                    conIds.add(so.OrderApi__Contact__c);
                }
            }
        }
        
        ncpCredits = [
            SELECT  Id,
            FON_Session_Date__c,
            Status__c
            FROM NCP_Credits__c
            WHERE Contact_Name__c IN :conIds
            AND Status__c = 'Pending for Approval'
            AND Session_Type__c != 'NCP CE Workshop'
        ];
        
        for(NCP_Credits__c ncp : ncpCredits){
            if(ncp.FON_Session_Date__c.year() == system.today().year() - 1){
                ncp.Status__c = 'Approved';
                ncpCreditsUpd.add(ncp);
            }
        }
        
        if(!ncpCreditsUpd.isEmpty()){
            update ncpCreditsUpd;
        }
        
    }
    
    /***
*  This method will be called on update of the SO and if the is posted is made from false then it will query the
*  Related application and make the field is paid to true
**/
    public static void ApproveApplications(List<OrderApi__Sales_Order__c> records, Map<Id,OrderApi__Sales_Order__c> oldRecords) {
        List<Application__c> applicationList = new List<Application__c>();
        for(OrderApi__Sales_Order__c so : records){
            OrderApi__Sales_Order__c oldRec = oldRecords.get(so.Id);
            if(oldRec.OrderApi__Is_Posted__c == false && so.OrderApi__Is_Posted__c == true){
                Application__c app = new Application__c();
                if(so.Application__c!=null){
                    app.Id = so.Application__c;
                    app.IsPaid__c = true;
                    applicationList.add(app);
                }
            }
        }
        if(applicationList != null && !applicationList.isEmpty()){
            update applicationList;
        }
    }
    
    public static void generateCandidateId(List<OrderApi__Sales_Order__c> records){
        List<OrderApi__Sales_Order_Line__c> sols = [SELECT Id, OrderApi__Sales_Order__c, OrderApi__Contact__c 
                                                    FROM OrderApi__Sales_Order_Line__c 
                                                    WHERE OrderApi__Sales_Order__c IN: records AND (Event_Is_NCP_Exam__c = true OR Event_Name__c LIKE '%Exam%')];
        
        Integer currentYear = system.today().year();
        List<CandidateId__c> ci = [SELECT Id  FROM CandidateId__c LIMIT 1];
        
        if(ci.size() == 0){
            CandidateId__c newCI = new CandidateId__c();
            newCI.Candidate_Id_Number__c = 0;
            newCI.Candidate_Id_Text__c= 'HRNCP';
            insert newCI;
        }
        
        List<CandidateId__c> ciG = [SELECT Id, Candidate_Id_Number__c, Candidate_Id_Text__c  FROM CandidateId__c LIMIT 1];
        
        String lastCandidateText;
        Integer currentCandidateNumber;
        String currentCandidateFull;
        
        lastCandidateText = ciG[0].Candidate_Id_Text__c + string.valueOf(currentYear).right(2);
        currentCandidateNumber = integer.valueOf(ciG[0].Candidate_Id_Number__c + 1);
        currentCandidateFull = lastCandidateText + string.valueOf(currentCandidateNumber).leftPad(4,'0');
        
        
        List<String> contIds = new List<String>();
        Set<Contact> contsToUpdateSet = new Set<Contact>();
        List<Contact> contsToUpdate = new List<Contact>();
        Map<String, List<OrderApi__Sales_Order_Line__c>> soToExamSols = new Map<String, List<OrderApi__Sales_Order_Line__c>>();
        for(OrderApi__Sales_Order_Line__c sol : sols){
            contIds.add(sol.OrderApi__Contact__c);
            if(soToExamSols.containsKey(sol.OrderApi__Sales_Order__c)){
                soToExamSols.get(sol.OrderApi__Sales_Order__c).add(sol);
            }else{
                soToExamSols.put(sol.OrderApi__Sales_Order__c, new List<OrderApi__Sales_Order_Line__c>{sol});
            }
        }
        List<Contact> conts = [SELECT Id, FON_NCP_Candidate_ID__c, FON_Candidate_Id_Generated_On__c FROM Contact WHERE Id IN: contIds];
        Map<Id, Contact> mapConts = new Map<Id, Contact>(conts);
        for(OrderApi__Sales_Order__c so : records){
            if(soToExamSols.containsKey(so.Id)){
                if(string.isBlank(mapConts.get(so.OrderApi__Contact__c).FON_NCP_Candidate_ID__c)){
                    mapConts.get(so.OrderApi__Contact__c).FON_NCP_Candidate_ID__c = currentCandidateFull;
                    mapConts.get(so.OrderApi__Contact__c).FON_Candidate_Id_Generated_On__c = system.now();
                    contsToUpdateSet.add(mapConts.get(so.OrderApi__Contact__c));
                    currentCandidateNumber += 1;
                    currentCandidateFull = lastCandidateText + string.valueOf(currentCandidateNumber).leftPad(4,'0');
                }
            }
        }
        ciG[0].Candidate_Id_Number__c = currentCandidateNumber - 1;
        update ciG;
        
        if(contsToUpdateSet.size() > 0){
            contsToUpdate.addAll(contsToUpdateSet);
            update contsToUpdate;
        }
    }
    
}