unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label># Application</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_number__c.field-meta.xml
<CustomField>
    <fullName>Application_number__c</fullName>
    <label>Application #</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/NCP_Sessions__c.object-meta.xml
<CustomObject>
    <label>NCP Session</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCP Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NCP Sessions</relationshipLabel>
    <relationshipName>NCP_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/App_Fee_Submitting__c.field-meta.xml
<CustomField>
    <fullName>App_Fee_Submitting__c</fullName>
    <formula>VALUE(TEXT(VALUE(Minutes_EDU_Submitting__c) / 50))*100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>App Fee (Submitting)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>NCP Sessions</relationshipLabel>
    <relationshipName>NCP_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <formula>Application__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Concurrent_Session__c.field-meta.xml
<CustomField>
    <fullName>Concurrent_Session__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Concurrent Session</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>NCP Sessions</relationshipLabel>
    <relationshipName>NCP_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Credit_Val__c.field-meta.xml
<CustomField>
    <fullName>Credit_Val__c</fullName>
    <formula>TEXT(VALUE(Minutes_EDU_Submitting__c) / 50)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Credits</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Files_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Files_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Files Uploaded</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/FON_Sales_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>FON_Sales_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Line</label>
    <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
    <relationshipLabel>NCP Sessions</relationshipLabel>
    <relationshipName>NCP_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Held_in_Conjunction__c.field-meta.xml
<CustomField>
    <fullName>Held_in_Conjunction__c</fullName>
    <label>Held in Conjunction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <label>Instructor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Instructor_Title__c.field-meta.xml
<CustomField>
    <fullName>Instructor_Title__c</fullName>
    <label>Instructor Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Is_Paid__c.field-meta.xml
<CustomField>
    <fullName>Is_Paid__c</fullName>
    <formula>Application__r.IsPaid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Paid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Minutes_EDU_Submitting__c.field-meta.xml
<CustomField>
    <fullName>Minutes_EDU_Submitting__c</fullName>
    <label>Minutes EDU (Submitting)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Provider_Notes__c.field-meta.xml
<CustomField>
    <fullName>Provider_Notes__c</fullName>
    <label>Provider Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipLabel>NCP Sessions</relationshipLabel>
    <relationshipName>NCP_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Series_Name__c.field-meta.xml
<CustomField>
    <fullName>Series_Name__c</fullName>
    <label>Series Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Session_ID__c.field-meta.xml
<CustomField>
    <fullName>Session_ID__c</fullName>
    <formula>IF(Provider_Name__c = &#39;ECCHO&#39;, 
(&#39;001.&#39; + Sequential_number__c  + &#39;.&#39;+  Session_Type_for_ID__c  +&#39;-&#39;+ Credit_Val__c ),
(Account__r.FON_Partner_Provider_ID__c + &#39;.&#39; + Sequential_number__c  + &#39;.&#39;+  Session_Type_for_ID__c  +&#39;-&#39;+ Credit_Val__c ))</formula>
    <label>Session ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Session_Time__c.field-meta.xml
<CustomField>
    <fullName>Session_Time__c</fullName>
    <label>Session Time</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <label>Session Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Workshop</fullName>
            </value>
            <value>
                <fullName>Conference Call</fullName>
            </value>
            <value>
                <fullName>e-Publication</fullName>
            </value>
            <value>
                <fullName>ECCHO Business Committee Meeting</fullName>
            </value>
            <value>
                <fullName>ECCHO Hosted Session</fullName>
            </value>
            <value>
                <fullName>ECCHO NCP Editorial Board</fullName>
            </value>
            <value>
                <fullName>ECCHO OPS Chairman</fullName>
            </value>
            <value>
                <fullName>ECCHO OPS Committee Meeting</fullName>
            </value>
            <value>
                <fullName>General Session</fullName>
            </value>
            <value>
                <fullName>In-Person Meeting</fullName>
            </value>
            <value>
                <fullName>In-Person Training</fullName>
            </value>
            <value>
                <fullName>Lunch-N-Learn</fullName>
            </value>
            <value>
                <fullName>NCP CE Workshop</fullName>
            </value>
            <value>
                <fullName>NCP Evaluation of Pilot Items</fullName>
            </value>
            <value>
                <fullName>NCP Guide Program</fullName>
            </value>
            <value>
                <fullName>NCP Partner Training</fullName>
            </value>
            <value>
                <fullName>OnDemand</fullName>
            </value>
            <value>
                <fullName>Roundtable</fullName>
            </value>
            <value>
                <fullName>Seminar</fullName>
            </value>
            <value>
                <fullName>User Group</fullName>
            </value>
            <value>
                <fullName>Web Based Training</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>ECCHO Ed</fullName>
            </value>
            <value>
                <fullName>NCP Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/classes/Fon_CreateNCPSession.cls
/**
 * THis is the class which is associated with the Fon_CreateNCPSession lightning component
 */
public without sharing class Fon_CreateNCPSession {
    
    // This method will be called when component is loaded
    @AuraEnabled
    public static OnLoadWrapper handleComponentLoad(){
        
        // getting contact of current user which is logged in
        String ContactId = Fon_CEInfoCntrl.fetchCurrentlogged();
        system.debug('\n--ContactId--'+ContactId);
        
        string AccId = fetchCurrentloggedAccount();
        
        // getting aplication record
        Application__c applciation = fetchApplication(ContactId, AccId);
        system.debug('\n--applciation--'+applciation);        
               
        // getting the sales order
        OrderApi__Sales_Order__c so = fetchSalesOrder(ContactId,applciation);
        system.debug('\n--so--'+so);
        
        // this is going to be pull the session for the contact
        List<NCP_Sessions__c> lstSession= fetchContactSession(ContactId);
        system.debug('\n--lstSession--'+lstSession);
        
        
        // making instance of the wrapper to be returned
        return new OnLoadWrapper(applciation, so, lstSession, ContactId, AccId);        
    }
     
    
    // code to get the Session based on login user contact id
 	private static List<NCP_Sessions__c> fetchContactSession(string ContactId){
        return [SELECT ID,
                        Name,
                        Session_ID__c,
                        Account__c,Account__r.Name,
                        App_Fee_Submitting__c,
                		Application_Number__c,
                		Is_Paid__c,
                        Application__c,Concurrent_Session__c,
                        Contact__c,Credit_Val__c,Contact__r.Name,
                        Description__c,Held_in_Conjunction__c,
                        Instructor__c,Instructor_Title__c,
                        Minutes_EDU_Submitting__c,
                        Provider_Name__c,Provider_Notes__c,
                        Sales_Order__c,FON_Sales_Order_Line__c,                        
                        Series_Name__c,
                        Session_Date__c,Session_Time__c,                       
                        Session_Type__c,
                		Files_Uploaded__c,
                        Session_Type_for_ID__c,Status__c,Year__c
                	FROM NCP_Sessions__c
               	 	WHERE Contact__c =: ContactId
                    ORDER BY CreatedDate DESC];
    }
    
    // code to get the application else create the application
    private static Application__c fetchApplication(string ContactId, string AccId){
        
        // getting the latest applciation
        List<Application__c> lstApplication = [SELECT ID,
                                                        Application_number__c
                                               		FROM Application__c 
                                                    WHERE Contact__c =: ContactId 
                                               		AND IsPaid__c = false LIMIT 1];
        // if we have the applciation record then return it
        if(!lstApplication.isEmpty()){
            return lstApplication[0];
        }
        
        // code to create new application
        else{
            lstApplication = [SELECT ID,
                                      	Application_number__c
                                	FROM Application__c
                                	WHERE Application_number__c != null
                                	Order By CreatedDate desc LIMIT 1];
            
            // this will save the application number
            Integer applicationNum = 1;
            if(!lstApplication.isEmpty()){
                applicationNum = Integer.valueOf(lstApplication[0].Application_number__c) + 1;
            }
            
            // code to create new application
            Application__c application = new Application__c();
            application.Contact__c = ContactId;
            application.Account__c = AccId;
            application.Application_number__c = string.valueOf(applicationNum);
            application.IsPaid__c = false;
            insert application;
            return application;
        }
    }
    
    // code to get the application else create the application
    private static OrderApi__Sales_Order__c fetchSalesOrder(string ContactId,Application__c applciation){
        
        // pulling sales order based uon contact
        List<OrderApi__Sales_Order__c> lstSO = [SELECT ID
                                                    FROM OrderApi__Sales_Order__c
                                                    WHERE OrderApi__Contact__c =: ContactId
                                                    AND Application__c =: applciation.Id];
        
        // if contact is found then return 
        if(!lstSO.isEmpty()){            
            return lstSO[0];
        }
        
        // if no SO is found then create the new on
        else{
            OrderApi__Sales_Order__c so = new OrderApi__Sales_Order__c();
            so.OrderApi__Contact__c = ContactId;
            so.Application__c = applciation.Id;
            insert so;
            return so;
        }        
        
    }
    
    Public class OnLoadWrapper{
        @AuraEnabled public Application__c applicationRecord {get;set;}
        @AuraEnabled public OrderApi__Sales_Order__c salesOrderRecord {get;set;}
        @AuraEnabled public List<NCP_Sessions__c> lstSession {get;set;}
        @AuraEnabled public string conId {get;set;}
        @AuraEnabled public string AccountId {get;set;}
        
        // constructor
        public OnLoadWrapper(Application__c applicationRecord, OrderApi__Sales_Order__c salesOrderRecord, List<NCP_Sessions__c> lstSession, string conId, string accId){
            this.applicationRecord = applicationRecord;
            this.salesOrderRecord = salesOrderRecord;
            this.lstSession = lstSession;
            this.conId = conId;
            this.AccountId =  accId;
        }
    }
    
    // method will be used to fetch ncp sesion record based on their parent application record and contact id 
    private static List<NCP_Sessions__c> fetchSessionRec(String ContactId){
        return [SELECT Id,
                		Application__c,
                		Credit_Val__c,
                		App_Fee_Submitting__c,
                		Application_Number__c,
                		Application__r.IsPaid__c,
                		FON_Sales_Order_Line__c
                	FROM NCP_Sessions__c
                	WHERE Contact__c =: ContactId
                	AND Application__r.IsPaid__c = false];
    }

	private static string  fetchCurrentloggedAccount(){
        string currentloginuserId = UserInfo.getUserId();
        List<User> userList = [SELECT Id,ContactId,contact.accountId FROM User WHERE Id =: currentloginuserId];
        return userList[0].contact.accountId;
    }
    
    // this method will be used to insert sales Order line records.
    @auraEnabled
    public static void createSalesOrderLines(OrderApi__Sales_Order__c sORec){
        System.debug('sORec : '+ sORec);
        if(sORec != null){
            
            // this will save the session to be updated with SOL
            List<NCP_Sessions__c> lstUpdateSession = new List<NCP_Sessions__c>();
            
            // getting contact of current user which is logged in
            String ContactId = Fon_CEInfoCntrl.fetchCurrentlogged();
            system.debug('\n--ContactId--'+ContactId);
            
            // getting contact Information
            contact conDetails = [SELECT Partner_External_Provider__c 
                                 		FROM Contact where Id =: ContactId];
            
            //getting ncp session records
            List<NCP_Sessions__c> ncpSessionList = fetchSessionRec(ContactId);
            System.debug('\n--ncpSessionList--'+ ncpSessionList);
            
            // getting items
            List<OrderApi__Item__c> lstItem = [SELECT ID 
                                               		FROM OrderApi__Item__c 
                                               		WHERE NAME = 'NCP Session Application Fee'];
            
            // Create Sales Order Line Records
            if(!ncpSessionList.isEmpty()
              	&& !lstItem.isEmpty()){
                    
                List<OrderApi__Sales_Order_Line__c> salesOrdrLineList = new List<OrderApi__Sales_Order_Line__c>();
                system.debug('\n--sess.FON_Sales_Order_Line__c--'+salesOrdrLineList);
                for(NCP_Sessions__c sess : ncpSessionList){
                    system.debug('\n--sess.FON_Sales_Order_Line__c--'+sess.FON_Sales_Order_Line__c);
                    
                    // adding SOL if the sales order line is not added
                    if(sess.FON_Sales_Order_Line__c == null){                        
                        OrderApi__Sales_Order_Line__c sOL = new OrderApi__Sales_Order_Line__c();
                        sOL.OrderApi__Sales_Order__c = sORec.Id;
                        sOL.OrderApi__Price_Override__c = true;
                        if(conDetails.Partner_External_Provider__c != 'Partner'){
                            sOL.OrderApi__Sale_Price__c = sess.App_Fee_Submitting__c;
                        }
                        else{
                           sOL.OrderApi__Sale_Price__c = 0; 
                        }
                        
                        sOL.OrderApi__Item__c = lstItem[0].Id;
                        salesOrdrLineList.add(sOL);
                        
                        // update the session list with SOL Id
                        sess.FON_Sales_Order_Line__r = sOL;
                        lstUpdateSession.add(sess);
                    }
                }
                
                // Insert Sales Order Line Records
                if(!salesOrdrLineList.isEmpty()){
                    insert salesOrdrLineList;
                    
                    // update session with SOL Lines
                    for(NCP_Sessions__c session : lstUpdateSession){
                        session.FON_Sales_Order_Line__c = session.FON_Sales_Order_Line__r.Id;
                        session.FON_Sales_Order_Line__r = null;
                    }
                    
                    update lstUpdateSession;
                }                
            }
        }
    }
    
    
    @auraEnabled
    public static void createCloneNCPSession(NCP_Sessions__c sess){
        
        System.debug('sess :-'+ sess);
        if(sess != null){
            insert sess;
            System.debug('sess :-'+ sess);
        }
    }
    
    @auraEnabled
    public static void checkUploaded(String rid){
        
        NCP_Sessions__c ns = [SELECT Id,Files_Uploaded__c FROM NCP_Sessions__c WHERE Id =: rid];
        ns.Files_Uploaded__c = true;
        update ns;
    }
}