unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label># Application</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>Contact__r.FirstName&amp;&#39; &#39;&amp;Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/NCP_Credits__c.object-meta.xml
<CustomObject>
    <label>NCP Credit</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>NCP_Credit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCP Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NCP_Credits__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>FON_Credits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/FON_Session_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Session_Date__c</fullName>
    <label>Session Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Program_Term__c.field-meta.xml
<CustomField>
    <fullName>Program_Term__c</fullName>
    <label>Program Term</label>
    <referenceTo>ProgramApi__Program_Term__c</referenceTo>
    <relationshipLabel>NCP Credits</relationshipLabel>
    <relationshipName>NCP_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Session_Title__c.field-meta.xml
<CustomField>
    <fullName>Session_Title__c</fullName>
    <label>Session Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending for Approval</fullName>
                <default>true</default>
                <label>Pending for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Audited - Approved</fullName>
            </value>
            <value>
                <fullName>Audited - Rejected</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
                <isActive>false</isActive>
                <label>Manual</label>
            </value>
            <value>
                <fullName>Not Considered</fullName>
                <isActive>false</isActive>
                <label>Not Considered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/NCP_Sessions__c.object-meta.xml
<CustomObject>
    <label>NCP Session</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCP Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NCP Sessions</relationshipLabel>
    <relationshipName>NCP_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>NCP Sessions</relationshipLabel>
    <relationshipName>NCP_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>NCP Sessions</relationshipLabel>
    <relationshipName>NCP_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <label>Instructor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Minutes_EDU_Submitting__c.field-meta.xml
<CustomField>
    <fullName>Minutes_EDU_Submitting__c</fullName>
    <label>Minutes EDU (Submitting)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Business_Group__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Items can be related to Business Groups to separate business lines and/or legal entities on transactional (sales) and financial reports.</description>
    <inlineHelpText>Items can be related to Business Groups to separate business lines and/or legal entities on transactional (sales) and financial reports.</inlineHelpText>
    <label>Business Group</label>
    <referenceTo>OrderApi__Business_Group__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reserved for future use.</description>
    <inlineHelpText>Reserved for future use.</inlineHelpText>
    <label>RESERVED</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item_Class__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Required ** Link to related Item Class</description>
    <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
    <label>Item Class</label>
    <referenceTo>OrderApi__Item_Class__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item_Class__c/OrderApi__Item_Class__c.object-meta.xml
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item_Class__c/fields/OrderApi__Business_Group__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Group</label>
    <referenceTo>OrderApi__Business_Group__c</referenceTo>
    <relationshipLabel>Item Classes</relationshipLabel>
    <relationshipName>Item_Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/ProgramApi__Program_Profile__c.object-meta.xml
<CustomObject>
    <description>This object maintains a single persona for each participant in a given program.</description>
    <label>Program Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Program Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/Allowed_Credits__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Credits__c</fullName>
    <label>Allowed Credits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/Allowed_Workshops__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Workshops__c</fullName>
    <label>Allowed Workshops</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_End_Date__c</fullName>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_Start_Date__c</fullName>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Account__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</description>
    <inlineHelpText>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Contact to program profile; a Contact has only one profile for a program</description>
    <inlineHelpText>Identifies Contact to program profile; a Contact has only one profile for a program</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/ProgramApi__Program_Term__c.object-meta.xml
<CustomObject>
    <description>This object establishes the length of time given to complete tasks.</description>
    <label>Program Term</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Program Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Profile__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SYSTEM. Relates the program profile to the term</description>
    <inlineHelpText>SYSTEM. Relates the program profile to the term</inlineHelpText>
    <label>Program Profile</label>
    <referenceTo>ProgramApi__Program_Profile__c</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FON_NCPCreditsRuleTest.cls
@IsTest
public class FON_NCPCreditsRuleTest  {
    
    @TestSetup
    private static void install() {

            Framework.Installer.install();
            PagesApi.PackageScripts.install();
            OrderApi.PackageScripts.install();
            EventApi.PackageScripts.install();
            
            Framework.RegisteredObject[] regObjects = new List<Framework.RegisteredObject>();
            Framework.RegisteredObject profobj = new Framework.RegisteredObject();
                profobj.sObjectName = 'NCP_Credits__c';
                profobj.apexClass = FON_NCPCreditTrigger.class.getName();
                profobj.namespace = '';
                profobj.isEnabled = true;
                profobj.isStandard = true;
                profobj.triggersEnabled = true;
                profobj.soqlLimit = String.valueOf(2000);
                profobj.soqlOrderBy = 'Name ASC';
                regObjects.add(profobj);
            Framework.Config.push(regObjects);
            
            // Create a routing rule for Contact
            Framework.RoutingRule[] rules = new List<Framework.RoutingRule>();
            Framework.RoutingRule cons = new Framework.RoutingRule();
            cons.apexClass = FON_NCPCreditsRule.class.getName();
            cons.namespace = '';
            cons.isEnabled = true;
            cons.sObjectName = 'NCP_Credits__c';
            cons.executionOrder = 0;
            rules.add(cons);
            Framework.Config.push(rules);               
            



    }
    
    @IsTest
    public static void NewYearBatchJob_Test(){
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('ECCHO Account').getRecordTypeId();

		OrderApi__Business_Group__c businessGroup = new OrderApi__Business_Group__c(Name='test');
        insert businessGroup;
        //system.debug(' '+);
        
        Account acc = new Account(recordtypeId = devRecordTypeId,Name = 'Test Acc');
        insert acc;
        //system.debug(' '+);
        
        Contact con = new contact(LastName='Test Con',AccountId = acc.Id);
        insert con;
        //system.debug(' '+);
        
        ProgramApi__Program_Profile__c ppp = new ProgramApi__Program_Profile__c();
        ppp.ProgramApi__Account__c = acc.Id;
        ppp.ProgramApi__Contact__c = con.Id;
        ppp.FON_Program_Start_Date__c = System.today();
        ppp.FON_Program_End_Date__c = System.today();
        ppp.Allowed_Workshops__c = 3;
        ppp.Allowed_Credits__c = 2;
        ppp.ProgramApi__Contact__c = con.Id;
        insert ppp;
        //system.debug(' '+);
        
        
        ProgramApi__Program_Term__c ppt = new ProgramApi__Program_Term__c();
        ppt.ProgramApi__Profile__c = ppp.Id;
        insert ppt;
        //system.debug(' '+);
        
        OrderApi__Item_Class__c itemClass = new OrderApi__Item_Class__c();
        itemClass.Name = 'item class test';
        insert itemClass;
        //system.debug(' '+);
        
         OrderApi__Item__c itm = new OrderApi__Item__c();
        itm.Name = 'CE Credit Filing Fee';
        itm.OrderApi__Business_Group__c = businessGroup.Id;
        itm.OrderApi__Item_Class__c = itemClass.Id;
        insert itm;
        //system.debug(' '+);

         OrderApi__Item__c itm2 = new OrderApi__Item__c();
        itm2.Name = 'CE Credits – Late Filing Fee';
        itm2.OrderApi__Business_Group__c = businessGroup.Id;
        itm2.OrderApi__Item_Class__c = itemClass.Id;
        insert itm2;

         Application__c app = new Application__c();
         app.Account__c = acc.Id;
         app.Contact__c = con.Id;
         insert app;
         
         NCP_Sessions__c ncs = new NCP_Sessions__c();
         ncs.Name = 'Test session';
         ncs.Account__c = acc.Id;
         ncs.Contact__c = con.Id;
         ncs.Application__c = app.Id;
         ncs.Status__c = 'Approved';
        ncs.Session_Date__c = System.today();
        ncs.Instructor__c = 'ins';
        ncs.Minutes_EDU_Submitting__c = '60';
        ncs.Description__c = 'desc';
        ncs.Session_Title__c = 'sesh title';
         insert ncs;

        
        NCP_Credits__c ncp1 = new NCP_Credits__c();
        ncp1.Program_Term__c = ppt.Id;
        ncp1.Contact_Name__c = con.Id;
        ncp1.Status__c = 'Pending for Approval';
        ncp1.FON_Session_Date__c = Date.today().addDays(-366);
        ncp1.NCP_Session__c = ncs.Id;
        insert ncp1;
        //system.debug(' '+);
        
        ncp1.FON_Session_Date__c =  Date.today().addDays(-386);
        update ncp1;
        
        Test.startTest();
        	
        Test.stopTest();
    }
}