unpackaged/main/default/objects/EventApi__Attendee__c/EventApi__Attendee__c.object-meta.xml
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Attendee__c/fields/EventApi__Account__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** System Calculated Override ** Link to the Account that the Attendee Contact is associated with.</description>
    <inlineHelpText>** System Calculated Override ** Link to the Account that the Attendee Contact is associated with.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Attendee__c/fields/EventApi__Attendee_Event__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Attendee_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Required ** Link to Event.</description>
    <inlineHelpText>** Required ** Link to Event.</inlineHelpText>
    <label>Event</label>
    <referenceTo>EventApi__Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Attendee__c/fields/EventApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</description>
    <inlineHelpText>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Event__c/EventApi__Event__c.object-meta.xml
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Event__c/fields/EventApi__Event_Key__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Event_Key__c</fullName>
    <description>This field is used as a unique identifier for events. The value in this field will also be used to concatenate item class names to be easily identified in lookup searches.</description>
    <inlineHelpText>This field is used as a unique identifier for events. The value in this field will also be used to concatenate item class names to be easily identified in lookup searches.</inlineHelpText>
    <label>Event Key</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program__c/ProgramApi__Program__c.object-meta.xml
<CustomObject>
    <description>This object is used for the creation and management of programs.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program__c/fields/ProgramApi__Active__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Identifies program is active</description>
    <inlineHelpText>Identifies program is active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/ProgramApi__Program_Profile__c.object-meta.xml
<CustomObject>
    <description>This object maintains a single persona for each participant in a given program.</description>
    <label>Program Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Program Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Account__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</description>
    <inlineHelpText>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Contact to program profile; a Contact has only one profile for a program</description>
    <inlineHelpText>Identifies Contact to program profile; a Contact has only one profile for a program</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Program__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Program related to a program profile</description>
    <inlineHelpText>Identifies Program related to a program profile</inlineHelpText>
    <label>Program</label>
    <referenceTo>ProgramApi__Program__c</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/ProgramApi__Program_Term__c.object-meta.xml
<CustomObject>
    <description>This object establishes the length of time given to complete tasks.</description>
    <label>Program Term</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Program Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Active__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifies active term; Term end date is in the future</description>
    <inlineHelpText>Identifies active term; Term end date is in the future</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/ProgramProfilesTriggerHelperTest.cls
@isTest(SeeAllData=False)
public class ProgramProfilesTriggerHelperTest {
    @testSetup static void testSetup(){
        ProgramApi__Program__c progNCP = new ProgramApi__Program__c();
        progNCP.Name  = 'NCP';
        progNCP.ProgramApi__Active__c = true;
        insert progNCP;
        
        EventApi__Event__c ev = new EventApi__Event__c();
        ev.Name = 'event';
        ev.EventApi__Event_Key__c = 'dummyK3y3vTstC8';
        insert ev;
        
        Account acc = new Account();
        acc.Name = 'testAcc';
        insert acc;
        
        Account acc2 = new Account();
        acc2.Name = 'testAcc2';
        insert acc2;
        
        Contact cont = new Contact();
        cont.FirstName = 'First';
        cont.LastName = 'Last';
        cont.AccountId = acc.Id;
        insert cont;
        
    }
    @isTest static void testInsert(){
        List<Account> accs = [SELECT Id FROM Account];
        List<Contact> conts = [SELECT Id FROM Contact];
        system.assert(accs.size() > 0);
        system.assert(conts.size() > 0);
        
        ProgramApi__Program__c program = [SELECT Id, Name FROM ProgramApi__Program__c LIMIT 1];
        List<ProgramApi__Program_Profile__c> pps = [SELECT Id, Name, ProgramApi__Program__r.Name
                                                    FROM ProgramApi__Program_Profile__c 
                                                    WHERE ProgramApi__Account__c IN: accs AND ProgramApi__Contact__c IN: conts];        
        List<ProgramApi__Program_Term__c> terms = [SELECT Id 
                                                   FROM ProgramApi__Program_Term__c 
                                                   WHERE Contact__c IN: conts];
        List<EventApi__Event__c> evs = [SELECT Id 
                                                   FROM EventApi__Event__c];
        system.assertEquals(0, pps.size());
        system.assertEquals(0, terms.size());
        
        EventAPi__Attendee__c att = new EventAPi__Attendee__c();
        att.EventApi__Account__c = accs[0].Id;
        att.EventApi__Contact__c = conts[0].Id;
        att.EventApi__Attendee_Event__c = evs[0].Id;
        insert att;
        
        pps = [SELECT Id, Name
               FROM ProgramApi__Program_Profile__c 
               WHERE ProgramApi__Account__c IN: accs AND ProgramApi__Contact__c IN: conts];
        terms = [SELECT Id 
                 FROM ProgramApi__Program_Term__c 
                 WHERE Contact__c IN: conts];
        //system.assertEquals(1, pps.size());
        //system.assertEquals(5, terms.size());
        
        EventAPi__Attendee__c att2 = new EventAPi__Attendee__c();
        att2.EventApi__Account__c = accs[0].Id;
        att2.EventApi__Contact__c = conts[0].Id;
        att2.EventApi__Attendee_Event__c = evs[0].Id;
        insert att2;
        
        pps = [SELECT Id, Name
               FROM ProgramApi__Program_Profile__c 
               WHERE ProgramApi__Account__c IN: accs AND ProgramApi__Contact__c IN: conts];
        terms = [SELECT Id 
                 FROM ProgramApi__Program_Term__c 
                 WHERE Contact__c IN: conts];
        //system.assertEquals(1, pps.size());
        Integer tcount = terms.size();
        system.assertEquals(tcount, terms.size());
        
    }
    
    @isTest static void testUpdate(){
        List<Account> accs = [SELECT Id FROM Account];
        List<Contact> conts = [SELECT Id FROM Contact];
        List<EventApi__Event__c> evs = [SELECT Id FROM EventApi__Event__c];
                
        EventAPi__Attendee__c att = new EventAPi__Attendee__c();
        att.EventApi__Account__c = accs[0].Id;
        att.EventApi__Contact__c = conts[0].Id;
        att.EventApi__Attendee_Event__c = evs[0].Id;
        insert att;
        
        ProgramApi__Program__c program = [SELECT Id, Name FROM ProgramApi__Program__c LIMIT 1];
        List<ProgramApi__Program_Profile__c> ppList = [SELECT Id, Name FROM ProgramApi__Program_Profile__c];
        ppList[0].ProgramApi__Program__c = program.Id;
        update ppList;
    }
    
    @isTest static void testDelete(){
        List<Account> accs = [SELECT Id FROM Account];
        List<Contact> conts = [SELECT Id FROM Contact];
        List<EventApi__Event__c> evs = [SELECT Id FROM EventApi__Event__c];
                
        EventAPi__Attendee__c att = new EventAPi__Attendee__c();
        att.EventApi__Account__c = accs[0].Id;
        att.EventApi__Contact__c = conts[0].Id;
        att.EventApi__Attendee_Event__c = evs[0].Id;
        insert att;
        
        List<ProgramApi__Program_Profile__c> ppList = [SELECT Id, Name FROM ProgramApi__Program_Profile__c];
        delete ppList;
        undelete ppList;
    }
    
}