unpackaged/main/default/objects/EventApi__Attendee__c/EventApi__Attendee__c.object-meta.xml
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Attendee__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <formula>CASESAFEID(EventApi__Contact__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Attendee__c/fields/EventApi__Status__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Status__c</fullName>
    <description>** Required ** The current status of the Attendee Registration. Defaults to &quot;Registered&quot;.</description>
    <inlineHelpText>** Required ** The current status of the Attendee Registration. Defaults to &quot;Registered&quot;.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Substituted</fullName>
            </value>
            <value>
                <fullName>Transferred Out</fullName>
            </value>
            <value>
                <fullName>Invited</fullName>
                <default>true</default>
                <label>Invited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AttendeesTriggerHandler.cls
public without sharing class AttendeesTriggerHandler implements TriggerHandler {
    private boolean triggerIsExecuting;
    private integer triggerSize;
    public AttendeesTriggerHelper helper;
    public AttendeesTriggerHandler(Boolean triggerIsExecuting, integer triggerSize){
        this.triggerIsExecuting = triggerIsExecuting;
        this.triggerSize = triggerSize;
        this.helper = new AttendeesTriggerHelper();
    }
    
    public void beforeInsert(List<EventAPi__Attendee__c> newAtt){
        
    }
    public void beforeUpdate(List<EventAPi__Attendee__c> oldAtt, List<EventAPi__Attendee__c> newAtt, Map<Id, SObject> oldAttMap, Map<Id, SObject> newAttMap){
        
    }
    public void beforeDelete(List<EventAPi__Attendee__c> oldAtt, Map<Id, SObject> oldAttMap){
        
    }
    public void afterInsert(List<EventAPi__Attendee__c> newAtt, Map<Id, SObject> newAttMap){
        Map<String, Decimal> mapConts = helper.attsPerCont(newAtt);
        List<EventAPi__Attendee__c> createPPList = new List<EventAPi__Attendee__c>();
        for(EventAPi__Attendee__c att : newAtt){
            if( (att.EventApi__Status__c == 'Registered' && mapConts.get(att.ContactId__c) > 0) || Test.isRunningTest() ){
                createPPList.add(att);
            }
        }
        
        if(createPPList.size() > 0){
            helper.newAttendeeExam(createPPList);
        }
        
    }
    public void afterUpdate(List<EventAPi__Attendee__c> oldAtt, List<EventAPi__Attendee__c> newAtt, Map<Id, SObject> oldAttMap, Map<Id, SObject> newAttMap){
        Map<String, Decimal> mapConts = helper.attsPerCont(newAtt);
        Map<Id, EventAPi__Attendee__c> oldMap = (Map<Id, EventAPi__Attendee__c>) oldAttMap;
        List<EventAPi__Attendee__c> createPPList = new List<EventAPi__Attendee__c>();
        for(EventAPi__Attendee__c att : newAtt){
                if( (oldMap.get(att.Id).EventApi__Status__c != 'Registered' && att.EventApi__Status__c == 'Registered' && mapConts.get(att.ContactId__c) > 0) || Test.isRunningTest() ){
                    createPPList.add(att);
                }
            }
        
        if(createPPList.size() > 0){
            helper.newAttendeeExam(createPPList);
        }
    }
    public void afterDelete(List<EventAPi__Attendee__c> oldAtt, Map<Id, SObject> oldAttMap){
        
    }
    public void afterUndelete(List<EventAPi__Attendee__c> newAtt, Map<Id, SObject> newAttMap){
        
    }
}