unpackaged/main/default/objects/EventApi__Attendee__c/EventApi__Attendee__c.object-meta.xml
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Event__c/EventApi__Event__c.object-meta.xml
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/EventApi__Attendee__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to related Attendee.</description>
    <inlineHelpText>Link to related Attendee.</inlineHelpText>
    <label>Attendee</label>
    <referenceTo>EventApi__Attendee__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/EventApi__Event__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to related Event.</description>
    <inlineHelpText>Link to related Event.</inlineHelpText>
    <label>Event</label>
    <referenceTo>EventApi__Event__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/SalesOrderLinesTriggerHandler.cls
public without sharing class SalesOrderLinesTriggerHandler implements TriggerHandler {
    private boolean triggerIsExecuting;
    private integer triggerSize;
    public SalesOrderLinesTriggerHelper helper;
    public SalesOrderLinesTriggerHandler(boolean triggerIsExecuting, integer triggerSize) {
        this.triggerIsExecuting = triggerIsExecuting;
        this.triggerSize = triggerSize;
        this.helper = new SalesOrderLinesTriggerHelper();
    }
    public void beforeInsert(List<OrderApi__Sales_Order_Line__c> newSOLs) {
        
    }
    public void beforeUpdate(List<OrderApi__Sales_Order_Line__c> oldSOLs, List<OrderApi__Sales_Order_Line__c> newSOLs, Map<ID, SObject> oldSOLsMap, Map<ID, SObject> newSOLsMap) {
        List<OrderApi__Sales_Order_Line__c> updAtt = new List<OrderApi__Sales_Order_Line__c>();
        for(OrderApi__Sales_Order_Line__c sol : newSOLs){
            if(string.isBlank(sol.EventApi__Attendee__c) && !string.isBlank(sol.OrderApi__Contact__c) && !string.isBlank(sol.EventApi__Event__c)){
                updAtt.add(sol);
            }
        }
        helper.updateAttendee(updAtt);
    }
    
    public void beforeDelete(List<OrderApi__Sales_Order_Line__c> oldSOLs, Map<ID, SObject> oldSOLsMap) {
        
    }
    public void afterInsert(List<OrderApi__Sales_Order_Line__c> newSOLs, Map<ID, SObject> newSOLsMap) {
        
    }
    public void afterUpdate(List<OrderApi__Sales_Order_Line__c> oldSOLs, List<OrderApi__Sales_Order_Line__c> newSOLs, Map<ID, SObject> oldSOLsMap, Map<ID, SObject> newSOLsMap) {
        
    }
    public void afterDelete(List<OrderApi__Sales_Order_Line__c> oldSOLs, Map<ID, SObject> oldSOLsMap) {
        
    }
    public void afterUndelete(List<OrderApi__Sales_Order_Line__c> newSOLs, Map<ID, SObject> newSOLsMap) {
        
    }
}