unpackaged/main/default/objects/EventApi__Attendee__c/EventApi__Attendee__c.object-meta.xml
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Registration_Item__c/EventApi__Registration_Item__c.object-meta.xml
<CustomObject>
    <description>Registration Items store the various products and break-out sessions for an Attendee.</description>
    <label>Registration Item</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Registration Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Registration_Item__c/fields/EventApi__Attendee__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Attendee__c</fullName>
    <description>** Required ** Master-detail link to the related Attendee.</description>
    <inlineHelpText>** Required ** Master-detail link to the related Attendee.</inlineHelpText>
    <label>Attendee</label>
    <referenceTo>EventApi__Attendee__c</referenceTo>
    <relationshipLabel>Registration Items</relationshipLabel>
    <relationshipName>Registration_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/EventApi__Registration_Item__c/fields/EventApi__Registration_Item__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Registration_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to related &quot;Parent Registration Item&quot;.</description>
    <inlineHelpText>Links to related &quot;Parent Registration Item&quot;.</inlineHelpText>
    <label>Registration Item</label>
    <referenceTo>EventApi__Registration_Item__c</referenceTo>
    <relationshipLabel>Registration Items</relationshipLabel>
    <relationshipName>Registration_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Registration_Item__c/fields/EventApi__Schedule_Item__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Schedule_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related schedule item.</description>
    <inlineHelpText>Link to the related schedule item.</inlineHelpText>
    <label>Schedule Item</label>
    <referenceTo>EventApi__Schedule_Item__c</referenceTo>
    <relationshipLabel>Registered Attendees</relationshipLabel>
    <relationshipName>Registration_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Schedule_Item__c/EventApi__Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Create and publish a schedule of activities configured for a given event.</description>
    <label>Schedule Item</label>
    <nameField>
        <label>Schedule Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/GetEventSessionsControllerTest.cls
@isTest
public class GetEventSessionsControllerTest {
    @testSetup
    static void setupTestData() {
        // Create test data for EventApi__Schedule_Item__c
        EventApi__Schedule_Item__c scheduleItem = new EventApi__Schedule_Item__c(Name = 'Test Schedule Item');
        insert scheduleItem;

        // Create test data for EventApi__Attendee__c
        EventApi__Attendee__c attendee = new EventApi__Attendee__c();
        insert attendee;

        // Create test data for EventApi__Registration_Item__c
        EventApi__Registration_Item__c regItem = new EventApi__Registration_Item__c(
            EventApi__Attendee__c = attendee.Id,
            EventApi__Schedule_Item__c = scheduleItem.Id
        );
        insert regItem;
    }

    @isTest
    static void testGetEventSessionsController() {
        // Retrieve the test data
        EventApi__Attendee__c testAttendee = [SELECT Id FROM EventApi__Attendee__c LIMIT 1];
        String attendeeId = testAttendee.Id;

        // Instantiate the controller with the test data
        Test.startTest();
        GetEventSessionsController controller = new GetEventSessionsController();
        controller.attendeeId = attendeeId;
        controller.getdisplaydata();
        Test.stopTest();

        // Verify the results
        System.assertNotEquals(null, controller.wrapObj, 'The wrapObj should not be null.');
        System.assertNotEquals(null, controller.wrapObj.sessions, 'The sessions list should not be null.');
        System.assertEquals(1, controller.wrapObj.sessions.size(), 'The sessions list should contain one item.');

        // Verify the data of the session
        EventApi__Registration_Item__c regItem = controller.wrapObj.sessions[0];
        System.assertEquals('Test Schedule Item', regItem.EventApi__Schedule_Item__r.Name, 'The schedule item name should match.');
    }

    @isTest
    static void testGetEventSessionsController_NoSessions() {
        // Create a new attendee without any sessions
        EventApi__Attendee__c newAttendee = new EventApi__Attendee__c();
        insert newAttendee;

        // Instantiate the controller with the new attendee
        Test.startTest();
        GetEventSessionsController controller = new GetEventSessionsController();
        controller.attendeeId = newAttendee.Id;
        controller.getdisplaydata();
        Test.stopTest();

        // Verify the results
        System.assertNotEquals(null, controller.wrapObj, 'The wrapObj should not be null.');
        System.assertEquals(0, controller.wrapObj.sessions.size(), 'The sessions list should be empty.');
    }
}