unpackaged/main/default/objects/EventApi__Attendee__c/EventApi__Attendee__c.object-meta.xml
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Attendee__c/fields/EventApi__Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Ticket_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Required ** Link to Ticket Type.</description>
    <inlineHelpText>** Required ** Link to Ticket Type.</inlineHelpText>
    <label>Ticket Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.EventApi__Attendee_Event__c</field>
            <operation>equals</operation>
            <valueField>EventApi__Ticket_Type__c.EventApi__Event__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EventApi__Ticket_Type__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Registration_Item__c/EventApi__Registration_Item__c.object-meta.xml
<CustomObject>
    <description>Registration Items store the various products and break-out sessions for an Attendee.</description>
    <label>Registration Item</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Registration Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Registration_Item__c/fields/EventApi__Schedule_Item__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Schedule_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related schedule item.</description>
    <inlineHelpText>Link to the related schedule item.</inlineHelpText>
    <label>Schedule Item</label>
    <referenceTo>EventApi__Schedule_Item__c</referenceTo>
    <relationshipLabel>Registered Attendees</relationshipLabel>
    <relationshipName>Registration_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Registration_Item__c/fields/EventApi__Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Ticket_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Ticket Type.</description>
    <inlineHelpText>Link to the related Ticket Type.</inlineHelpText>
    <label>Ticket Type</label>
    <referenceTo>EventApi__Ticket_Type__c</referenceTo>
    <relationshipLabel>Registration Items</relationshipLabel>
    <relationshipName>Registration_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Assignment__c/OrderApi__Assignment__c.object-meta.xml
<CustomObject>
    <description>Assignments track Contacts assigned to purchases of Items (Only available when Items are available for Assignment - determined by the parent Item Class)</description>
    <label>Assignment</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Assignment__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Required ** Link to assigned Contact record</description>
    <inlineHelpText>** Required ** Link to assigned Contact record</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Activities</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Assignment__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** System Calculated ** Link to related Item.</description>
    <inlineHelpText>** System Calculated ** Link to related Item.</inlineHelpText>
    <label>Item</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Assignment__c/fields/OrderApi__Sales_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Required ** Assignments must be linked to a source Sales Order Line</description>
    <inlineHelpText>** Required ** Assignments must be linked to a source Sales Order Line</inlineHelpText>
    <label>Sales Order Line (Source)</label>
    <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/EventApi__Schedule_Item__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Schedule_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** System Calculated ** Link to Schedule Item (Circular Reference) do not manually update.</description>
    <inlineHelpText>** System Calculated ** Link to Schedule Item (Circular Reference) do not manually update.</inlineHelpText>
    <label>Schedule Item</label>
    <referenceTo>EventApi__Schedule_Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/EventApi__Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Ticket_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** System Calculated ** Link to Ticket Type (Circular Reference) do not manually update.</description>
    <inlineHelpText>** System Calculated ** Link to Ticket Type (Circular Reference) do not manually update.</inlineHelpText>
    <label>Ticket Type</label>
    <referenceTo>EventApi__Ticket_Type__c</referenceTo>
    <relationshipLabel>DO NOT DISPLAY</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reserved for future use.</description>
    <inlineHelpText>Reserved for future use.</inlineHelpText>
    <label>RESERVED</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</description>
    <inlineHelpText>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/EventApi__Attendee__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to related Attendee.</description>
    <inlineHelpText>Link to related Attendee.</inlineHelpText>
    <label>Attendee</label>
    <referenceTo>EventApi__Attendee__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/EventApi__Schedule_Item__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Schedule_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to related Schedule Item.</description>
    <inlineHelpText>Link to related Schedule Item.</inlineHelpText>
    <label>Schedule Item</label>
    <referenceTo>EventApi__Schedule_Item__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/EventApi__Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Ticket_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to related Ticket Type.</description>
    <inlineHelpText>Link to related Ticket Type.</inlineHelpText>
    <label>Ticket Type</label>
    <referenceTo>EventApi__Ticket_Type__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Account__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the item related to the sales order.</description>
    <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
    <label>Item</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/classes/CHACreateAttendeesBatchable.cls
global without sharing class CHACreateAttendeesBatchable
    implements Database.Batchable<SObject>, Database.AllowsCallouts
{
    global List<String> listIds;
    global String fields;
    global String filters;
    global String errorMsg;
    //global String reportId;

    // Must be global so the no-arg constructor is found at runtime
    global CHACreateAttendeesBatchable() {
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        if (Test.isRunningTest()) {
            return Database.getQueryLocator(
                [
                    SELECT
                        Id,
                        OrderApi__Item__c,
                        OrderApi__Sales_Order__c,
                        OrderApi__Account__c,
                        OrderApi__Contact__c,
                        EventApi__Ticket_Type__c,
                        (
                            SELECT
                                Id,
                                OrderApi__Sales_Order__c,
                                OrderApi__Account__c,
                                OrderApi__Contact__c,
                                EventApi__Ticket_Type__c,
                                EventApi__Schedule_Item__c
                            FROM OrderApi__Sales_Order_Lines__r
                            WHERE EventApi__Schedule_Item__c != null
                        )
                    FROM OrderApi__Sales_Order_Line__c
                ]
            );
        } else {
            String whereId = '';
            String fetchFields = '';
            String additionalWhere = '';

            if (!String.isBlank(fields)) {
                // If the caller passed in a custom “fields” string, append it
                fetchFields = ', ' + fields;
            } else {
                // Otherwise default to these fields + the two child‐relationship subqueries
                fetchFields =
                    'Id, '
                  + 'OrderApi__Item__c, '
                  + 'OrderApi__Sales_Order__c, '
                  + 'OrderApi__Account__c, '
                  + 'OrderApi__Contact__c, '
                  + 'EventApi__Ticket_Type__c, '
                  + '(SELECT '
                        + 'Id, '
                        + 'OrderApi__Sales_Order__c, '
                        + 'OrderApi__Account__c, '
                        + 'OrderApi__Contact__c, '
                        + 'EventApi__Ticket_Type__c, '
                        + 'EventApi__Schedule_Item__c '
                      + 'FROM OrderApi__Sales_Order_Lines__r '
                      + 'WHERE EventApi__Schedule_Item__c != null), '
                  + '(SELECT Id FROM OrderApi__Assignments__r)';
            }

            if (!String.isBlank(filters)) {
                additionalWhere = ' AND ' + filters + ' AND ';
            } else if (listIds == null) {
                // no additional filters specified
            }

            // Build the dynamic SOQL
            String query =
                  'SELECT ' + fetchFields
                + ' FROM OrderApi__Sales_Order_Line__c WHERE ';

            if (listIds == null) {
                // If no IDs were passed in, just append whatever “filters” was
                query += additionalWhere;
            } else {
                whereId = 'Id IN (\'' + String.join(listIds, '\', \'') + '\') ';
                query += whereId + additionalWhere;
            }

            System.debug('QUERY ' + query);
            return Database.getQueryLocator(query);
        }
    }

    global void execute(Database.BatchableContext BC, List<SObject> scope) {
        // 1) Build attendee records
        List<EventApi__Attendee__c> attendees = new List<EventApi__Attendee__c>();
        Map<Id, List<OrderApi__Sales_Order_Line__c>> mapSOLxSOLS = new Map<Id, List<OrderApi__Sales_Order_Line__c>>();
        Map<Id, Id> mapTicketxItem = new Map<Id, Id>();

        for (SObject s : scope) {
            OrderApi__Sales_Order_Line__c sol = (OrderApi__Sales_Order_Line__c) s;

            if (!Test.isRunningTest()) {
                // Map ticketType → itemId for the later registration‐item insert
                mapTicketxItem.put(sol.EventApi__Ticket_Type__c, sol.OrderApi__Item__c);
            }

            // Create the Attendee record
            EventApi__Attendee__c att = new EventApi__Attendee__c();
            att.EventApi__Account__c          = sol.OrderApi__Account__c;
            att.EventApi__Contact__c          = sol.OrderApi__Contact__c;
            att.EventApi__Sales_Order__c      = sol.OrderApi__Sales_Order__c;
            att.EventApi__Sales_Order_Line__c = sol.Id;
            if (!Test.isRunningTest()) {
                att.EventApi__Ticket_Type__c = sol.EventApi__Ticket_Type__c;
            }
            att.EventApi__Status__c = 'Registered';

            // If there is an Assignment child, attach its Id
            List<OrderApi__Assignment__c> asst = sol.OrderApi__Assignments__r;
            if (asst != null && !asst.isEmpty()) {
                att.EventApi__Assignment__c = asst[0].Id;
            }

            attendees.add(att);

            // Gather all “child” Sales Order Lines (packages) under this SOL
            List<OrderApi__Sales_Order_Line__c> psols = sol.OrderApi__Sales_Order_Lines__r;
            if (psols != null && !psols.isEmpty()) {
                mapSOLxSOLS.put(sol.Id, psols);
            }
        }

        if (!attendees.isEmpty()) {
            insert attendees;

            // 2) For each inserted Attendee, create Registration_Item__c records
            List<EventApi__Registration_Item__c> regs = new List<EventApi__Registration_Item__c>();
			List<OrderApi__Sales_Order_Line__c> usols = new List<OrderApi__Sales_Order_Line__c>();
            for (EventApi__Attendee__c att : attendees) {
                // “Main” registration item for the ticket itself
                EventApi__Registration_Item__c mreg = new EventApi__Registration_Item__c();
                mreg.EventApi__Attendee__c         = att.Id;
                mreg.EventApi__Sales_Order__c      = att.EventApi__Sales_Order__c;
                mreg.EventApi__Sales_Order_Line__c = att.EventApi__Sales_Order_Line__c;
                mreg.EventApi__Status__c           = 'Registered';
                mreg.EventApi__Ticket_Type__c      = att.EventApi__Ticket_Type__c;

                Id itemId = mapTicketxItem.get(att.EventApi__Ticket_Type__c);
                if (itemId != null) {
                    mreg.EventApi__Item__c = itemId;
                }
                regs.add(mreg);
                
                // update main sol
                OrderApi__Sales_Order_Line__c usol = new OrderApi__Sales_Order_Line__c();
                usol.Id = att.EventApi__Sales_Order_Line__c;
                usol.EventApi__Attendee__c = att.Id;
                
                usols.add(usol);

                // Now “package” registration items (child SOLs) under this attendee
                List<OrderApi__Sales_Order_Line__c> childSols =
                    mapSOLxSOLS.get(att.EventApi__Sales_Order_Line__c);
                if (childSols != null && !childSols.isEmpty()) {
                    for (OrderApi__Sales_Order_Line__c psol : childSols) {
                        EventApi__Registration_Item__c preg = new EventApi__Registration_Item__c();
                        preg.EventApi__Attendee__c         = att.Id;
                        preg.EventApi__Sales_Order__c      = att.EventApi__Sales_Order__c;
                        preg.EventApi__Sales_Order_Line__c = att.EventApi__Sales_Order_Line__c;
                        preg.EventApi__Status__c           = 'Registered';
                        preg.EventApi__Schedule_Item__c    = psol.EventApi__Schedule_Item__c;
                        preg.EventApi__Item__c             = psol.OrderApi__Item__c;
                        regs.add(preg);
                    }
                }
            }

            if (!regs.isEmpty()) {
                insert regs;
            }
            if (!usols.isEmpty()) {
                update usols;
            }

        }
    }

    global void finish(Database.BatchableContext BC) {
        // The vars++ loops stay exactly as they were
        Integer vars = 0;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
    }
}