unpackaged/main/default/objects/EventApi__Attendee__c/EventApi__Attendee__c.object-meta.xml
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Attendee__c/fields/EventApi__Attendee_Event__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Attendee_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Required ** Link to Event.</description>
    <inlineHelpText>** Required ** Link to Event.</inlineHelpText>
    <label>Event</label>
    <referenceTo>EventApi__Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Attendee__c/fields/EventApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</description>
    <inlineHelpText>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Event__c/EventApi__Event__c.object-meta.xml
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/EventApi__Attendee__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to related Attendee.</description>
    <inlineHelpText>Link to related Attendee.</inlineHelpText>
    <label>Attendee</label>
    <referenceTo>EventApi__Attendee__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/EventApi__Event__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to related Event.</description>
    <inlineHelpText>Link to related Event.</inlineHelpText>
    <label>Event</label>
    <referenceTo>EventApi__Event__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/SalesOrderLinesTriggerHelper.cls
public without sharing class SalesOrderLinesTriggerHelper {
    public SalesOrderLinesTriggerHelper() {
        System.debug('Inside SalesOrderLinesTriggerHelper Constructor');
    }
    
    public void updateAttendee(List<OrderApi__Sales_Order_Line__c> newSOLs) {
        List<String> eventList = new List<String>();
        List<String> contactList = new List<String>();
        
        for(OrderApi__Sales_Order_Line__c sls : newSOLs){
            eventList.add(sls.EventApi__Event__c);
            contactList.add(sls.OrderApi__Contact__c);
        }
        
        List<EventApi__Attendee__c> atts = [SELECT Id, Name, EventApi__Contact__c, EventApi__Attendee_Event__c 
                                            FROM EventApi__Attendee__c 
                                            WHERE EventApi__Contact__c IN: contactList AND EventApi__Attendee_Event__c IN: eventList 
                                            ORDER BY CreatedDate DESC];
        Map<String, EventApi__Attendee__c> uniqueAttendee = new Map<String, EventApi__Attendee__c>();
        for(EventApi__Attendee__c att : atts){
            if(!uniqueAttendee.containsKey(string.valueOf(att.EventApi__Contact__c) + string.valueOf(att.EventApi__Attendee_Event__c))){
                uniqueAttendee.put(string.valueOf(att.EventApi__Contact__c) + string.valueOf(att.EventApi__Attendee_Event__c), att);
            }
        }
        
        for(OrderApi__Sales_Order_Line__c sol : newSOLs){
            if(uniqueAttendee.containsKey(string.valueOf(sol.OrderApi__Contact__c) + string.valueOf(sol.EventApi__Event__c))){
                sol.EventApi__Attendee__c = uniqueAttendee.get(string.valueOf(sol.OrderApi__Contact__c) + string.valueOf(sol.EventApi__Event__c)).Id;
            }
        }
    }
}