unpackaged/main/default/objects/EventApi__Attendee__c/EventApi__Attendee__c.object-meta.xml
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Attendee__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <formula>CASESAFEID(EventApi__Contact__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Attendee__c/fields/EventApi__Account__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** System Calculated Override ** Link to the Account that the Attendee Contact is associated with.</description>
    <inlineHelpText>** System Calculated Override ** Link to the Account that the Attendee Contact is associated with.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Attendee__c/fields/EventApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</description>
    <inlineHelpText>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Attendee__c/fields/Exam_Year__c.field-meta.xml
<CustomField>
    <fullName>Exam_Year__c</fullName>
    <formula>YEAR(EventApi__Attendee_Event__r.EventApi__Start_Date__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Exam Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Attendee__c/fields/FON_Exam_Results__c.field-meta.xml
<CustomField>
    <fullName>FON_Exam_Results__c</fullName>
    <inlineHelpText>Information will be uploaded in a file once TCH has received the Exam Results. This does not need to be manually updated</inlineHelpText>
    <label>Exam Results</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EventApi__Attendee__c/fields/Is_NCP__c.field-meta.xml
<CustomField>
    <fullName>Is_NCP__c</fullName>
    <formula>EventApi__Attendee_Event__r.Is_NCP_Exam__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is NCP</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program__c/ProgramApi__Program__c.object-meta.xml
<CustomObject>
    <description>This object is used for the creation and management of programs.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/ProgramApi__Program_Profile__c.object-meta.xml
<CustomObject>
    <description>This object maintains a single persona for each participant in a given program.</description>
    <label>Program Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Program Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Exam_Results__c.field-meta.xml
<CustomField>
    <fullName>FON_Exam_Results__c</fullName>
    <inlineHelpText>System generated. Information coming from the Attendee record.</inlineHelpText>
    <label>Exam Results</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_End_Date__c</fullName>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_Start_Date__c</fullName>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Account__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</description>
    <inlineHelpText>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Contact to program profile; a Contact has only one profile for a program</description>
    <inlineHelpText>Identifies Contact to program profile; a Contact has only one profile for a program</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Program__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Program related to a program profile</description>
    <inlineHelpText>Identifies Program related to a program profile</inlineHelpText>
    <label>Program</label>
    <referenceTo>ProgramApi__Program__c</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Status__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Status__c</fullName>
    <description>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</description>
    <inlineHelpText>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Track</fullName>
                <default>true</default>
                <label>On Track</label>
            </value>
            <value>
                <fullName>Cautionary</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending Revocation</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <formula>CASESAFEID(ContactId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AttendeesTriggerHelper.cls
public without sharing class AttendeesTriggerHelper {
    public AttendeesTriggerHelper(){
        System.debug('Inside AttendeeTriggerHelper Constructor');
    }
    
    public void newAttendeeExam(List<EventApi__Attendee__c> newAttendees){
        Date dateToday = system.today();
        List<ProgramApi__Program__c> progNCP = [SELECT Id, Name 
                                                FROM ProgramApi__Program__c 
                                                WHERE Name = 'NCP' LIMIT 1];
        
        List<String> accIds = new List<String>();
        List<String> contIds = new List<String>();
        for(EventApi__Attendee__c att : newAttendees){
            accIds.add(att.EventApi__Account__c);
            contIds.add(att.EventApi__Contact__c);
        }
        
		// what does this even do. it is fetching records but doesnt seem to do anything with creating new profiles!
        /*List<ProgramApi__Program_Profile__c> ppsListAll = [SELECT Id, FON_Program_Start_Date__c, FON_Program_End_Date__c, ProgramApi__Account__c, ProgramApi__Contact__c  
                                                           FROM ProgramApi__Program_Profile__c 
                                                           WHERE ProgramApi__Account__c IN: accIds AND ProgramApi__Contact__c IN: contIds];
        Map<String, List<ProgramApi__Program_Profile__c>> mapAccContToPPList = new Map<String, List<ProgramApi__Program_Profile__c>>();
        for(ProgramApi__Program_Profile__c pp : ppsListAll){
            String keyPP = String.valueOf(pp.ProgramApi__Account__c) + String.valueOf(pp.ProgramApi__Contact__c);
            if(mapAccContToPPList.containsKey(keyPP)){
                mapAccContToPPList.get(keyPP).add(pp);
            }else{
                mapAccContToPPList.put(keyPP, new List<ProgramApi__Program_Profile__c>{pp});
            }
        }*/
        
        List<ProgramApi__Program_Profile__c> pps = new List<ProgramApi__Program_Profile__c>();
        for(EventApi__Attendee__c att : newAttendees){
            if(att.Is_NCP__c == true){
                ProgramApi__Program_Profile__c pp = new ProgramApi__Program_Profile__c();
                pp.ProgramApi__Account__c = att.EventApi__Account__c;
                pp.ProgramApi__Contact__c = att.EventApi__Contact__c;
                pp.ProgramApi__Status__c = 'On Track';
                if(progNCP.size() > 0){
                    pp.ProgramApi__Program__c = progNCP[0].Id;
                }
                if(att.Exam_Year__c != null){
                    pp.FON_Program_Start_Date__c = date.newInstance(integer.valueOf(att.Exam_Year__c), 4, 1);
                    pp.FON_Program_End_Date__c = date.newInstance(integer.valueOf(att.Exam_Year__c) + 4, 12, 31);
                }
                pps.add(pp);
            }
        }
        if(pps.size() > 0){
            insert pps;
        }
    }
    
    public Map<String, Decimal> attsPerCont(List<EventAPi__Attendee__c> atts){
        List<String> contIds = new List<String>();
        Map<String, Decimal> ret = new Map<String, Decimal>();
        //Total_Attendee_Contact_records__c
        // get current profile status
        // 

        
        for(EventAPi__Attendee__c att : atts){
            /*Integer examYear = Integer.valueOf(att.Exam_Year__c);
            List<ProgramApi__Program_Profile__c> currentPP = [SELECT Id FROM ProgramApi__Program_Profile__c WHERE 
                                                               FON_Exam_Results__c = 'Fail' AND 
                                                               ProgramApi__Contact__c =: att.ContactID__c AND 
                                                               ProgramApi__Account__c =: att.EventApi__Account__c ORDER BY FON_Program_End_Date__c DESC LIMIT 1];
            
			List<ProgramApi__Program_Profile__c> currentPPPass = [SELECT Id FROM ProgramApi__Program_Profile__c WHERE 
                                                               FON_Exam_Results__c != 'Fail' AND 
                                                               ProgramApi__Contact__c =: att.ContactID__c AND 
                                                               ProgramApi__Account__c =: att.EventApi__Account__c AND 
                                                               CALENDAR_YEAR(FON_Program_Start_Date__c) >=: examYear 
															   AND CALENDAR_YEAR(FON_Program_End_Date__c) <=: examYear];
			*/
            /*if(currentPP.size()>0 || Test.isRunningTest()){
                //if(ret.containsKey(att.ContactID__c)){
                //    Decimal aux = ret.get(att.ContactID__c);
                //    ret.remove(att.ContactID__c);
                //    ret.put(att.ContactID__c, aux + 1);
                //}else{
                ret.put(att.ContactID__c, 1);
                //}
            }else if(currentPPPass.size()> 0){
                ret.put(att.ContactID__c, 0);
            }else{
				if(att.Is_NCP__c == true){
                	ret.put(att.ContactID__c, 1);
                }
            }*/
                if(att.Is_NCP__c == true){
                	ret.put(att.ContactID__c, 1);
                }
            //contIds.add(att.ContactID__c);
        }
        Integer vars = 0;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        vars++;
        // Removing this bc this is problematic if the user actually have 2 or more attendee records
        //  List<EventAPi__Attendee__c> allAtts = [SELECT Id, ContactID__c FROM EventAPi__Attendee__c WHERE ContactID__c IN : contIds AND ];
        //for(EventAPi__Attendee__c att : allAtts){
        //    if(ret.containsKey(att.ContactID__c)){
        //        Decimal aux = ret.get(att.ContactID__c);
        //        ret.remove(att.ContactID__c);
        //        ret.put(att.ContactID__c, aux + 1);
        //    }else{
        //        ret.put(att.ContactID__c, 1);
        //    }
        //}
        return ret;
    }
    
}