unpackaged/main/default/objects/Avalara_Config__mdt/Avalara_Config__mdt.object-meta.xml
<CustomObject>
    <description>Configuration for the Avalara AvaTax integration. Stores company code, environment, ship-from address, and feature flags.</description>
    <label>Avalara Config</label>
    <pluralLabel>Avalara Configs</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Avalara_Config__mdt/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>Avalara Company Code, sent in every CreateTransaction request.</description>
    <label>Company Code</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/Avalara_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Avalara_Tax_Code__c</fullName>
    <description>Avalara tax code for this product (e.g., P0000000 for tangible goods, SW054000 for SaaS, NT for non-taxable). Sent in the CreateTransaction API request.</description>
    <inlineHelpText>Avalara tax code classification. Examples: P0000000 (tangible goods), SW054000 (SaaS), NT (non-taxable).</inlineHelpText>
    <label>Avalara Tax Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Is_Shipping_Rate__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Shipping_Rate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to create a Shipping Rate.</description>
    <inlineHelpText>Select the checkbox to create a Shipping Rate.</inlineHelpText>
    <label>Is Shipping Rate</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reserved for future use.</description>
    <inlineHelpText>Reserved for future use.</inlineHelpText>
    <label>RESERVED</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__SKU__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__SKU__c</fullName>
    <description>A SKU (Stock Keeping Unit) is a unique Item identifier that references attributes associated with the Item and that distinguish it from all other Items primarily used for inventory control and management.</description>
    <inlineHelpText>A SKU (Stock Keeping Unit) is a unique Item identifier that references attributes associated with the Item and that distinguish it from all other Items primarily used for inventory control and management.</inlineHelpText>
    <label>SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</description>
    <inlineHelpText>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Country__c</fullName>
    <description>The value of this field will be updated with the Account&#39;s Shipping Country or Contact&#39;s Mailing Country, based on &quot;Entity&quot; if not defined on record entry.</description>
    <inlineHelpText>The value of this field will be updated with the Account&#39;s Shipping Country or Contact&#39;s Mailing Country, based on &quot;Entity&quot; if not defined on record entry.</inlineHelpText>
    <label>Shipping Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Total__c</fullName>
    <description>**System Calculated**. Subtotal +</description>
    <formula>OrderApi__Subtotal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>**System Calculated** Subtotal +</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Account__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Is_Shipping_Rate__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Shipping_Rate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines the Sales Order Line that is being used for shipping.</description>
    <inlineHelpText>Select the checkbox to have this Sales Order Line represent shipping.</inlineHelpText>
    <label>Is Shipping Rate</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the item related to the sales order.</description>
    <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
    <label>Item</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Quantity__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>**Conditionally Required** The quantity (number of units) of the item related to the sales order line. Required when an Item is linked that does not have &quot;Disable Price Rules&quot; checked. Default 1.</description>
    <inlineHelpText>**Conditionally Required** The quantity (number of units) of the item related to the sales order line. Required when an Item is linked that does not have &quot;Disable Price Rules&quot; checked. Default 1.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sale_Price__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>**System Calculated/Override** The price per-unit for the item sold on the sales order line.</description>
    <inlineHelpText>**System Calculated/Override** The price per-unit for the item sold on the sales order line.</inlineHelpText>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_City__c</fullName>
    <description>Optional shipping city for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping City&quot; field.</description>
    <inlineHelpText>Optional shipping city for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping City&quot; field.</inlineHelpText>
    <label>Shipping City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Country__c</fullName>
    <description>Optional shipping country for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Country&quot; field.</description>
    <inlineHelpText>Optional shipping country for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Country&quot; field.</inlineHelpText>
    <label>Shipping Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Postal_Code__c</fullName>
    <description>Optional shipping postal code for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &#39;&quot;Shipping Postal Code&quot; field.</description>
    <inlineHelpText>Optional shipping postal code for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &#39;&quot;Shipping Postal Code&quot; field.</inlineHelpText>
    <label>Shipping Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_State__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_State__c</fullName>
    <description>Optional shipping state for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping State&quot; field.</description>
    <inlineHelpText>Optional shipping state for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping State&quot; field.</inlineHelpText>
    <label>Shipping State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_Street__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Street__c</fullName>
    <description>Optional shipping street for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Street&quot; field.</description>
    <inlineHelpText>Optional shipping street for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Street&quot; field.</inlineHelpText>
    <label>Shipping Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Total__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>**System Calculated** Total amount of Sales Order Line</description>
    <inlineHelpText>**System Calculated** Total amount of Sales Order Line</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/AvalaraTaxCalculationService.cls
/**
 * Orchestrator for Avalara tax calculation.
 * Validates the shipping address, calls CreateTransaction (SalesOrder estimate),
 * then creates tax SOLs on the Sales Order for each response line.
 */
public without sharing class AvalaraTaxCalculationService {

    private class TaxContext {
        public Id salesOrderId;
        public OrderApi__Sales_Order__c salesOrder;
        public List<OrderApi__Sales_Order_Line__c> productLines;
        public Avalara_Config__mdt config;
        public AvalaraCreateTransaction.Address shipFrom;
        public AvalaraCreateTransaction.Address shipTo;
        public AvalaraCreateTransaction.Response response;
        public Map<String, Id> lineNumberToSolId;
        public Map<String, Id> lineNumberToTaxItemId;
    }

    public static void calculateTax(Id salesOrderId) {
        TaxContext ctx = new TaxContext();
        ctx.salesOrderId = salesOrderId;
        ctx.salesOrder = queryProductLines(salesOrderId);
        ctx.productLines = ctx.salesOrder.OrderApi__Sales_Order_Lines__r;

        if (ctx.productLines == null || ctx.productLines.isEmpty()) {
            return;
        }

        ctx.config = queryActiveConfig();
        ctx.shipFrom = buildShipFromAddress(ctx.config);
        ctx.shipTo = buildShipToAddress(ctx.salesOrder);

        validateAddress(ctx.shipTo);
        ctx.response = callCreateTransaction(ctx);
        replaceTaxLines(ctx);
    }

    // ─── Queries ───

    private static OrderApi__Sales_Order__c queryProductLines(Id salesOrderId) {
        return [
            SELECT Id, OrderApi__Contact__c, OrderApi__Account__c,
                   OrderApi__Shipping_Street__c, OrderApi__Shipping_City__c,
                   OrderApi__Shipping_State__c, OrderApi__Shipping_Postal_Code__c,
                   OrderApi__Shipping_Country__c,
                   (SELECT Id, OrderApi__Item__c, OrderApi__Item__r.Name,
                           OrderApi__Item__r.Avalara_Tax__c,
                           OrderApi__Item__r.Avalara_Tax__r.Avalara_Tax_Code__c,
                           OrderApi__Item__r.OrderApi__SKU__c,
                           OrderApi__Sale_Price__c, OrderApi__Quantity__c, OrderApi__Total__c
                    FROM OrderApi__Sales_Order_Lines__r
                    WHERE OrderApi__Item__r.Avalara_Tax__c != null
                      AND OrderApi__Is_Shipping_Rate__c = false)
            FROM OrderApi__Sales_Order__c
            WHERE Id = :salesOrderId
            WITH SYSTEM_MODE
        ];
    }

    private static Avalara_Config__mdt queryActiveConfig() {
        List<Avalara_Config__mdt> configs = [
            SELECT Company_Code__c, ShipFrom_Street__c, ShipFrom_City__c,
                   ShipFrom_State__c, ShipFrom_PostalCode__c, ShipFrom_Country__c
            FROM Avalara_Config__mdt
            WHERE Is_Active__c = true
            WITH SYSTEM_MODE
            LIMIT 1
        ];

        if (configs.isEmpty()) {
            throw new AvalaraAuthProviderService.AvalaraException('No active Avalara_Config__mdt record found.');
        }

        return configs[0];
    }

    // ─── Address ───

    private static AvalaraCreateTransaction.Address buildShipFromAddress(Avalara_Config__mdt config) {
        AvalaraCreateTransaction.Address address = new AvalaraCreateTransaction.Address();
        address.line1 = config.ShipFrom_Street__c;
        address.city = config.ShipFrom_City__c;
        address.region = config.ShipFrom_State__c;
        address.postalCode = config.ShipFrom_PostalCode__c;
        address.country = config.ShipFrom_Country__c;
        return address;
    }

    private static AvalaraCreateTransaction.Address buildShipToAddress(OrderApi__Sales_Order__c salesOrder) {
        AvalaraCreateTransaction.Address address = new AvalaraCreateTransaction.Address();
        address.line1 = salesOrder.OrderApi__Shipping_Street__c;
        address.city = salesOrder.OrderApi__Shipping_City__c;
        address.region = salesOrder.OrderApi__Shipping_State__c;
        address.postalCode = salesOrder.OrderApi__Shipping_Postal_Code__c;
        address.country = salesOrder.OrderApi__Shipping_Country__c;
        return address;
    }

    private static void validateAddress(AvalaraCreateTransaction.Address shipTo) {
        if (String.isBlank(shipTo.line1) || String.isBlank(shipTo.city) || String.isBlank(shipTo.region) || String.isBlank(shipTo.postalCode) || String.isBlank(shipTo.country)) {
            throw new AvalaraAuthProviderService.AvalaraException(
                'Address validation failed: shipping address is incomplete. Please update your address.'
            );
        }

        try {
            AvalaraResolveAddress.Request request = new AvalaraResolveAddress.Request();
            request.line1 = shipTo.line1;
            request.city = shipTo.city;
            request.region = shipTo.region;
            request.postalCode = shipTo.postalCode;
            request.country = shipTo.country;

            AvalaraResolveAddress.Response response = AvalaraResolveAddressService.execute(request);

            if (response.messages != null && !response.messages.isEmpty()) {
                throw new AvalaraAuthProviderService.AvalaraException(
                    'Address validation failed: ' + response.messages[0].summary
                );
            }
        } catch (AvalaraAuthProviderService.AvalaraException e) {
            if (e.getMessage().startsWith('Address validation failed')) {
                throw e;
            }
            throw new AvalaraAuthProviderService.AvalaraException(
                'Address validation failed: the shipping address could not be verified. Please update your address.'
            );
        }
    }

    // ─── Transaction ───

    private static AvalaraCreateTransaction.Response callCreateTransaction(TaxContext ctx) {
        AvalaraCreateTransaction.Request request = new AvalaraCreateTransaction.Request();
        request.companyCode = ctx.config.Company_Code__c;
        request.type = 'SalesOrder';
        request.transactionDate = String.valueOf(Date.today());
        request.customerCode = resolveCustomerCode(ctx.salesOrder);
        request.shipFromAddress = ctx.shipFrom;
        request.shipToAddress = ctx.shipTo;
        request.lineItems = buildLineItems(ctx.productLines);

        return AvalaraCreateTransactionService.execute(request);
    }

    private static String resolveCustomerCode(OrderApi__Sales_Order__c salesOrder) {
        if (salesOrder.OrderApi__Contact__c != null) {
            return salesOrder.OrderApi__Contact__c;
        }
        if (salesOrder.OrderApi__Account__c != null) {
            return salesOrder.OrderApi__Account__c;
        }
        return 'UNKNOWN';
    }

    private static List<AvalaraCreateTransaction.LineItem> buildLineItems(List<OrderApi__Sales_Order_Line__c> productLines) {
        List<AvalaraCreateTransaction.LineItem> lineItems = new List<AvalaraCreateTransaction.LineItem>();
        Integer lineNumber = 1;

        for (OrderApi__Sales_Order_Line__c sol : productLines) {
            AvalaraCreateTransaction.LineItem lineItem = new AvalaraCreateTransaction.LineItem();
            lineItem.number_x = String.valueOf(lineNumber);
            lineItem.quantity = sol.OrderApi__Quantity__c;
            lineItem.amount = sol.OrderApi__Total__c;
            lineItem.itemCode = String.isNotBlank(sol.OrderApi__Item__r.OrderApi__SKU__c)
                ? sol.OrderApi__Item__r.OrderApi__SKU__c
                : sol.OrderApi__Item__c;
            lineItem.taxCode = sol.OrderApi__Item__r.Avalara_Tax__r.Avalara_Tax_Code__c;
            lineItems.add(lineItem);
            lineNumber++;
        }

        return lineItems;
    }

    // ─── Tax SOL Management ───

    private static void replaceTaxLines(TaxContext ctx) {
        buildLineNumberMaps(ctx);
        deleteExistingTaxLines(ctx.salesOrderId);
        createTaxLines(ctx);
    }

    private static void buildLineNumberMaps(TaxContext ctx) {
        ctx.lineNumberToSolId = new Map<String, Id>();
        ctx.lineNumberToTaxItemId = new Map<String, Id>();
        Integer lineNumber = 1;

        for (OrderApi__Sales_Order_Line__c sol : ctx.productLines) {
            String key = String.valueOf(lineNumber);
            ctx.lineNumberToSolId.put(key, sol.Id);
            ctx.lineNumberToTaxItemId.put(key, sol.OrderApi__Item__r.Avalara_Tax__c);
            lineNumber++;
        }
    }

    private static void deleteExistingTaxLines(Id salesOrderId) {
        List<OrderApi__Sales_Order_Line__c> existingTaxLines = [
            SELECT Id
            FROM OrderApi__Sales_Order_Line__c
            WHERE OrderApi__Sales_Order__c = :salesOrderId
              AND OrderApi__Item__r.Avalara_Tax_Code__c != null
              AND OrderApi__Item__r.Avalara_Tax__c = null
            WITH SYSTEM_MODE
        ];

        if (!existingTaxLines.isEmpty()) {
            delete existingTaxLines;
        }
    }

    private static void createTaxLines(TaxContext ctx) {
        List<OrderApi__Sales_Order_Line__c> taxLines = new List<OrderApi__Sales_Order_Line__c>();

        for (AvalaraCreateTransaction.ResponseLine responseLine : ctx.response.lines) {
            taxLines.add(new OrderApi__Sales_Order_Line__c(
                OrderApi__Sales_Order__c = ctx.salesOrderId,
                OrderApi__Price_Override__c = true,
                OrderApi__Sale_Price__c = responseLine.tax,
                OrderApi__Quantity__c = 1,
                OrderApi__Item__c = ctx.lineNumberToTaxItemId.get(responseLine.number_x),
                OrderApi__Sales_Order_Line__c = ctx.lineNumberToSolId.get(responseLine.number_x)
            ));
        }

        if (!taxLines.isEmpty()) {
            insert taxLines;
        }
    }
}