unpackaged/main/default/objects/OrderApi__Renewal__c/OrderApi__Renewal__c.object-meta.xml
<CustomObject>
    <description>Terms track the Subscription terms, dates for all Customer Subscriptions.</description>
    <label>Term</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Term ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Renewal__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines the active subscription term.</description>
    <inlineHelpText>Defines the active subscription term.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Renewal__c/fields/OrderApi__Subscription__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Subscription__c</fullName>
    <description>** System Calculated Required ** Link to related Subscription</description>
    <inlineHelpText>** System Calculated Required ** Link to related Subscription</inlineHelpText>
    <label>Subscription</label>
    <referenceTo>OrderApi__Subscription__c</referenceTo>
    <relationshipLabel>Terms</relationshipLabel>
    <relationshipName>Renewals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Subscription__c/OrderApi__Subscription__c.object-meta.xml
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Subscription__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</description>
    <inlineHelpText>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/FON_SubscriptionBatch.cls
global class FON_SubscriptionBatch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        Integer nextYear = Date.today().year() + 1;
        Integer lastTwoYears = Date.today().year() - 2;

        String query = 'SELECT Id FROM OrderApi__Subscription__c WHERE OrderApi__Is_Active__c = true';
        
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<OrderApi__Subscription__c> subscriptions) {
		
        List<OrderApi__Renewal__c> renewalToUpdate = new List<OrderApi__Renewal__c>();
        
        Map<Id, OrderApi__Subscription__c> subscriptionById = new Map<Id, OrderApi__Subscription__c>(subscriptions);
        Map<Id, List<OrderApi__Renewal__c>> renewalsBySubscriptionId= new Map<Id, List<OrderApi__Renewal__c>>();

        for(OrderApi__Renewal__c renewal : [SELECT Id, OrderApi__Subscription__c FROM OrderApi__Renewal__c WHERE OrderApi__Subscription__c IN :subscriptionById.keyset()]){
            
            Id key = renewal.OrderApi__Subscription__c;
            List<OrderApi__Renewal__c> renewals = new List<OrderApi__Renewal__c>();
            
            if(renewalsBySubscriptionId.containsKey(key)) {
                
                renewals = renewalsBySubscriptionId.get(key);
            }
            
            renewals.add(renewal);
            renewalsBySubscriptionId.put(key, renewals);
        }
        
        for(Id subscriptionId : renewalsBySubscriptionId.keyset()){
            
            for(OrderApi__Renewal__c renewal : renewalsBySubscriptionId.get(subscriptionId)) {
                //compare by date and the newest gets to be active and the others inactive.
                
            }
        }
        
        
        

    }

    global void finish(Database.BatchableContext BC) {
    }
}