unpackaged/main/default/objects/OrderApi__Renewal__c/OrderApi__Renewal__c.object-meta.xml
<CustomObject>
    <description>Terms track the Subscription terms, dates for all Customer Subscriptions.</description>
    <label>Term</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Term ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Renewal__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines the active subscription term.</description>
    <inlineHelpText>Defines the active subscription term.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Renewal__c/fields/OrderApi__Subscription__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Subscription__c</fullName>
    <description>** System Calculated Required ** Link to related Subscription</description>
    <inlineHelpText>** System Calculated Required ** Link to related Subscription</inlineHelpText>
    <label>Subscription</label>
    <referenceTo>OrderApi__Subscription__c</referenceTo>
    <relationshipLabel>Terms</relationshipLabel>
    <relationshipName>Renewals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Subscription__c/OrderApi__Subscription__c.object-meta.xml
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Subscription__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</description>
    <inlineHelpText>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Subscription__c/fields/OrderApi__Paid_Through_Date__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Paid_Through_Date__c</fullName>
    <description>Defines the last active date of the subscription including all subscription renewals.</description>
    <inlineHelpText>Defines the last active date of the subscription including all subscription renewals.</inlineHelpText>
    <label>Paid Through Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/MembershipsTriggerHelper.cls
public without sharing class MembershipsTriggerHelper {
    public MembershipsTriggerHelper(){
        System.debug('Inside MembershipsTriggerHelper Constructor');
    }
    
    public void inactivateSubs(List<OrderApi__Subscription__c> newSubs){
        List<OrderApi__Renewal__c> termsToUpdate = new List<OrderApi__Renewal__c>();
        List<OrderApi__Renewal__c> terms = [SELECT Id, OrderApi__Subscription__c, OrderApi__Is_Active__c 
                                            FROM OrderApi__Renewal__c 
                                            WHERE OrderApi__Subscription__c IN: newSubs ORDER BY CreatedDate DESC];
        Map<String, List<OrderApi__Renewal__c>> mapMembToTerms = new Map<String, List<OrderApi__Renewal__c>>();
        for(OrderApi__Renewal__c term : terms){
            if(mapMembToTerms.containsKey(term.OrderApi__Subscription__c)){
                mapMembToTerms.get(term.OrderApi__Subscription__c).add(term);
            }else{
                mapMembToTerms.put(term.OrderApi__Subscription__c, new List<OrderApi__Renewal__c>{term});
            }
        }
        
        for(OrderApi__Subscription__c sub : newSubs){
            //for(OrderApi__Renewal__c memb : mapMembToTerms.get(sub.Id)){
            if(mapMembToTerms.get(sub.Id)[0].OrderApi__Is_Active__c && mapMembToTerms.get(sub.Id)[1].OrderApi__Is_Active__c){
                mapMembToTerms.get(sub.Id)[1].OrderApi__Is_Active__c = false;
                sub.OrderApi__Paid_Through_Date__c = system.today();
                termsToUpdate.add(mapMembToTerms.get(sub.Id)[1]);
            }  
            //}
        }
        
        if(termsToUpdate.size() > 0){
            update termsToUpdate;
        }
    }
    
}