unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Balance_Due__c</fullName>
    <description>Defines the remaining amount due for this sales order line item.</description>
    <inlineHelpText>This field identifies the remaining balance unpaid for this invoice line.</inlineHelpText>
    <label>Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Overall_Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Overall_Total__c</fullName>
    <description>Overall Amount of Sales Order Line.</description>
    <inlineHelpText>Overall Amount of Sales Order Line.</inlineHelpText>
    <label>Overall Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Subscription_Plan__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Subscription_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required ** Link to the related plan that controls Activation and Expiration dates related to any Subscription Item. Required when the Sales Order Line is linked to a Item that is the child of a &quot;Subscription&quot; Item Class.</description>
    <inlineHelpText>** Conditionally Required ** Link to the related plan that controls Activation and Expiration dates related to any Subscription Item. Required when the Sales Order Line is linked to a Item that is the child of a &quot;Subscription&quot; Item Class.</inlineHelpText>
    <label>Subscription Plan</label>
    <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Total__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>**System Calculated** Total amount of Sales Order Line</description>
    <inlineHelpText>**System Calculated** Total amount of Sales Order Line</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/SOID__c.field-meta.xml
<CustomField>
    <fullName>SOID__c</fullName>
    <formula>CASESAFEID(OrderApi__Sales_Order__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SOID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/SRID__c.field-meta.xml
<CustomField>
    <fullName>SRID__c</fullName>
    <formula>CASESAFEID(Sponsoring_Relationship__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SRID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Subscription_Plan__c/OrderApi__Subscription_Plan__c.object-meta.xml
<CustomObject>
    <description>Subscription Plans control the subscription dates with &quot;Termed&quot;, &quot;Evergreen&quot;, and &quot;Calendar&quot; options.</description>
    <label>Subscription Plan</label>
    <nameField>
        <label>Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/UpdateSalesOrderLineInvocable.cls
global class UpdateSalesOrderLineInvocable {
    // https://developer.salesforce.com/forums/?id=9060G0000005nusQAA

    @InvocableMethod(label='Update Sales Order Line' Description='Update Multiple Order Line')
    global static List<String> fetchSalesOrderLine(List<methodVars> rels) {
   
        List<String> test = new List<String>();
        List<String> recs = rels[0].mlist;
        
        system.debug('RELS '+rels[0].mlist);
        system.debug('RECORDS '+rels[0].mlist);
        
        for (Integer i = 0; i < recs.size(); i++) {
            
            system.debug('CURRENT RECORD '+i+'--'+recs[i]);
            system.debug('CURRENT SO '+i+'--'+rels[0].so);
            String srid = recs[i].trim();
            OrderApi__Sales_Order_Line__c sol = [Select Id,OrderApi__Overall_Total__c from OrderApi__Sales_Order_Line__c where SOID__c =: rels[0].so AND SRID__c =: srid ];
            sol.OrderApi__Subscription_Plan__c = rels[0].plan;
            update sol;
            
            // update pricing
            if(rels[0].quarter != '1QFull'){
                if(rels[0].timing != 'Annual'){
                    OrderApi__Sales_Order_Line__c nsol = [Select Id,OrderApi__Overall_Total__c from OrderApi__Sales_Order_Line__c where Id =: sol.Id];
                    nsol.OrderApi__Balance_Due__c = nsol.OrderApi__Overall_Total__c / 4;
                    nsol.OrderApi__Total__c = nsol.OrderApi__Overall_Total__c / 4;
                    nsol.OrderApi__Overall_Total__c = nsol.OrderApi__Overall_Total__c / 4;
                    update nsol;
                    system.debug('PRICE UPDATED '+i+'--'+nsol);
                }
            }
            
            
            
        }
        
		test.add('done');
        return test;
    }
           //input details that comes to apex from flow
    global class methodVars{
        @InvocableVariable
        global String quarter;
        
        @InvocableVariable
        global String item;
        
        @InvocableVariable
        global String so;
        
        @InvocableVariable
        global String plan;
        
        @InvocableVariable
        global String acc;
        
        @InvocableVariable
        global String contact;
        
        @InvocableVariable
        global String rel;
        
        @InvocableVariable
        global List<String> mlist;
        
		@InvocableVariable
        global String timing;
    }
    
    //output details which goes from apex to flow
    /*public class methodOutputs{
        @InvocableVariable
        public String accountPreviousName ;
        @InvocableVariable
        public String DMLResult ;
    } */
}