unpackaged/main/default/objects/Account/fields/Billing_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Billing_Quarter__c</fullName>
    <label>Billing Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1Q</fullName>
            </value>
            <value>
                <fullName>1QFull</fullName>
            </value>
            <value>
                <fullName>2Q</fullName>
            </value>
            <value>
                <fullName>3Q</fullName>
            </value>
            <value>
                <fullName>4Q</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Flow_Notes__c.field-meta.xml
<CustomField>
    <fullName>Flow_Notes__c</fullName>
    <label>Flow Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/Item_Based_Upload_Information__c.object-meta.xml
<CustomObject>
    <label>Item Based Upload Information</label>
    <nameField>
        <label>Item Based Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Based Uploads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Item Based Uploads</relationshipLabel>
    <relationshipName>Item_Based_Uploads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/FON_Total_Volume__c.field-meta.xml
<CustomField>
    <fullName>FON_Total_Volume__c</fullName>
    <label>Total Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Item Based Uploads (Parent)</relationshipLabel>
    <relationshipName>Item_Based_Uploads1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1Q</fullName>
            </value>
            <value>
                <fullName>2Q</fullName>
            </value>
            <value>
                <fullName>3Q</fullName>
            </value>
            <value>
                <fullName>4Q</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/Sponsoring_Relationships__c.object-meta.xml
<CustomObject>
    <label>Sponsored Relationship</label>
    <nameField>
        <displayFormat>SP- {0000}</displayFormat>
        <label>Sponsoring Relationships ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsored Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Billing_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Billing_Quarter__c</fullName>
    <inlineHelpText>Specifies the quarter when the sponsoring organization will be billed for this membership</inlineHelpText>
    <label>Billing Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1Q</fullName>
            </value>
            <value>
                <fullName>1QFull</fullName>
            </value>
            <value>
                <fullName>2Q</fullName>
            </value>
            <value>
                <fullName>3Q</fullName>
            </value>
            <value>
                <fullName>4Q</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Flow_Notes__c.field-meta.xml
<CustomField>
    <fullName>Flow_Notes__c</fullName>
    <label>Flow Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Item_Based_Upload__c.field-meta.xml
<CustomField>
    <fullName>Item_Based_Upload__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Based Upload Record</label>
    <referenceTo>Item_Based_Upload_Information__c</referenceTo>
    <relationshipLabel>Sponsored Relationships</relationshipLabel>
    <relationshipName>Sponsored_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Rate_Upload__c.field-meta.xml
<CustomField>
    <fullName>Rate_Upload__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsored_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsored_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sponsored Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsoring_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsoring_Organization__c</fullName>
    <label>Sponsoring Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Volume_Upload__c.field-meta.xml
<CustomField>
    <fullName>Volume_Upload__c</fullName>
    <description>calculated from SPwithVolume apex</description>
    <label>Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/UpdateSPVolumeBatchable.cls
global class UpdateSPVolumeBatchable implements Database.Batchable<sObject>, Database.Stateful {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String processDate = System.Label.Volume_Upload_Process_Date;
        String ddate;
        String ddate2;
        Pattern p = Pattern.compile('.*\\d+.*');
        Matcher m = p.matcher(processDate);
        
        Boolean hasNumber = m.matches();
        system.debug('HAS NUMBER '+hasNumber);
        if(!hasNumber){
            ddate = processDate;
        }else{
            ddate = processDate + 'T00:00:00Z';
            ddate2 = processDate + 'T23:59:00Z';
        }
        //return Database.getQueryLocator('SELECT Id,Sponsored_Organization__c,Sponsoring_Organization__c,Billing_Quarter__c,Rate_Upload__c,Volume_Upload__c,Flow_Notes__c FROM Sponsoring_Relationships__c');
        //system.debug('QUERY '+'SELECT Id,(select Id,Sponsored_Organization__c,Sponsoring_Organization__c,Billing_Quarter__c,Rate_Upload__c,Volume_Upload__c,Flow_Notes__c FROM Sponsoring_Relationships1__r),(select Id,Parent__c,Account_Name__c,FON_Total_Volume__c,Rate__c,Quarter__c FROM Item_Based_Uploads__r ORDER BY Report_Date__c DESC LIMIT 1) FROM Account WHERE Id IN (SELECT Sponsored_Organization__c FROM Sponsoring_Relationships__c) AND Id IN (SELECT Account_Name__c FROM Item_Based_Upload_Information__c WHERE CreatedDate ='+ ddate +')');
        String qry = 'SELECT Id,(select Id,Sponsored_Organization__c,Sponsoring_Organization__c,Billing_Quarter__c,Rate_Upload__c,Volume_Upload__c,Flow_Notes__c FROM Sponsoring_Relationships1__r),(select Id,Parent__c,Account_Name__c,FON_Total_Volume__c,Rate__c,Quarter__c FROM Item_Based_Uploads__r ORDER BY Report_Date__c DESC LIMIT 1) FROM Account WHERE Id IN (SELECT Sponsored_Organization__c FROM Sponsoring_Relationships__c) AND Id IN (SELECT Account_Name__c FROM Item_Based_Upload_Information__c WHERE CreatedDate ='+ddate+')';
        if(hasNumber){
            qry = 'SELECT Id,(select Id,Sponsored_Organization__c,Sponsoring_Organization__c,Billing_Quarter__c,Rate_Upload__c,Volume_Upload__c,Flow_Notes__c FROM Sponsoring_Relationships1__r),(select Id,Parent__c,Account_Name__c,FON_Total_Volume__c,Rate__c,Quarter__c FROM Item_Based_Uploads__r ORDER BY Report_Date__c DESC LIMIT 1) FROM Account WHERE Id IN (SELECT Sponsored_Organization__c FROM Sponsoring_Relationships__c) AND Id IN (SELECT Account_Name__c FROM Item_Based_Upload_Information__c WHERE CreatedDate >='+ddate+' AND CreatedDate <='+ddate2+')';
        }
        return Database.getQueryLocator(qry);
    }
    global void execute(Database.BatchableContext bc, List<Account> scope){
        // process each batch of record
        List<Sponsoring_Relationships__c> lst = new List<Sponsoring_Relationships__c>();
        
        for (Account acc : scope) {
            
            List<Sponsoring_Relationships__c> sr = new List<Sponsoring_Relationships__c>();
                sr = acc.Sponsoring_Relationships1__r;
            List<Item_Based_Upload_Information__c> ib = new List<Item_Based_Upload_Information__c>();
                ib = acc.Item_Based_Uploads__r;
            
            for (Sponsoring_Relationships__c s : sr) {
                for (Item_Based_Upload_Information__c i : ib) {
                    if( i.Account_Name__c==s.Sponsored_Organization__c && i.Parent__c==s.Sponsoring_Organization__c ){
                            //s.Billing_Quarter__c = i.Quarter__c;
                            s.Rate_Upload__c = i.Rate__c;
                            s.Volume_Upload__c = i.FON_Total_Volume__c;
                        	s.Item_Based_Upload__c=i.Id;
                            s.Flow_Notes__c = 'Bachable Update - '+system.now();
                    }
                }
                lst.add(s);
            }

        }
        
        update lst;
    }

    
    global void finish(Database.BatchableContext bc){
        System.debug('>>>Finish');
    }    
 
}