unpackaged/main/default/objects/Account/fields/Billing_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Billing_Quarter__c</fullName>
    <label>Billing Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1Q</fullName>
            </value>
            <value>
                <fullName>1QFull</fullName>
            </value>
            <value>
                <fullName>2Q</fullName>
            </value>
            <value>
                <fullName>3Q</fullName>
            </value>
            <value>
                <fullName>4Q</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <inlineHelpText>*System Generated* The latest volume record uploaded into the &quot;Item Based Upload&quot; Object</inlineHelpText>
    <label>Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/Item_Based_Upload_Information__c.object-meta.xml
<CustomObject>
    <label>Item Based Upload Information</label>
    <nameField>
        <label>Item Based Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Based Uploads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Item Based Uploads</relationshipLabel>
    <relationshipName>Item_Based_Uploads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/FON_Total_Volume__c.field-meta.xml
<CustomField>
    <fullName>FON_Total_Volume__c</fullName>
    <label>Total Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Item Based Uploads (Parent)</relationshipLabel>
    <relationshipName>Item_Based_Uploads1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1Q</fullName>
            </value>
            <value>
                <fullName>2Q</fullName>
            </value>
            <value>
                <fullName>3Q</fullName>
            </value>
            <value>
                <fullName>4Q</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/Sponsoring_Relationships__c.object-meta.xml
<CustomObject>
    <label>Sponsored Relationship</label>
    <nameField>
        <displayFormat>SP- {0000}</displayFormat>
        <label>Sponsoring Relationships ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsored Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Billing_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Billing_Quarter__c</fullName>
    <inlineHelpText>Specifies the quarter when the sponsoring organization will be billed for this membership</inlineHelpText>
    <label>Billing Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1Q</fullName>
            </value>
            <value>
                <fullName>1QFull</fullName>
            </value>
            <value>
                <fullName>2Q</fullName>
            </value>
            <value>
                <fullName>3Q</fullName>
            </value>
            <value>
                <fullName>4Q</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Item_Based_Upload__c.field-meta.xml
<CustomField>
    <fullName>Item_Based_Upload__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Based Upload Record</label>
    <referenceTo>Item_Based_Upload_Information__c</referenceTo>
    <relationshipLabel>Sponsored Relationships</relationshipLabel>
    <relationshipName>Sponsored_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Rate_Upload__c.field-meta.xml
<CustomField>
    <fullName>Rate_Upload__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsored_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsored_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sponsored Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsoring_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsoring_Organization__c</fullName>
    <label>Sponsoring Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Volume_Upload__c.field-meta.xml
<CustomField>
    <fullName>Volume_Upload__c</fullName>
    <description>calculated from SPwithVolume apex</description>
    <label>Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/SPwithVolume.cls
public class SPwithVolume {
    @invocableMethod
    
    public static void ItemBasedUploads(List <ID> ItemIds)
    {
        List<Item_Based_Upload_Information__c> ItemBasedUpload = [select Id, Account_Name__C,Parent__c,FON_Total_Volume__c, Account_Name__r.ID, Account_Name__r.Volume__c,Rate__c,Quarter__c from Item_Based_Upload_Information__C where createddate = TODAY and id in: Itemids LIMIT 1];
        system.debug('IBU: '+ ItemBasedUpload);

        For (Item_Based_Upload_Information__c IBU: ItemBasedUpload){
            Sponsoring_Relationships__c sp = new Sponsoring_Relationships__c();
            system.debug('IBU ID:'+IBU.Id);
            //String IBUID = IBU.Sponsored_Relationship__c;
            try {
                sp = [select Id,Volume_Upload__c from Sponsoring_Relationships__c where Sponsored_Organization__c=:IBU.Account_Name__c AND Sponsoring_Organization__c=:IBU.Parent__c LIMIT 1];
                sp.Volume_Upload__c = IBU.FON_Total_Volume__c;
                sp.Rate_Upload__c = IBU.Rate__c;
                //sp.Billing_Quarter__c = IBU.Quarter__c;
                sp.Item_Based_Upload__c= IBU.Id;
                Update sp;
            } catch(DmlException e) {
                System.debug('SPwithVolume Error: ' + e.getMessage());
            }
        }
        
    }
}