unpackaged/main/default/objects/Account/fields/FON_Account_is_Archived__c.field-meta.xml
<CustomField>
    <fullName>FON_Account_is_Archived__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This is a manual process. Check this box to archive a record. Default is unchecked. Used for reporting purposes and remove an Account as a potential option for member sponsorship</inlineHelpText>
    <label>Organization is Inactive</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/FON_Annual_Dues__c.field-meta.xml
<CustomField>
    <fullName>FON_Annual_Dues__c</fullName>
    <formula>IF(Total_Deposits__c  &lt;= 10000000, &quot;$25&quot;,
IF(Total_Deposits__c  &gt;= 10000001 &amp;&amp; Total_Deposits__c  &lt;= 25000000 , &quot;$50&quot;,
IF(Total_Deposits__c  &gt;= 25000001 &amp;&amp; Total_Deposits__c  &lt;= 50000000, &quot;$75&quot;,
IF(Total_Deposits__c  &gt;= 50000001 &amp;&amp; Total_Deposits__c  &lt;= 100000000, &quot;$100&quot;,
IF(Total_Deposits__c  &gt;= 100000001 &amp;&amp; Total_Deposits__c  &lt;= 500000000, &quot;$200&quot;,
IF(Total_Deposits__c  &gt;= 500000001 &amp;&amp; Total_Deposits__c  &lt;= 1000000000, &quot;$750&quot;,
IF(Total_Deposits__c  &gt;= 1000000001 &amp;&amp; Total_Deposits__c  &lt;= 5000000000, &quot;$2,000&quot;,
IF(Total_Deposits__c  &gt;= 5000000001 &amp;&amp; Total_Deposits__c  &lt;= 20000000000, &quot;$7,000&quot;,
IF(Total_Deposits__c  &gt;= 20000000001 &amp;&amp; Total_Deposits__c  &lt;= 60000000000, &quot;$20,000&quot;,
IF(Total_Deposits__c  &gt;= 60000000001 &amp;&amp; Total_Deposits__c  &lt;= 100000000000, &quot;$40,000&quot;,
IF(Total_Deposits__c  &gt;= 100000000001 &amp;&amp; Total_Deposits__c  &lt;= 150000000000, &quot;$75,000&quot;,
IF(Total_Deposits__c  &gt;= 150000000001 &amp;&amp; Total_Deposits__c  &lt;= 200000000000,&quot;$100,000&quot;,
IF(Total_Deposits__c  &gt;= 200000000001, &quot;$120,000&quot;, null
)))))))))))))</formula>
    <label>SM Annual Dues</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/FON_Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>FON_Billing_Type__c</fullName>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Item Based</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/FON_Is_Member__c.field-meta.xml
<CustomField>
    <fullName>FON_Is_Member__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>*System Generated* Identifies whether an Account is a Member or Not a Member. Default is unchecked</inlineHelpText>
    <label>Is Member?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/FON_Is_Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>FON_Is_Subsidiary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Manually check the box if the Account record is a known subsidiary of another Account. Default is unchecked.</inlineHelpText>
    <label>Is Subsidiary?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Primary_R_T_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_R_T_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>i.e. 9 digits only, no formatting</inlineHelpText>
    <label>Primary RT Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FON_MembershipCalculator.cls
public without sharing class FON_MembershipCalculator {
    @AuraEnabled(cacheable=true)
    public static List<Account> getAccounts(String searchText) {
        String escapedSearchText = '%' + searchText.trim() + '%';
        return [
            SELECT Id, Name, Primary_R_T_Number__c, FON_Billing_Type__c, FON_Annual_Dues__c, FON_Is_Member__c,
            BillingAddress
            FROM Account WHERE Name LIKE :escapedSearchText AND FON_Billing_Type__c !='Exception'
            AND FON_Account_is_Archived__c = false AND FON_Is_Subsidiary__c = false AND Primary_R_T_Number__c != null
            LIMIT 50
        ];
    }
}