unpackaged/main/default/objects/Account/fields/FON_Charter_Number__c.field-meta.xml
<CustomField>
    <fullName>FON_Charter_Number__c</fullName>
    <label>Charter Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Organization_URL__c.field-meta.xml
<CustomField>
    <fullName>Organization_URL__c</fullName>
    <label>Organization URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Parent_Type__c.field-meta.xml
<CustomField>
    <fullName>Parent_Type__c</fullName>
    <inlineHelpText>Determines the type of Parent Account. This is not the same as Membership Type. Default is None. Must be populated manually.</inlineHelpText>
    <label>Parent Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sponsoring Organization</fullName>
            </value>
            <value>
                <fullName>Licensing Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Primary_R_T_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_R_T_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>i.e. 9 digits only, no formatting</inlineHelpText>
    <label>Primary RT Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TCH_Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>TCH_Membership_Type__c</fullName>
    <label>Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Member</fullName>
            </value>
            <value>
                <fullName>Participating Member</fullName>
            </value>
            <value>
                <fullName>Associate Member</fullName>
            </value>
            <value>
                <fullName>Affiliate Member</fullName>
            </value>
            <value>
                <fullName>Licensed Participant</fullName>
            </value>
            <value>
                <fullName>Sponsored Member</fullName>
            </value>
            <value>
                <fullName>Education Subscriber</fullName>
                <isActive>false</isActive>
                <label>Education Subscriber</label>
            </value>
            <value>
                <fullName>Licensing Organization</fullName>
                <isActive>false</isActive>
                <label>Licensing Organization</label>
            </value>
            <value>
                <fullName>Sponsoring Organization</fullName>
                <isActive>false</isActive>
                <label>Sponsoring Organization</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/OrderApi__Work_Phone__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Work_Phone__c</fullName>
    <description>The Work Phone for the Contact.</description>
    <inlineHelpText>The Work Phone for the Contact.</inlineHelpText>
    <label>Work Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Badge__c/OrderApi__Badge__c.object-meta.xml
<CustomObject>
    <description>Badges are assigned to Contacts either automatically (Badge Workflow) or manually. Badges can enable Contacts for special Price Rules - as well as permission to read, update, or delete certain content types.</description>
    <label>Badge</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Badge ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Badge__c/fields/OrderApi__Badge_Type__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Badge_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Badge Type</label>
    <referenceTo>OrderApi__Badge_Type__c</referenceTo>
    <relationshipLabel>Badges</relationshipLabel>
    <relationshipName>Badges</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Badge__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the assigned Contact.</description>
    <inlineHelpText>Link to the assigned Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Badges</relationshipLabel>
    <relationshipName>Badges</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Badge_Type__c/OrderApi__Badge_Type__c.object-meta.xml
<CustomObject>
    <description>Configure Badge Types to assign to Contacts to allow greater control and flexibility around pricing and content accessibility.</description>
    <label>Badge Type</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badge Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsoring_Relationships__c/Sponsoring_Relationships__c.object-meta.xml
<CustomObject>
    <label>Sponsored Relationship</label>
    <nameField>
        <displayFormat>SP- {0000}</displayFormat>
        <label>Sponsoring Relationships ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsored Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Agreement_URL__c.field-meta.xml
<CustomField>
    <fullName>Agreement_URL__c</fullName>
    <inlineHelpText>Filled in when invitation is sent.</inlineHelpText>
    <label>Agreement URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Agreement_URL_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Agreement_URL_Coordinator__c</fullName>
    <label>Agreement URL - Coordinator</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Application_Submission_Options__c.field-meta.xml
<CustomField>
    <fullName>Application_Submission_Options__c</fullName>
    <description>Selection of options provided to the SM Coordinator for how they will be submitting the Agreement.</description>
    <inlineHelpText>Selection of options provided to the SM Coordinator for how they will be submitting the Agreement. Scanning and Mailing Separately assume the Agreement is complete and ready for TCH to approve.</inlineHelpText>
    <label>Application Submission Options</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I Am Scanning and Attaching a PDF</fullName>
            </value>
            <value>
                <fullName>I Am Mailing the Executed Member Agreement</fullName>
            </value>
            <value>
                <fullName>I Am Sending an Invitation to the Potential Member to Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Charter_Number__c.field-meta.xml
<CustomField>
    <fullName>Charter_Number__c</fullName>
    <label>Charter Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Date_Submitted_for_Review__c.field-meta.xml
<CustomField>
    <fullName>Date_Submitted_for_Review__c</fullName>
    <description>*System Generated* Date when Sponsoring Organization (Parent Account) submitted agreement to their child for approval</description>
    <inlineHelpText>*System Generated* Date when Sponsoring Organization (Parent Account) submitted agreement to their child for approval</inlineHelpText>
    <label>Date Submitted for Review</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Executed_By_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Executed_By_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executed By Lookup</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sponsoring_Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Future_Notification_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Future_Notification_Address_City__c</fullName>
    <label>Future Notification Address City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Future_Notification_Address_Country__c.field-meta.xml
<CustomField>
    <fullName>Future_Notification_Address_Country__c</fullName>
    <label>Future Notification Address Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Future_Notification_Address_State__c.field-meta.xml
<CustomField>
    <fullName>Future_Notification_Address_State__c</fullName>
    <label>Future Notification Address State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Future_Notification_Address_Street__c.field-meta.xml
<CustomField>
    <fullName>Future_Notification_Address_Street__c</fullName>
    <label>Future Notification Address Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Future_Notification_Address_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Future_Notification_Address_Zip_Code__c</fullName>
    <label>Future Notification Address Zip Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Legal_Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Organization_Name__c</fullName>
    <inlineHelpText>This is the Name of the Account</inlineHelpText>
    <label>Organization</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Mailing_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address_City__c</fullName>
    <label>Mailing City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Mailing_Address_Street__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address_Street__c</fullName>
    <label>Mailing Street Address</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Mailing_Address_Zip_Code_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address_Zip_Code_Postal_Code__c</fullName>
    <label>Mailing Zip Code/Postal Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country__c</fullName>
    <label>Mailing Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <label>State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Organization_URL__c.field-meta.xml
<CustomField>
    <fullName>Organization_URL__c</fullName>
    <inlineHelpText>URL of the Account being sponsored for Membership</inlineHelpText>
    <label>Organization URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Primary_Contact_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Lookup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Looks up the Contact for the Primary Contact of a Sponsoring Relationship</inlineHelpText>
    <label>Primary Contact (Lookup)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sponsoring_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Primary_R_T_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_R_T_Number__c</fullName>
    <description>i.e. 9 digits only, no formatting</description>
    <inlineHelpText>9 digits only, no formatting</inlineHelpText>
    <label>Primary R/T Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Same_as_Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Same_as_Mailing_Address__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Same as Mailing Address</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsored_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsored_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sponsored Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsoring_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsoring_Organization__c</fullName>
    <label>Sponsoring Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application in Process</fullName>
                <default>true</default>
                <label>Application in Process</label>
            </value>
            <value>
                <fullName>Submitted to Sponsored Org Account for Review</fullName>
            </value>
            <value>
                <fullName>Submitted to Sponsoring Account for Final Review</fullName>
                <label>Submitted to Sponsoring Org for Final Review</label>
            </value>
            <value>
                <fullName>Final Approval by Sponsor</fullName>
            </value>
            <value>
                <fullName>Final Review by ECCHO Staff</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending Drop</fullName>
            </value>
            <value>
                <fullName>Expired/Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/FON_CreateSponsoringRelationshipCtl.cls
/**
 * @description       : 
 * @author            : Malik Gray
 * @group             : 
 * @last modified on  : 01-20-2021
 * @last modified by  : Malik Gray
 * Modifications Log 
 * Ver   Date         Author       Modification
 * 1.0   11-12-2020   Malik Gray   Initial Version
**/
global without sharing class FON_CreateSponsoringRelationshipCtl {
    @AuraEnabled(cacheable=true)
    public static Sponsoring_Relationships__c getSponsoringRelationship(String Id) {
        return [
            SELECT Id, Sponsoring_Organization__c, Sponsored_Organization__c, Primary_Contact_Lookup__c,
            Executed_By_Lookup__c, Mailing_Address_Street__c, Mailing_Address_City__c,
            Mailing_State__c, Mailing_Address_Zip_Code_Postal_Code__c, Mailing_Country__c,
            Future_Notification_Address_Street__c, Future_Notification_Address_City__c,
            Future_Notification_Address_State__c, Future_Notification_Address_Zip_Code__c,
            Future_Notification_Address_Country__c, Same_as_Mailing_Address__c,
            Legal_Organization_Name__c, Charter_Number__c, Organization_URL__c, Application_Submission_Options__c,
            Primary_R_T_Number__c, Status__c
            FROM Sponsoring_Relationships__c WHERE Id = :Id LIMIT 1
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Account getSponsoringOrganization(String Id) {
        return [SELECT Id, Name, Parent_Type__c, TCH_Membership_Type__c FROM Account WHERE Id = :Id LIMIT 1];
    }

    @AuraEnabled(cacheable=true)
    public static Account getSponsoredOrganization(String Id) {
        return [
            SELECT Id, Name, Primary_R_T_Number__c, FON_Charter_Number__c, Phone, Organization_URL__c
            //BillingCountryCode, BillingStateCode, BillingStreet, BillingCity, BillingPostalCode
            FROM Account WHERE Id = :Id LIMIT 1
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Contact getPrimaryContact(String Id) {
        return [
            SELECT Id, FirstName, LastName, Title, Email, OrderApi__Work_Phone__c 
            FROM Contact WHERE Id = :Id LIMIT 1
        ];
    }

    @AuraEnabled
    public static void createCommunityUser(String Id) {
        createCommunityUserAsync(Id);
    }

    @TestVisible @Future
    private static void createCommunityUserAsync(String Id) {
        System.debug('createCommunityUserAsync');
        
        Profile communityProfile = [
            SELECT Id FROM Profile
            WHERE Name = 'Fonteva Customer Community Login User' 
            LIMIT 1
        ];

        Contact contact = [
            SELECT Id, Email, FirstName, LastName FROM Contact
            WHERE Id = :Id
            LIMIT 1
        ];

        User user = new User(
            Username = contact.Email,
            FirstName = contact.FirstName,
            LastName = contact.LastName,
            Email = contact.Email,
            Alias = contact.FirstName.left(8),
            ContactId = Id,
            Profile = communityProfile,
            ProfileId = communityProfile.Id,
            EmailEncodingKey = 'UTF-8',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US'
        );

        System.debug('Profile ' + communityProfile);
        System.debug('Contact ' + contact);
        System.debug('CommunityUser ' + user);

        List<User> lstUser = new List<User>();
        lstUser.add(user);

        Database.DMLOptions dlo = new Database.DMLOptions();
        dlo.EmailHeader.triggerUserEmail = true;
        Database.insert(lstUser,dlo);
        //insert user;
    }

    @AuraEnabled
    public static Sponsoring_Relationships__c createSponsoringRelationship(
        Sponsoring_Relationships__c sponsoringRelationship,
        Contact contact
    ) {
        Savepoint savepoint = Database.setSavepoint();
        try {
            if(contact != null) {
                insert contact;
            }

            insert sponsoringRelationship;
        } catch (Exception ex) {
            System.debug('Found Exception: ' + ex.getMessage());

            Database.rollback(savepoint);
            return null;
        }

        return sponsoringRelationship;
    }

    @AuraEnabled
    public static Sponsoring_Relationships__c updateSponsoringRelationship(
        Sponsoring_Relationships__c sponsoringRelationship
    ) {
        Savepoint savepoint = Database.setSavepoint();
        try {
            update sponsoringRelationship;
        } catch (Exception ex) {
            Database.rollback(savepoint);
            throw new AuraHandledException(ex.getMessage());
        }

        return sponsoringRelationship;
    }

    @AuraEnabled(cacheable=false)
    public static String sendInvitation(String executedByContactId, String sponsoringRelationshipId, String message) {
        List<Contact> contacts = [SELECT Id, Name,FirstName,LastName, Email FROM Contact WHERE Id = :executedByContactId];
        List<OrderApi__Badge__c> badges = [
            SELECT Id, Name, OrderApi__Badge_Type__r.Name
            FROM OrderApi__Badge__c 
            WHERE OrderApi__Contact__c = :executedByContactId
            AND OrderApi__Badge_Type__r.Name = 'Sponsor Agreement Badge'
        ];
        List<Sponsoring_Relationships__c> sponsoringRelationships = [
            SELECT Id, Legal_Organization_Name__c,Sponsored_Organization__c,Sponsoring_Organization__c
            FROM Sponsoring_Relationships__c
            WHERE Id = :sponsoringRelationshipId
        ];
        Contact contact = contacts.get(0);

        // get contact user
        /*List<User> cusr = new List<User>();
        try {
            cusr = [SELECT Id FROM User WHERE ContactId = :executedByContactId];
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
        if (cusr.size() < 1) {
            User user = new User();
            user.ProfileID = [Select Id From Profile Where Name='Fonteva Customer Community Login User'].id;
            user.EmailEncodingKey = 'ISO-8859-1';
            user.LanguageLocaleKey = 'en_US';
            user.TimeZoneSidKey = 'America/New_York';
            user.LocaleSidKey = 'en_US';
            user.FirstName = contact.FirstName;
            user.LastName = contact.LastName;
            user.Username = contact.Email;   
            user.CommunityNickname = String.valueOf(contact.Id).substring(0,6);
            user.Alias = String.valueOf(contact.Id).substring(0,6);
            user.Email = contact.Email;
            user.IsActive = true;
            user.ContactId = contact.Id;
          
            insert user;
        }*/

        Sponsoring_Relationships__c sponsoringRelationship = sponsoringRelationships.get(0);
        sponsoringRelationship.Status__c = 'Submitted to Sponsored Org Account for Review';
        sponsoringRelationship.Date_Submitted_for_Review__c = System.today();

        // setup form url
        String formURL = Label.Sponsoring_Agreement_Form_URL;
        String formURLCo = Label.Sponsoring_Agreement_Form_Coordinator_URL;
        //formURL = formURL.replace('[sponsor]', sponsoringRelationship.Sponsoring_Organization__c);
        //formURL = formURL.replace('[member]', sponsoringRelationship.Sponsored_Organization__c);
        formURL = formURL.replace('[relationship]', sponsoringRelationship.Id);
        formURL = formURL + '&soid='+ String.valueOf(sponsoringRelationship.Sponsoring_Organization__c);
        formURLCo = formURLCo.replace('[relationship]', sponsoringRelationship.Id);
        //formURLCo = formURLCo + '&soid='+ String.valueOf(sponsoringRelationship.Sponsoring_Organization__c) + '&smid='+String.valueOf(sponsoringRelationship.Sponsored_Organization__c) + '&srid='+String.valueOf(sponsoringRelationship.Id);
        formURLCo = formURLCo + '&srid='+String.valueOf(sponsoringRelationship.Id);

        sponsoringRelationship.Agreement_URL__c = formURL;
        sponsoringRelationship.Agreement_URL_Coordinator__c = formURLCo;

        formURL = formURL + '&srid='+String.valueOf(sponsoringRelationship.Id);

        formURL = '<a href="' + formURL + '">' + formURL + '</a>';
        message = message.replace('[formURL]', formURL);



        List<OrderApi__Badge_Type__c> badgeTypes = [
            SELECT Id, Name
            FROM OrderApi__Badge_Type__c
            WHERE Name = 'Sponsor Agreement Badge'
        ];

        OrderApi__Badge_Type__c sponsorAgreementBadgeType;

        if(!badgeTypes.isEmpty()) {
            sponsorAgreementBadgeType = badgeTypes.get(0);
        }

        if(badges.isEmpty()) {
            // Create a new Sponsor Agreement Badge
        }
        
        try {
            List<String> toAddresses = new List<String> { contact.Email };
            //String subject = 'Email for ' + contact.Name + ' Sponsoring Agreement with ' + 
            //    sponsoringRelationship.Legal_Organization_Name__c;
            String subject = 'Please complete your ECCHO Sponsored Member Agreement';
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

            mail.setToAddresses(toAddresses);
            mail.setSubject(subject);
            mail.setHtmlBody(message);
            mail.setPlainTextBody(message);

            mail.setUseSignature(false);

            Messaging.SendEmailResult[] resultMail = Messaging.sendEmail(new List<Messaging.SingleEmailMessage> { mail });

            update sponsoringRelationship;

            //display success or error message
            String resp;
            if (resultMail[0].isSuccess()) {
                resp = 'ok sent!';
            } else {
                resp = resultMail[0].getErrors().get(0).getMessage();
            }

            return contact.Email;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
}