unpackaged/main/default/objects/Account/fields/FON_Account_is_Archived__c.field-meta.xml
<CustomField>
    <fullName>FON_Account_is_Archived__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This is a manual process. Check this box to archive a record. Default is unchecked. Used for reporting purposes and remove an Account as a potential option for member sponsorship</inlineHelpText>
    <label>Organization is Inactive</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/FON_Is_Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>FON_Is_Subsidiary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Manually check the box if the Account record is a known subsidiary of another Account. Default is unchecked.</inlineHelpText>
    <label>Is Subsidiary?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Primary_R_T_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_R_T_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>i.e. 9 digits only, no formatting</inlineHelpText>
    <label>Primary RT Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Additional_RT_Number__c/Additional_RT_Number__c.object-meta.xml
<CustomObject>
    <label>Additional RT Number</label>
    <nameField>
        <displayFormat>Add-{000000000}</displayFormat>
        <label>Additional RT Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional RT Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Additional_RT_Number__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>The Account the additional RT Number belongs to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Additional RT Numbers</relationshipLabel>
    <relationshipName>Additional_RT_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Additional_RT_Number__c/fields/Additional_RT_Number__c.field-meta.xml
<CustomField>
    <fullName>Additional_RT_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>9 digital RT Number. Primary is housed on the Account record.</inlineHelpText>
    <label>Additional RT Number</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FON_RTNSearchController.cls
/**
 * @description       : 
 * @author            : Malik Gray
 * @group             : 
 * @last modified on  : 01-20-2021
 * @last modified by  : Malik Gray
 * Modifications Log 
 * Ver   Date         Author       Modification
 * 1.0   01-20-2021   Malik Gray   Initial Version
**/
public without sharing class FON_RTNSearchController {
    public static String exactDigitsRequired = 'Please enter 9 digits for the R/T Number';
    public static String atLeast7DigitsRequired = 'Please enter at least 7 digits for the R/T Number';

    @AuraEnabled
    public static Account getSearchResults(String rtn, Boolean exactMatch) {
        Account account = null;

        if(String.isNotBlank(rtn)) {
            if(exactMatch) {
                if(rtn.length() != 9) {
                    throw new AuraHandledException(exactDigitsRequired);
                }

                account = searchByRTN(rtn);
            } else {
                if(rtn.length() < 7) {
                    throw new AuraHandledException(atLeast7DigitsRequired);
                }

                String calculatedRTN = FON_RTNCalculator.calculate(rtn);

                account = searchByRTN(calculatedRTN);
            }
        }

        return account;
    }

    private static Account searchByRTN(String rtn) {
        Account account = null;

        List<Account> accounts = [
            SELECT Id, Name, BillingCity, BillingState FROM Account 
            WHERE Primary_R_T_Number__c = :rtn
            AND FON_Account_is_Archived__c = false AND FON_Is_Subsidiary__c = false
        ];
        if(accounts.size() > 0) {
            account = accounts.get(0);
        } else {
            List<Account> additionalRTNAccounts = [
                SELECT Id, Name, BillingCity, BillingState FROM Account 
                WHERE  Id IN (SELECT Account__c FROM Additional_RT_Number__c WHERE Additional_RT_Number__c = :rtn)
            ];

            if(additionalRTNAccounts.size() > 0) {
                account = additionalRTNAccounts.get(0);
            }
        }

        return account;
    }
}