unpackaged/main/default/objects/Account/fields/OrderApi__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for the Account will auto-populate on all Account Transactions, Payments, etc... by default.</description>
    <inlineHelpText>The Primary Contact for the Account will auto-populate on all Account Transactions, Payments, etc... by default.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Contact Accounts</relationshipLabel>
    <relationshipName>Primary_Contact_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</description>
    <inlineHelpText>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Is_Subscription__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Subscription__c</fullName>
    <defaultValue>false</defaultValue>
    <description>** System Calculated Override ** Enable Subscription specific controls and features for this Item. Defaults to the value of the same field on the Item&#39;s related Item Class.</description>
    <inlineHelpText>** System Calculated Override ** Enable Subscription specific controls and features for this Item. Defaults to the value of the same field on the Item&#39;s related Item Class.</inlineHelpText>
    <label>Is Subscription</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reserved for future use.</description>
    <inlineHelpText>Reserved for future use.</inlineHelpText>
    <label>RESERVED</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item_Class__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Required ** Link to related Item Class</description>
    <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
    <label>Item Class</label>
    <referenceTo>OrderApi__Item_Class__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item_Class__c/OrderApi__Item_Class__c.object-meta.xml
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item_Class__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</description>
    <inlineHelpText>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item_Class__c/fields/OrderApi__Is_Subscription__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Subscription__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, Items created that are associated with this Item Class will automatically be
enabled with extra subscription related controls and features. Defaults unchecked.</description>
    <inlineHelpText>When checked, Items created that are associated with this Item Class will automatically be
enabled with extra subscription related controls and features. Defaults unchecked.</inlineHelpText>
    <label>Is Subscription</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>**System Calculated/Override** Checked when a recurring order or contract is active.</description>
    <inlineHelpText>**System Calculated/Override** Checked when a recurring order or contract is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Is_Subscription__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Subscription__c</fullName>
    <defaultValue>false</defaultValue>
    <description>** System Calculated ** Checked when the Sales Order Line is linked to a &quot;Subscription&quot; Item.</description>
    <inlineHelpText>** System Calculated ** Checked when the Sales Order Line is linked to a &quot;Subscription&quot; Item.</inlineHelpText>
    <label>Is Subscription</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the item related to the sales order.</description>
    <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
    <label>Item</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Item_Class__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** System Calculated / Override ** Link to the related Item Class.</description>
    <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
    <label>Item Class</label>
    <referenceTo>OrderApi__Item_Class__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Subscription_Plan__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Subscription_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required ** Link to the related plan that controls Activation and Expiration dates related to any Subscription Item. Required when the Sales Order Line is linked to a Item that is the child of a &quot;Subscription&quot; Item Class.</description>
    <inlineHelpText>** Conditionally Required ** Link to the related plan that controls Activation and Expiration dates related to any Subscription Item. Required when the Sales Order Line is linked to a Item that is the child of a &quot;Subscription&quot; Item Class.</inlineHelpText>
    <label>Subscription Plan</label>
    <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Subscription_Plan__c/OrderApi__Subscription_Plan__c.object-meta.xml
<CustomObject>
    <description>Subscription Plans control the subscription dates with &quot;Termed&quot;, &quot;Evergreen&quot;, and &quot;Calendar&quot; options.</description>
    <label>Subscription Plan</label>
    <nameField>
        <label>Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Subscription_Plan__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the Subscription Plan will be made available for selection - as configured for Subscription Plan Items.</description>
    <inlineHelpText>When checked, the Subscription Plan will be made available for selection - as configured for Subscription Plan Items.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/Sponsoring_Relationships__c.object-meta.xml
<CustomObject>
    <label>Sponsored Relationship</label>
    <nameField>
        <displayFormat>SP- {0000}</displayFormat>
        <label>Sponsoring Relationships ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsored Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Date_Accepted_by_ECCHO__c.field-meta.xml
<CustomField>
    <fullName>Date_Accepted_by_ECCHO__c</fullName>
    <description>Date ECCHO accepted agreement into membership</description>
    <inlineHelpText>Date ECCHO accepted agreement into membership. Denotes membership start date. Date needs to be manually populated by ECCHO Staff.</inlineHelpText>
    <label>Membership Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Primary_Contact_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Lookup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Looks up the Contact for the Primary Contact of a Sponsoring Relationship</inlineHelpText>
    <label>Primary Contact (Lookup)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sponsoring_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsored_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsored_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sponsored Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsoring_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsoring_Organization__c</fullName>
    <label>Sponsoring Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/CreateSalesOrderLineInvocableTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-02-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   04-02-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
@isTest 
public class CreateSalesOrderLineInvocableTest {

    private static User CreateTestCommunityUser(Id contactId) 
    {
        Profile targetProfile = [SELECT Id FROM Profile WHERE Name = 'Fonteva Customer Community Login User' LIMIT 1];
        User newUser = new User(
            FirstName = 'Test',
            LastName = 'Community User',
            Alias = 'cstuser',
            Email = 'createsponsortestuser@fonteva.com',
            LanguageLocaleKey = 'en_US',
            TimeZoneSidKey = 'America/Los_Angeles',
            ProfileId = targetProfile.Id,
            UserName = 'createsponsortestuser@fonteva.com',
            ContactId = contactId,
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8'
        );
        return newUser;
    }

    @TestSetup static void setup()
    {
        Account testSponsorAccount = new Account(name = 'Test Sponsoring Account');
        insert testSponsorAccount;

        Contact testContact = new Contact(FirstName = 'Test', LastName = 'Tester', Email = 'createsponsertest@fontevatest.com');
        insert testContact;

        Account testSponsoredAccount = new Account(Name = 'Test Sponsored Account', OrderApi__Primary_Contact__c = testContact.Id);
        insert testSponsoredAccount;

        testContact.AccountId = testSponsoredAccount.Id;
        update testContact;

        User testCommunityUser = [SELECT Id, ContactId, UserName FROM User WHERE ContactId != null LIMIT 1];

        Account test = [SELECT Id, OrderApi__Primary_Contact__c, OrderApi__Primary_Contact__r.FirstName, OrderApi__Primary_Contact__r.Email 
                        FROM Account 
                        WHERE Id=:testSponsoredAccount.Id 
                        LIMIT 1];

        OrderApi__Item_Class__c newItemClass = new OrderApi__Item_Class__c(Name = 'Test Item Class', 
                                                                            OrderApi__Is_Subscription__c = true, 
                                                                            OrderApi__Is_Active__c = true);
        insert newItemClass;

        OrderApi__Item__c newItem = new OrderApi__Item__c(Name = 'Test Item', 
                                                        OrderApi__Is_Subscription__c = true,
                                                        OrderApi__Item_Class__c = newItemClass.Id);
        insert newItem;

        OrderApi__Sales_Order__c testSalesOrder = new OrderApi__Sales_Order__c();
        insert testSalesOrder;

        OrderApi__Subscription_Plan__c testSubscriptionPlan = new OrderApi__Subscription_Plan__c();
        insert testSubscriptionPlan;

        System.runAs(CreateTestCommunityUser(testContact.Id))
        {
            Sponsoring_Relationships__c sponsorRelationship = new Sponsoring_Relationships__c(
                Sponsoring_Organization__c = testSponsoredAccount.Id,
                Sponsored_Organization__c = testSponsorAccount.Id,
                Primary_Contact_Lookup__c = testContact.Id,
                Date_Accepted_by_ECCHO__c = Date.today().addDays(-90)
            );
            insert sponsorRelationship;
        }
    }
    
    @isTest static void CreateSalesOrderLineInvocableTest_HappyPath() 
    {
        Sponsoring_Relationships__c sponsoringRelationship = [SELECT Id FROM Sponsoring_Relationships__c LIMIT 1];
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        OrderApi__Item__c testItem = [SELECT Id FROM OrderApi__Item__c LIMIT 1];
        OrderApi__Sales_Order__c testSO = [SELECT Id FROM OrderApi__Sales_Order__c LIMIT 1];
        OrderApi__Subscription_Plan__c testSubPlan = [SELECT Id FROM OrderApi__Subscription_Plan__c LIMIT 1];
        

        List<CreateSalesOrderLineInvocable.methodVars> argumentList = new List<CreateSalesOrderLineInvocable.methodVars>();
        CreateSalesOrderLineInvocable.methodVars arguments = new CreateSalesOrderLineInvocable.methodVars();

        arguments.quarter = '1QFull'; // options - 1Q, 2Q, 3Q, 4Q, 1QFull
        arguments.item = (String) testItem.Id;
        arguments.so = (String) testSO.Id;
        arguments.plan = (String) testSubPlan.Id;
        arguments.acc = (String) testAccount.Id;
        arguments.contact = (String) testContact.Id;
        arguments.rel = (String) sponsoringRelationship.Id;
        arguments.sups = new List<String>();
        arguments.timing = 'Annual';
        arguments.is_prorate = 'true';   // Test using an IsBlank = true value as well
        arguments.prev_sol =  '';    // Not needed unless quarter != '1QFull' OrderApi__Sales_Order_Line__c.Id
        arguments.year = '23';
        arguments.eDate = '';
        arguments.subQuarter = '2Q';

        argumentList.add(arguments);

        System.debug(arguments.rel);

        List<String> testSOLine = CreateSalesOrderLineInvocable.fetchSalesOrderLine(argumentList);
        System.assert(testSOLine != null);
    }

    @isTest static void CreateSalesOrderLineInvocableTest_isProrate() 
    {
        Test.startTest();
        Sponsoring_Relationships__c sponsoringRelationship = [SELECT Id FROM Sponsoring_Relationships__c LIMIT 1];
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        OrderApi__Item__c testItem = [SELECT Id FROM OrderApi__Item__c LIMIT 1];
        OrderApi__Sales_Order__c testSO = [SELECT Id FROM OrderApi__Sales_Order__c LIMIT 1];
        OrderApi__Subscription_Plan__c testSubPlan = [SELECT Id FROM OrderApi__Subscription_Plan__c LIMIT 1];
        Test.stopTest();

        List<CreateSalesOrderLineInvocable.methodVars> argumentList = new List<CreateSalesOrderLineInvocable.methodVars>();
        CreateSalesOrderLineInvocable.methodVars arguments = new CreateSalesOrderLineInvocable.methodVars();

        arguments.quarter = '1QFull'; // options - 1Q, 2Q, 3Q, 4Q, 1QFull
        arguments.item = (String) testItem.Id;
        arguments.so = (String) testSO.Id;
        arguments.plan = (String) testSubPlan.Id;
        arguments.acc = (String) testAccount.Id;
        arguments.contact = (String) testContact.Id;
        arguments.rel = (String) sponsoringRelationship.Id;
        arguments.sups = new List<String>();
        arguments.timing = 'Annual';
        arguments.is_prorate = ''; 
        arguments.prev_sol =  ''; 
        arguments.year = '23';
        arguments.eDate = '';
        arguments.subQuarter = '2Q';

        argumentList.add(arguments);

        System.debug(arguments.rel);

        List<String> testSOLine = CreateSalesOrderLineInvocable.fetchSalesOrderLine(argumentList);
        System.assert(testSOLine != null);
    }

    @isTest static void CreateSalesOrderLineInvocableTest_fixedDues() 
    {
        Test.startTest();
        Sponsoring_Relationships__c sponsoringRelationship = [SELECT Id FROM Sponsoring_Relationships__c LIMIT 1];
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        OrderApi__Item__c testItem = [SELECT Id FROM OrderApi__Item__c LIMIT 1];
        OrderApi__Sales_Order__c testSO = [SELECT Id FROM OrderApi__Sales_Order__c LIMIT 1];
        OrderApi__Subscription_Plan__c testSubPlan = [SELECT Id FROM OrderApi__Subscription_Plan__c LIMIT 1];
        Test.stopTest();

        List<CreateSalesOrderLineInvocable.methodVars> argumentList = new List<CreateSalesOrderLineInvocable.methodVars>();
        CreateSalesOrderLineInvocable.methodVars arguments = new CreateSalesOrderLineInvocable.methodVars();

        arguments.quarter = '1QFull'; // options - 1Q, 2Q, 3Q, 4Q, 1QFull
        arguments.item = (String) testItem.Id;
        arguments.so = (String) testSO.Id;
        arguments.plan = (String) testSubPlan.Id;
        arguments.acc = (String) testAccount.Id;
        arguments.contact = (String) testContact.Id;
        arguments.rel = (String) sponsoringRelationship.Id;
        arguments.sups = new List<String>();
        arguments.timing = 'Annual';
        arguments.is_prorate = '';   
        arguments.prev_sol =  '';    
        arguments.year = '23';
        arguments.eDate = '';
        arguments.subQuarter = '2Q';
        arguments.fixedDues = 0.05;

        argumentList.add(arguments);

        List<String> testSOLine = CreateSalesOrderLineInvocable.fetchSalesOrderLine(argumentList);
        System.assert(testSOLine != null);
    }
}