unpackaged/main/default/objects/Account/fields/OrderApi__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for the Account will auto-populate on all Account Transactions, Payments, etc... by default.</description>
    <inlineHelpText>The Primary Contact for the Account will auto-populate on all Account Transactions, Payments, etc... by default.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Contact Accounts</relationshipLabel>
    <relationshipName>Primary_Contact_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Badge__c/OrderApi__Badge__c.object-meta.xml
<CustomObject>
    <description>Badges are assigned to Contacts either automatically (Badge Workflow) or manually. Badges can enable Contacts for special Price Rules - as well as permission to read, update, or delete certain content types.</description>
    <label>Badge</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Badge ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Badge__c/fields/OrderApi__Badge_Type__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Badge_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Badge Type</label>
    <referenceTo>OrderApi__Badge_Type__c</referenceTo>
    <relationshipLabel>Badges</relationshipLabel>
    <relationshipName>Badges</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Badge_Type__c/OrderApi__Badge_Type__c.object-meta.xml
<CustomObject>
    <description>Configure Badge Types to assign to Contacts to allow greater control and flexibility around pricing and content accessibility.</description>
    <label>Badge Type</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badge Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsoring_Relationships__c/Sponsoring_Relationships__c.object-meta.xml
<CustomObject>
    <label>Sponsored Relationship</label>
    <nameField>
        <displayFormat>SP- {0000}</displayFormat>
        <label>Sponsoring Relationships ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsored Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Date the membership was terminated. To be manually populated by ECCHO staff</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Primary_Contact_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Lookup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Looks up the Contact for the Primary Contact of a Sponsoring Relationship</inlineHelpText>
    <label>Primary Contact (Lookup)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sponsoring_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsored_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsored_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sponsored Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsoring_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsoring_Organization__c</fullName>
    <label>Sponsoring Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/FON_CreateSponsoringRelationshipCtlTest.cls
@IsTest public class FON_CreateSponsoringRelationshipCtlTest 
{
    private static User CreateTestCommunityUser(Id sourceContactId, String lastName)
    {
        Profile targetProfile = [SELECT Id FROM Profile WHERE Name = 'Fonteva Customer Community Login User' LIMIT 1];
        return new User(
            FirstName='Test',
            LastName='Community User',
            Alias='cstuser',
            Email='createsponsortestuser@fonteva.com',
            LanguageLocaleKey='en_US',
            TimeZoneSidKey='America/Los_Angeles',
            ProfileId=targetProfile.Id,
            UserName='test' + Date.today().day() + Date.today().month() + Date.today().year() + 'createsponsor' + lastName + '@fonteva.com',
            ContactId=sourceContactId,
            LocaleSidKey='en_US',
            EmailEncodingKey='UTF-8'
        );
    }

    private static Sponsoring_Relationships__c InsertNewSponsorRelationship(Account sponsoringAccount, 
                                                                            Account sponsoredAccount, 
                                                                            Contact primaryContact,
                                                                            Boolean insertRecord)
    {
        Sponsoring_Relationships__c sponsorRelationship;

        System.runAs(CreateTestCommunityUser(primaryContact.Id, primaryContact.LastName))
        {
            sponsorRelationship = new Sponsoring_Relationships__c(
                Sponsoring_Organization__c = sponsoringAccount.Id,
                Sponsored_Organization__c = sponsoredAccount.Id,
                Primary_Contact_Lookup__c = primaryContact.Id
            );
            
            if (insertRecord)
            {
                insert sponsorRelationship;
            }
        }

        return sponsorRelationship;
    }

    @TestSetup static void Setup()
    {
        Account testSponsorAccount = new Account(Name='Test Sponsoring Account');
        insert testSponsorAccount;

        Contact testContact = new Contact(
            FirstName = 'CreateSponsor', 
            LastName = 'TestContact', 
            Email = 'auefheiufssgrrhshttrhth@adaffgrryjyjyj.com');
        insert testContact;

        Account testSponsoredAccount = new Account(
            Name='Test Sponsored Account', 
            OrderApi__Primary_Contact__c=testContact.Id);
        insert testSponsoredAccount;

        testContact.AccountId = testSponsoredAccount.Id;
        update testContact;

        InsertNewSponsorRelationship(testSponsorAccount, testSponsoredAccount, testContact, true);
    }

    @IsTest static void TestGetSponsoringRelationship()
    {
        Sponsoring_Relationships__c sponsorRelationship = [SELECT Id FROM Sponsoring_Relationships__c LIMIT 1];

        Test.startTest();
        Sponsoring_Relationships__c foundSponsorRecord = FON_CreateSponsoringRelationshipCtl.getSponsoringRelationship(sponsorRelationship.Id);
        Test.stopTest();

        System.assert(foundSponsorRecord != null);
        System.assertEquals(sponsorRelationship.Id, foundSponsorRecord.Id, 'The Received Record Id doesn\'t match the expected Id');
    }

    @IsTest static void TestGetSponsoringOrganization()
    {
        Account targetAccount = [SELECT Id FROM Account LIMIT 1];

        Test.startTest();
        Account receivedAccount = FON_CreateSponsoringRelationshipCtl.getSponsoringOrganization(targetAccount.Id);
        Test.stopTest();

        System.assert(receivedAccount != null);
        System.assertEquals(targetAccount.Id, receivedAccount.Id, 'The Received Record Id doesn\'t match the expected Id');
    }

    @IsTest static void TestGetSponsoredOrganization()
    {
        Account targetAccount = [SELECT Id FROM Account LIMIT 1];

        Test.startTest();
        Account receivedAccount = FON_CreateSponsoringRelationshipCtl.getSponsoredOrganization(targetAccount.Id);
        Test.stopTest();

        System.assert(receivedAccount != null);
        System.assertEquals(targetAccount.Id, receivedAccount.Id, 'The Received Record Id doesn\'t match the expected Id');
    }

    @IsTest static void TestGetPrimaryContact()
    {
        Contact targetContact = [SELECT Id FROM Contact LIMIT 1];

        Test.startTest();
        Contact receivedContact = FON_CreateSponsoringRelationshipCtl.getPrimaryContact(targetContact.Id);
        Test.stopTest();

        System.assert(receivedContact != null);
        System.assertEquals(targetContact.Id, receivedContact.Id, 'The Received Record Id doesn\'t match the expected Id');
    }

    @IsTest static void TestCreateCommunityUser()
    {
        User systemAdminUser = [SELECT Id FROM User WHERE Profile.Name='System Administrator' AND IsActive = true AND UserRoleId != null LIMIT 1];
        Account targetAccount = [SELECT Id FROM Account LIMIT 1];

        Contact newContact = new Contact(FirstName='Unique', LastName='Community Contact', Email='testcommunity222@test.com', AccountId=targetAccount.Id);
        insert newContact;

        System.runAs(systemAdminUser)
        {
            Test.startTest();
            FON_CreateSponsoringRelationshipCtl.CreateCommunityUser(newContact.Id); 
            Test.stopTest();
        }

        User createdUser = [SELECT Id, Email, UserName, ContactId, FirstName, LastName FROM User WHERE UserName = :newContact.Email LIMIT 1];

        System.assert(createdUser != null, 'A user with a UserName of ' + newContact.Email + ' was not created');
        System.assertEquals(newContact.Email, createdUser.UserName);
        System.assertEquals(newContact.Email, createdUser.Email);
        System.assertEquals(newContact.FirstName, createdUser.FirstName);
        System.assertEquals(newContact.LastName, createdUser.LastName);
        System.assertEquals(newContact.Id, createdUser.ContactId);
    }

    @IsTest static void TestCreateSponsoringRelationship()
    {
        Account sponsoringAccount = [SELECT Id FROM Account WHERE Name='Test Sponsoring Account' LIMIT 1];
        Account sponsoredAccount = [SELECT Id FROM Account WHERE Name='Test Sponsored Account' LIMIT 1];
        
        Contact primaryContact = new Contact(LastName='TestCreateSponsoringRelationshipContact', AccountId=sponsoringAccount.Id);
        insert primaryContact;

        Sponsoring_Relationships__c relationShipToInsert = new Sponsoring_Relationships__c(
            Sponsoring_Organization__c = sponsoringAccount.Id,
            Sponsored_Organization__c = sponsoredAccount.Id,
            Primary_Contact_Lookup__c = primaryContact.Id
        );

        Sponsoring_Relationships__c newRelationship;
        Integer contactCountBeforeTest = [SELECT count() FROM Contact];

        System.runAs(CreateTestCommunityUser(primaryContact.Id, primaryContact.LastName))
        {
            Test.startTest();
            newRelationship = FON_CreateSponsoringRelationshipCtl.createSponsoringRelationship(relationShipToInsert, new Contact(FirstName='New', 
                                                                                                                                LastName='Contact'));
            Test.stopTest();
        }

        Integer contactCountAfterTest = [SELECT count() FROM Contact];
        
        System.assert(contactCountAfterTest > contactCountBeforeTest, 'A new contact wasn\'t inserted');
        System.assert(newRelationship != null);
    }

    @IsTest static void TestUpdateSponsoringRelationship()
    {
        Account sponsoringAccount = [SELECT Id FROM Account WHERE Name='Test Sponsoring Account' LIMIT 1];
        Account sponsoredAccount = [SELECT Id FROM Account WHERE Name='Test Sponsored Account' LIMIT 1];
        
        Contact primaryContact = new Contact(LastName='TestUpdateSponsoringRelationship', AccountId=sponsoringAccount.Id);
        insert primaryContact;

        Sponsoring_Relationships__c initalRelationship = InsertNewSponsorRelationship(sponsoringAccount, sponsoredAccount, primaryContact, true);
        initalRelationship.End_Date__c = Date.today();

        Test.startTest();
        Sponsoring_Relationships__c updatedRelationship = FON_CreateSponsoringRelationshipCtl.updateSponsoringRelationship(initalRelationship);
        Test.stopTest();

        System.assertEquals(initalRelationship.End_Date__c, updatedRelationship.End_Date__c);
    }

    @IsTest static void TestSendInvitation()
    {
        OrderApi__Badge_Type__c sponsorBadgeType = new OrderApi__Badge_Type__c(
            Name='Sponsor Agreement Badge'
        );
        insert sponsorBadgeType;

        OrderApi__Badge__c sponsorBadge = new OrderApi__Badge__c(
            OrderApi__Badge_Type__c=sponsorBadgeType.Id
        );
        insert sponsorBadge;

        Contact invitationTestContact = new Contact(LastName='TestSendInvitationContact', Email='testsendinvitation@fontevatest.com');
        insert invitationTestContact;

        Sponsoring_Relationships__c sponsorRelationship = [SELECT Id FROM Sponsoring_Relationships__c LIMIT 1];
        String message = 'HERE IS [formURL]';

        String returnedEmail;

        Test.startTest();
        try {
            returnedEmail = FON_CreateSponsoringRelationshipCtl.sendInvitation(invitationTestContact.Id, sponsorRelationship.Id, message);
        } catch (Exception ex) {
            System.debug('Received Error: ' + ex.getMessage());
        }
        // System.assertEquals(1, Limits.getEmailInvocations(), 'No Email was sent out'); 
        Test.stopTest();

        // System.assertEquals(invitationTestContact.Email, returnedEmail);
    }
}