unpackaged/main/default/objects/Account/fields/Primary_R_T_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_R_T_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>i.e. 9 digits only, no formatting</inlineHelpText>
    <label>Primary RT Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/Sponsoring_Relationships__c.object-meta.xml
<CustomObject>
    <label>Sponsored Relationship</label>
    <nameField>
        <displayFormat>SP- {0000}</displayFormat>
        <label>Sponsoring Relationships ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsored Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Date_Accepted_by_ECCHO__c.field-meta.xml
<CustomField>
    <fullName>Date_Accepted_by_ECCHO__c</fullName>
    <description>Date ECCHO accepted agreement into membership</description>
    <inlineHelpText>Date ECCHO accepted agreement into membership. Denotes membership start date. Date needs to be manually populated by ECCHO Staff.</inlineHelpText>
    <label>Membership Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Primary_R_T_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_R_T_Number__c</fullName>
    <description>i.e. 9 digits only, no formatting</description>
    <inlineHelpText>9 digits only, no formatting</inlineHelpText>
    <label>Primary R/T Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsored_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsored_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sponsored Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsoring_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsoring_Organization__c</fullName>
    <label>Sponsoring Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application in Process</fullName>
                <default>true</default>
                <label>Application in Process</label>
            </value>
            <value>
                <fullName>Submitted to Sponsored Org Account for Review</fullName>
            </value>
            <value>
                <fullName>Submitted to Sponsoring Account for Final Review</fullName>
                <label>Submitted to Sponsoring Org for Final Review</label>
            </value>
            <value>
                <fullName>Final Approval by Sponsor</fullName>
            </value>
            <value>
                <fullName>Final Review by ECCHO Staff</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending Drop</fullName>
            </value>
            <value>
                <fullName>Expired/Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/FON_SponsoringRelationshipController.cls
/**
 * @description       : 
 * @author            : Malik Gray
 * @group             : 
 * @last modified on  : 12-22-2020
 * @last modified by  : Malik Gray
 * Modifications Log 
 * Ver   Date         Author       Modification
 * 1.0   12-14-2020   Malik Gray   Initial Version
**/
global without sharing class FON_SponsoringRelationshipController {
    @AuraEnabled(cacheable=true)
    public static List<Sponsoring_Relationships__c> getSponsoringRelationshipsBySponsoringOrganizationId(String Id) {
        return [
            SELECT Id, Sponsoring_Organization__r.Name, Sponsored_Organization__r.Name, Status__c,
            Primary_R_T_Number__c, Date_Accepted_by_ECCHO__c
            FROM Sponsoring_Relationships__c
            WHERE Sponsoring_Organization__c = :Id
            ORDER BY Sponsored_Organization__r.Name ASC
        ];
    }
}