unpackaged/main/default/objects/Account/fields/Primary_R_T_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_R_T_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>i.e. 9 digits only, no formatting</inlineHelpText>
    <label>Primary RT Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Deposits__c.field-meta.xml
<CustomField>
    <fullName>Total_Deposits__c</fullName>
    <inlineHelpText>The total deposit amount of this Account</inlineHelpText>
    <label>Total Deposits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Deposit_Based_Upload_Information__c/Deposit_Based_Upload_Information__c.object-meta.xml
<CustomObject>
    <description>When TCH uploads the deposit information into Fonteva from Accuity, it will be in this custom object.</description>
    <label>Deposit Based Upload Information</label>
    <nameField>
        <label>Deposit Based Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposit Based Uploads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Deposit_Based_Upload_Information__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Acquity_Deposit_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Deposit_Based_Upload_Information__c/fields/Primary_R_T_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_R_T_Number__c</fullName>
    <externalId>true</externalId>
    <label>Primary R/T Number</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Deposit_Based_Upload_Information__c/fields/Report_Source__c.field-meta.xml
<CustomField>
    <fullName>Report_Source__c</fullName>
    <label>Report Source</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Deposit_Based_Upload_Information__c/fields/Total_Deposits__c.field-meta.xml
<CustomField>
    <fullName>Total_Deposits__c</fullName>
    <label>Total Deposits</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/UpdateAccountTotalDepositBatchableTEST.cls
@isTest 
public class UpdateAccountTotalDepositBatchableTEST 
{
    static testMethod void testMethod1() 
    {
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('ECCHO Account').getRecordTypeId();
        Account acc = new Account(recordtypeId = devRecordTypeId,Name = 'Test Acc',Primary_R_T_Number__c = '12345678');
        insert acc;
        
        Deposit_Based_Upload_Information__c dp = new Deposit_Based_Upload_Information__c();
        dp.Account_Name__c = acc.Id;
        dp.Report_Date__c = system.today();
        dp.Report_Source__c = 'Sample';
        dp.Total_Deposits__c = 3333;
        dp.Primary_R_T_Number__c = '12345678';
        insert dp;
        
        Test.startTest();

            UpdateAccountTotalDepositBatchable obj = new UpdateAccountTotalDepositBatchable();
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
    }
}