unpackaged/main/default/objects/Account/fields/Primary_R_T_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_R_T_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>i.e. 9 digits only, no formatting</inlineHelpText>
    <label>Primary RT Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/Item_Based_Upload_Information__c.object-meta.xml
<CustomObject>
    <label>Item Based Upload Information</label>
    <nameField>
        <label>Item Based Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Based Uploads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Item Based Uploads</relationshipLabel>
    <relationshipName>Item_Based_Uploads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/FON_Total_Volume__c.field-meta.xml
<CustomField>
    <fullName>FON_Total_Volume__c</fullName>
    <label>Total Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Item Based Uploads (Parent)</relationshipLabel>
    <relationshipName>Item_Based_Uploads1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/Primary_R_T_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_R_T_Number__c</fullName>
    <formula>Account_Name__r.Primary_R_T_Number__c</formula>
    <inlineHelpText>Formula Field, populates the Primary R/T Number belonging to the Account populated in the lookup field</inlineHelpText>
    <label>Primary R/T Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1Q</fullName>
            </value>
            <value>
                <fullName>2Q</fullName>
            </value>
            <value>
                <fullName>3Q</fullName>
            </value>
            <value>
                <fullName>4Q</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/Sponsoring_Relationships__c.object-meta.xml
<CustomObject>
    <label>Sponsored Relationship</label>
    <nameField>
        <displayFormat>SP- {0000}</displayFormat>
        <label>Sponsoring Relationships ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsored Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Primary_R_T_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_R_T_Number__c</fullName>
    <description>i.e. 9 digits only, no formatting</description>
    <inlineHelpText>9 digits only, no formatting</inlineHelpText>
    <label>Primary R/T Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsored_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsored_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sponsored Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsoring_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsoring_Organization__c</fullName>
    <label>Sponsoring Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/UpdateSPVolumeBatchableTEST.cls
@isTest 
public class UpdateSPVolumeBatchableTEST 
{
    static testMethod void testMethod1() 
    {
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('ECCHO Account').getRecordTypeId();
        Account acc = new Account(recordtypeId = devRecordTypeId,Name = 'Test Acc',Primary_R_T_Number__c = '12345678');
        insert acc;
        
        Account acc2 = new Account(recordtypeId = devRecordTypeId,Name = 'Test Acc2',Primary_R_T_Number__c = '12345651');
        insert acc2;
        
        Sponsoring_Relationships__c sp = new Sponsoring_Relationships__c();
        sp.Sponsored_Organization__c = acc2.Id;
        sp.Sponsoring_Organization__c = acc.Id;
        insert sp;
        
        Item_Based_Upload_Information__c dp = new Item_Based_Upload_Information__c();
        dp.Account_Name__c = acc2.Id;
        dp.Parent__c = acc.Id;
        dp.Report_Date__c = system.today();
        dp.Report_Source__c = 'Sample';
        dp.FON_Total_Volume__c = 3333;
        dp.Rate__c = 0.00058;
        dp.Quarter__c = '1Q';
        insert dp;
        
        Test.startTest();

            UpdateSPVolumeBatchable obj = new UpdateSPVolumeBatchable();
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
    }
}