unpackaged/main/default/objects/Account/fields/Total_Deposits__c.field-meta.xml
<CustomField>
    <fullName>Total_Deposits__c</fullName>
    <inlineHelpText>The total deposit amount of this Account</inlineHelpText>
    <label>Total Deposits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Deposit_Based_Upload_Information__c/Deposit_Based_Upload_Information__c.object-meta.xml
<CustomObject>
    <description>When TCH uploads the deposit information into Fonteva from Accuity, it will be in this custom object.</description>
    <label>Deposit Based Upload Information</label>
    <nameField>
        <label>Deposit Based Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposit Based Uploads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Deposit_Based_Upload_Information__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Acquity_Deposit_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Deposit_Based_Upload_Information__c/fields/Total_Deposits__c.field-meta.xml
<CustomField>
    <fullName>Total_Deposits__c</fullName>
    <label>Total Deposits</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/AccountwithUpload.cls
public class AccountwithUpload {
    @invocableMethod
    
    public static void ItemBasedUploads(List <ID> ItemIds)
    {
        List<Deposit_Based_Upload_Information__c> Uploads = [select Id, Account_Name__c,Total_Deposits__c from Deposit_Based_Upload_Information__c where createddate = TODAY and id in: Itemids LIMIT 1];
        system.debug('IBU: '+ Uploads);

        For (Deposit_Based_Upload_Information__c IBU: Uploads){
            Account acc = new Account();
            system.debug('IBU ID:'+IBU.Id);
            //String IBUID = IBU.Sponsored_Relationship__c;
            try {
                acc = [select Id,Total_Deposits__c from Account where Id=:IBU.Account_Name__c LIMIT 1];
                acc.Total_Deposits__c = IBU.Total_Deposits__c;
                Update acc;
            } catch(DmlException e) {
                System.debug('SPwithVolume Error: ' + e.getMessage());
            }
        }
        
    }
}