unpackaged/main/default/objects/Account/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <inlineHelpText>*System Generated* The latest volume record uploaded into the &quot;Item Based Upload&quot; Object</inlineHelpText>
    <label>Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/Item_Based_Upload_Information__c.object-meta.xml
<CustomObject>
    <label>Item Based Upload Information</label>
    <nameField>
        <label>Item Based Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Based Uploads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Item Based Uploads</relationshipLabel>
    <relationshipName>Item_Based_Uploads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/FON_Total_Volume__c.field-meta.xml
<CustomField>
    <fullName>FON_Total_Volume__c</fullName>
    <label>Total Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/AccountwithVolume.cls
Public Class AccountwithVolume
{
@invocableMethod

public static void ItemBasedUploads(List <ID> ItemIds)
{
List<Item_Based_Upload_Information__C> ItemBasedUpload = [select id, Account_Name__C, FON_Total_Volume__C, Account_Name__r.ID, Account_Name__r.Volume__c from Item_Based_Upload_Information__C where createddate = TODAY and id in: Itemids];
List <Account> Acc = [select id, Name, Volume__C from account];
List <Account> Acc2 = New List <Account>();
For (Item_Based_Upload_Information__C IBU: ItemBasedUpload){
For (Account A: ACC){
IF (A.id==IBU.Account_Name__C){

    system.debug (a.name+' Account');
                              A.Volume__C = IBU.FON_Total_Volume__C;
                              Acc2.add(A);
                              }}}
                              Update ACC2;
                              }
                              }