unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/Total_Count_of_Lines__c.field-meta.xml
<CustomField>
    <fullName>Total_Count_of_Lines__c</fullName>
    <label>Total Count of Lines</label>
    <summaryForeignKey>OrderApi__Sales_Order_Line__c.OrderApi__Sales_Order__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/classes/FON_SalesOrderTrigger.cls
/**
 * Created by nkopparthi on 11/16/20.
 */

global without sharing class FON_SalesOrderTrigger extends Framework.Domain{

    public FON_SalesOrderTrigger(List<OrderApi__Sales_Order__c> sObjectList) {
        super(sObjectList);
    }

    global class Constructor implements Framework.Domain.DomainConstructor  {
        global Framework.Domain construct(List<SObject> sObjectList) {
            return new FON_SalesOrderTrigger(sObjectList);
        }
    }
    public override void afterInsert(){
        Framework.Log.push(FON_SalesOrderTrigger.class.getName(),'afterInsert');
        FON_SalesOrderService.generateCandidateId((OrderApi__Sales_Order__c []) records);
        Framework.Log.pop();
    }
    
    public override void afterUpdate(Map<Id,SObject> oldMap){
        Map<Id,OrderApi__Sales_Order__c> old = (Map<Id,OrderApi__Sales_Order__c>) oldMap;
        List<OrderApi__Sales_Order__c> recordsSO = (List<OrderApi__Sales_Order__c>) records;
        List<OrderApi__Sales_Order__c> checkCandidateId = new List<OrderApi__Sales_Order__c>();
        Framework.Log.push(FON_SalesOrderTrigger.class.getName(),'afterUpdate');
        FON_SalesOrderService.approveOldCredits((OrderApi__Sales_Order__c []) records, (Map<Id,OrderApi__Sales_Order__c>) oldMap);
        FON_SalesOrderService.ApproveApplications((OrderApi__Sales_Order__c []) records, (Map<Id,OrderApi__Sales_Order__c>) oldMap);
        for(OrderApi__Sales_Order__c so : recordsSO){
            if(so.Total_Count_of_Lines__c != old.get(so.Id).Total_Count_of_Lines__c){
                checkCandidateId.add(so);
            }
        }
        if(checkCandidateId.size() > 0){
            FON_SalesOrderService.generateCandidateId(checkCandidateId);
        }
        Framework.Log.pop();
    }
}