unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/FON_Actual_Sum__c.field-meta.xml
<CustomField>
    <fullName>FON_Actual_Sum__c</fullName>
    <label>Actual Sum</label>
    <summarizedField>OrderApi__Sales_Order_Line__c.OrderApi__Total__c</summarizedField>
    <summaryForeignKey>OrderApi__Sales_Order_Line__c.OrderApi__Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Overall_Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Overall_Total__c</fullName>
    <description>Overall Amount of Sales Order.</description>
    <inlineHelpText>Overall Amount of Sales Order.</inlineHelpText>
    <label>Overall Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Sales_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order_Status__c</fullName>
    <description>Status of the Sales Order</description>
    <formula>IF(ISPICKVAL(OrderApi__Posting_Entity__c,&#39;Invoice&#39;),
            IF(AND((OrderApi__Is_Cancelled__c), NOT(OrderApi__Is_Voided__c)),
            &#39;Cancelled&#39;,
            IF(AND(NOT(OrderApi__Is_Posted__c), NOT(OrderApi__Is_Voided__c)),
            &#39;Draft&#39;,
            IF(AND(OrderApi__Is_Closed__c, OrderApi__Is_Posted__c, NOT(OrderApi__Is_Voided__c),  TODAY() &gt; OrderApi__Due_Date__c, OrderApi__Balance_Due__c &gt; 0),
            &#39;Overdue&#39;,
            IF(AND( OrderApi__Balance_Due__c &gt; 0,OrderApi__Is_Closed__c, OrderApi__Is_Posted__c, NOT(OrderApi__Is_Voided__c)),
            &#39;Unpaid&#39;,
            IF(AND(OrderApi__Balance_Due__c &lt;= 0, NOT(OrderApi__Is_Voided__c),OrderApi__Is_Closed__c,OrderApi__Is_Posted__c),
            &#39;Paid&#39;,
            IF(OrderApi__Is_Voided__c,
            &#39;Voided&#39;,
            /*Default Value for Invoice*/
            &#39;&#39;)))))),
            /* Receipt Changes goes here */
            IF(ISPICKVAL(OrderApi__Posting_Entity__c,&#39;Receipt&#39;),
            IF(AND(NOT(OrderApi__Is_Closed__c), NOT(OrderApi__Is_Posted__c), NOT(OrderApi__Is_Voided__c)),
            &#39;Draft&#39;,
            IF(AND(OrderApi__Is_Closed__c, NOT(OrderApi__Is_Posted__c), NOT(OrderApi__Is_Voided__c),  TODAY() &gt; OrderApi__Due_Date__c, OrderApi__Balance_Due__c &gt; 0),
            &#39;Overdue&#39;,
            IF(AND(OrderApi__Is_Closed__c, NOT(OrderApi__Is_Posted__c), NOT(OrderApi__Is_Voided__c)),
            &#39;Unpaid&#39;,
            IF(AND(OrderApi__Balance_Due__c &lt;= 0, NOT(OrderApi__Is_Voided__c),OrderApi__Is_Closed__c,OrderApi__Is_Posted__c),
            &#39;Paid&#39;,
            IF(OrderApi__Is_Voided__c,
            &#39;Voided&#39;,
            /*Default Value for Receipt*/
            &#39;&#39;))))),
            &#39;&#39;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FONCalculateSOTotalBatchable.cls
global without sharing class FONCalculateSOTotalBatchable implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        if(Test.isRunningTest()){
            return Database.getQueryLocator([Select Id,OrderApi__Overall_Total__c,FON_Actual_Sum__c,OrderApi__Sales_Order_Status__c FROM OrderApi__Sales_Order__c]);
        }else{
            return Database.getQueryLocator([Select Id,OrderApi__Overall_Total__c,FON_Actual_Sum__c,OrderApi__Sales_Order_Status__c FROM OrderApi__Sales_Order__c WHERE OrderApi__Sales_Order_Status__c != 'Paid']);
        }
    }
    global void execute(Database.BatchableContext bc, List<OrderApi__Sales_Order__c> scope){

        List<OrderApi__Sales_Order__c> sos = new List<OrderApi__Sales_Order__c>();
        for (OrderApi__Sales_Order__c so : scope) {
            if( ( so.OrderApi__Overall_Total__c != so.FON_Actual_Sum__c && so.OrderApi__Sales_Order_Status__c != 'Paid' ) || Test.isRunningTest()){
                so.OrderApi__Overall_Total__c = so.FON_Actual_Sum__c;
                sos.add(so);
            }
        }
        if(sos.isEmpty() == false){
            update sos;
        }
        
    }
    
    global void finish(Database.BatchableContext bc){
        
    }    
    
}