unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Overall_Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Overall_Total__c</fullName>
    <description>Overall Amount of Sales Order.</description>
    <inlineHelpText>Overall Amount of Sales Order.</inlineHelpText>
    <label>Overall Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Overall_Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Overall_Total__c</fullName>
    <description>Overall Amount of Sales Order Line.</description>
    <inlineHelpText>Overall Amount of Sales Order Line.</inlineHelpText>
    <label>Overall Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/classes/FON_SalesOrderLineService.cls
public without sharing class FON_SalesOrderLineService {
    public static void recalculateTotal(List<OrderApi__Sales_Order_Line__c> records) {
		List<OrderApi__Sales_Order__c> usos = new List<OrderApi__Sales_Order__c>();
        Map<String, Decimal> mapSOLxTOTAL = new Map<String, Decimal>();
        Set<Id> soIDs = new Set<Id>();
        
        for(OrderApi__Sales_Order_Line__c sol : records){
            soIDs.add(sol.OrderApi__Sales_Order__c);
        }
        
        List<OrderApi__Sales_Order_Line__c> sols = [Select Id,OrderApi__Sales_Order__c,OrderApi__Overall_Total__c FROM OrderApi__Sales_Order_Line__c WHERE OrderApi__Sales_Order__c IN: soIDs];
        for(OrderApi__Sales_Order_Line__c sol : sols){
            Decimal total = mapSOLxTOTAL.get(sol.OrderApi__Sales_Order__c);
            if(total == null){
                mapSOLxTOTAL.put(sol.OrderApi__Sales_Order__c,sol.OrderApi__Overall_Total__c);
            }else{
                Decimal ntotal = total + sol.OrderApi__Overall_Total__c;
                mapSOLxTOTAL.remove(sol.OrderApi__Sales_Order__c);
                mapSOLxTOTAL.put(sol.OrderApi__Sales_Order__c,ntotal);
            }
        }
        
        if(soIDs.size()>0){
            for(OrderApi__Sales_Order__c so : [Select Id,OrderApi__Overall_Total__c FROM OrderApi__Sales_Order__c WHERE Id IN: soIDs]){
                so.OrderApi__Overall_Total__c = mapSOLxTOTAL.get(so.Id);
                usos.add(so);
            }
        }
        if(usos.size()>0){
            update usos;
        }
    }
}