unpackaged/main/default/objects/Item_Based_Upload_Information__c/Item_Based_Upload_Information__c.object-meta.xml
<CustomObject>
    <label>Item Based Upload Information</label>
    <nameField>
        <label>Item Based Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Based Uploads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Item Based Uploads</relationshipLabel>
    <relationshipName>Item_Based_Uploads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/FON_Total_Item_Based_Deposits__c.field-meta.xml
<CustomField>
    <fullName>FON_Total_Item_Based_Deposits__c</fullName>
    <inlineHelpText>populated from Acuity file</inlineHelpText>
    <label>Total Item Based Deposits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/FON_Total_Volume__c.field-meta.xml
<CustomField>
    <fullName>FON_Total_Volume__c</fullName>
    <label>Total Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Item Based Uploads (Parent)</relationshipLabel>
    <relationshipName>Item_Based_Uploads1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Item_Based_Upload_Information__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1Q</fullName>
            </value>
            <value>
                <fullName>2Q</fullName>
            </value>
            <value>
                <fullName>3Q</fullName>
            </value>
            <value>
                <fullName>4Q</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/Sponsoring_Relationships__c.object-meta.xml
<CustomObject>
    <label>Sponsored Relationship</label>
    <nameField>
        <displayFormat>SP- {0000}</displayFormat>
        <label>Sponsoring Relationships ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsored Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsored_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsored_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sponsored Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsoring_Relationships__c/fields/Sponsoring_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsoring_Organization__c</fullName>
    <label>Sponsoring Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sponsoring_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/SPwithVolumeTest.cls
@isTest
public class SPwithVolumeTest {
    @isTest static void getEvent() {
        Account acc = new Account();
        acc.Name = 'Test account';
        insert acc;
        
        Account acc2 = new Account();
        acc2.Name = 'Test account';
        insert acc2;
        
        Sponsoring_Relationships__c sp = new Sponsoring_Relationships__c();
        sp.Sponsored_Organization__c = acc.Id;
        sp.Sponsoring_Organization__c = acc2.Id;
        insert sp;
        
        Item_Based_Upload_Information__c ibu = new Item_Based_Upload_Information__c();
        ibu.Account_Name__c = acc.Id;
        ibu.Quarter__c = '1Q';
        ibu.Parent__c = acc2.Id;
        ibu.Rate__c = 0.00080;
        ibu.FON_Total_Item_Based_Deposits__c = 111111;
        ibu.FON_Total_Volume__c	 = 11111;
        ibu.Report_Source__c = 'test';
        insert ibu;
        
        List <ID> ibus = new List <ID>();
        ibus.add(ibu.Id);
       
        //SPwithVolume spv = new SPwithVolume();
        SPwithVolume.ItemBasedUploads(ibus);
        
    }
}