unpackaged/main/default/objects/CandidateId__c/CandidateId__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Candidate Id</label>
</CustomObject>

unpackaged/main/default/objects/CandidateId__c/fields/Candidate_Id_Number__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Id_Number__c</fullName>
    <label>Candidate Id Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CandidateId__c/fields/Candidate_Id_Text__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Id_Text__c</fullName>
    <label>Candidate Id Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FON_Exam_Year__c.field-meta.xml
<CustomField>
    <fullName>FON_Exam_Year__c</fullName>
    <label>Exam Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Event__c/EventApi__Event__c.object-meta.xml
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Event__c/fields/EventApi__Event_Key__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Event_Key__c</fullName>
    <description>This field is used as a unique identifier for events. The value in this field will also be used to concatenate item class names to be easily identified in lookup searches.</description>
    <inlineHelpText>This field is used as a unique identifier for events. The value in this field will also be used to concatenate item class names to be easily identified in lookup searches.</inlineHelpText>
    <label>Event Key</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/EventApi__Event__c/fields/Is_NCP_Exam__c.field-meta.xml
<CustomField>
    <fullName>Is_NCP_Exam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is NCP Exam</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__GL_Account__c/OrderApi__GL_Account__c.object-meta.xml
<CustomObject>
    <description>GL Accounting codes used for linking debits and credits with the appropriate codes.</description>
    <label>GL Account</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__GL_Account__c/fields/OrderApi__Business_Group__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Business_Group__c</fullName>
    <description>**Required** Master-Detail Relationship to Business Group.</description>
    <inlineHelpText>**Required** Master-Detail Relationship to Business Group.</inlineHelpText>
    <label>Business Group</label>
    <referenceTo>OrderApi__Business_Group__c</referenceTo>
    <relationshipLabel>Chart of Accounts</relationshipLabel>
    <relationshipName>GL_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/EventApi__Event__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to related Event.</description>
    <inlineHelpText>Link to related Event.</inlineHelpText>
    <label>Event</label>
    <referenceTo>EventApi__Event__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Business_Group__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Items can be related to Business Groups to separate business lines and/or legal entities on transactional (sales) and financial reports.</description>
    <inlineHelpText>Items can be related to Business Groups to separate business lines and/or legal entities on transactional (sales) and financial reports.</inlineHelpText>
    <label>Business Group</label>
    <referenceTo>OrderApi__Business_Group__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item_Class__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Required ** Link to related Item Class</description>
    <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
    <label>Item Class</label>
    <referenceTo>OrderApi__Item_Class__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item_Class__c/OrderApi__Item_Class__c.object-meta.xml
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item_Class__c/fields/EventApi__Event__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to related Event.</description>
    <inlineHelpText>Link to related Event.</inlineHelpText>
    <label>Event</label>
    <referenceTo>EventApi__Event__c</referenceTo>
    <relationshipLabel>Item Classes</relationshipLabel>
    <relationshipName>Item_Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item_Class__c/fields/OrderApi__Business_Group__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Group</label>
    <referenceTo>OrderApi__Business_Group__c</referenceTo>
    <relationshipLabel>Item Classes</relationshipLabel>
    <relationshipName>Item_Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Business_Group__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Link to the business group record - business groups will auto-populate if not defined on entry.</description>
    <inlineHelpText>**System Calculated/Override** Link to the business group record - business groups will auto-populate if not defined on entry.</inlineHelpText>
    <label>Business Group</label>
    <referenceTo>OrderApi__Business_Group__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</description>
    <inlineHelpText>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/EventApi__Event__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to related Event.</description>
    <inlineHelpText>Link to related Event.</inlineHelpText>
    <label>Event</label>
    <referenceTo>EventApi__Event__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Account__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Business_Group__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Default value is mapped from the parent sales order. The Business Group controls what items are available to associate with the order line. If no value exists, all active items will be allowed to be associated.</description>
    <inlineHelpText>**System Calculated/Override** Default value is mapped from the parent sales order. The Business Group controls what items are available to associate with the order line. If no value exists, all active items will be allowed to be associated.</inlineHelpText>
    <label>Business Group</label>
    <referenceTo>OrderApi__Business_Group__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__GL_Account__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Required/Override** Link to the related GL Account.</description>
    <inlineHelpText>**System Calculated/Required/Override** Link to the related GL Account.</inlineHelpText>
    <label>GL Account</label>
    <referenceTo>OrderApi__GL_Account__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/classes/FON_SalesOrder_Service_Test.cls
@isTest(SeeAllData=False)
public class FON_SalesOrder_Service_Test {
 public static Boolean isInstalled = false;
    
    @testSetup static void testSetup(){
        CandidateId__c newCI = new CandidateId__c();
        newCI.Candidate_Id_Number__c = 0;
        newCI.Candidate_Id_Text__c= 'HRNCP';
        insert newCI;
        
        Account acc = new Account();
        acc.Name = 'testAcc';
        insert acc;
        
        Contact cont = new Contact();
        cont.LastName = 'LastName';
        cont.AccountId = acc.Id;
        cont.FON_Exam_Year__c = system.today().year();
        insert cont;
        
        EventApi__Event__c event = new EventApi__Event__c();
        event.EventApi__Event_Key__c = 'test1238512';
        event.Is_NCP_Exam__c = true;
        event.Name = 'Exam Test';
        insert event;
        
        OrderApi__Sales_Order__c so = new OrderApi__Sales_Order__c();
        so.OrderApi__Account__c = acc.Id;
        so.OrderApi__Contact__c = cont.Id;
        insert so;
        
        OrderApi__Sales_Order_Line__c sol = new OrderApi__Sales_Order_Line__c();
        sol.EventApi__Event__c = event.Id;
        sol.OrderApi__Sales_Order__c = so.Id;
        sol.OrderApi__Account__c = acc.Id;
        sol.OrderApi__Contact__c = cont.Id;
        insert sol;
    }
    
    private static void install() {
            if (!isInstalled) {
                //Fon_PackageScripts.install();
                Framework.Installer.install();
                PagesApi.PackageScripts.install();
                OrderApi.PackageScripts.install();
                 EventApi.PackageScripts.install();
                
                // Create a routing rule for Contact
                Framework.RoutingRule[] rules = new List<Framework.RoutingRule>();
                Framework.RoutingRule cons = new Framework.RoutingRule();
                cons.apexClass = FON_SalesOrderTrigger.class.getName();
                cons.namespace = 'OrderApi';
                cons.isEnabled = true;
                cons.sObjectName = 'OrderApi__Sales_Order__c';
                cons.executionOrder = 0;
                rules.add(cons);
               
                Framework.Config.push(rules);  
                isInstalled = true;
               
            }
        }
        
    static testMethod void validateItemClassIns_Test() {
        
        Account acc = new Account();
        acc.name = 'AccName';
        insert acc;
        
        Account acc2 = new Account();
        acc2.name = 'Acc2Name';
        insert acc2;
        
        Contact con1 = new Contact();
        con1.Lastname = 'con1Lastname';
        con1.Firstname = 'testdata';
        con1.Email = 'test1@email.com';
        con1.AccountId = acc.ID;
        con1.FON_Exam_Year__c = system.today().year();
        insert con1;
        
        Contact con2 = new Contact();
        con2.Lastname = 'con2Lastname';
        con2.Firstname = 'testdata';
        con2.Email = 'test2@email.com';
        con2.AccountId = acc2.ID;
        con2.FON_Exam_Year__c = system.today().year();
        insert con2;
        
        Profile p = [select Id, Name from Profile where Name IN ('Fonteva Customer Community Login User') limit 1];
        
        User newUser = new User(
             profileId = p.id,
             username = 'newUser@yahoo.com',
             emailencodingkey = 'UTF-8',
             localesidkey = 'en_US',
             languagelocalekey = 'en_US',
             timezonesidkey = 'America/Los_Angeles',
             alias='nuser',
             lastname='lastname',
             contactId = con1.id
        );
        newUser.Email = 'test1@email.com';
        insert newUser;
                
        OrderApi__Business_Group__c BG1 =  new OrderApi__Business_Group__c();
        BG1.Name = 'BG1Name';
        insert BG1;
        
        OrderApi__GL_Account__c gl = new OrderApi__GL_Account__c();
        gl.OrderApi__Business_Group__c = BG1.id;
        insert gl;
        
        OrderApi__Item_Class__c itmc = new OrderApi__Item_Class__c();
        itmc.Name = 'Test Class';
        itmc.OrderApi__Is_Subscription__c=false;
        itmc.OrderApi__Enable_Assignments__c = false;
        itmc.OrderApi__Assignment_SObject__c = 'TEST__C';
        itmc.OrderApi__Business_Group__c = BG1.ID;
        itmc.OrderApi__Is_Active__c = true;
        insert itmc;     

        OrderApi__Item__c itm = new OrderApi__Item__c();
        itm.OrderApi__Price__c = 100;
        itm.OrderApi__Item_Class__c = itmc.Id;
        itm.OrderApi__Business_Group__c = BG1.Id;
        itm.Name = 'CE Credit Filing Fee';
        itm.OrderApi__Income_Account__c = gl.id;
        itm.OrderApi__Adjustment_Account__c = gl.id;
        itm.OrderApi__Refund_Account__c = gl.id;
        insert itm;                               
        
        Test.startTest();
        
        install();
        
        OrderApi__Sales_Order__c so = new OrderApi__Sales_Order__c();
        so.OrderApi__Contact__c = con1.Id;
        so.OrderApi__Account__c = acc.Id;
        so.OrderApi__Entity__c = 'Contact';
        so.OrderApi__Posting_Entity__c = 'Receipt';
        so.OrderApi__Business_Group__c = BG1.ID;
        so.OrderApi__Schedule_Type__c ='Simple Receipt';
        insert so;
        
        OrderApi__Sales_Order__c so2 = new OrderApi__Sales_Order__c();
        so2.OrderApi__Contact__c = con2.Id;
        so2.OrderApi__Account__c = acc2.Id;
        so2.OrderApi__Entity__c = 'Contact';
        so2.OrderApi__Posting_Entity__c = 'Receipt';
        so2.OrderApi__Business_Group__c = BG1.ID;
        so2.OrderApi__Schedule_Type__c ='Simple Receipt';
        insert so2;
        
        List<EventApi__Event__c> event = [SELECT Id FROM EventApi__Event__c];
        
        Contact contBefore = [SELECT Id, FON_NCP_Candidate_ID__c, FON_Candidate_Id_Generated_On__c FroM Contact WHERE Id =: con1.Id];
        system.assertEquals(contBefore.FON_NCP_Candidate_ID__c, null);
        system.assertEquals(contBefore.FON_Candidate_Id_Generated_On__c, null);
        
        List<OrderApi__Sales_Order_Line__c> lstSOL = new List<OrderApi__Sales_Order_Line__c>();
        OrderApi__Sales_Order_Line__c sol = new OrderApi__Sales_Order_Line__c();
        sol.OrderApi__Contact__c = con1.Id;
        sol.OrderApi__Account__c = acc.Id;
        sol.OrderApi__Sales_Order__c = so.Id;
        sol.OrderApi__Item__c = itm.Id;
        sol.OrderApi__Business_Group__c = BG1.ID;
        sol.EventApi__Event__c = event[0].Id;
        lstSOL.add(sol);
        
        insert lstSOL;
                
        Contact contUpdated = [SELECT Id, FON_NCP_Candidate_ID__c, FON_Candidate_Id_Generated_On__c FroM Contact WHERE Id =: con1.Id];
        system.assertNotEquals(contUpdated.FON_NCP_Candidate_ID__c, null);
        system.assertNotEquals(null, contUpdated.FON_Candidate_Id_Generated_On__c);
        
        
        OrderApi__Sales_Order_Line__c sol2 = new OrderApi__Sales_Order_Line__c();
        sol2.OrderApi__Contact__c = con1.Id;
        sol2.OrderApi__Account__c = acc.Id;
        sol2.OrderApi__Sales_Order__c = so.Id;
        sol2.OrderApi__Item__c = itm.Id;
        sol2.OrderApi__Business_Group__c = BG1.ID;
        sol2.EventApi__Event__c = event[0].Id;
        
        insert sol2;
                
        Contact contUpdated2 = [SELECT Id, FON_NCP_Candidate_ID__c, FON_Candidate_Id_Generated_On__c FroM Contact WHERE Id =: con1.Id];
        system.assertNotEquals(null, contUpdated2.FON_NCP_Candidate_ID__c);
        system.assertNotEquals(null, contUpdated2.FON_Candidate_Id_Generated_On__c);
                    
        OrderApi__Sales_Order_Line__c sol3 = new OrderApi__Sales_Order_Line__c();
        sol3.OrderApi__Contact__c = con2.Id;
        sol3.OrderApi__Account__c = acc2.Id;
        sol3.OrderApi__Sales_Order__c = so2.Id;
        sol3.OrderApi__Item__c = itm.Id;
        sol3.OrderApi__Business_Group__c = BG1.ID;
        sol3.EventApi__Event__c = event[0].Id;
        
        insert sol3;
                
        Contact contUpdated3 = [SELECT Id, FON_NCP_Candidate_ID__c, FON_Candidate_Id_Generated_On__c FroM Contact WHERE Id =: con2.Id];
        system.assertNotEquals(null, contUpdated3.FON_NCP_Candidate_ID__c);
        system.assertNotEquals(null, contUpdated3.FON_Candidate_Id_Generated_On__c);
        
        Test.stopTest();
       
        
   }
    
    
    
}