unpackaged/main/default/objects/EventApi__Event__c/EventApi__Event__c.object-meta.xml
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Event__c/fields/EventApi__End_Time__c.field-meta.xml
<CustomField>
    <fullName>EventApi__End_Time__c</fullName>
    <description>**Required** The event end time (HH:MM).</description>
    <inlineHelpText>**Required** The event end time (HH:MM).</inlineHelpText>
    <label>End Time</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Event__c/fields/EventApi__Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Start_Date_Time__c</fullName>
    <description>**Required** The event start date and time (mm/dd/yyyy hh:mm:ss).</description>
    <inlineHelpText>**Required** The event start date and time (mm/dd/yyyy hh:mm:ss).</inlineHelpText>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Event__c/fields/EventApi__Start_Time__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Start_Time__c</fullName>
    <description>**Required** The event start time (HH:MM).</description>
    <inlineHelpText>**Required** The event start time (HH:MM).</inlineHelpText>
    <label>Start Time</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Event__c/fields/EventApi__Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Time_Zone__c</fullName>
    <description>The time zone of the event location.</description>
    <inlineHelpText>The time zone of the event location.</inlineHelpText>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>(GMT+13:00) Pacific/Enderbury</fullName>
            </value>
            <value>
                <fullName>(GMT+13:00) Pacific/Tongatapu</fullName>
            </value>
            <value>
                <fullName>(GMT+12:45) Pacific/Chatham</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Asia/Kamchatka</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Pacific/Auckland</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Pacific/Fiji</fullName>
            </value>
            <value>
                <fullName>(GMT+11:30) Pacific/Norfolk</fullName>
            </value>
            <value>
                <fullName>(GMT+11:00) Pacific/Guadalcanal</fullName>
            </value>
            <value>
                <fullName>(GMT+10:30) Australia/Lord_Howe</fullName>
            </value>
            <value>
                <fullName>(GMT+10:00) Australia/Brisbane</fullName>
            </value>
            <value>
                <fullName>(GMT+10:00) Australia/Sydney</fullName>
            </value>
            <value>
                <fullName>(GMT+09:30) Australia/Adelaide</fullName>
            </value>
            <value>
                <fullName>(GMT+09:30) Australia/Darwin</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Asia/Seoul</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Asia/Tokyo</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Asia/Hong_Kong</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Asia/Kuala_Lumpur</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Asia/Manila</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Asia/Shanghai</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Asia/Singapore</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Asia/Taipei</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Australia/Perth</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Asia/Bangkok</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Asia/Ho_Chi_Minh</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Asia/Jakarta</fullName>
            </value>
            <value>
                <fullName>(GMT+06:30) Asia/Rangoon</fullName>
            </value>
            <value>
                <fullName>(GMT+06:00) Asia/Dhaka</fullName>
            </value>
            <value>
                <fullName>(GMT+05:45) Asia/Kathmandu</fullName>
            </value>
            <value>
                <fullName>(GMT+05:30) Asia/Colombo</fullName>
            </value>
            <value>
                <fullName>(GMT+05:30) Asia/Kolkata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EventApi__Registration_Item__c/EventApi__Registration_Item__c.object-meta.xml
<CustomObject>
    <description>Registration Items store the various products and break-out sessions for an Attendee.</description>
    <label>Registration Item</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Registration Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Registration_Item__c/fields/EventApi__Attendee__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Attendee__c</fullName>
    <description>** Required ** Master-detail link to the related Attendee.</description>
    <inlineHelpText>** Required ** Master-detail link to the related Attendee.</inlineHelpText>
    <label>Attendee</label>
    <referenceTo>EventApi__Attendee__c</referenceTo>
    <relationshipLabel>Registration Items</relationshipLabel>
    <relationshipName>Registration_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/EventApi__Registration_Item__c/fields/EventApi__Date__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Date__c</fullName>
    <description>** System Calculated ** The schedule date.</description>
    <formula>DATEVALUE( EventApi__Schedule_Item__r.EventApi__Start_Date_Time__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>** System Calculated ** The schedule date.</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Registration_Item__c/fields/EventApi__End_Time__c.field-meta.xml
<CustomField>
    <fullName>EventApi__End_Time__c</fullName>
    <description>** System Calculated ** The scheduled end time.</description>
    <formula>EventApi__Schedule_Item__r.EventApi__Session_End_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>** System Calculated ** The scheduled end time.</inlineHelpText>
    <label>End Time</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Registration_Item__c/fields/EventApi__Registration_Item__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Registration_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to related &quot;Parent Registration Item&quot;.</description>
    <inlineHelpText>Links to related &quot;Parent Registration Item&quot;.</inlineHelpText>
    <label>Registration Item</label>
    <referenceTo>EventApi__Registration_Item__c</referenceTo>
    <relationshipLabel>Registration Items</relationshipLabel>
    <relationshipName>Registration_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Registration_Item__c/fields/EventApi__Schedule_Item__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Schedule_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related schedule item.</description>
    <inlineHelpText>Link to the related schedule item.</inlineHelpText>
    <label>Schedule Item</label>
    <referenceTo>EventApi__Schedule_Item__c</referenceTo>
    <relationshipLabel>Registered Attendees</relationshipLabel>
    <relationshipName>Registration_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Registration_Item__c/fields/EventApi__Start_Time__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Start_Time__c</fullName>
    <description>** System Calculated ** The scheduled start time.</description>
    <formula>EventApi__Schedule_Item__r.EventApi__Session_Start_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>** System Calculated ** The scheduled start time.</inlineHelpText>
    <label>Start Time</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Schedule_Item__c/EventApi__Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Create and publish a schedule of activities configured for a given event.</description>
    <label>Schedule Item</label>
    <nameField>
        <label>Schedule Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Schedule_Item__c/fields/EventApi__End_Time__c.field-meta.xml
<CustomField>
    <fullName>EventApi__End_Time__c</fullName>
    <description>** System Calculated ** The scheduled end time.</description>
    <formula>IF(
  OR(
    VALUE( MID( TEXT( EventApi__End_Date_Time__c + (VALUE(SUBSTITUTE(SUBSTITUTE(LEFT(TEXT(EventApi__Event__r.EventApi__Time_Zone__c), 10),&quot;(GMT&quot;,&quot;&quot;),&quot;:&quot;,&quot;.&quot;))/24) ), 12, 2 ) ) = 0,
    VALUE( MID( TEXT( EventApi__End_Date_Time__c +  (VALUE(SUBSTITUTE(SUBSTITUTE(LEFT(TEXT(EventApi__Event__r.EventApi__Time_Zone__c), 10),&quot;(GMT&quot;,&quot;&quot;),&quot;:&quot;,&quot;.&quot;))/24) ), 12, 2 ) ) = 12
  ),
  &quot;12&quot;,
  TEXT( VALUE( MID( TEXT( EventApi__End_Date_Time__c +  (VALUE(SUBSTITUTE(SUBSTITUTE(LEFT(TEXT(EventApi__Event__r.EventApi__Time_Zone__c), 10),&quot;(GMT&quot;,&quot;&quot;),&quot;:&quot;,&quot;.&quot;))/24)), 12, 2 ) )
   -
   IF(
     VALUE( MID( TEXT( EventApi__End_Date_Time__c +  (VALUE(SUBSTITUTE(SUBSTITUTE(LEFT(TEXT(EventApi__Event__r.EventApi__Time_Zone__c), 10),&quot;(GMT&quot;,&quot;&quot;),&quot;:&quot;,&quot;.&quot;))/24) ), 12, 2 ) ) &lt; 12,
     0,
     12
   )
  )
)
&amp; &quot;:&quot; &amp;
MID( TEXT( EventApi__End_Date_Time__c +  (VALUE(SUBSTITUTE(SUBSTITUTE(LEFT(TEXT(EventApi__Event__r.EventApi__Time_Zone__c), 10),&quot;(GMT&quot;,&quot;&quot;),&quot;:&quot;,&quot;.&quot;))/24) ), 15, 2 )
&amp; &quot; &quot; &amp;
IF(
  VALUE( MID( TEXT( EventApi__End_Date_Time__c +  (VALUE(SUBSTITUTE(SUBSTITUTE(LEFT(TEXT(EventApi__Event__r.EventApi__Time_Zone__c), 10),&quot;(GMT&quot;,&quot;&quot;),&quot;:&quot;,&quot;.&quot;))/24) ), 12, 2 ) ) &lt; 12,
  &quot;AM&quot;,
  &quot;PM&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>** System Calculated ** The scheduled end time.</inlineHelpText>
    <label>End Time</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Schedule_Item__c/fields/EventApi__Event__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related event.</description>
    <inlineHelpText>Link to the related event.</inlineHelpText>
    <label>Event</label>
    <referenceTo>EventApi__Event__c</referenceTo>
    <relationshipLabel>Schedule</relationshipLabel>
    <relationshipName>Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Schedule_Item__c/fields/EventApi__Session_End_Time__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Session_End_Time__c</fullName>
    <description>**Required** The event end time (HH:MM).</description>
    <inlineHelpText>**Required** The event end time (HH:MM).</inlineHelpText>
    <label>End Time</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Schedule_Item__c/fields/EventApi__Session_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Session_Start_Time__c</fullName>
    <description>**Required** The event start time (HH:MM).</description>
    <inlineHelpText>**Required** The event start time (HH:MM).</inlineHelpText>
    <label>Start Time</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Schedule_Item__c/fields/EventApi__Start_Time__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Start_Time__c</fullName>
    <description>** System Calculated ** The scheduled start time.</description>
    <formula>IF(
  OR(
    VALUE( MID( TEXT( EventApi__Start_Date_Time__c + (VALUE(SUBSTITUTE(SUBSTITUTE(LEFT(TEXT(EventApi__Event__r.EventApi__Time_Zone__c), 10),&quot;(GMT&quot;,&quot;&quot;),&quot;:&quot;,&quot;.&quot;))/24) ), 12, 2 ) ) = 0,
    VALUE( MID( TEXT( EventApi__Start_Date_Time__c +  (VALUE(SUBSTITUTE(SUBSTITUTE(LEFT(TEXT(EventApi__Event__r.EventApi__Time_Zone__c), 10),&quot;(GMT&quot;,&quot;&quot;),&quot;:&quot;,&quot;.&quot;))/24) ), 12, 2 ) ) = 12
  ),
  &quot;12&quot;,
  TEXT( VALUE( MID( TEXT( EventApi__Start_Date_Time__c +  (VALUE(SUBSTITUTE(SUBSTITUTE(LEFT(TEXT(EventApi__Event__r.EventApi__Time_Zone__c), 10),&quot;(GMT&quot;,&quot;&quot;),&quot;:&quot;,&quot;.&quot;))/24)), 12, 2 ) )
   -
   IF(
     VALUE( MID( TEXT( EventApi__Start_Date_Time__c +  (VALUE(SUBSTITUTE(SUBSTITUTE(LEFT(TEXT(EventApi__Event__r.EventApi__Time_Zone__c), 10),&quot;(GMT&quot;,&quot;&quot;),&quot;:&quot;,&quot;.&quot;))/24) ), 12, 2 ) ) &lt; 12,
     0,
     12
   )
  )
)
&amp; &quot;:&quot; &amp;
MID( TEXT( EventApi__Start_Date_Time__c +  (VALUE(SUBSTITUTE(SUBSTITUTE(LEFT(TEXT(EventApi__Event__r.EventApi__Time_Zone__c), 10),&quot;(GMT&quot;,&quot;&quot;),&quot;:&quot;,&quot;.&quot;))/24) ), 15, 2 )
&amp; &quot; &quot; &amp;
IF(
  VALUE( MID( TEXT( EventApi__Start_Date_Time__c +  (VALUE(SUBSTITUTE(SUBSTITUTE(LEFT(TEXT(EventApi__Event__r.EventApi__Time_Zone__c), 10),&quot;(GMT&quot;,&quot;&quot;),&quot;:&quot;,&quot;.&quot;))/24) ), 12, 2 ) ) &lt; 12,
  &quot;AM&quot;,
  &quot;PM&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>** System Calculated ** The scheduled start time.</inlineHelpText>
    <label>Start Time</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/GetEventSessionsController.cls
public without sharing class GetEventSessionsController {
    
    public detailsWrapper wrapObj {get;set;}
    public string attendeeId {get; set;}
    
    public GetEventSessionsController() {
        getdisplaydata();
    }
    
    public void getdisplaydata(){
        
        List<EventApi__Registration_Item__c> sess = [SELECT Id, EventApi__Schedule_Item__r.EventApi__Event__r.EventApi__Time_Zone__c,EventApi__Schedule_Item__r.Name,EventApi__Schedule_Item__r.EventApi__Session_Start_Time__c,EventApi__Schedule_Item__r.EventApi__Session_End_Time__c,EventApi__Date__c,EventApi__Start_Time__c,EventApi__End_Time__c 
                                                               FROM EventApi__Registration_Item__c
                                                               WHERE EventApi__Attendee__c=:attendeeId AND EventApi__Schedule_Item__C != NULL 
                                                     			ORDER BY EventApi__Schedule_Item__r.EventApi__Start_Date_Time__c
                                                    ];
        
        // set event timezone
        
        system.debug('ACCTS '+sess);
        wrapObj = new detailsWrapper();
        
        //if(sess.size()>0){
        //    wrapObj.sessions = sess;
        //}  
        if (sess.size() > 0) {
        	wrapObj.sessions = sess;
            
            /*Map<Id,Map<String,Object>> fsessions = new Map<Id,Map<String,Object>>();
            for (EventApi__Registration_Item__c item : sess) {
                // get timezone
                String tz = item.EventApi__Schedule_Item__r.EventApi__Event__r.EventApi__Time_Zone__c;
                String targetTimeZone = tz.substringAfter(') ').trim();
                
                Map<String,Object> sesh = new Map<String,Object>();
                sesh.put('Name',item.EventApi__Schedule_Item__r.Name);
                sesh.put('EventApi__Date__c', (Date) convertToLocalTime(Datetime.newInstance(item.EventApi__Date__c.year(), item.EventApi__Date__c.month(), item.EventApi__Date__c.day()), targetTimeZone).date());
            	sesh.put('EventApi__Start_Time__c', convertToLocalTime(Datetime.newInstance(item.EventApi__Date__c.year(), item.EventApi__Date__c.month(), item.EventApi__Date__c.day(), item.EventApi__Start_Time__c.hour(), item.EventApi__Start_Time__c.minute(), item.EventApi__Start_Time__c.second()), targetTimeZone).time());
            	sesh.put('EventApi__End_Time__c',convertToLocalTime(Datetime.newInstanceGmt(item.EventApi__End_Time__c.year(), item.EventApi__End_Time__c.month(), item.EventApi__End_Time__c.day(), item.EventApi__End_Time__c.hour(), item.EventApi__End_Time__c.minute(), item.EventApi__End_Time__c.second()), targetTimeZone).time());
        	}*/
    	}     
    }

    public class detailsWrapper{
        @auraEnabled
        public List<EventApi__Registration_Item__c> sessions{get;set;}
        //@auraEnabled
        //public Map<Id,Map<String,String>> sessionObjects{get;set;}

        public detailsWrapper(){
            sessions = new List<EventApi__Registration_Item__c>();
            //sessionObjects = new Map<Id,Map<String,String>>();
        }
        
    }
    
    /*public Datetime convertToLocalTime(Datetime inputDateTime, String targetTimeZone) {
        TimeZone tz = TimeZone.getTimeZone(targetTimeZone);
        Integer offset = tz.getOffset(inputDateTime.getTime()) / 1000;
        return inputDateTime.addSeconds(offset);
    }*/


}