unpackaged/main/default/objects/EventApi__Event__c/EventApi__Event__c.object-meta.xml
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Event__c/fields/EventApi__Event_Key__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Event_Key__c</fullName>
    <description>This field is used as a unique identifier for events. The value in this field will also be used to concatenate item class names to be easily identified in lookup searches.</description>
    <inlineHelpText>This field is used as a unique identifier for events. The value in this field will also be used to concatenate item class names to be easily identified in lookup searches.</inlineHelpText>
    <label>Event Key</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/OrderApi__Renewal__c/OrderApi__Renewal__c.object-meta.xml
<CustomObject>
    <description>Terms track the Subscription terms, dates for all Customer Subscriptions.</description>
    <label>Term</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Term ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Renewal__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines the active subscription term.</description>
    <inlineHelpText>Defines the active subscription term.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Renewal__c/fields/OrderApi__Subscription__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Subscription__c</fullName>
    <description>** System Calculated Required ** Link to related Subscription</description>
    <inlineHelpText>** System Calculated Required ** Link to related Subscription</inlineHelpText>
    <label>Subscription</label>
    <referenceTo>OrderApi__Subscription__c</referenceTo>
    <relationshipLabel>Terms</relationshipLabel>
    <relationshipName>Renewals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Renewal__c/fields/OrderApi__Subscription_Plan__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Subscription_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>System Calculated Required Override ** Link to the Subscription Plan.</description>
    <inlineHelpText>** System Calculated ** Link to related Subscription Plan</inlineHelpText>
    <label>Subscription Plan</label>
    <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
    <relationshipLabel>Terms</relationshipLabel>
    <relationshipName>Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Subscription__c/OrderApi__Subscription__c.object-meta.xml
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Subscription__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</description>
    <inlineHelpText>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Subscription__c/fields/OrderApi__Paid_Through_Date__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Paid_Through_Date__c</fullName>
    <description>Defines the last active date of the subscription including all subscription renewals.</description>
    <inlineHelpText>Defines the last active date of the subscription including all subscription renewals.</inlineHelpText>
    <label>Paid Through Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Subscription__c/fields/OrderApi__Subscription_Plan__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Subscription_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Plan</label>
    <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Subscription_Plan__c/OrderApi__Subscription_Plan__c.object-meta.xml
<CustomObject>
    <description>Subscription Plans control the subscription dates with &quot;Termed&quot;, &quot;Evergreen&quot;, and &quot;Calendar&quot; options.</description>
    <label>Subscription Plan</label>
    <nameField>
        <label>Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Subscription_Plan__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the Subscription Plan will be made available for selection - as configured for Subscription Plan Items.</description>
    <inlineHelpText>When checked, the Subscription Plan will be made available for selection - as configured for Subscription Plan Items.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program__c/ProgramApi__Program__c.object-meta.xml
<CustomObject>
    <description>This object is used for the creation and management of programs.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program__c/fields/ProgramApi__Active__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Identifies program is active</description>
    <inlineHelpText>Identifies program is active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/MembershipTriggerHelperTest.cls
@isTest(SeeAllData=False)
public class MembershipTriggerHelperTest {
    @testSetup static void testSetup(){
        ProgramApi__Program__c progNCP = new ProgramApi__Program__c();
        progNCP.Name  = 'NCP';
        progNCP.ProgramApi__Active__c = true;
        insert progNCP;
        
        EventApi__Event__c ev = new EventApi__Event__c();
        ev.Name = 'event';
        ev.EventApi__Event_Key__c = 'dummyK3y3vTstC8';
        insert ev;
        
        Account acc = new Account();
        acc.Name = 'testAcc';
        insert acc;
        
        Account acc2 = new Account();
        acc2.Name = 'testAcc2';
        insert acc2;
        
        Contact cont = new Contact();
        cont.FirstName = 'First';
        cont.LastName = 'Last';
        cont.AccountId = acc.Id;
        insert cont;
        
        OrderApi__Subscription_Plan__c plan = new OrderApi__Subscription_Plan__c();
        insert plan;
        
        OrderApi__Subscription__c memb = new OrderApi__Subscription__c();
        memb.OrderApi__Subscription_Plan__c = plan.Id;
        insert memb;
        
        OrderApi__Renewal__c term = new OrderApi__Renewal__c();
        term.OrderApi__Is_Active__c = true;
        term.OrderApi__Subscription__c = memb.Id;
        term.OrderApi__Subscription_Plan__c = plan.Id;
        insert term;
        
    }
    @isTest static void testInsertTerm(){
        List<Account> accs = [SELECT Id FROM Account];
        List<Contact> conts = [SELECT Id FROM Contact];
        List<OrderApi__Renewal__c> terms = [SELECT Id, OrderApi__Is_Active__c FROM OrderApi__Renewal__c];
        List<OrderApi__Subscription__c> memb = [SELECT Id, OrderApi__Paid_Through_Date__c FROM OrderApi__Subscription__c];
        List<OrderApi__Subscription_Plan__c> plan = [SELECT Id FROM OrderApi__Subscription_Plan__c];
        
        system.assertEquals(1, terms.size());
        system.assertEquals(1, memb.size());
        system.assertEquals(1, plan.size());
        system.assertEquals(true, terms[0].OrderApi__Is_Active__c);
        system.assertEquals(null, memb[0].OrderApi__Paid_Through_Date__c);
        
        OrderApi__Renewal__c term = new OrderApi__Renewal__c();
        term.OrderApi__Is_Active__c = true;
        term.OrderApi__Subscription__c = memb[0].Id;
        term.OrderApi__Subscription_Plan__c = plan[0].Id;
        insert term;
        
        List<OrderApi__Renewal__c> termsAfterIns = [SELECT Id, OrderApi__Is_Active__c FROM OrderApi__Renewal__c ORDER BY CreatedDate DESC];
        List<OrderApi__Subscription__c> membAfterIns = [SELECT Id, OrderApi__Paid_Through_Date__c FROM OrderApi__Subscription__c];
        system.assertEquals(true, termsAfterIns[0].OrderApi__Is_Active__c);
        system.assertEquals(false, termsAfterIns[1].OrderApi__Is_Active__c);
        system.assertEquals(system.today(), membAfterIns[0].OrderApi__Paid_Through_Date__c);
    }
    
    @isTest static void testGenericUpdate(){
        List<OrderApi__Subscription__c> subs = [SELECT Id FROM OrderApi__Subscription__c];
                       
        update subs;
    }
    
    @isTest static void testGenericDelete(){
        List<OrderApi__Subscription__c> subs = [SELECT Id FROM OrderApi__Subscription__c];
                   
        delete subs;
        undelete subs;
    }
    
}