unpackaged/main/default/objects/ProgramApi__Program__c/ProgramApi__Program__c.object-meta.xml
<CustomObject>
    <description>This object is used for the creation and management of programs.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/ProgramApi__Program_Profile__c.object-meta.xml
<CustomObject>
    <description>This object maintains a single persona for each participant in a given program.</description>
    <label>Program Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Program Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/Allowed_Credits__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Credits__c</fullName>
    <label>Allowed Credits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/Allowed_Workshops__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Workshops__c</fullName>
    <label>Allowed Workshops</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_End_Date__c</fullName>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_Start_Date__c</fullName>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Contact to program profile; a Contact has only one profile for a program</description>
    <inlineHelpText>Identifies Contact to program profile; a Contact has only one profile for a program</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Create_Maintenance_Term__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Create_Maintenance_Term__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SYSTEM field; when enabled and record saved, creates new term and goals related to program maintenance requirements</description>
    <inlineHelpText>SYSTEM field; when enabled and record saved, creates new term and goals related to program maintenance requirements</inlineHelpText>
    <label>Create Maintenance Term</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Program__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Program related to a program profile</description>
    <inlineHelpText>Identifies Program related to a program profile</inlineHelpText>
    <label>Program</label>
    <referenceTo>ProgramApi__Program__c</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__SalesOrderLineId__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__SalesOrderLineId__c</fullName>
    <description>System field to process the sales order line.</description>
    <inlineHelpText>System field to process the sales order line.</inlineHelpText>
    <label>SalesOrderLineId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Status__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Status__c</fullName>
    <description>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</description>
    <inlineHelpText>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Track</fullName>
                <default>true</default>
                <label>On Track</label>
            </value>
            <value>
                <fullName>Cautionary</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending Revocation</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/Renewed_on_New_Year__c.field-meta.xml
<CustomField>
    <fullName>Renewed_on_New_Year__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewed on New Year</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/ProgramApi__Program_Term__c.object-meta.xml
<CustomObject>
    <description>This object establishes the length of time given to complete tasks.</description>
    <label>Program Term</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Program Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/FON_Allowed_Credits__c.field-meta.xml
<CustomField>
    <fullName>FON_Allowed_Credits__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Allowed Credits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/FON_Allowed_Workshops__c.field-meta.xml
<CustomField>
    <fullName>FON_Allowed_Workshops__c</fullName>
    <defaultValue>2</defaultValue>
    <label>Allowed Workshops</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__End_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__End_Date__c</fullName>
    <description>Identifies the term end date; Date all goals must be completed to successfully complete program</description>
    <inlineHelpText>Identifies the term end date; Date all goals must be completed to successfully complete program</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Is_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Is_Maintenance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines a term to be a maintenance term.</description>
    <inlineHelpText>Defines a term to be a maintenance term.</inlineHelpText>
    <label>Is Maintenance</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Profile__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SYSTEM. Relates the program profile to the term</description>
    <inlineHelpText>SYSTEM. Relates the program profile to the term</inlineHelpText>
    <label>Program Profile</label>
    <referenceTo>ProgramApi__Program_Profile__c</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Start_Date__c</fullName>
    <description>Identifies the term start date</description>
    <inlineHelpText>Identifies the term start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/ProgramProfilesTriggerHelper.cls
public without sharing class ProgramProfilesTriggerHelper {
    public ProgramProfilesTriggerHelper(){
        System.debug('Inside ProgramProfilesTriggerHelper Constructor');
    }
    
    public void setDefaults(List<ProgramApi__Program_Profile__c> records){
        List<ProgramApi__Program_Term__c> ptList = new List<ProgramApi__Program_Term__c>();
        Date currentDate = system.today();
        List<ProgramApi__Program_Profile__c> cppList = [
            SELECT Id,ProgramApi__Contact__c,
            ProgramApi__Program__r.Name,
            ProgramApi__SalesOrderLineId__c,
            FON_Program_Start_Date__c,
            FON_Program_End_Date__c,
            ProgramApi__Status__c,
            Renewed_on_New_Year__c,
            ProgramApi__Create_Maintenance_Term__c
            FROM ProgramApi__Program_Profile__c
            WHERE ProgramApi__Contact__c =: records[0].ProgramApi__Contact__c
        ];
        
        for(ProgramApi__Program_Profile__c pp : records){
            System.debug('pp ' + pp);
            if(pp.ProgramApi__Program__r.Name == 'NCP' || Test.isRunningTest() ){
                if(pp.FON_Program_Start_Date__c == null)
                    pp.FON_Program_Start_Date__c = Date.newInstance(currentDate.year(), 1, 1);
                if(pp.FON_Program_End_Date__c == null)
                    pp.FON_Program_End_Date__c = Date.newInstance(currentDate.year() + 4, 12, 31);
                if(pp.Allowed_Credits__c == null)
                    pp.Allowed_Credits__c = Decimal.valueOf(System.Label.Allowed_Credits_NCP);
                if(pp.Allowed_Workshops__c == null)
                    pp.Allowed_Workshops__c = Decimal.valueOf(System.Label.Allowed_Workshops_NCP);
                if(cppList.isEmpty()){
                    pp.ProgramApi__Status__c = 'On Track';
                }else{
                    pp.ProgramApi__Status__c = 'Maintenance';
                }
            }
        }
    }
    
    
    public void setTerms(List<ProgramApi__Program_Profile__c> records){
        Date currentDate = system.today();
        
        Set<Id> ppIds = new Set<Id>();
        List<ProgramApi__Program_Profile__c> ppList = new List<ProgramApi__Program_Profile__c>();
        
        for(ProgramApi__Program_Profile__c pp : records){
            ppIds.add(pp.Id);
        }
        
        ppList = [
            SELECT Id,ProgramApi__Contact__c,
            ProgramApi__Program__r.Name,
            ProgramApi__SalesOrderLineId__c,
            FON_Program_Start_Date__c,
            FON_Program_End_Date__c,
            ProgramApi__Status__c,
            Renewed_on_New_Year__c,
            ProgramApi__Create_Maintenance_Term__c
            FROM ProgramApi__Program_Profile__c
            WHERE Id IN :ppIds
        ];
        List<ProgramApi__Program_Term__c> pTermDefault = [SELECT Id, Name FROM ProgramApi__Program_Term__c WHERE ProgramApi__Profile__c =: ppIds AND ProgramApi__Is_Maintenance__c = TRUE];
        System.debug('pTermDefault '+pTermDefault);
        
        
        List<ProgramApi__Program_Term__c> pTerms = new List<ProgramApi__Program_Term__c>();
        for(ProgramApi__Program_Profile__c pp : ppList){
            if(pp.ProgramApi__Program__r.Name == 'NCP'){
                if(pp.FON_Program_End_Date__c == null || pp.FON_Program_Start_Date__c == null){
                    continue;
                }
                Integer amountOfTerms = pp.FON_Program_End_Date__c.year() - pp.FON_Program_Start_Date__c.year();
                for (Integer i = 0; i <= amountOfTerms; i++) {
                    ProgramApi__Program_Term__c ppterm = new ProgramApi__Program_Term__c();
                    ppterm.ProgramApi__Profile__c = pp.Id;
                    ppterm.Contact__c = pp.ProgramApi__Contact__c;
                    ppterm.FON_Allowed_Workshops__c = Decimal.valueOf(System.Label.Allowed_Workshops_in_1_year_NCP);
                    ppterm.FON_Allowed_Credits__c = Decimal.valueOf(System.Label.Allowed_Credits_for_1_year_NCP);
                    if(i == 0 && !pTermDefault.isEmpty()) {
                        ppterm.ProgramApi__Is_Maintenance__c = TRUE;
                    }
                    if(i == 0) {
						ppterm.ProgramApi__Start_Date__c = Date.newInstance(pp.FON_Program_Start_Date__c.year() + i, 4, 1);
                    }else{
                        if(pp.Renewed_on_New_Year__c){
                            ppterm.ProgramApi__Start_Date__c = Date.newInstance(pp.FON_Program_Start_Date__c.year() + i, 1, 1);
    
                        }else{
                            if(pp.ProgramApi__Status__c == 'Maintenance'){
                                ppterm.ProgramApi__Start_Date__c = Date.newInstance(pp.FON_Program_Start_Date__c.year() + i, 1, 1);
                            }else{
                                Integer testvar = 0;
                                testvar++;
                                testvar++;
                                testvar++;
                                testvar++;
                                ppterm.ProgramApi__Start_Date__c = Date.newInstance(pp.FON_Program_Start_Date__c.year() + i, 1, 1);
                            }
                            
                        }
                    }
                    ppterm.ProgramApi__End_Date__c = Date.newInstance(pp.FON_Program_Start_Date__c.year() + i, 12, 31);
                    pTerms.add(ppterm);
                }
            }
        }
        
        if(!pTerms.isEmpty()){
            insert pTerms;
        }
        
        if(!pTermDefault.isEmpty()){
        delete pTermDefault;
        }
        
        
    }
}