unpackaged/main/default/objects/ProgramApi__Program__c/ProgramApi__Program__c.object-meta.xml
<CustomObject>
    <description>This object is used for the creation and management of programs.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/ProgramApi__Program_Profile__c.object-meta.xml
<CustomObject>
    <description>This object maintains a single persona for each participant in a given program.</description>
    <label>Program Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Program Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_End_Date__c</fullName>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_Start_Date__c</fullName>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Account__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</description>
    <inlineHelpText>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Contact to program profile; a Contact has only one profile for a program</description>
    <inlineHelpText>Identifies Contact to program profile; a Contact has only one profile for a program</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Program__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Program related to a program profile</description>
    <inlineHelpText>Identifies Program related to a program profile</inlineHelpText>
    <label>Program</label>
    <referenceTo>ProgramApi__Program__c</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Status__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Status__c</fullName>
    <description>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</description>
    <inlineHelpText>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Track</fullName>
                <default>true</default>
                <label>On Track</label>
            </value>
            <value>
                <fullName>Cautionary</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending Revocation</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/Registration_Origin__c.field-meta.xml
<CustomField>
    <fullName>Registration_Origin__c</fullName>
    <label>Registration Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Registrant</fullName>
                <default>true</default>
                <label>New Registrant</label>
            </value>
            <value>
                <fullName>Retake</fullName>
            </value>
            <value>
                <fullName>Transfer In (from a different year)</fullName>
            </value>
            <value>
                <fullName>Transfer In (from a different person)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/Renewed_on_New_Year__c.field-meta.xml
<CustomField>
    <fullName>Renewed_on_New_Year__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewed on New Year</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/RenewPPsNewYearsBatch.cls
global class RenewPPsNewYearsBatch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Integer lastYear = Date.today().year() - 1;

        String query = 'SELECT Id, FON_Program_End_Date__c, FON_Program_Start_Date__c, ProgramApi__Account__c, ProgramApi__Contact__c, ProgramApi__Program__c FROM ProgramApi__Program_Profile__c ' + 
            'WHERE CALENDAR_YEAR(FON_Program_End_Date__c) = '+ lastYear;
        //String query = 'SELECT Id, FON_Program_End_Date__c, FON_Program_Start_Date__c, ProgramApi__Account__c, ProgramApi__Contact__c, ProgramApi__Program__c FROM ProgramApi__Program_Profile__c ' + 
        //    'WHERE Id = \'a1t6g000000GbCfAAK\'';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<ProgramApi__Program_Profile__c> pps) {
		Date currentDate = Date.today();
        Integer currentYear = Date.today().year();
        List<ProgramApi__Program_Profile__c> ppsNewYear = [SELECT Id, ProgramApi__Contact__c 
                                                           FROM ProgramApi__Program_Profile__c 
                                                           WHERE CALENDAR_YEAR(FON_Program_Start_Date__c) =: currentYear];
        Set<String> contsWithPPs = new Set<String>();
        for(ProgramApi__Program_Profile__c p : ppsNewYear){
            contsWithPPs.add(p.ProgramApi__Contact__c);
        }
        List<ProgramApi__Program_Profile__c> ppsToInsert = new List<ProgramApi__Program_Profile__c>();
        for(ProgramApi__Program_Profile__c pp : pps){
            if(contsWithPPs.contains(pp.ProgramApi__Contact__c)){
                continue;
            }
            ProgramApi__Program_Profile__c newPP = new ProgramApi__Program_Profile__c();
            newPP.ProgramApi__Account__c = pp.ProgramApi__Account__c;
            newPP.ProgramApi__Contact__c = pp.ProgramApi__Contact__c;
            newPP.ProgramApi__Program__c = pp.ProgramApi__Program__c;
            newPP.ProgramApi__Status__c = 'On Track';
            newPP.FON_Program_Start_Date__c = date.newInstance(currentDate.year(), 1, 1);
            newPP.FON_Program_End_Date__c = date.newInstance(currentDate.year() + 4, 12, 31);
            newPP.Renewed_on_New_Year__c = true;
            newPP.Registration_Origin__c = null;
            ppsToInsert.add(newPP);
        }
        if(ppsToInsert.size() > 0)
            insert ppsToInsert;
    }

    global void finish(Database.BatchableContext BC) {
    }
}