unpackaged/main/default/objects/ProgramApi__Program__c/ProgramApi__Program__c.object-meta.xml
<CustomObject>
    <description>This object is used for the creation and management of programs.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program__c/fields/ProgramApi__Active__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Identifies program is active</description>
    <inlineHelpText>Identifies program is active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/ProgramApi__Program_Profile__c.object-meta.xml
<CustomObject>
    <description>This object maintains a single persona for each participant in a given program.</description>
    <label>Program Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Program Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_End_Date__c</fullName>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_Start_Date__c</fullName>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Account__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</description>
    <inlineHelpText>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Contact to program profile; a Contact has only one profile for a program</description>
    <inlineHelpText>Identifies Contact to program profile; a Contact has only one profile for a program</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Program__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Program related to a program profile</description>
    <inlineHelpText>Identifies Program related to a program profile</inlineHelpText>
    <label>Program</label>
    <referenceTo>ProgramApi__Program__c</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/RenewNewYearBatch_Test.cls
@IsTest(SeeAllData = false)
public class RenewNewYearBatch_Test {
    @IsTest
    public static void testNewYear(){
        ProgramApi__Program__c progNCP = new ProgramApi__Program__c();
        progNCP.Name  = 'NCP';
        progNCP.ProgramApi__Active__c = true;
        insert progNCP;
        
        Date currentDate = system.today();
        //Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('ECCHO Account').getRecordTypeId();
        
        Account acc = new Account(Name = 'Test Acc');
        insert acc;
        
        Contact con = new contact(LastName='Test Con',AccountId = acc.Id);
        insert con;
        
        ProgramApi__Program_Profile__c pp = new ProgramApi__Program_Profile__c();
        pp.ProgramApi__Account__c = acc.Id;
        pp.ProgramApi__Contact__c = con.Id;
        pp.ProgramApi__Program__c = progNcp.Id;
        pp.FON_Program_Start_Date__c = Date.newInstance(currentDate.year() - 2, 1, 1);
        pp.FON_Program_End_Date__c = Date.newInstance(currentDate.year() - 1, 1, 1);
        insert pp;
             
        List<ProgramApi__Program_Profile__c> pps = [SELECT Id 
                                              FROM ProgramApi__Program_Profile__c 
                                              WHERE ProgramApi__Account__c =: acc.Id AND ProgramApi__Contact__c =: con.Id];
        system.assertEquals(1, pps.size());
        
        Test.startTest();
        RenewPPsNewYearsBatch batch = new RenewPPsNewYearsBatch();
        DataBase.executeBatch(batch, 50); 
        Test.stopTest();
        List<ProgramApi__Program_Profile__c> ppsAfterBatch = [SELECT Id 
                                              FROM ProgramApi__Program_Profile__c 
                                              WHERE ProgramApi__Account__c =: acc.Id AND ProgramApi__Contact__c =: con.Id];
        system.assertEquals(2, ppsAfterBatch.size());
        
    }
}