unpackaged/main/default/objects/ProgramApi__Program_Term__c/ProgramApi__Program_Term__c.object-meta.xml
<CustomObject>
    <description>This object establishes the length of time given to complete tasks.</description>
    <label>Program Term</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Program Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Active__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifies active term; Term end date is in the future</description>
    <inlineHelpText>Identifies active term; Term end date is in the future</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__End_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__End_Date__c</fullName>
    <description>Identifies the term end date; Date all goals must be completed to successfully complete program</description>
    <inlineHelpText>Identifies the term end date; Date all goals must be completed to successfully complete program</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Start_Date__c</fullName>
    <description>Identifies the term start date</description>
    <inlineHelpText>Identifies the term start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/CHA_ProgramTermsBatchableTest.cls
@isTest
public class CHA_ProgramTermsBatchableTest {
    @isTest static void testTerms(){
        Contact con = new Contact();
        con.LastName = 'conLast';
        con.FirstName = 'conFirst';
        con.Email = 'conEmail@mail.com';
        insert con;
        
        ProgramApi__Program_Term__c pt1 = new ProgramApi__Program_Term__c();
        pt1.ProgramApi__Start_Date__c = Date.Today().addDays(-30);
        pt1.ProgramApi__End_Date__c = Date.Today().addDays(-10);
        pt1.ProgramApi__Active__c = true;
        insert pt1;
        
        ProgramApi__Program_Term__c pt2 = new ProgramApi__Program_Term__c();
        pt2.ProgramApi__Start_Date__c = Date.Today();
        pt2.ProgramApi__End_Date__c = Date.Today().addDays(+90);
        pt2.ProgramApi__Active__c = false;
        insert pt2;
        
        Test.startTest();
        
        	CHA_ProgramTermsBatchable bt = new CHA_ProgramTermsBatchable();
        	Id btID = Database.executeBatch(bt);
        
        Test.stopTest();
    }
}