unpackaged/main/default/objects/ProgramApi__Program_Term__c/ProgramApi__Program_Term__c.object-meta.xml
<CustomObject>
    <description>This object establishes the length of time given to complete tasks.</description>
    <label>Program Term</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Program Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Active__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifies active term; Term end date is in the future</description>
    <inlineHelpText>Identifies active term; Term end date is in the future</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__End_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__End_Date__c</fullName>
    <description>Identifies the term end date; Date all goals must be completed to successfully complete program</description>
    <inlineHelpText>Identifies the term end date; Date all goals must be completed to successfully complete program</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Profile__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SYSTEM. Relates the program profile to the term</description>
    <inlineHelpText>SYSTEM. Relates the program profile to the term</inlineHelpText>
    <label>Program Profile</label>
    <referenceTo>ProgramApi__Program_Profile__c</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Start_Date__c</fullName>
    <description>Identifies the term start date</description>
    <inlineHelpText>Identifies the term start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/FON_ProgramTermBatchInactivate.cls
global class FON_ProgramTermBatchInactivate implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        Integer currentYear = Date.today().year();

        String query = 'SELECT Id, ProgramApi__Active__c, ProgramApi__End_Date__c, ProgramApi__Start_Date__c FROM ProgramApi__Program_Term__c ' + 
            'WHERE ProgramApi__Profile__c != null AND Contact__c != null AND CALENDAR_YEAR(ProgramApi__Start_Date__c ) != ' + currentYear;
        
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<ProgramApi__Program_Term__c> terms) {
		
        List<ProgramApi__Program_Term__c> termsToUpdate = new List<ProgramApi__Program_Term__c>();
        
        for(ProgramApi__Program_Term__c term : terms){
            if(term.ProgramApi__Active__c){
                term.ProgramApi__Active__c = false;
                if(term.ProgramApi__End_Date__c.year() != term.ProgramApi__Start_Date__c.year()){
                    term.ProgramApi__End_Date__c = date.newInstance(term.ProgramApi__Start_Date__c.year(), 12, 31);
                }
                termsToUpdate.add(term);
            }
        }
        if(termsToUpdate.size() > 0)
            update termsToUpdate;
    }

    global void finish(Database.BatchableContext BC) {
        Database.executeBatch(new FON_ProgramTermBatchActivate(), 50);
    }
}