unpackaged/main/default/objects/ProgramApi__Program_Term__c/ProgramApi__Program_Term__c.object-meta.xml
<CustomObject>
    <description>This object establishes the length of time given to complete tasks.</description>
    <label>Program Term</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Program Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Active__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifies active term; Term end date is in the future</description>
    <inlineHelpText>Identifies active term; Term end date is in the future</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__End_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__End_Date__c</fullName>
    <description>Identifies the term end date; Date all goals must be completed to successfully complete program</description>
    <inlineHelpText>Identifies the term end date; Date all goals must be completed to successfully complete program</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Start_Date__c</fullName>
    <description>Identifies the term start date</description>
    <inlineHelpText>Identifies the term start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/CHA_ProgramTermsBatchable.cls
global without sharing class CHA_ProgramTermsBatchable implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful{
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator('Select Id,ProgramApi__Start_Date__c,ProgramApi__End_Date__c,ProgramApi__Active__c FROM ProgramApi__Program_Term__c WHERE (ProgramApi__Start_Date__c <= TODAY AND ProgramApi__End_Date__c > TODAY AND ProgramApi__Active__c = false) OR ( ProgramApi__End_Date__c <= TODAY AND ProgramApi__Active__c = true)');
    }
    global void execute(Database.BatchableContext bc, List<ProgramApi__Program_Term__c> scope){
        
        Date tDay = System.Today();
        // lists to update
        List<ProgramApi__Program_Term__c> expireTerms = new List<ProgramApi__Program_Term__c>();
        List<ProgramApi__Program_Term__c> activateTerms =  new List<ProgramApi__Program_Term__c>();
        
        for(ProgramApi__Program_Term__c pt : scope){
            if(pt.ProgramApi__Start_Date__c <= tDay && pt.ProgramApi__End_Date__c > tDay && pt.ProgramApi__Active__c == false){
                pt.ProgramApi__Active__c = true;
                activateTerms.add(pt);
            }
            if(pt.ProgramApi__End_Date__c < tDay && pt.ProgramApi__Active__c == true){
                pt.ProgramApi__Active__c = false;
                expireTerms.add(pt);
            }
        }
        
        update activateTerms;
        update expireTerms;
        
    }
    global void finish(Database.BatchableContext bc){
        
    }
    
    
}