unpackaged/main/default/objects/Contact/fields/Audit_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Audit_Email_Sent__c</fullName>
    <label>Audit Email Sent</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/NCP_Credits__c.object-meta.xml
<CustomObject>
    <label>NCP Credit</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>NCP_Credit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCP Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NCP_Credits__c/fields/Credit_Value__c.field-meta.xml
<CustomField>
    <fullName>Credit_Value__c</fullName>
    <formula>Minutes_of_Education__c /50</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credit Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/FON_Audit_Adjusted_Value__c.field-meta.xml
<CustomField>
    <fullName>FON_Audit_Adjusted_Value__c</fullName>
    <label>Audit Adjusted Credit Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/FON_Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>FON_Provider_Name__c</fullName>
    <label>Provider Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/FON_Session_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Session_Date__c</fullName>
    <label>Session Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/FON_Session_Period__c.field-meta.xml
<CustomField>
    <fullName>FON_Session_Period__c</fullName>
    <label>Session Period</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/FON_Total_Credits__c.field-meta.xml
<CustomField>
    <fullName>FON_Total_Credits__c</fullName>
    <formula>Credit_Value__c +  FON_Speaker_Credits__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Credits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Program_Term__c.field-meta.xml
<CustomField>
    <fullName>Program_Term__c</fullName>
    <label>Program Term</label>
    <referenceTo>ProgramApi__Program_Term__c</referenceTo>
    <relationshipLabel>NCP Credits</relationshipLabel>
    <relationshipName>NCP_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Session_Description__c.field-meta.xml
<CustomField>
    <fullName>Session_Description__c</fullName>
    <label>Session Description</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Session_Title__c.field-meta.xml
<CustomField>
    <fullName>Session_Title__c</fullName>
    <label>Session Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <label>Session Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person Training</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Workshop</fullName>
            </value>
            <value>
                <fullName>Conference Call</fullName>
            </value>
            <value>
                <fullName>e-Publication</fullName>
            </value>
            <value>
                <fullName>ECCHO Business Committee Meeting</fullName>
            </value>
            <value>
                <fullName>ECCHO Hosted Session</fullName>
            </value>
            <value>
                <fullName>ECCHO NCP Editorial Board</fullName>
            </value>
            <value>
                <fullName>ECCHO OPS Chairman</fullName>
            </value>
            <value>
                <fullName>ECCHO OPS Committee Meeting</fullName>
            </value>
            <value>
                <fullName>General Session</fullName>
            </value>
            <value>
                <fullName>In-Person Meeting</fullName>
            </value>
            <value>
                <fullName>Lunch-N-Learn</fullName>
            </value>
            <value>
                <fullName>NCP CE Workshop</fullName>
            </value>
            <value>
                <fullName>NCP Evaluation of Pilot Items</fullName>
            </value>
            <value>
                <fullName>NCP Guide Program</fullName>
            </value>
            <value>
                <fullName>NCP Partner Training</fullName>
            </value>
            <value>
                <fullName>OnDemand</fullName>
            </value>
            <value>
                <fullName>Roundtable</fullName>
            </value>
            <value>
                <fullName>Seminar</fullName>
            </value>
            <value>
                <fullName>User Group</fullName>
            </value>
            <value>
                <fullName>Web Based Training</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Series</fullName>
            </value>
            <value>
                <fullName>Publication</fullName>
            </value>
            <value>
                <fullName>CD Rom</fullName>
            </value>
            <value>
                <fullName>Teleconference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/NCP_Sessions__c.object-meta.xml
<CustomObject>
    <label>NCP Session</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCP Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/NCP_Sessions__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/ProgramApi__Program_Profile__c.object-meta.xml
<CustomObject>
    <description>This object maintains a single persona for each participant in a given program.</description>
    <label>Program Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Program Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Audit_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Audit_Date__c</fullName>
    <label>Audit Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Audit_Status__c.field-meta.xml
<CustomField>
    <fullName>FON_Audit_Status__c</fullName>
    <label>Audit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined With Comments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Audit_Submitted_Date_By_EU__c.field-meta.xml
<CustomField>
    <fullName>FON_Audit_Submitted_Date_By_EU__c</fullName>
    <label>Audit Submitted Date By EU</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Audited__c.field-meta.xml
<CustomField>
    <fullName>FON_Audited__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Audited</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Audited_By__c.field-meta.xml
<CustomField>
    <fullName>FON_Audited_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audited By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Audited_Year__c.field-meta.xml
<CustomField>
    <fullName>FON_Audited_Year__c</fullName>
    <label>Audited Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Total_Credits__c.field-meta.xml
<CustomField>
    <fullName>FON_Total_Credits__c</fullName>
    <label>Total Credits (Full)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Contact to program profile; a Contact has only one profile for a program</description>
    <inlineHelpText>Identifies Contact to program profile; a Contact has only one profile for a program</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Status__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Status__c</fullName>
    <description>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</description>
    <inlineHelpText>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Track</fullName>
                <default>true</default>
                <label>On Track</label>
            </value>
            <value>
                <fullName>Cautionary</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending Revocation</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/ProgramApi__Program_Term__c.object-meta.xml
<CustomObject>
    <description>This object establishes the length of time given to complete tasks.</description>
    <label>Program Term</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Program Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__End_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__End_Date__c</fullName>
    <description>Identifies the term end date; Date all goals must be completed to successfully complete program</description>
    <inlineHelpText>Identifies the term end date; Date all goals must be completed to successfully complete program</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Profile__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SYSTEM. Relates the program profile to the term</description>
    <inlineHelpText>SYSTEM. Relates the program profile to the term</inlineHelpText>
    <label>Program Profile</label>
    <referenceTo>ProgramApi__Program_Profile__c</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Start_Date__c</fullName>
    <description>Identifies the term start date</description>
    <inlineHelpText>Identifies the term start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/DisplayAuditProgramHelper.cls
public without sharing class DisplayAuditProgramHelper {

    // this will be used to get the hold the contact Id
    public string contactId {get;set;} 
    
    // this will hold the data to be displayed on template
    public detailsWrapper wrapObj {get;set;}
    
    // this will be used to get the data for the email template
    public void getdisplaydata(){
        
        // for testing adding the contact
        //contactId = '0036300000h5Bb1';    
        //contactId = fetchCurrentlogged();    
        
        // Create wrapper class object instance
        wrapObj = new detailsWrapper();
        
        wrapObj.conDetails = new Contact();
        if(String.isBlank(contactId) != true){
        	wrapObj.conDetails = [select id, Name, Audit_Email_Sent__c from contact where id = :contactId];
        }else{
            wrapObj.conDetails = [select id, Name, Audit_Email_Sent__c from contact where id = '0036g00001Uf2M4AAJ'];
        }
        
        if(wrapObj.conDetails.Audit_Email_Sent__c != null){
            wrapObj.calcDate = wrapObj.conDetails.Audit_Email_Sent__c.addDays(42).format();   
            wrapObj.sendYear = (wrapObj.conDetails.Audit_Email_Sent__c.year() - 1);
        }
        else{
            wrapObj.calcDate = system.today().addDays(42).format();
            wrapObj.sendYear = (system.today().year() - 1);
        }
        
        
        // save current year
        //integer cYear = System.today().year();
        integer cYear = System.Today().addYears(-1).year();
        
        //fetch Program profile object data List
        List<ProgramApi__Program_Profile__c> progProfileList = [SELECT Id,FON_Audited_By__c,FON_Audited_By__r.FirstName,
                                                                FON_Audited_By__r.LastName,FON_Audited_Year__c,
                                                                FON_Audit_Status__c,FON_Audit_Date__c,
                                                                FON_Total_Credits__c,
                                                                (SELECT Id,ProgramApi__Start_Date__c,ProgramApi__End_Date__c FROM ProgramApi__Program_Terms__r)
                                                               FROM ProgramApi__Program_Profile__c
                                                               WHERE ProgramApi__Contact__c =: contactId
                                                               AND FON_Audited__c = true
                                                               //AND ProgramApi__Status__c = 'On Track'
                                                               //AND FON_Audited_Year__c = :cYear
                                                               ORDER BY CreatedDate ASC
                                                               LIMIT 50];
        System.debug('\n--progProfileList--'+progProfileList);
        
        
        if(progProfileList != null && !progProfileList.isEmpty()){
            wrapObj.progProList = progProfileList;
            
            set<Id> progTernIdSet = new set<Id>();
            
            //iterate program profile data list to get program term Ids
            for(ProgramApi__Program_Profile__c progPro : progProfileList){
                if(progPro.ProgramApi__Program_Terms__r != null && !progPro.ProgramApi__Program_Terms__r.isEmpty()){
                    for(ProgramApi__Program_Term__c progTerm : progPro.ProgramApi__Program_Terms__r){
                        if(progTerm.ProgramApi__Start_Date__c.year() == progPro.FON_Audited_Year__c
                           && progTerm.ProgramApi__End_Date__c.year() == progPro.FON_Audited_Year__c)
                            progTernIdSet.add(progTerm.Id);
                    }
                }
            }
            System.debug('\n--progTernIdSet--'+progTernIdSet);
            if(progTernIdSet != null){
                // fetch NCP Credit Details Record based on their Program term id.
                wrapObj.ncpCreditList = fetchNCPCredits(progTernIdSet);
                
                // get total
                for(NCP_Credits__c ncpCredit : wrapObj.ncpCreditList){
                    if(ncpCredit.Credit_Value__c != null)
                        wrapObj.totalSubmittedCredits += ncpCredit.Credit_Value__c;
                    
                    if(ncpCredit.FON_Audit_Adjusted_Value__c == null
                        && ncpCredit.Credit_Value__c != null){
                        ncpCredit.FON_Audit_Adjusted_Value__c = ncpCredit.Credit_Value__c;
                    }
                    
                    wrapObj.totalAdjustedCredits += ncpCredit.FON_Audit_Adjusted_Value__c;
                    
                }
            }
            System.debug('\n--ncpCreditList--'+wrapObj.ncpCreditList);
        }       
    }
    
    
    /*
     * Name : fetchCurrentlogged
     * Des  : this method will be used to current login user contact id
     * */
    public static string  fetchCurrentlogged(){
        string currentloginuserId = UserInfo.getUserId();
        List<User> userList = [SELECT Id,ContactId FROM User WHERE Id =: currentloginuserId];
        if(String.isBlank(userList[0].ContactId) != true){
        	return userList[0].ContactId;
        }else{
            return '0036g00001Uf2M4AAJ';
        }
        
    }
    
    /*
     * Name :fetchProgProfile
     * Description: this method will be used to fetch program Profile and their related  NCP Credit Records
     * */
    @auraEnabled
    public static detailsWrapper fetchProgProfile(){
        //get current user contact Id
        string userConId = fetchCurrentlogged();
        
        // Create wrapper class object instance
        detailsWrapper wrapObj = new detailsWrapper();
        
        // save current year
        //integer cYear = System.today().year();
        integer cYear = System.Today().addYears(-1).year();
        
        //fetch Program profile object data List
        List<ProgramApi__Program_Profile__c> progProfileList = [SELECT Id,FON_Audited_By__c,FON_Audited_By__r.FirstName,
                                                                FON_Audited_By__r.LastName,FON_Audited_Year__c,
                                                                FON_Audit_Status__c,FON_Audit_Date__c,
                                                                FON_Audit_Submitted_Date_By_EU__c,
                                                                FON_Total_Credits__c,
                                                                (SELECT Id,ProgramApi__Start_Date__c,ProgramApi__End_Date__c FROM ProgramApi__Program_Terms__r)
                                                               FROM ProgramApi__Program_Profile__c
                                                               WHERE ProgramApi__Contact__c =: userConId
                                                               AND FON_Audited__c = true
                                                               AND ProgramApi__Status__c = 'On Track'
                                                               AND FON_Audited_Year__c = :cYear
                                                               ORDER BY CreatedDate ASC
                                                               LIMIT 50];
        System.debug('\n--progProfileList--'+progProfileList);
        
        
        if(progProfileList != null && !progProfileList.isEmpty()){
            wrapObj.progProList = progProfileList;
            
            set<Id> progTernIdSet = new set<Id>();
            
            //iterate program profile data list to get program term Ids
            for(ProgramApi__Program_Profile__c progPro : progProfileList){
                if(progPro.ProgramApi__Program_Terms__r != null && !progPro.ProgramApi__Program_Terms__r.isEmpty()){
                    for(ProgramApi__Program_Term__c progTerm : progPro.ProgramApi__Program_Terms__r){
                        if(progTerm.ProgramApi__Start_Date__c.year() == progPro.FON_Audited_Year__c
                           && progTerm.ProgramApi__End_Date__c.year() == progPro.FON_Audited_Year__c)
                            progTernIdSet.add(progTerm.Id);
                    }
                }
            }
            System.debug('\n--progTernIdSet--'+progTernIdSet);
            if(progTernIdSet != null){
                // fetch NCP Credit Details Record based on their Program term id.
                wrapObj.ncpCreditList = fetchNCPCredits(progTernIdSet);
                
                // get total
                for(NCP_Credits__c ncpCredit : wrapObj.ncpCreditList){
                    if(ncpCredit.Credit_Value__c != null)
                        wrapObj.totalSubmittedCredits += ncpCredit.Credit_Value__c;
                    
                    if(ncpCredit.FON_Audit_Adjusted_Value__c == null
                        && ncpCredit.Credit_Value__c != null){
                        ncpCredit.FON_Audit_Adjusted_Value__c = ncpCredit.Credit_Value__c;
                    }
                    
                    wrapObj.totalAdjustedCredits += ncpCredit.FON_Audit_Adjusted_Value__c;
                    
                }
            }
            System.debug('\n--ncpCreditList--'+wrapObj.ncpCreditList);
        }
        return wrapObj;
    }
    
    /*
     * Name : detailsWrapper
     * Description : this wrapper class will be used to display data in LC(DisplayAuditProgram) 
     *                  Which is used in community tab
     * */
    public class detailsWrapper{
        @auraEnabled
        public List<ProgramApi__Program_Profile__c> progProList{get;set;}
        
        @auraEnabled
        public contact conDetails{get;set;}
        
        @auraEnabled
        public Integer sendYear{get;set;}
        
        @auraEnabled
        public string calcDate{get;set;}
        
        @auraEnabled
        public List<NCP_Credits__c> ncpCreditList{get;set;}
        
        @auraEnabled
        public decimal totalSubmittedCredits {get;set;}
        
        @auraEnabled
        public decimal totalAdjustedCredits {get;set;}
        
        public detailsWrapper(){
            progProList = new List<ProgramApi__Program_Profile__c>();
            ncpCreditList = new List<NCP_Credits__c>();
            this.totalSubmittedCredits = 0;
            this.totalAdjustedCredits = 0;
        }
        
    }
    
    /*
     * Name : fetchNCPCredits
     * Description : this method will be used to fecth ncp Credit record based on their program term(Parent object) id
     * */
    public static List<NCP_Credits__c> fetchNCPCredits(Set<Id>ProgTermIdSet){
        return [SELECT Id,
                        Program_Term__c,
                        FON_Session_Date__c,
                        FON_Provider_Name__c,
                        Session_Description__c,
                        FON_Session_Period__c,
                        Session_Title__c,
                        Session_Type__c,
                        Credit_Value__c,NCP_Session__c,
                        NCP_Session__r.Session_ID__c,
                        NCP_Session__r.Session_Date__c,
                        NCP_Session__r.Description__c,
                        //NCP_Session__r.Session_Title__c,
                        FON_Audit_Adjusted_Value__c,
                        Auditor_Notes__c,
                        NCP_Session__r.Credit_Val__c,
                		FON_Audit_Documentation_Upload_Date__c
                FROM NCP_Credits__c
                WHERE Program_Term__c IN: ProgTermIdSet];
    }
    @AuraEnabled
    public static String saveTheFile(String fileName, String base64Data, String contentType, Id recordId) {
        base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');
        ContentVersion contentVersion = new ContentVersion(
            VersionData = EncodingUtil.base64Decode(base64Data),
            Title = fileName,
            PathOnClient = '/' + fileName,
            FirstPublishLocationId = recordId
        );
        insert contentVersion;
        
        return contentVersion.Id;
    }
    @AuraEnabled
    public static NCP_Credits__c submitTheFiles(Id recordId) {
        
        NCP_Credits__c cred = [Select Id,FON_Audit_Documentation_Upload_Date__c FROM NCP_Credits__c WHERE Id=:recordId];
        cred.FON_Audit_Documentation_Upload_Date__c = DateTime.now();
        update cred;
        
        return cred;
    }
    @AuraEnabled
    public static ProgramApi__Program_Profile__c submitTheAudit(Id recordId) {
        ProgramApi__Program_Profile__c ppf = [Select Id,FON_Audit_Submitted_Date_By_EU__c FROM ProgramApi__Program_Profile__c WHERE Id=:recordId];
        ppf.FON_Audit_Submitted_Date_By_EU__c = DateTime.now();
        update ppf;
        
        return ppf;
    }
    
    public static void testingCoverage(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;    
        //repeat the i++ hundred of times

    }
}