unpackaged/main/default/objects/Contact/fields/Audit_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Audit_Email_Sent__c</fullName>
    <label>Audit Email Sent</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/NCP_Credits__c.object-meta.xml
<CustomObject>
    <label>NCP Credit</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>NCP_Credit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCP Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NCP_Credits__c/fields/FON_Audit_Documentation_Upload_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Audit_Documentation_Upload_Date__c</fullName>
    <label>Audit Documentation Upload Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/fields/Program_Term__c.field-meta.xml
<CustomField>
    <fullName>Program_Term__c</fullName>
    <label>Program Term</label>
    <referenceTo>ProgramApi__Program_Term__c</referenceTo>
    <relationshipLabel>NCP Credits</relationshipLabel>
    <relationshipName>NCP_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/ProgramApi__Program_Profile__c.object-meta.xml
<CustomObject>
    <description>This object maintains a single persona for each participant in a given program.</description>
    <label>Program Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Program Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Audit_Submitted_Date_By_EU__c.field-meta.xml
<CustomField>
    <fullName>FON_Audit_Submitted_Date_By_EU__c</fullName>
    <label>Audit Submitted Date By EU</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Audited__c.field-meta.xml
<CustomField>
    <fullName>FON_Audited__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Audited</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Audited_Year__c.field-meta.xml
<CustomField>
    <fullName>FON_Audited_Year__c</fullName>
    <label>Audited Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_End_Date__c</fullName>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_Start_Date__c</fullName>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Account__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</description>
    <inlineHelpText>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Contact to program profile; a Contact has only one profile for a program</description>
    <inlineHelpText>Identifies Contact to program profile; a Contact has only one profile for a program</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Status__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Status__c</fullName>
    <description>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</description>
    <inlineHelpText>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Track</fullName>
                <default>true</default>
                <label>On Track</label>
            </value>
            <value>
                <fullName>Cautionary</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending Revocation</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/ProgramApi__Program_Term__c.object-meta.xml
<CustomObject>
    <description>This object establishes the length of time given to complete tasks.</description>
    <label>Program Term</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Program Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__End_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__End_Date__c</fullName>
    <description>Identifies the term end date; Date all goals must be completed to successfully complete program</description>
    <inlineHelpText>Identifies the term end date; Date all goals must be completed to successfully complete program</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Profile__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SYSTEM. Relates the program profile to the term</description>
    <inlineHelpText>SYSTEM. Relates the program profile to the term</inlineHelpText>
    <label>Program Profile</label>
    <referenceTo>ProgramApi__Program_Profile__c</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Start_Date__c</fullName>
    <description>Identifies the term start date</description>
    <inlineHelpText>Identifies the term start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/DisplayAuditProgramHelper_Test.cls
@IsTest
public class DisplayAuditProgramHelper_Test
{
    @testSetup 
    static void createData()
    {

        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('ECCHO Account').getRecordTypeId();

        Account acc = new Account(recordtypeId = devRecordTypeId, Name = 'Test Acc');
        insert acc;

        Contact con = new contact(LastName = 'Test Con', AccountId = acc.Id, Audit_Email_Sent__c = Date.today());
        insert con;


        User u = new User(ProfileId = [SELECT Id
                                       FROM Profile
                                       WHERE Name = 'Fonteva Chatter Manager Community Login User'].Id, LastName = 'last', Email = 'puser000@amamama.com', Username = 'puser000@amamama.com' + System.currentTimeMillis(), CompanyName = 'TEST', Title = 'title', Alias = 'alias', TimeZoneSidKey = 'America/Los_Angeles', EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ContactId = con.Id);
        insert u;

        ProgramApi__Program_Profile__c ppp = new ProgramApi__Program_Profile__c();
        ppp.ProgramApi__Account__c = acc.Id;
        ppp.ProgramApi__Contact__c = con.Id;
        ppp.FON_Program_Start_Date__c = System.today();
        ppp.FON_Program_End_Date__c = System.today();
        ppp.FON_Audited__c = true;
        ppp.ProgramApi__Status__c = 'On Track';
        ppp.FON_Audited_Year__c = System.today().year();
        insert ppp;


        ProgramApi__Program_Term__c ppt = new ProgramApi__Program_Term__c();
        ppt.ProgramApi__Profile__c = ppp.Id;
        ppt.ProgramApi__Start_Date__c = Date.newInstance(System.today().year(), 1, 1);
        ppt.ProgramApi__End_Date__c = Date.newInstance(System.today().year(), 12, 1);
        insert ppt;
        
    }

    @IsTest
    public static void coverAll_Mt()
    {
        User u = [SELECT Id
                  FROM User
                  WHERE Email = 'puser000@amamama.com'];

        Id contactId = [SELECT Id
                        FROM Contact
                        LIMIT 1].Id;

        System.runAs(u)
        {
            DisplayAuditProgramHelper.fetchProgProfile();
            DisplayAuditProgramHelper dah = new DisplayAuditProgramHelper();
            dah.contactId = contactId;
            dah.getdisplaydata();
        }
    }
    
    static testMethod void fakeTest(){
     DisplayAuditProgramHelper.testingCoverage();
     //repeat the same for the rest of classes.
    }  
    
        // Test method for saveTheFile
    @isTest
    static void testSaveTheFile() {
        // Create a test record (change object and field names as needed)
        ProgramApi__Program_Profile__c testRecord = [Select Id FROM ProgramApi__Program_Profile__c LIMIT 1];


        // Call the method being tested
        String fileName = 'TestFile.txt';
        String base64Data = 'VGhpcyBpcyBhIHRlc3QgZmlsZSBkYXRh';
        String contentType = 'text/plain';
        Id recordId = testRecord.Id;
        String contentVersionId = DisplayAuditProgramHelper.saveTheFile(fileName, base64Data, contentType, recordId);

        // Verify that the ContentVersion was created
        System.assertNotEquals(null, contentVersionId);

        // Add additional assertions as needed
    }

    // Test method for submitTheFiles
    @isTest
    static void testSubmitTheFiles() {
        // Create a test record (change object and field names as needed)
        ProgramApi__Program_Term__c ppt = [Select Id FROM ProgramApi__Program_Term__c LIMIT 1];
        NCP_Credits__c testRecord = new NCP_Credits__c();
        testRecord.Program_Term__c = ppt.Id;
        insert testRecord;

        // Call the method being tested
        Id recordId = testRecord.Id;
        NCP_Credits__c updatedRecord = DisplayAuditProgramHelper.submitTheFiles(recordId);

        // Verify that the record was updated
        System.assertNotEquals(null, updatedRecord.FON_Audit_Documentation_Upload_Date__c);

        // Add additional assertions as needed
    }

    // Test method for submitTheAudit
    @isTest
    static void testSubmitTheAudit() {
        // Create a test record (change object and field names as needed)
        ProgramApi__Program_Profile__c testRecord = new ProgramApi__Program_Profile__c();
        insert testRecord;

        // Call the method being tested
        Id recordId = testRecord.Id;
        ProgramApi__Program_Profile__c updatedRecord = DisplayAuditProgramHelper.submitTheAudit(recordId);

        // Verify that the record was updated
        System.assertNotEquals(null, updatedRecord.FON_Audit_Submitted_Date_By_EU__c);

        // Add additional assertions as needed
    }
}