unpackaged/main/default/objects/Contact/fields/FON_Is_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>FON_Is_Billing_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Billing Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FON_Is_Business_Committee_Alternate__c.field-meta.xml
<CustomField>
    <fullName>FON_Is_Business_Committee_Alternate__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Manually check when a contact is a known Business Committee Alternate. Default is unchecked.</inlineHelpText>
    <label>Is Business Committee Alternate</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FON_Is_Main_Business_Committee_Contact__c.field-meta.xml
<CustomField>
    <fullName>FON_Is_Main_Business_Committee_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check when the contact is a Business Committee Main Contact. Default is unchecked.</inlineHelpText>
    <label>Is Main Business Committee Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FON_Is_Main_Operations_Committee_Contact__c.field-meta.xml
<CustomField>
    <fullName>FON_Is_Main_Operations_Committee_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Manually check when a contact is a known Main Operations Committee Contact. Default is unchecked.</inlineHelpText>
    <label>Is Main Operations Committee Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FON_Is_Primary_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>FON_Is_Primary_Billing_Contact__c</fullName>
    <description>Automatically checks the box when a Contact is populated in the Primary Billing Contact lookup field housed on the Account record</description>
    <formula>Id ==  Account.FON_Primary_Billing_Contact__r.Id</formula>
    <inlineHelpText>Automatically checks the box when a Contact is populated in the Primary Billing Contact lookup field housed on the Account record</inlineHelpText>
    <label>Is Primary Billing Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FON_LP_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>FON_LP_Coordinator__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Manually populated by TCH if the information is known. Will need to manually assign a badge for special permissions</inlineHelpText>
    <label>Is LP Coordinator</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FON_LP_Representative__c.field-meta.xml
<CustomField>
    <fullName>FON_LP_Representative__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Manually populated by TCH if the information is known. Will need to manually assign a badge for special permissions</inlineHelpText>
    <label>Is LP Representative</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FON_Ops_Committee_Alternate__c.field-meta.xml
<CustomField>
    <fullName>FON_Ops_Committee_Alternate__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Manually populated by TCH if the information is known. Will need to manually assign a badge for special permissions</inlineHelpText>
    <label>Is Ops Committee Alternate</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FON_SM_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>FON_SM_Coordinator__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Manually populated by TCH if the information is known. Will need to manually assign a badge for special permissions</inlineHelpText>
    <label>Is SM Coordinator</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FON_SM_Representative__c.field-meta.xml
<CustomField>
    <fullName>FON_SM_Representative__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Manually populated by TCH if the information is known. Will need to manually assign a badge for special permissions</inlineHelpText>
    <label>Is SM Representative</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/FON_ContactFilterCls.cls
public class FON_ContactFilterCls {
    List <Contact> PBcon {get;set;}
    List <Contact> Bcon {get;set;}
    List <Contact> SMcon {get;set;}
    List <Contact> SMrepcon {get;set;}
    List <Contact> Oppsconalt {get;set;}
    List <Contact> LPCcon {get;set;}
    List <Contact> LPRcon {get;set;}
    List <Contact> BusComMaincon {get;set;}
    List <Contact> BusComAltcon {get;set;}
    List <Contact> MainOpscon {get;set;}
    public List <Contact>  GetPBcon() {
        PBcon= [select Id, name, email, phone, title from contact where Accountid = :ApexPages.currentPage().getParameters().get('id') AND FON_Is_Primary_Billing_Contact__c = true];
        return PBcon; 
    }
    public List <Contact>  GetBcon() {
        Bcon= [select Id, name, email, phone, title from contact where Accountid = :ApexPages.currentPage().getParameters().get('id') AND FON_Is_Billing_Contact__c = true];
        return Bcon; 
    }
    public List <Contact>  GetSMcon() {
        SMcon= [select Id, name, email, phone, title from contact where Accountid = :ApexPages.currentPage().getParameters().get('id') AND FON_SM_Coordinator__c = true];
        return SMcon;

    }
    public List <Contact>  GetSMrepcon() {
        SMrepcon= [select Id, name, email, phone, title from contact where Accountid = :ApexPages.currentPage().getParameters().get('id') AND FON_SM_Representative__c = true];
        return SMrepcon;

    }
    public List <Contact>  GetOppsconalt() {
        Oppsconalt= [select Id, name, email, phone, title from contact where Accountid = :ApexPages.currentPage().getParameters().get('id') AND FON_Ops_Committee_Alternate__c = true];
        return Oppsconalt;

    }
    public List <Contact>  GetLPCcon() {
        LPCcon= [select Id, name, email, phone, title from contact where Accountid = :ApexPages.currentPage().getParameters().get('id') AND FON_LP_Coordinator__c = true];
        return LPCcon;

    }
    public List <Contact>  GetLPRcon() {
        LPRcon= [select Id, name, email, phone, title from contact where Accountid = :ApexPages.currentPage().getParameters().get('id') AND FON_LP_Representative__c = true];
        return LPRcon;

    }
    public List <Contact>  GetBusComMaincon() {
        BusComMaincon= [select Id, name, email, phone, title from contact where Accountid = :ApexPages.currentPage().getParameters().get('id') AND FON_Is_Main_Business_Committee_Contact__c = true];
        return BusComMaincon;

    }
    public List <Contact>  GetBusComAltcon() {
        BusComAltcon= [select Id, name, email, phone, title from contact where Accountid = :ApexPages.currentPage().getParameters().get('id') AND FON_Is_Business_Committee_Alternate__c = true];
        return BusComAltcon;

    }
    public List <Contact>  GetMainOpscon() {
        MainOpscon= [select Id, name, email, phone, title from contact where Accountid = :ApexPages.currentPage().getParameters().get('id') AND FON_Is_Main_Operations_Committee_Contact__c = true];
        return MainOpscon;

    }
    
}