unpackaged/main/default/objects/Contact/fields/FON_Candidate_Id_Generated_On__c.field-meta.xml
<CustomField>
    <fullName>FON_Candidate_Id_Generated_On__c</fullName>
    <label>Candidate Id Generated On</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FON_Exam_Year__c.field-meta.xml
<CustomField>
    <fullName>FON_Exam_Year__c</fullName>
    <label>Exam Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FON_NCP_Candidate_ID__c.field-meta.xml
<CustomField>
    <fullName>FON_NCP_Candidate_ID__c</fullName>
    <inlineHelpText>*System Generated* Candidate ID for exam registration. Always 11 digits long. Infromation coming from the Attendee record</inlineHelpText>
    <label>NCP Candidate ID</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/FON_Session_Types__c.field-meta.xml
<CustomField>
    <fullName>FON_Session_Types__c</fullName>
    <inlineHelpText>List of the different Session Types for earning CE Credits</inlineHelpText>
    <label>Session Types</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Conference Call</fullName>
            </value>
            <value>
                <fullName>e-Publication</fullName>
            </value>
            <value>
                <fullName>ECCHO Business Committee Meeting</fullName>
            </value>
            <value>
                <fullName>ECCHO Hosted Session</fullName>
            </value>
            <value>
                <fullName>ECCHO NCP Editorial Board</fullName>
            </value>
            <value>
                <fullName>ECCHO OPS Chairman</fullName>
            </value>
            <value>
                <fullName>ECCHO OPS Committee Meeting</fullName>
            </value>
            <value>
                <fullName>General Session</fullName>
            </value>
            <value>
                <fullName>In-Person Meeting</fullName>
            </value>
            <value>
                <fullName>In-Person Training</fullName>
            </value>
            <value>
                <fullName>Lunch-N-Learn</fullName>
            </value>
            <value>
                <fullName>NCP CE Workshop</fullName>
            </value>
            <value>
                <fullName>NCP Evaluation of Pilot Items</fullName>
            </value>
            <value>
                <fullName>NCP Guide Program</fullName>
            </value>
            <value>
                <fullName>NCP Partner Training</fullName>
            </value>
            <value>
                <fullName>OnDemand</fullName>
            </value>
            <value>
                <fullName>Roundtable</fullName>
            </value>
            <value>
                <fullName>Seminar</fullName>
            </value>
            <value>
                <fullName>User Group</fullName>
            </value>
            <value>
                <fullName>Web Based Training</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Workshop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/NCP_Exam_year__c.field-meta.xml
<CustomField>
    <fullName>NCP_Exam_year__c</fullName>
    <formula>EventApi__Event__r.Exam_Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NCP Exam year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reserved for future use.</description>
    <inlineHelpText>Reserved for future use.</inlineHelpText>
    <label>RESERVED</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item_Class__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Required ** Link to related Item Class</description>
    <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
    <label>Item Class</label>
    <referenceTo>OrderApi__Item_Class__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/ProgramApi__Program__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conditionally Required with Is Program Fee ** Defines the program for which a program profile is created as a result of purchasing/invoicing this item.</description>
    <inlineHelpText>Conditionally Required with Is Program Fee ** Defines the program for which a program profile is created as a result of purchasing/invoicing this item.</inlineHelpText>
    <label>Program</label>
    <referenceTo>ProgramApi__Program__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Receipt__c/OrderApi__Receipt__c.object-meta.xml
<CustomObject>
    <description>Receipts track Customer Payments and Refunds.</description>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Receipt__c/fields/OrderApi__Balance__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Balance__c</fullName>
    <description>**System Calculated** The difference between the Payment Amount and the Applied Amount.</description>
    <formula>OrderApi__Total__c - OrderApi__Applied_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>**System Calculated** The difference between the Payment Amount and the Applied Amount.</inlineHelpText>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Receipt__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override/Required** The contact the payment was received from or the refund is being sent to.</description>
    <inlineHelpText>**System Calculated/Override/Required** The contact the payment was received from or the refund is being sent to.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Receipt__c/fields/OrderApi__Is_Posted__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Posted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Default unchecked. When checked, the receipt will create a new cash transaction (journal entry) and the posted date will populate with the value of today&#39;s date.</description>
    <inlineHelpText>Default unchecked. When checked, the receipts will create a new cash transaction (journal entry) and the posted date will populate with the value of today&#39;s date.</inlineHelpText>
    <label>Is Posted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Receipt__c/fields/OrderApi__Receipt__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Caluclated** Lookup to the reciept for which you are refunding.</description>
    <inlineHelpText>**System Caluclated** Lookup to the reciept for which you are refunding.</inlineHelpText>
    <label>Receipt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OrderApi__Receipt__c.OrderApi__Is_Payment__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OrderApi__Receipt__c</referenceTo>
    <relationshipLabel>Refunds</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Receipt_Line__c/OrderApi__Receipt_Line__c.object-meta.xml
<CustomObject>
    <description>Receipt Lines apply cash related to either refunds or payments to Invoices or Items.</description>
    <label>Receipt Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Receipt Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Receipt_Line__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is populated to show the related contact.</description>
    <inlineHelpText>This field is populated to show the related contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Receipt Lines</relationshipLabel>
    <relationshipName>Receipt_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Receipt_Line__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**Required** Link to related Item.</description>
    <inlineHelpText>**Required** Link to related Item.</inlineHelpText>
    <label>Item</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipName>Receipt_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Receipt_Line__c/fields/OrderApi__Receipt__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Receipt__c</fullName>
    <description>**Required** All Receipt details require a parent receipt that summarizes all receipt lines.</description>
    <inlineHelpText>**Required** All Receipt details require a parent receipt that summarizes all receipt lines.</inlineHelpText>
    <label>Receipt</label>
    <referenceTo>OrderApi__Receipt__c</referenceTo>
    <relationshipName>Receipt_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/OrderApi__Receipt_Line__c/fields/OrderApi__Receipt_Line__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Receipt_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to related parent Receipt Line.</description>
    <inlineHelpText>Link to related parent Receipt Line.</inlineHelpText>
    <label>Parent Receipt Line</label>
    <referenceTo>OrderApi__Receipt_Line__c</referenceTo>
    <relationshipLabel>Packaged Items</relationshipLabel>
    <relationshipName>Receipt_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/ProgramApi__Program_Profile__c.object-meta.xml
<CustomObject>
    <description>This object maintains a single persona for each participant in a given program.</description>
    <label>Program Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Program Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Program__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Program related to a program profile</description>
    <inlineHelpText>Identifies Program related to a program profile</inlineHelpText>
    <label>Program</label>
    <referenceTo>ProgramApi__Program__c</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/ProgramApi__Program_Term__c.object-meta.xml
<CustomObject>
    <description>This object establishes the length of time given to complete tasks.</description>
    <label>Program Term</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Program Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FON_ReceiptService.cls
/**
 * Created by nkopparthi on 9/21/20.
 */

public without sharing class FON_ReceiptService {

    /*public static void generateCandidateID(List<OrderApi__Receipt__c> records, Map<Id,OrderApi__Receipt__c> oldRecords){

        Set<Id> receiptIds = new Set<Id>();
        List<OrderApi__Receipt_Line__c> recLines = new List<OrderApi__Receipt_Line__c>();
        Set<Id> contactIds = new Set<Id>();
        List<Contact> contacts = new List<Contact>();
        Set<Id> newCandidates = new Set<Id>();
        List<Contact> latestCandidate = new List<Contact>();
        List<Contact> finalList = new List<Contact>();
        List<Contact> lstUpdContacts = new List<Contact>();
        String lastCandidateId;
        Integer currentYear; // = date.today().year();


        for(OrderApi__Receipt__c rec : records){

            system.debug(LoggingLevel.INFO, '***Criteria1***'+rec.OrderApi__Is_Posted__c);
            system.debug(LoggingLevel.INFO, '***Criteria1***'+oldRecords.get(rec.Id).OrderApi__Is_Posted__c);
            system.debug(LoggingLevel.INFO, '***Criteria1***'+rec.OrderApi__Balance__c);

            if(rec.OrderApi__Is_Posted__c && oldRecords.get(rec.Id).OrderApi__Is_Posted__c != rec.OrderApi__Is_Posted__c && rec.OrderApi__Balance__c == 0){

                system.debug(LoggingLevel.INFO, '***FON_ReceiptService Criteria Satisfied***');

                receiptIds.add(rec.Id);

            }
        }

        recLines = [
                SELECT Id,
                        OrderApi__Item__r.ProgramApi__Program__r.Name,
                        OrderApi__Receipt__c,
                        OrderApi__Receipt__r.OrderApi__Contact__c,
                        OrderApi__Item__r.NCP_Exam_year__c
                FROM OrderApi__Receipt_Line__c
                WHERE OrderApi__Receipt__c IN :receiptIds
                AND OrderApi__Item__r.ProgramApi__Program__r.Name = 'NCP'
        ];

        system.debug(LoggingLevel.INFO, '***recLines***'+recLines);

        if(!recLines.isEmpty()) {
            for (OrderApi__Receipt_Line__c rls : recLines) {
                contactIds.add(rls.OrderApi__Receipt__r.OrderApi__Contact__c);
                if (rls.OrderApi__Item__r.NCP_Exam_year__c != NULL) {
                    currentYear = Integer.valueOf(rls.OrderApi__Item__r.NCP_Exam_year__c);
                }
            }


            system.debug(LoggingLevel.INFO, '***contactIds***' + contactIds);

            contacts = [
                    SELECT Id,
                            FON_NCP_Candidate_ID__c
                    FROM Contact
                    WHERE Id IN :contactIds
            ];

            system.debug(LoggingLevel.INFO, '***contacts***' + contacts);

            for (Contact con : contacts) {
                if (con.FON_NCP_Candidate_ID__c == NULL || con.FON_NCP_Candidate_ID__c == '') {
                    newCandidates.add(con.Id);
                }
            }

            system.debug(LoggingLevel.INFO, '***newCandidates***' + newCandidates);

            latestCandidate = [
                    SELECT Id,
                            FON_NCP_Candidate_ID__c
                    FROM Contact
                    WHERE FON_NCP_Candidate_ID__c != NULL
                    AND FON_Exam_Year__c = :currentYear
                    //AND CALENDAR_YEAR(FON_Candidate_Id_Generated_On__c) = :currentYear
                    ORDER BY FON_Candidate_Id_Generated_On__c DESC
                    LIMIT 1
            ];

            system.debug(LoggingLevel.INFO, '***latestCandidate***' + latestCandidate);

            if (!latestCandidate.isEmpty()) {
                lastCandidateId = latestCandidate[0].FON_NCP_Candidate_ID__c;
            } else {
                //lastCandidateId = 'HRNCP'+system.now().format('YY')+'0000';
                lastCandidateId = 'HRNCP' + string.valueOf(currentYear).right(2) + '0000';
            }

            system.debug(LoggingLevel.INFO, '***lastCandidateId***' + lastCandidateId);

            finalList = [
                    SELECT Id,
                            FON_NCP_Candidate_ID__c,
                            FON_Candidate_Id_Generated_On__c
                    FROM Contact
                    WHERE Id IN :newCandidates
            ];

            system.debug(LoggingLevel.INFO, '***finalList***' + finalList);

            Integer lastFour = Integer.valueOf(lastCandidateId.right(4));

            system.debug(LoggingLevel.INFO, '***lastFour***' + lastFour);

            for (Contact con : finalList) {
                lastFour = lastFour + 1;
                system.debug(LoggingLevel.INFO, '***lastFour***' + lastFour);
                String strZeros = '';
                system.debug(LoggingLevel.INFO, '***strZeros***' + strZeros);
                Integer length = string.valueOf(lastFour).length();
                system.debug(LoggingLevel.INFO, '***length***' + length);
                Integer i;
                system.debug(LoggingLevel.INFO, '***i***' + i);
                for (i = 0; i < 4 - length; i++) {
                    strZeros = strZeros + '0';
                }
                system.debug(LoggingLevel.INFO, '***strZeros***' + strZeros);
                String strNum = strZeros + string.valueOf(lastFour);
                system.debug(LoggingLevel.INFO, '***strNum***' + strNum);
                //con.FON_NCP_Candidate_ID__c = 'HRNCP'+system.now().format('YY')+strNum;
                con.FON_NCP_Candidate_ID__c = 'HRNCP' + string.valueOf(currentYear).right(2) + strNum;
                con.FON_Candidate_Id_Generated_On__c = system.now();
                con.FON_Exam_Year__c = Integer.valueOf(system.now().format('YYYY'));
                lstUpdContacts.add(con);
            }

            system.debug(LoggingLevel.INFO, '***lstUpdContacts***' + lstUpdContacts);

            if (!lstUpdContacts.isEmpty()) {
                update lstUpdContacts;
            }
        }

    }*/

    public static void createCEWrkshp(List<OrderApi__Receipt__c> records, Map<Id,OrderApi__Receipt__c> oldRecords){

        Set<Id> receiptIds = new Set<Id>();
        List<OrderApi__Receipt_Line__c> recLines = new List<OrderApi__Receipt_Line__c>();
        Set<Id> conId = new Set<Id>();
        List<ProgramApi__Program_Profile__c> ppList = new List<ProgramApi__Program_Profile__c>();
        Map<Id, Id> mapConPT = new Map<Id, Id>();
        List<NCP_Credits__c> lstNCPIns = new List<NCP_Credits__c>();

        for(OrderApi__Receipt__c rec : records){

            if(rec.OrderApi__Is_Posted__c && oldRecords.get(rec.Id).OrderApi__Is_Posted__c != rec.OrderApi__Is_Posted__c && rec.OrderApi__Balance__c == 0){

                receiptIds.add(rec.Id);

            }
        }

        recLines = [
                SELECT  Id,
                        OrderApi__Contact__c,
                        OrderApi__Item__r.FON_Session_Types__c,
                        OrderApi__Receipt__c,
                        OrderApi__Receipt__r.OrderApi__Contact__c
                FROM OrderApi__Receipt_Line__c
                WHERE OrderApi__Receipt__c IN :receiptIds
                AND (OrderApi__Item__r.FON_Session_Types__c = 'NCP CE Workshop' OR OrderApi__Item__r.OrderApi__Item_Class__r.Name = 'NCP CE Workshops')
        ];

        for(OrderApi__Receipt_Line__c rl : recLines){
            conId.add(rl.OrderApi__Contact__c);
        }

        ppList = [SELECT Id, ProgramApi__Contact__c, (SELECT Id, ProgramApi__Active__c FROM ProgramApi__Program_Terms__r) FROM ProgramApi__Program_Profile__c WHERE ProgramApi__Contact__c IN :conId];

        for(ProgramApi__Program_Profile__c pp : ppList){
            for(ProgramApi__Program_Term__c pt : pp.ProgramApi__Program_Terms__r){
                if(pt.ProgramApi__Active__c == TRUE){
                    mapConPT.put(pp.ProgramApi__Contact__c, pt.Id);
                }
            }
        }

        for(OrderApi__Receipt_Line__c rl : recLines){
            NCP_Credits__c ncp = new NCP_Credits__c();
            ncp.Contact_Name__c = rl.OrderApi__Contact__c;
            ncp.Session_Type__c = 'NCP CE Workshop';
            ncp.Program_Term__c = mapConPT.get(rl.OrderApi__Contact__c);
            lstNCPIns.add(ncp);
        }

        if(!lstNCPIns.isEmpty()){
            insert lstNCPIns;
        }

    }
}