unpackaged/main/default/objects/Contact/fields/OrderApi__Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Personal_Email__c</fullName>
    <description>Personal/Home Email address for the Contact.</description>
    <inlineHelpText>Personal/Home Email address for the Contact.</inlineHelpText>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/OrderApi__Preferred_Email_Type__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Preferred_Email_Type__c</fullName>
    <description>**Defaults to Personal Email** Select the Preferred Email Type for the Contact. The value of the corresponding email field will update the standard Contact Email field.</description>
    <inlineHelpText>**Defaults to Personal Email** Select the Preferred Email Type for the Contact. The value of the corresponding email field will update the standard Contact Email field.</inlineHelpText>
    <label>Preferred Email Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CYRIL_Invoice_Line_Types__mdt/CYRIL_Invoice_Line_Types__mdt.object-meta.xml
<CustomObject>
    <label>CYRIL Order Type Sets</label>
    <pluralLabel>CYRIL Order Type Sets</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/CYRIL_Invoice_Line_Types__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Lines</fullName>
                <default>true</default>
                <label>Order Lines</label>
            </value>
            <value>
                <fullName>Order Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Business_Group__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Items can be related to Business Groups to separate business lines and/or legal entities on transactional (sales) and financial reports.</description>
    <inlineHelpText>Items can be related to Business Groups to separate business lines and/or legal entities on transactional (sales) and financial reports.</inlineHelpText>
    <label>Business Group</label>
    <referenceTo>OrderApi__Business_Group__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</description>
    <inlineHelpText>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Is_Subscription__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Subscription__c</fullName>
    <defaultValue>false</defaultValue>
    <description>** System Calculated Override ** Enable Subscription specific controls and features for this Item. Defaults to the value of the same field on the Item&#39;s related Item Class.</description>
    <inlineHelpText>** System Calculated Override ** Enable Subscription specific controls and features for this Item. Defaults to the value of the same field on the Item&#39;s related Item Class.</inlineHelpText>
    <label>Is Subscription</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reserved for future use.</description>
    <inlineHelpText>Reserved for future use.</inlineHelpText>
    <label>RESERVED</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item_Class__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Required ** Link to related Item Class</description>
    <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
    <label>Item Class</label>
    <referenceTo>OrderApi__Item_Class__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Price__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Price__c</fullName>
    <description>The default price for the item will be used to automatically create the default price rule which can only be edited by updating the price of the item.</description>
    <inlineHelpText>The default price for the item will be used to automatically create the default price rule which can only be edited by updating the price of the item.</inlineHelpText>
    <label>Item Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item_Class__c/OrderApi__Item_Class__c.object-meta.xml
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item_Class__c/fields/OrderApi__Business_Group__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Group</label>
    <referenceTo>OrderApi__Business_Group__c</referenceTo>
    <relationshipLabel>Item Classes</relationshipLabel>
    <relationshipName>Item_Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item_Class__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</description>
    <inlineHelpText>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item_Class__c/fields/OrderApi__Is_Subscription__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Subscription__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, Items created that are associated with this Item Class will automatically be
enabled with extra subscription related controls and features. Defaults unchecked.</description>
    <inlineHelpText>When checked, Items created that are associated with this Item Class will automatically be
enabled with extra subscription related controls and features. Defaults unchecked.</inlineHelpText>
    <label>Is Subscription</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Business_Group__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Link to the business group record - business groups will auto-populate if not defined on entry.</description>
    <inlineHelpText>**System Calculated/Override** Link to the business group record - business groups will auto-populate if not defined on entry.</inlineHelpText>
    <label>Business Group</label>
    <referenceTo>OrderApi__Business_Group__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>**System Calculated/Override** Checked when a recurring order or contract is active.</description>
    <inlineHelpText>**System Calculated/Override** Checked when a recurring order or contract is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Business_Group__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Default value is mapped from the parent sales order. The Business Group controls what items are available to associate with the order line. If no value exists, all active items will be allowed to be associated.</description>
    <inlineHelpText>**System Calculated/Override** Default value is mapped from the parent sales order. The Business Group controls what items are available to associate with the order line. If no value exists, all active items will be allowed to be associated.</inlineHelpText>
    <label>Business Group</label>
    <referenceTo>OrderApi__Business_Group__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Is_Subscription__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Subscription__c</fullName>
    <defaultValue>false</defaultValue>
    <description>** System Calculated ** Checked when the Sales Order Line is linked to a &quot;Subscription&quot; Item.</description>
    <inlineHelpText>** System Calculated ** Checked when the Sales Order Line is linked to a &quot;Subscription&quot; Item.</inlineHelpText>
    <label>Is Subscription</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the item related to the sales order.</description>
    <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
    <label>Item</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Item_Class__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** System Calculated / Override ** Link to the related Item Class.</description>
    <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
    <label>Item Class</label>
    <referenceTo>OrderApi__Item_Class__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/classes/GetCYRILOrderLinesControllerTest.cls
@isTest
public class GetCYRILOrderLinesControllerTest {
    @isTest static void getTest() {
        
        Account a = new Account(Name = 'Test Account', ShippingCountry = 'United States');
        insert a;
        
        Contact c = new Contact(FirstName = 'Test', LastName = 'Contact', AccountId = a.Id, OrderApi__Personal_Email__c = 'fsemailupdatetest@example.com',
                                OrderApi__Preferred_Email_Type__c = 'Personal');
        insert c;
        OrderApi__Business_Group__c busGroup = new OrderApi__Business_Group__c(Name = 'Test');
        insert busGroup;
        
        OrderApi__Item_Class__c itemClass= new OrderApi__Item_Class__c(Name = 'Test',
                                                                       OrderApi__Business_Group__c = busGroup.Id, OrderApi__Is_Subscription__c = false);
        insert itemClass;
        OrderApi__Item__c  item1 = new OrderApi__Item__c(Name='Test Chapter1',
                                                         OrderApi__Business_Group__c = busGroup.Id,
                                                         OrderApi__Item_Class__c = itemClass.Id, OrderApi__Is_Subscription__c = false,
                                                        OrderApi__Is_Active__c = true, OrderApi__Price__c = 70);
        OrderApi__Sales_Order__c salesOrderOne = new OrderApi__Sales_Order__c(OrderApi__Contact__c = c.Id,OrderApi__Posting_Status__c='Pending',OrderApi__Status__c='Open');
        insert salesOrderOne;
        OrderApi__Sales_Order_Line__c soLine=new OrderApi__Sales_Order_Line__c(OrderApi__Sales_Order__c=salesOrderOne.Id,OrderApi__Item__c=item1.Id,OrderApi__Item_Class__c=itemClass.Id);
        insert soLine;
        
        CYRIL_Invoice_Line_Types__mdt ilines = [Select Id FROM CYRIL_Invoice_Line_Types__mdt WHERE Type__c='Order Lines' LIMIT 1];
        
        CYRIL_Order_Set_Group__mdt igroup = [SELECT Id, MasterLabel FROM CYRIL_Order_Set_Group__mdt ORDER BY MasterLabel LIMIT 1]; 
		CYRIL_Invoice_Line_Types__mdt ilines2 = [Select Id FROM CYRIL_Invoice_Line_Types__mdt WHERE Type__c='Order Lines' LIMIT 1];
        
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name LIKE '%Administrator%' LIMIT 1].Id,
            LastName = 'last',
            Email = 'puser000@amamama.com',
            Username = 'puser000@amamama.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US');
        insert u;

        //system.runAs(u)
        //{
        Test.startTest();
        	Map<String,List<String>> gitems = GetCYRILOrderLinesController.getItems('OrderApi__Sales_Order_Line__c', String.valueOf(soLine.Id), ilines.id, 'false');
        
        	List<String> gcols = GetCYRILOrderLinesController.getColumns('OrderApi__Sales_Order_Line__c', String.valueOf(soLine.Id), ilines.Id, 'false');
        
        	String gquery = GetCYRILOrderLinesController.getQuery('OrderApi__Sales_Order__c', 'Name,OrderApi__Posting_Status__c', 'OrderApi__Status__c=\'Open\'', 'Id', String.valueOf(salesOrderOne.Id), null, null, 'false');
        
        	Map<String,Map<String,String>> gitems2 = GetCYRILOrderInfoController.getItems('OrderApi__Sales_Order__c', String.valueOf(salesOrderOne.Id), String.valueOf(igroup.Id), 'false');
        
        Test.stopTest();
        //}
        
    }
    
    @isTest static void testGetDefaultValue() {
        GetCYRILOrderInfoTypesController controller = new GetCYRILOrderInfoTypesController();
		GetCYRILOrderLineTypesController controller2 = new GetCYRILOrderLineTypesController();
        // Test getDefaultValue method
        VisualEditor.DataRow defaultValue = controller.getDefaultValue();
        VisualEditor.DataRow defaultValue2 = controller2.getDefaultValue();
        //System.assertNotEquals(null, defaultValue, 'Default value should not be null');
        //System.assertEquals('Select Order Information Set Group', defaultValue.label, 'Label should match the default value');
        //System.assertEquals('', defaultValue.value, 'Value should be an empty string');
    }

    @isTest static void testGetValues() {
        GetCYRILOrderInfoTypesController controller = new GetCYRILOrderInfoTypesController();
    	GetCYRILOrderLineTypesController controller2 = new GetCYRILOrderLineTypesController();
        
        // Test getValues method
        VisualEditor.DynamicPickListRows values = controller.getValues();
        VisualEditor.DynamicPickListRows values2 = controller2.getValues();
        //System.assertNotEquals(null, values, 'Values should not be null');

    }
}