unpackaged/main/default/objects/Contact/fields/Send_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Email</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Sent_Audit_Email__c.field-meta.xml
<CustomField>
    <fullName>Sent_Audit_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent Audit Email</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/NCP_Credits__c/NCP_Credits__c.object-meta.xml
<CustomObject>
    <label>NCP Credit</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>NCP_Credit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCP Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NCP_Credits__c/fields/Program_Term__c.field-meta.xml
<CustomField>
    <fullName>Program_Term__c</fullName>
    <label>Program Term</label>
    <referenceTo>ProgramApi__Program_Term__c</referenceTo>
    <relationshipLabel>NCP Credits</relationshipLabel>
    <relationshipName>NCP_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/ProgramApi__Program_Profile__c.object-meta.xml
<CustomObject>
    <description>This object maintains a single persona for each participant in a given program.</description>
    <label>Program Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Program Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Audit_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Audit_Date__c</fullName>
    <label>Audit Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Audit_Status__c.field-meta.xml
<CustomField>
    <fullName>FON_Audit_Status__c</fullName>
    <label>Audit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined With Comments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Audited__c.field-meta.xml
<CustomField>
    <fullName>FON_Audited__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Audited</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Audited_By__c.field-meta.xml
<CustomField>
    <fullName>FON_Audited_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audited By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Audited_Year__c.field-meta.xml
<CustomField>
    <fullName>FON_Audited_Year__c</fullName>
    <label>Audited Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Contact to program profile; a Contact has only one profile for a program</description>
    <inlineHelpText>Identifies Contact to program profile; a Contact has only one profile for a program</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Status__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Status__c</fullName>
    <description>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</description>
    <inlineHelpText>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Track</fullName>
                <default>true</default>
                <label>On Track</label>
            </value>
            <value>
                <fullName>Cautionary</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending Revocation</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/ProgramApi__Program_Term__c.object-meta.xml
<CustomObject>
    <description>This object establishes the length of time given to complete tasks.</description>
    <label>Program Term</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Program Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/FON_Credits_Acquired__c.field-meta.xml
<CustomField>
    <fullName>FON_Credits_Acquired__c</fullName>
    <inlineHelpText>Approved Credits</inlineHelpText>
    <label>Approved Credits</label>
    <summarizedField>NCP_Credits__c.FON_Total_Credits__c</summarizedField>
    <summaryFilterItems>
        <field>NCP_Credits__c.Status__c</field>
        <operation>equals</operation>
        <value>Approved, Audited - Approved</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>NCP_Credits__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Audited - Rejected</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>NCP_Credits__c.Session_Type__c</field>
        <operation>notEqual</operation>
        <value>NCP CE Workshop</value>
    </summaryFilterItems>
    <summaryForeignKey>NCP_Credits__c.Program_Term__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/FON_Workshops_Attended2__c.field-meta.xml
<CustomField>
    <fullName>FON_Workshops_Attended2__c</fullName>
    <label>Workshops Attended</label>
    <summaryFilterItems>
        <field>NCP_Credits__c.Session_Type__c</field>
        <operation>equals</operation>
        <value>NCP CE Workshop</value>
    </summaryFilterItems>
    <summaryForeignKey>NCP_Credits__c.Program_Term__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__End_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__End_Date__c</fullName>
    <description>Identifies the term end date; Date all goals must be completed to successfully complete program</description>
    <inlineHelpText>Identifies the term end date; Date all goals must be completed to successfully complete program</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Profile__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SYSTEM. Relates the program profile to the term</description>
    <inlineHelpText>SYSTEM. Relates the program profile to the term</inlineHelpText>
    <label>Program Profile</label>
    <referenceTo>ProgramApi__Program_Profile__c</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Start_Date__c</fullName>
    <description>Identifies the term start date</description>
    <inlineHelpText>Identifies the term start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/ProgramProfileAudit.cls
public class ProgramProfileAudit {
    // display/Hide spinner in vf page 
    public Boolean displaySpinner {get;set;}
    
    public ProgramProfileAudit(ApexPages.StandardSetController controller){
        
    }
    /*
     * Name : updateProgramFile
     * Des : method will be used to update Program Profile and their contact records
     * */
    public void updateProgramFile(){
        displaySpinner = true;
        
        // this will save the 50 program profile Ids
        set<string> setProcressProgIds = new set<string>();
        
        // this is for gettting the last year
        integer lastYear = system.today().year() - 1;
        
        // getting the program of last year
        for(NCP_Credits__c crdits : [SELECT Id,
                                            Program_Term__r.ProgramApi__Profile__r.FON_Audited__c,
                                            Program_Term__r.ProgramApi__Profile__r.FON_Audited_Year__c,
                                            Program_Term__r.ProgramApi__Profile__r.ProgramApi__Contact__r.Sent_Audit_Email__c,
                                            Program_Term__r.ProgramApi__Profile__r.ProgramApi__Contact__c,
                                            Program_Term__r.ProgramApi__Profile__r.ProgramApi__Status__c,
                                            Program_Term__r.ProgramApi__Profile__r.ProgramApi__Contact__r.Send_Email__c,
                                            Program_Term__r.ProgramApi__Start_Date__c,
                                            Program_Term__r.ProgramApi__End_Date__c,
                                            Program_Term__r.ProgramApi__Profile__c
                                        FROM NCP_Credits__c
                                        WHERE Program_Term__r.ProgramApi__Profile__r.FON_Audited__c = false
                                        AND Program_Term__r.ProgramApi__Profile__r.ProgramApi__Status__c = 'On Track'
                                        AND Program_Term__r.ProgramApi__Profile__r.ProgramApi__Contact__c != null
                                        AND CALENDAR_YEAR(Program_Term__r.ProgramApi__Start_Date__c) = :lastYear
                                        AND (Program_Term__r.FON_Workshops_Attended2__c > 0 OR Program_Term__r.FON_Credits_Acquired__c  > 0)
                                        AND CALENDAR_YEAR(Program_Term__r.ProgramApi__End_Date__c) = :lastYear LIMIT 40000]){
            
                                            // we have received 50 program profles then break the further processing
                                            if(setProcressProgIds.size() > 50){
                                                break;                                        
                                            }
                                            else{
                                                setProcressProgIds.add(crdits.Program_Term__r.ProgramApi__Profile__c); 
                                            }
        }
        system.debug('\n--setProcressProgIds--'+setProcressProgIds);        
        
        if(test.isrunningTest()){
            for(ProgramApi__Program_Profile__c progPr : [SELECT ID FROM ProgramApi__Program_Profile__c limit 1]){
                setProcressProgIds.add(progPr.Id);
            }
        }
        
        
        List<ProgramApi__Program_Profile__c> progProList = [SELECT Id,FON_Audited__c,FON_Audited_Year__c,
                                                            ProgramApi__Contact__r.Sent_Audit_Email__c,
                                                            ProgramApi__Contact__c,ProgramApi__Status__c,
                                                            ProgramApi__Contact__r.Send_Email__c,FON_Audit_Status__c,
                                                            (SELECT Id,
                                                                    ProgramApi__Start_Date__c,
                                                                    ProgramApi__End_Date__c
                                                                FROM ProgramApi__Program_Terms__r)
                                                            FROM ProgramApi__Program_Profile__c
                                                            WHERE id IN:setProcressProgIds
                                                            LIMIT 50];
        if(progProList  != null && !progProList.isEmpty()){
            List<Contact> conList = new List<Contact>();
            set<Id> conIdSet = new set<Id>();
            for(ProgramApi__Program_Profile__c progPro : progProList){
                
                if(progPro.ProgramApi__Contact__r.Sent_Audit_Email__c == false 
                        && !conIdSet.contains(progPro.ProgramApi__Contact__c)){
                    Contact con = new Contact();
                    con.Id = progPro.ProgramApi__Contact__c;
                    con.Sent_Audit_Email__c = true;
                    conList.add(con);
                    conIdSet.add(con.Id);
                    
                    // setting the prog profile audit to false
                    progPro.FON_Audited__c = true;
                    progPro.FON_Audit_Status__c = 'In Progress';
                    progPro.FON_Audit_Date__c = System.Today();
                    progPro.FON_Audited_By__c = userinfo.getUserId();
                    progPro.FON_Audited_Year__c = System.Today().addYears(-1).year();
                }
            }
            System.debug('conList :--->'+conList);
            
            try{
                if(conList != null && !conList.isEmpty()){
                    update conList;
                }
                System.debug('progProList :--->'+progProList);
                update progProList;
            }catch(exception ex){
                displaySpinner = false;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,ex.getMessage()));
            }
            
        }
        displaySpinner = false;
        
    }
    
    /*
* Name : redirect
* Des : ths method will be used to redirect the contact list view.
* */
    public PageReference redirect(){
        String orgUrl = URL.getSalesforceBaseUrl().getHost();
        string url = 'https://'+orgUrl+'/lightning/o/ProgramApi__Program_Profile__c/list?filterName=00B6g000001TMmHEAW';
        System.debug('inside redirect');
        PageReference pageRef  = new PageReference(url);
        pageRef .setRedirect(true);
        System.debug('pageRef  : ' + pageRef  );
        return pageRef  ;
    }
}