unpackaged/main/default/objects/CYRIL_Batchables__mdt/CYRIL_Batchables__mdt.object-meta.xml
<CustomObject>
    <label>CYRIL Batchables</label>
    <pluralLabel>CYRIL Batchables</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/CYRIL_Batchables__mdt/fields/Batchable_Name__c.field-meta.xml
<CustomField>
    <fullName>Batchable_Name__c</fullName>
    <label>Batchable Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Event__c/EventApi__Event__c.object-meta.xml
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EventApi__Event__c/fields/EventApi__Display_Name__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Display_Name__c</fullName>
    <description>Event name as you would like it to appear on registration pages, calendar reminders, and emails.</description>
    <inlineHelpText>Event name as you would like it to appear on registration pages, calendar reminders, and emails.</inlineHelpText>
    <label>Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Event__c/fields/EventApi__End_Date__c.field-meta.xml
<CustomField>
    <fullName>EventApi__End_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <description>**Required** The event end date.</description>
    <inlineHelpText>**Required** The event end date.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Event__c/fields/EventApi__Event_Key__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Event_Key__c</fullName>
    <description>This field is used as a unique identifier for events. The value in this field will also be used to concatenate item class names to be easily identified in lookup searches.</description>
    <inlineHelpText>This field is used as a unique identifier for events. The value in this field will also be used to concatenate item class names to be easily identified in lookup searches.</inlineHelpText>
    <label>Event Key</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/EventApi__Event__c/fields/EventApi__Logo_Image__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Logo_Image__c</fullName>
    <description>The image defined in this field appears in the lefthand side of the navbar in the microsite.
            Recommended size 90px by 90px. (Image will be cropped to these dimensions)</description>
    <inlineHelpText>The image defined in this field appears in the lefthand side of the navbar in the microsite.
            Recommended size 90px by 90px. (Image will be cropped to these dimensions)</inlineHelpText>
    <label>Logo Image URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/EventApi__Event__c/fields/EventApi__Status__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Status__c</fullName>
    <description>Status of the event. Must be &quot;active&quot; to be visible in the Portal.</description>
    <inlineHelpText>Status of the event. Must be &quot;active&quot; to be visible in the Portal.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <color>#E27001</color>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EventApi__Event__c/fields/EventApi__Ticket_Sales_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Ticket_Sales_Start_Date__c</fullName>
    <description>The date ticket sales or registration begins for the event. Defaults to the &quot;Active&quot; date if left blank.</description>
    <inlineHelpText>The date ticket sales or registration begins for the event. Defaults to the &quot;Active&quot; date if left blank.</inlineHelpText>
    <label>Ticket Sales Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</description>
    <inlineHelpText>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Entity__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Entity__c</fullName>
    <description>**Required** Select &quot;Account&quot; if the related the account is responsible payment of the customer order, Select &quot;Contact&quot; if the related contact is responsible payment of the customer order.</description>
    <inlineHelpText>**Required** Select &quot;Account&quot; if the related the account is responsible payment of the customer order, Select &quot;Contact&quot; if the related contact is responsible payment of the customer order.</inlineHelpText>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Overall_Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Overall_Total__c</fullName>
    <description>Overall Amount of Sales Order.</description>
    <inlineHelpText>Overall Amount of Sales Order.</inlineHelpText>
    <label>Overall Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/EventApi__Event__c.field-meta.xml
<CustomField>
    <fullName>EventApi__Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to related Event.</description>
    <inlineHelpText>Link to related Event.</inlineHelpText>
    <label>Event</label>
    <referenceTo>EventApi__Event__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Account__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Entity__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Entity__c</fullName>
    <description>** Conditionally Required ** Select &quot;Account&quot; to assign the Item on the Sales Order Line to the linked &quot;Account&quot; field -- otherwise select &quot;Contact&quot;. Defaults to the value of the same field on the Sales Order.</description>
    <inlineHelpText>** Conditionally Required ** Select &quot;Account&quot; to assign the Item on the Sales Order Line to the linked &quot;Account&quot; field -- otherwise select &quot;Contact&quot;. Defaults to the value of the same field on the Sales Order.</inlineHelpText>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Overall_Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Overall_Total__c</fullName>
    <description>Overall Amount of Sales Order Line.</description>
    <inlineHelpText>Overall Amount of Sales Order Line.</inlineHelpText>
    <label>Overall Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/classes/CHACreateAttendeesBatchableTest.cls
@isTest(SeeAllData=False)
public class CHACreateAttendeesBatchableTest {
	
    @isTest
    public static void testBatch() {
        
        Account account = new Account(Name = 'Account 1');
        insert account;
        
        Contact contact = new Contact();
        contact.AccountId = account.Id;
        contact.Email = 'test2432324@email.com';
        contact.FirstName = 'Test First Name';
        contact.LastName = 'T2est Last Name';
        insert contact;
        
        // Create Event
        EventApi__Event__c testEvent = new EventApi__Event__c(
            Name = 'Test Event',
            EventApi__Display_Name__c = 'Test Event Display',
            EventApi__Logo_Image__c = 'https://example.com/logo.png',
            EventApi__Status__c = 'Active',
            EventApi__Ticket_Sales_Start_Date__c = Date.today().addDays(-1),
            EventApi__End_Date__c = Date.today().addDays(5),
            EventApi__Event_Key__c = '4bf97723-5c80-4'
        );
        insert testEvent;
        
        
                // Create Sales Order
        ORDERAPI__Sales_Order__c so = new ORDERAPI__Sales_Order__c(
            OrderApi__Account__c = account.Id,
            OrderApi__Entity__c = 'Contact',
            OrderApi__Contact__c = contact.Id);
        insert so;
        
        // Create test Sales Order Lines
        List<OrderApi__Sales_Order_Line__c> testSalesOrderLines = new List<OrderApi__Sales_Order_Line__c>();
        for (Integer i = 0; i < 5; i++) {
            OrderApi__Sales_Order_Line__c sol = new OrderApi__Sales_Order_Line__c(
                OrderApi__Entity__c = 'Contact',
                OrderApi__Overall_Total__c = 10.0 + (i * 2),
                OrderApi__Sales_Order__c = so.Id,
            	EventApi__Event__c = testEvent.Id
            );
            testSalesOrderLines.add(sol);
        }
        insert testSalesOrderLines;

        
        //Test.startTest();
        	List<String> fids = new List<String>();
        	CHACreateAttendeesBatchable batch = new CHACreateAttendeesBatchable();
        	Id job1 = Database.executeBatch(batch);
       // Test.stopTest();
        
  
    }

    @IsTest
    static void testGetBatchsAndConfigBatchAndGetApexJob() {
        // Create a custom metadata record for CYRIL_Batchables__mdt so that configBatchTest can find it
        CYRIL_Batchables__mdt mdt = [Select Id,Batchable_Name__c FROM CYRIL_Batchables__mdt WHERE Batchable_Name__c = 'CHACreateAttendeesBatchable'];
        
        // ------ Test getBatchs() ------
        Test.startTest();
        List<CYRIL_Batchables__mdt> fetchedBatchables = CYRIL_Report_Generated_Batch.getBatchs();
        Test.stopTest();
        System.assertNotEquals(null, fetchedBatchables, 'getBatchs should not return null');
        System.assertEquals(1, fetchedBatchables.size(), 'There should be exactly one custom metadata record');
        System.assertEquals(
            mdt.Batchable_Name__c,
            fetchedBatchables[0].Batchable_Name__c,
            'Batchable_Name__c should match the inserted custom metadata'
        );
        
        // ------ Test configBatchTest(...) ------
        // Since Test.isRunningTest() == true inside configBatchTest, no batch is actually executed.
        //Test.startTest();
        AsyncApexJob returnedJob = CYRIL_Report_Generated_Batch.configBatchTest(
            /*reportId=*/          null,
            /*column=*/            null,
            /*fields=*/            'SomeField',
            /*filters=*/           'SomeFilter',
            /*batchId=*/           mdt.Id,
            /*batchSize=*/         '2',
            /*rId=*/               '000000000000000'
        );
        //Test.stopTest();
        
        // Because no batch was executed, batchprocessid was never set, and the query returns nothing.
        // The method returns a default AsyncApexJob instance (all fields null).
        System.assertNotEquals(null, returnedJob, 'configBatchTest should return a non-null AsyncApexJob object');
        System.assertEquals(null, returnedJob.Id, 'No actual AsyncApexJob record should have been enqueued in test context');
        System.assertEquals(0, returnedJob.JobItemsProcessed == null ? 0 : returnedJob.JobItemsProcessed, 'JobItemsProcessed should be null or 0');
        
        // ------ Test getApexJob(...) with a non-existent Id ------
        // Passing an arbitrary Id that does not exist means the SOQL returns an empty list,
        // so getApexJob returns a default AsyncApexJob instance.
        AsyncApexJob fetchedAj = CYRIL_Report_Generated_Batch.getApexJob('a000000000000000AAA');
        System.assertNotEquals(null, fetchedAj, 'getApexJob should return a non-null AsyncApexJob even if Id does not exist');
        System.assertEquals(null, fetchedAj.Id, 'No AsyncApexJob record should match a random Id');
    }
    
    @IsTest
    static void testGetReportsWithSeeAllDataFalse() {
        // getReports() queries Report. In a test with SeeAllData=false,
        // there are no Report rows, but it should return an empty list rather than throwing.
        //Test.startTest();
        List<Report> allReports = CYRIL_Report_Generated_Batch.getReports();
        //Test.stopTest();
        System.assertNotEquals(null, allReports, 'getReports should not return null (empty list expected)');
        System.assertEquals(0, allReports.size(), 'With SeeAllData=false, there should be no Report records available');
    }

}