unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/Avalara_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Avalara_Tax_Code__c</fullName>
    <description>Avalara tax code for this product (e.g., P0000000 for tangible goods, SW054000 for SaaS, NT for non-taxable). Sent in the CreateTransaction API request.</description>
    <inlineHelpText>Avalara tax code classification. Examples: P0000000 (tangible goods), SW054000 (SaaS), NT (non-taxable).</inlineHelpText>
    <label>Avalara Tax Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reserved for future use.</description>
    <inlineHelpText>Reserved for future use.</inlineHelpText>
    <label>RESERVED</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

avalara-fields-deploy/objects/OrderApi__Sales_Order__c/fields/Avalara_Transaction_Code__c.field-meta.xml
<CustomField>
    <fullName>Avalara_Transaction_Code__c</fullName>
    <description>Avalara transaction code returned by CreateTransaction. Used by CommitTransaction and VoidTransaction to reference the transaction in Avalara.</description>
    <inlineHelpText>Avalara transaction reference code. Auto-populated after tax calculation.</inlineHelpText>
    <label>Avalara Transaction Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

avalara-fields-deploy/objects/OrderApi__Sales_Order__c/fields/Avalara_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Avalara_Transaction_Id__c</fullName>
    <description>Avalara numeric transaction ID returned by CreateTransaction. Used for portal reference and troubleshooting in the Avalara admin console.</description>
    <inlineHelpText>Avalara numeric ID for portal reference. Auto-populated after tax calculation.</inlineHelpText>
    <label>Avalara Transaction Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</description>
    <inlineHelpText>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Country__c</fullName>
    <description>The value of this field will be updated with the Account&#39;s Shipping Country or Contact&#39;s Mailing Country, based on &quot;Entity&quot; if not defined on record entry.</description>
    <inlineHelpText>The value of this field will be updated with the Account&#39;s Shipping Country or Contact&#39;s Mailing Country, based on &quot;Entity&quot; if not defined on record entry.</inlineHelpText>
    <label>Shipping Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Account__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the item related to the sales order.</description>
    <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
    <label>Item</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Quantity__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>**Conditionally Required** The quantity (number of units) of the item related to the sales order line. Required when an Item is linked that does not have &quot;Disable Price Rules&quot; checked. Default 1.</description>
    <inlineHelpText>**Conditionally Required** The quantity (number of units) of the item related to the sales order line. Required when an Item is linked that does not have &quot;Disable Price Rules&quot; checked. Default 1.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sale_Price__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>**System Calculated/Override** The price per-unit for the item sold on the sales order line.</description>
    <inlineHelpText>**System Calculated/Override** The price per-unit for the item sold on the sales order line.</inlineHelpText>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_City__c</fullName>
    <description>Optional shipping city for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping City&quot; field.</description>
    <inlineHelpText>Optional shipping city for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping City&quot; field.</inlineHelpText>
    <label>Shipping City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Country__c</fullName>
    <description>Optional shipping country for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Country&quot; field.</description>
    <inlineHelpText>Optional shipping country for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Country&quot; field.</inlineHelpText>
    <label>Shipping Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Postal_Code__c</fullName>
    <description>Optional shipping postal code for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &#39;&quot;Shipping Postal Code&quot; field.</description>
    <inlineHelpText>Optional shipping postal code for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &#39;&quot;Shipping Postal Code&quot; field.</inlineHelpText>
    <label>Shipping Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_State__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_State__c</fullName>
    <description>Optional shipping state for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping State&quot; field.</description>
    <inlineHelpText>Optional shipping state for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping State&quot; field.</inlineHelpText>
    <label>Shipping State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_Street__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Street__c</fullName>
    <description>Optional shipping street for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Street&quot; field.</description>
    <inlineHelpText>Optional shipping street for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Street&quot; field.</inlineHelpText>
    <label>Shipping Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/classes/AvalaraPaymentConfirmationQueueableTest.cls
@isTest
private class AvalaraPaymentConfirmationQueueableTest {

    private class CommitMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = new HttpResponse();
            response.setStatusCode(200);

            if (request.getMethod() == 'GET') {
                response.setBody('{'
                    + '"address":{"line1":"1600 Pennsylvania Avenue NW","city":"Washington","region":"DC","country":"US","postalCode":"20500"},'
                    + '"validatedAddresses":[{"addressType":"StreetOrResidentialAddress","line1":"1600 PENNSYLVANIA AVE NW","city":"WASHINGTON","region":"DC","country":"US","postalCode":"20500-0005"}],'
                    + '"resolutionQuality":"Intersection"'
                    + '}');
            } else {
                response.setBody('{'
                    + '"id":111222333,"code":"TX-Q-001","status":"Committed","type":"SalesInvoice",'
                    + '"totalTax":5.00,"totalTaxable":100.00,"totalAmount":100.00,"totalExempt":0,"totalDiscount":0,'
                    + '"lines":[{"lineNumber":"1","tax":5.00,"taxableAmount":100.00,"taxCalculated":5.00,"lineAmount":100.00,"rate":0.05,"itemCode":"ITEM-001","taxCode":"P0000000","isItemTaxable":true,"details":[]}]'
                    + '}');
            }

            return response;
        }
    }

    private class FailingMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = new HttpResponse();
            response.setStatusCode(500);
            response.setBody('{"error":{"code":"ServerError","message":"Internal error"}}');
            return response;
        }
    }

    @TestSetup
    static void setupTestData() {
        Account acc = new Account(
            Name = 'Test Account',
            ShippingStreet = '1600 Pennsylvania Avenue NW',
            ShippingCity = 'Washington',
            ShippingState = 'District of Columbia',
            ShippingPostalCode = '20500',
            ShippingCountry = 'United States'
        );
        insert acc;

        Contact ct = new Contact(
            LastName = 'TestContact',
            AccountId = acc.Id,
            MailingStreet = '1600 Pennsylvania Avenue NW',
            MailingCity = 'Washington',
            MailingState = 'District of Columbia',
            MailingPostalCode = '20500',
            MailingCountry = 'United States'
        );
        insert ct;

        OrderApi__Item__c taxItem = new OrderApi__Item__c(
            Name = 'General Merchandise Tax',
            Avalara_Tax_Code__c = 'P0000000'
        );
        insert taxItem;

        OrderApi__Item__c productItem = new OrderApi__Item__c(
            Name = 'Test Product',
            Avalara_Tax__c = taxItem.Id
        );
        insert productItem;

        OrderApi__Sales_Order__c so = new OrderApi__Sales_Order__c(
            OrderApi__Contact__c = ct.Id,
            OrderApi__Account__c = acc.Id,
            OrderApi__Shipping_Street__c = '1600 Pennsylvania Avenue NW',
            OrderApi__Shipping_City__c = 'Washington',
            OrderApi__Shipping_State__c = 'District of Columbia',
            OrderApi__Shipping_Postal_Code__c = '20500',
            OrderApi__Shipping_Country__c = 'United States'
        );
        insert so;

        insert new OrderApi__Sales_Order_Line__c(
            OrderApi__Sales_Order__c = so.Id,
            OrderApi__Item__c = productItem.Id,
            OrderApi__Quantity__c = 1,
            OrderApi__Sale_Price__c = 100.00
        );
    }

    @isTest
    static void should_commit_tax_and_persist_transaction_details() {
        AvalaraAuthProviderService.isSandboxOverride = true;
        Test.setMock(HttpCalloutMock.class, new CommitMock());
        OrderApi__Sales_Order__c so = [SELECT Id FROM OrderApi__Sales_Order__c LIMIT 1];

        Test.startTest();
        System.enqueueJob(new AvalaraPaymentConfirmationQueueable(so.Id));
        Test.stopTest();

        so = [
            SELECT Avalara_Transaction_Code__c, Avalara_Transaction_Id__c
            FROM OrderApi__Sales_Order__c
            WHERE Id = :so.Id
        ];

        System.assertEquals('TX-Q-001', so.Avalara_Transaction_Code__c,
            'Transaction code should be persisted');
        System.assertEquals('111222333', so.Avalara_Transaction_Id__c,
            'Transaction ID should be persisted');
    }

    @isTest
    static void should_not_throw_when_commit_fails() {
        AvalaraAuthProviderService.isSandboxOverride = true;
        Test.setMock(HttpCalloutMock.class, new FailingMock());
        OrderApi__Sales_Order__c so = [SELECT Id FROM OrderApi__Sales_Order__c LIMIT 1];

        Test.startTest();
        System.enqueueJob(new AvalaraPaymentConfirmationQueueable(so.Id));
        Test.stopTest();

        so = [
            SELECT Avalara_Transaction_Code__c
            FROM OrderApi__Sales_Order__c
            WHERE Id = :so.Id
        ];

        System.assertEquals(null, so.Avalara_Transaction_Code__c,
            'Transaction code should remain null when commit fails (error caught gracefully)');
    }
}