unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reserved for future use.</description>
    <inlineHelpText>Reserved for future use.</inlineHelpText>
    <label>RESERVED</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Is_Proforma__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Proforma__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this field is checked, this sales order will be displayed in the community.</description>
    <inlineHelpText>When this field is checked, this sales order will be displayed in the community.</inlineHelpText>
    <label>Is Proforma</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Sales_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order_Status__c</fullName>
    <description>Status of the Sales Order</description>
    <formula>IF(ISPICKVAL(OrderApi__Posting_Entity__c,&#39;Invoice&#39;),
            IF(AND((OrderApi__Is_Cancelled__c), NOT(OrderApi__Is_Voided__c)),
            &#39;Cancelled&#39;,
            IF(AND(NOT(OrderApi__Is_Posted__c), NOT(OrderApi__Is_Voided__c)),
            &#39;Draft&#39;,
            IF(AND(OrderApi__Is_Closed__c, OrderApi__Is_Posted__c, NOT(OrderApi__Is_Voided__c),  TODAY() &gt; OrderApi__Due_Date__c, OrderApi__Balance_Due__c &gt; 0),
            &#39;Overdue&#39;,
            IF(AND( OrderApi__Balance_Due__c &gt; 0,OrderApi__Is_Closed__c, OrderApi__Is_Posted__c, NOT(OrderApi__Is_Voided__c)),
            &#39;Unpaid&#39;,
            IF(AND(OrderApi__Balance_Due__c &lt;= 0, NOT(OrderApi__Is_Voided__c),OrderApi__Is_Closed__c,OrderApi__Is_Posted__c),
            &#39;Paid&#39;,
            IF(OrderApi__Is_Voided__c,
            &#39;Voided&#39;,
            /*Default Value for Invoice*/
            &#39;&#39;)))))),
            /* Receipt Changes goes here */
            IF(ISPICKVAL(OrderApi__Posting_Entity__c,&#39;Receipt&#39;),
            IF(AND(NOT(OrderApi__Is_Closed__c), NOT(OrderApi__Is_Posted__c), NOT(OrderApi__Is_Voided__c)),
            &#39;Draft&#39;,
            IF(AND(OrderApi__Is_Closed__c, NOT(OrderApi__Is_Posted__c), NOT(OrderApi__Is_Voided__c),  TODAY() &gt; OrderApi__Due_Date__c, OrderApi__Balance_Due__c &gt; 0),
            &#39;Overdue&#39;,
            IF(AND(OrderApi__Is_Closed__c, NOT(OrderApi__Is_Posted__c), NOT(OrderApi__Is_Voided__c)),
            &#39;Unpaid&#39;,
            IF(AND(OrderApi__Balance_Due__c &lt;= 0, NOT(OrderApi__Is_Voided__c),OrderApi__Is_Closed__c,OrderApi__Is_Posted__c),
            &#39;Paid&#39;,
            IF(OrderApi__Is_Voided__c,
            &#39;Voided&#39;,
            /*Default Value for Receipt*/
            &#39;&#39;))))),
            &#39;&#39;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the item related to the sales order.</description>
    <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
    <label>Item</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/classes/FON_AprilBatchJob.cls
/**
 * Created by nkopparthi on 11/16/20.
 */

global class FON_AprilBatchJob implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        // collect the batches of records or objects to be passed to execute

        String query = 'SELECT Id, OrderApi__Sales_Order_Status__c FROM OrderApi__Sales_Order__c WHERE OrderApi__Sales_Order_Status__c = \'Unpaid\' AND OrderApi__Is_Proforma__c = true';
        if(test.isRunningTest()){
            query = 'SELECT Id, OrderApi__Sales_Order_Status__c FROM OrderApi__Sales_Order__c ';
        }
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<OrderApi__Sales_Order__c> soList) {

        List<Id> soIds = new List<Id>();
        List<OrderApi__Sales_Order__c> salesOrderList = new List<OrderApi__Sales_Order__c>();
        List<OrderApi__Sales_Order_Line__c> lstSolIns = new List<OrderApi__Sales_Order_Line__c>();
        Id ItemID = [SELECT Id FROM OrderApi__Item__c WHERE Name = 'CE Credit Filing Fee' LIMIT 1].Id;
        Id LateItemID = [SELECT Id FROM OrderApi__Item__c WHERE Name = 'CE Credits – Late Filing Fee' LIMIT 1].Id;

        // process each batch of records default size is 200

        for(OrderApi__Sales_Order__c so : soList){
            soIds.add(so.Id);
        }

        salesOrderList = [
                         SELECT  Id,
                         (SELECT Id,
                                 OrderApi__Item__c
                         FROM OrderApi__Sales_Order_Lines__r)
                         FROM OrderApi__Sales_Order__c
                         WHERE Id IN :soIds
        ];

        for(OrderApi__Sales_Order__c so : salesOrderList){
            for(OrderApi__Sales_Order_Line__c sol : so.OrderApi__Sales_Order_Lines__r){
                if(sol.OrderApi__Item__c == ItemID){
                    OrderApi__Sales_Order_Line__c newSol = new OrderApi__Sales_Order_Line__c();
                    newSol.OrderApi__Sales_Order__c = so.Id;
                    newSol.OrderApi__Item__c = LateItemID;
                    lstSolIns.add(newSol);
                }
            }
        }

        try {
            if(!lstSolIns.isEmpty()){
                insert lstSolIns;
            }

        } catch(Exception e) {
            System.debug(e);
        }

    }

    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations like sending email
    }
}