unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/Avalara_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Avalara_Tax_Code__c</fullName>
    <description>Avalara tax code for this product (e.g., P0000000 for tangible goods, SW054000 for SaaS, NT for non-taxable). Sent in the CreateTransaction API request.</description>
    <inlineHelpText>Avalara tax code classification. Examples: P0000000 (tangible goods), SW054000 (SaaS), NT (non-taxable).</inlineHelpText>
    <label>Avalara Tax Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reserved for future use.</description>
    <inlineHelpText>Reserved for future use.</inlineHelpText>
    <label>RESERVED</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

avalara-fields-deploy/objects/OrderApi__Sales_Order__c/fields/Avalara_Transaction_Code__c.field-meta.xml
<CustomField>
    <fullName>Avalara_Transaction_Code__c</fullName>
    <description>Avalara transaction code returned by CreateTransaction. Used by CommitTransaction and VoidTransaction to reference the transaction in Avalara.</description>
    <inlineHelpText>Avalara transaction reference code. Auto-populated after tax calculation.</inlineHelpText>
    <label>Avalara Transaction Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

avalara-fields-deploy/objects/OrderApi__Sales_Order__c/fields/Avalara_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Avalara_Transaction_Id__c</fullName>
    <description>Avalara numeric transaction ID returned by CreateTransaction. Used for portal reference and troubleshooting in the Avalara admin console.</description>
    <inlineHelpText>Avalara numeric ID for portal reference. Auto-populated after tax calculation.</inlineHelpText>
    <label>Avalara Transaction Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</description>
    <inlineHelpText>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Country__c</fullName>
    <description>The value of this field will be updated with the Account&#39;s Shipping Country or Contact&#39;s Mailing Country, based on &quot;Entity&quot; if not defined on record entry.</description>
    <inlineHelpText>The value of this field will be updated with the Account&#39;s Shipping Country or Contact&#39;s Mailing Country, based on &quot;Entity&quot; if not defined on record entry.</inlineHelpText>
    <label>Shipping Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Account__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the item related to the sales order.</description>
    <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
    <label>Item</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Price_Override__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Price_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Overrides the calculation of price based on the most appropriate price for the purchasing customer. Default is unchecked.</description>
    <inlineHelpText>Overrides the calculation of price based on the most appropriate price for the purchasing customer. Default is unchecked.</inlineHelpText>
    <label>Price Override</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Quantity__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>**Conditionally Required** The quantity (number of units) of the item related to the sales order line. Required when an Item is linked that does not have &quot;Disable Price Rules&quot; checked. Default 1.</description>
    <inlineHelpText>**Conditionally Required** The quantity (number of units) of the item related to the sales order line. Required when an Item is linked that does not have &quot;Disable Price Rules&quot; checked. Default 1.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sale_Price__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>**System Calculated/Override** The price per-unit for the item sold on the sales order line.</description>
    <inlineHelpText>**System Calculated/Override** The price per-unit for the item sold on the sales order line.</inlineHelpText>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_City__c</fullName>
    <description>Optional shipping city for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping City&quot; field.</description>
    <inlineHelpText>Optional shipping city for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping City&quot; field.</inlineHelpText>
    <label>Shipping City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Country__c</fullName>
    <description>Optional shipping country for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Country&quot; field.</description>
    <inlineHelpText>Optional shipping country for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Country&quot; field.</inlineHelpText>
    <label>Shipping Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Postal_Code__c</fullName>
    <description>Optional shipping postal code for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &#39;&quot;Shipping Postal Code&quot; field.</description>
    <inlineHelpText>Optional shipping postal code for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &#39;&quot;Shipping Postal Code&quot; field.</inlineHelpText>
    <label>Shipping Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_State__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_State__c</fullName>
    <description>Optional shipping state for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping State&quot; field.</description>
    <inlineHelpText>Optional shipping state for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping State&quot; field.</inlineHelpText>
    <label>Shipping State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_Street__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Street__c</fullName>
    <description>Optional shipping street for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Street&quot; field.</description>
    <inlineHelpText>Optional shipping street for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Street&quot; field.</inlineHelpText>
    <label>Shipping Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/classes/AvalaraTaxCalculationServiceTest.cls
@isTest
private class AvalaraTaxCalculationServiceTest {

    private static final String TEST_STREET = '1600 Pennsylvania Avenue NW';
    private static final String TEST_CITY = 'Washington';
    private static final String TEST_STATE = 'District of Columbia';
    private static final String TEST_POSTAL_CODE = '20500';
    private static final String TEST_COUNTRY = 'United States';

    // ─── Mock Implementations ───

    private class TaxCalculationSuccessMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = new HttpResponse();
            response.setStatusCode(200);

            if (request.getMethod() == 'GET') {
                response.setBody(buildResolveAddressSuccessJson());
            } else {
                response.setBody(buildCreateTransactionSuccessJson());
            }

            return response;
        }
    }

    private class AddressValidationFailMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = new HttpResponse();
            response.setStatusCode(200);
            response.setBody('{'
                + '"address":{"line1":"999 Fake St","city":"Nowhere","region":"ZZ","country":"US","postalCode":"00000"},'
                + '"validatedAddresses":[{"addressType":"UnknownAddressType","line1":"999 Fake St","city":"Nowhere","region":"ZZ","country":"US","postalCode":"00000"}],'
                + '"resolutionQuality":"External",'
                + '"messages":[{"summary":"Address not geocoded.","details":"Cannot be geocoded.","refersTo":"Address","severity":"Error","source":"Avalara.AvaTax.Common"}]'
                + '}');
            return response;
        }
    }

    // ─── Test Data ───

    @TestSetup
    static void setupTestData() {
        Account acc = new Account(
            Name = 'Test Account',
            ShippingStreet = '1600 Pennsylvania Avenue NW',
            ShippingCity = 'Washington',
            ShippingState = 'District of Columbia',
            ShippingPostalCode = '20500',
            ShippingCountry = 'United States'
        );
        insert acc;

        Contact ct = new Contact(
            LastName = 'TestContact',
            AccountId = acc.Id,
            MailingStreet = '1600 Pennsylvania Avenue NW',
            MailingCity = 'Washington',
            MailingState = 'District of Columbia',
            MailingPostalCode = '20500',
            MailingCountry = 'United States'
        );
        insert ct;

        OrderApi__Item__c taxItem = new OrderApi__Item__c(
            Name = 'General Merchandise Tax',
            Avalara_Tax_Code__c = 'P0000000'
        );
        insert taxItem;

        OrderApi__Item__c productItem = new OrderApi__Item__c(
            Name = 'Test Product',
            Avalara_Tax__c = taxItem.Id
        );
        insert productItem;

        OrderApi__Sales_Order__c so = new OrderApi__Sales_Order__c(
            OrderApi__Contact__c = ct.Id,
            OrderApi__Account__c = acc.Id,
            OrderApi__Shipping_Street__c = '1600 Pennsylvania Avenue NW',
            OrderApi__Shipping_City__c = 'Washington',
            OrderApi__Shipping_State__c = 'District of Columbia',
            OrderApi__Shipping_Postal_Code__c = '20500',
            OrderApi__Shipping_Country__c = 'United States'
        );
        insert so;

        insert new OrderApi__Sales_Order_Line__c(
            OrderApi__Sales_Order__c = so.Id,
            OrderApi__Item__c = productItem.Id,
            OrderApi__Quantity__c = 1,
            OrderApi__Sale_Price__c = 100.00
        );
    }

    // ─── Helpers ───

    private static OrderApi__Sales_Order__c getTestSalesOrder() {
        return [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c != null LIMIT 1];
    }

    private static String buildResolveAddressSuccessJson() {
        return '{'
            + '"address":{"line1":"1600 Pennsylvania Avenue NW","city":"Washington","region":"DC","country":"US","postalCode":"20500"},'
            + '"validatedAddresses":[{"addressType":"StreetOrResidentialAddress","line1":"1600 PENNSYLVANIA AVE NW","city":"WASHINGTON","region":"DC","country":"US","postalCode":"20500-0005","latitude":38.897199,"longitude":-77.036548}],'
            + '"coordinates":{"latitude":38.897199,"longitude":-77.036548},'
            + '"resolutionQuality":"Intersection"'
            + '}';
    }

    private static String buildCreateTransactionSuccessJson() {
        return '{'
            + '"id":123456789,"code":"TX-TEST-001","status":"Temporary","type":"SalesOrder",'
            + '"totalTax":6.00,"totalTaxable":100.00,"totalAmount":100.00,"totalExempt":0,"totalDiscount":0,'
            + '"lines":[{"lineNumber":"1","tax":6.00,"taxableAmount":100.00,"taxCalculated":6.00,"lineAmount":100.00,"rate":0.06,"itemCode":"ITEM-001","taxCode":"P0000000","isItemTaxable":true,"details":[]}]'
            + '}';
    }

    // ─── calculateTax Tests ───

    @isTest
    static void should_create_tax_sols_for_taxable_lines() {
        AvalaraAuthProviderService.isSandboxOverride = true;
        Test.setMock(HttpCalloutMock.class, new TaxCalculationSuccessMock());
        OrderApi__Sales_Order__c so = getTestSalesOrder();

        Test.startTest();
        AvalaraTaxCalculationService.calculateTax(so.Id);
        Test.stopTest();

        List<OrderApi__Sales_Order_Line__c> taxLines = [
            SELECT Id, OrderApi__Sale_Price__c, OrderApi__Quantity__c,
                   OrderApi__Price_Override__c, OrderApi__Item__c,
                   OrderApi__Sales_Order_Line__c
            FROM OrderApi__Sales_Order_Line__c
            WHERE OrderApi__Sales_Order__c = :so.Id
              AND OrderApi__Item__r.Avalara_Tax_Code__c != null
              AND OrderApi__Item__r.Avalara_Tax__c = null
        ];

        System.assertEquals(1, taxLines.size(), 'Should create one tax SOL');
        System.assertEquals(6.00, taxLines[0].OrderApi__Sale_Price__c, 'Tax amount should match Avalara response');
        System.assertEquals(1, taxLines[0].OrderApi__Quantity__c, 'Tax SOL quantity should be 1');
        System.assertEquals(true, taxLines[0].OrderApi__Price_Override__c, 'Price override should be true');
        System.assertNotEquals(null, taxLines[0].OrderApi__Sales_Order_Line__c, 'Tax SOL should link to parent product SOL');
    }

    @isTest
    static void should_return_early_when_no_taxable_lines() {
        Account acc = [SELECT Id FROM Account LIMIT 1];

        OrderApi__Item__c nonTaxItem = new OrderApi__Item__c(Name = 'Non-Taxable Item');
        insert nonTaxItem;

        OrderApi__Sales_Order__c emptySo = new OrderApi__Sales_Order__c(
            OrderApi__Account__c = acc.Id,
            OrderApi__Shipping_Street__c = TEST_STREET,
            OrderApi__Shipping_City__c = TEST_CITY,
            OrderApi__Shipping_State__c = TEST_STATE,
            OrderApi__Shipping_Postal_Code__c = TEST_POSTAL_CODE,
            OrderApi__Shipping_Country__c = TEST_COUNTRY
        );
        insert emptySo;

        insert new OrderApi__Sales_Order_Line__c(
            OrderApi__Sales_Order__c = emptySo.Id,
            OrderApi__Item__c = nonTaxItem.Id,
            OrderApi__Quantity__c = 1,
            OrderApi__Sale_Price__c = 50.00
        );

        Test.startTest();
        AvalaraTaxCalculationService.calculateTax(emptySo.Id);
        Test.stopTest();

        List<OrderApi__Sales_Order_Line__c> allLines = [
            SELECT Id FROM OrderApi__Sales_Order_Line__c
            WHERE OrderApi__Sales_Order__c = :emptySo.Id
        ];
        System.assertEquals(1, allLines.size(), 'Should only have the original non-taxable SOL, no callouts made');
    }

    @isTest
    static void should_throw_when_shipping_address_incomplete() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        OrderApi__Item__c productItem = [SELECT Id FROM OrderApi__Item__c WHERE Name = 'Test Product'];

        OrderApi__Sales_Order__c so = new OrderApi__Sales_Order__c(
            OrderApi__Account__c = acc.Id
        );
        insert so;

        insert new OrderApi__Sales_Order_Line__c(
            OrderApi__Sales_Order__c = so.Id,
            OrderApi__Item__c = productItem.Id,
            OrderApi__Quantity__c = 1,
            OrderApi__Sale_Price__c = 100.00
        );

        Boolean exceptionThrown = false;

        Test.startTest();
        try {
            AvalaraTaxCalculationService.calculateTax(so.Id);
        } catch (AvalaraAuthProviderService.AvalaraException e) {
            exceptionThrown = true;
            System.assert(e.getMessage().contains('shipping address is incomplete'),
                'Should mention incomplete address: ' + e.getMessage());
        }
        Test.stopTest();

        System.assert(exceptionThrown, 'Should throw when shipping address fields are blank');
    }

    @isTest
    static void should_throw_when_address_validation_fails() {
        AvalaraAuthProviderService.isSandboxOverride = true;
        Test.setMock(HttpCalloutMock.class, new AddressValidationFailMock());
        OrderApi__Sales_Order__c so = getTestSalesOrder();

        Boolean exceptionThrown = false;

        Test.startTest();
        try {
            AvalaraTaxCalculationService.calculateTax(so.Id);
        } catch (AvalaraAuthProviderService.AvalaraException e) {
            exceptionThrown = true;
            System.assert(e.getMessage().contains('Address validation failed'),
                'Should indicate address validation failure: ' + e.getMessage());
        }
        Test.stopTest();

        System.assert(exceptionThrown, 'Should throw when Avalara returns validation messages');
    }

    @isTest
    static void should_delete_existing_tax_lines_before_creating_new() {
        AvalaraAuthProviderService.isSandboxOverride = true;
        Test.setMock(HttpCalloutMock.class, new TaxCalculationSuccessMock());
        OrderApi__Sales_Order__c so = getTestSalesOrder();
        OrderApi__Item__c taxItem = [SELECT Id FROM OrderApi__Item__c WHERE Name = 'General Merchandise Tax'];

        // Pre-create an old tax SOL (simulates a previous calculateTax run)
        insert new OrderApi__Sales_Order_Line__c(
            OrderApi__Sales_Order__c = so.Id,
            OrderApi__Item__c = taxItem.Id,
            OrderApi__Quantity__c = 1,
            OrderApi__Sale_Price__c = 5.00,
            OrderApi__Price_Override__c = true
        );

        Integer linesBefore = [
            SELECT COUNT()
            FROM OrderApi__Sales_Order_Line__c
            WHERE OrderApi__Sales_Order__c = :so.Id
        ];

        Test.startTest();
        AvalaraTaxCalculationService.calculateTax(so.Id);
        Test.stopTest();

        List<OrderApi__Sales_Order_Line__c> taxLines = [
            SELECT Id, OrderApi__Sale_Price__c
            FROM OrderApi__Sales_Order_Line__c
            WHERE OrderApi__Sales_Order__c = :so.Id
              AND OrderApi__Item__r.Avalara_Tax_Code__c != null
              AND OrderApi__Item__r.Avalara_Tax__c = null
        ];

        System.assertEquals(1, taxLines.size(), 'Old tax SOL should be deleted, only new one remains');
        System.assertEquals(6.00, taxLines[0].OrderApi__Sale_Price__c, 'New tax SOL should have updated amount from Avalara');
    }

    // ─── commitTax Tests ───

    @isTest
    static void should_commit_tax_and_save_transaction_details() {
        AvalaraAuthProviderService.isSandboxOverride = true;
        Test.setMock(HttpCalloutMock.class, new TaxCalculationSuccessMock());
        OrderApi__Sales_Order__c so = getTestSalesOrder();

        Test.startTest();
        AvalaraTaxCalculationService.commitTax(so.Id);
        Test.stopTest();

        so = [
            SELECT Avalara_Transaction_Code__c, Avalara_Transaction_Id__c
            FROM OrderApi__Sales_Order__c
            WHERE Id = :so.Id
        ];

        System.assertEquals('TX-TEST-001', so.Avalara_Transaction_Code__c,
            'Transaction code should be persisted after commitTax');
        System.assertEquals('123456789', so.Avalara_Transaction_Id__c,
            'Transaction ID should be persisted after commitTax');
    }

    @isTest
    static void should_return_early_on_commit_when_no_taxable_lines() {
        Account acc = [SELECT Id FROM Account LIMIT 1];

        OrderApi__Item__c nonTaxItem = new OrderApi__Item__c(Name = 'Non-Taxable Commit');
        insert nonTaxItem;

        OrderApi__Sales_Order__c emptySo = new OrderApi__Sales_Order__c(
            OrderApi__Account__c = acc.Id,
            OrderApi__Shipping_Street__c = TEST_STREET,
            OrderApi__Shipping_City__c = TEST_CITY,
            OrderApi__Shipping_State__c = TEST_STATE,
            OrderApi__Shipping_Postal_Code__c = TEST_POSTAL_CODE,
            OrderApi__Shipping_Country__c = TEST_COUNTRY
        );
        insert emptySo;

        insert new OrderApi__Sales_Order_Line__c(
            OrderApi__Sales_Order__c = emptySo.Id,
            OrderApi__Item__c = nonTaxItem.Id,
            OrderApi__Quantity__c = 1,
            OrderApi__Sale_Price__c = 50.00
        );

        Test.startTest();
        AvalaraTaxCalculationService.commitTax(emptySo.Id);
        Test.stopTest();

        emptySo = [
            SELECT Avalara_Transaction_Code__c
            FROM OrderApi__Sales_Order__c
            WHERE Id = :emptySo.Id
        ];
        System.assertEquals(null, emptySo.Avalara_Transaction_Code__c,
            'No commit should happen when there are no taxable lines');
    }

    // ─── customerCode resolution ───

    @isTest
    static void should_use_account_as_customer_code_when_no_contact() {
        AvalaraAuthProviderService.isSandboxOverride = true;
        Test.setMock(HttpCalloutMock.class, new TaxCalculationSuccessMock());
        Account acc = [SELECT Id FROM Account LIMIT 1];
        OrderApi__Item__c productItem = [SELECT Id FROM OrderApi__Item__c WHERE Name = 'Test Product'];

        OrderApi__Sales_Order__c so = new OrderApi__Sales_Order__c(
            OrderApi__Account__c = acc.Id,
            OrderApi__Shipping_Street__c = TEST_STREET,
            OrderApi__Shipping_City__c = TEST_CITY,
            OrderApi__Shipping_State__c = TEST_STATE,
            OrderApi__Shipping_Postal_Code__c = TEST_POSTAL_CODE,
            OrderApi__Shipping_Country__c = TEST_COUNTRY
        );
        insert so;

        insert new OrderApi__Sales_Order_Line__c(
            OrderApi__Sales_Order__c = so.Id,
            OrderApi__Item__c = productItem.Id,
            OrderApi__Quantity__c = 1,
            OrderApi__Sale_Price__c = 75.00
        );

        Test.startTest();
        AvalaraTaxCalculationService.calculateTax(so.Id);
        Test.stopTest();

        List<OrderApi__Sales_Order_Line__c> taxLines = [
            SELECT Id
            FROM OrderApi__Sales_Order_Line__c
            WHERE OrderApi__Sales_Order__c = :so.Id
              AND OrderApi__Item__r.Avalara_Tax_Code__c != null
              AND OrderApi__Item__r.Avalara_Tax__c = null
        ];
        System.assertEquals(1, taxLines.size(), 'Should create tax SOL using Account as customer code');
    }
}