unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/Exam_Year__c.field-meta.xml
<CustomField>
    <fullName>Exam_Year__c</fullName>
    <label>Exam Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/NCP_Exam_year__c.field-meta.xml
<CustomField>
    <fullName>NCP_Exam_year__c</fullName>
    <formula>EventApi__Event__r.Exam_Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NCP Exam year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reserved for future use.</description>
    <inlineHelpText>Reserved for future use.</inlineHelpText>
    <label>RESERVED</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/ProgramApi__Program__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conditionally Required with Is Program Fee ** Defines the program for which a program profile is created as a result of purchasing/invoicing this item.</description>
    <inlineHelpText>Conditionally Required with Is Program Fee ** Defines the program for which a program profile is created as a result of purchasing/invoicing this item.</inlineHelpText>
    <label>Program</label>
    <referenceTo>ProgramApi__Program__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the item related to the sales order.</description>
    <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
    <label>Item</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/ProgramApi__Program_Profile__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Program_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates the Sales Order and Sales Order Line to the created program profile.</description>
    <inlineHelpText>Relates the Sales Order and Sales Order Line to the created program profile.</inlineHelpText>
    <label>Program Profile</label>
    <referenceTo>ProgramApi__Program_Profile__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/ProgramApi__Program_Term__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Program_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates the Sales Order and Sales Order Line to the created program term.</description>
    <inlineHelpText>Relates the Sales Order and Sales Order Line to the created program term.</inlineHelpText>
    <label>Program Term</label>
    <referenceTo>ProgramApi__Program_Term__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program__c/ProgramApi__Program__c.object-meta.xml
<CustomObject>
    <description>This object is used for the creation and management of programs.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/ProgramApi__Program_Profile__c.object-meta.xml
<CustomObject>
    <description>This object maintains a single persona for each participant in a given program.</description>
    <label>Program Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Program Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/Allowed_Credits__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Credits__c</fullName>
    <label>Allowed Credits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/Allowed_Workshops__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Workshops__c</fullName>
    <label>Allowed Workshops</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_End_Date__c</fullName>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_Name__c</fullName>
    <formula>ProgramApi__Program__r.ProgramApi__Progam_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FON Program Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FON_Program_Start_Date__c</fullName>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/FON_Trainer_Name__c.field-meta.xml
<CustomField>
    <fullName>FON_Trainer_Name__c</fullName>
    <label>Trainer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Account__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</description>
    <inlineHelpText>Identifies Account to a program profile when program entity is Account; an Account has only one profile for a program</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Contact to program profile; a Contact has only one profile for a program</description>
    <inlineHelpText>Identifies Contact to program profile; a Contact has only one profile for a program</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Create_Maintenance_Term__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Create_Maintenance_Term__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SYSTEM field; when enabled and record saved, creates new term and goals related to program maintenance requirements</description>
    <inlineHelpText>SYSTEM field; when enabled and record saved, creates new term and goals related to program maintenance requirements</inlineHelpText>
    <label>Create Maintenance Term</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Program__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies Program related to a program profile</description>
    <inlineHelpText>Identifies Program related to a program profile</inlineHelpText>
    <label>Program</label>
    <referenceTo>ProgramApi__Program__c</referenceTo>
    <relationshipLabel>Program Profiles</relationshipLabel>
    <relationshipName>Program_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__SalesOrderLineId__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__SalesOrderLineId__c</fullName>
    <description>System field to process the sales order line.</description>
    <inlineHelpText>System field to process the sales order line.</inlineHelpText>
    <label>SalesOrderLineId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Status__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Status__c</fullName>
    <description>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</description>
    <inlineHelpText>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Track</fullName>
                <default>true</default>
                <label>On Track</label>
            </value>
            <value>
                <fullName>Cautionary</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending Revocation</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/Registration_Origin__c.field-meta.xml
<CustomField>
    <fullName>Registration_Origin__c</fullName>
    <label>Registration Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Registrant</fullName>
                <default>true</default>
                <label>New Registrant</label>
            </value>
            <value>
                <fullName>Retake</fullName>
            </value>
            <value>
                <fullName>Transfer In (from a different year)</fullName>
            </value>
            <value>
                <fullName>Transfer In (from a different person)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/Renewed_on_New_Year__c.field-meta.xml
<CustomField>
    <fullName>Renewed_on_New_Year__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewed on New Year</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/ProgramApi__Program_Term__c.object-meta.xml
<CustomObject>
    <description>This object establishes the length of time given to complete tasks.</description>
    <label>Program Term</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Program Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/FON_ProgramProfileTrigger.cls
/**
 * Created by nkopparthi on 9/22/20.
 */

global without sharing class FON_ProgramProfileTrigger extends Framework.Domain{

    private boolean triggerIsExecuting;
    private integer triggerSize;
    public ProgramProfilesTriggerHelper helper;
    
    public FON_ProgramProfileTrigger(List<ProgramApi__Program_Profile__c> sObjectList) {
        super(sObjectList);
    }
    
    //public ProgramProfilesTriggerHandler(Boolean triggerIsExecuting, integer triggerSize){
    //    this.triggerIsExecuting = triggerIsExecuting;
    //    this.triggerSize = triggerSize;
    //    this.helper = new ProgramProfilesTriggerHelper();
    //}

    global class Constructor implements Framework.Domain.DomainConstructor  {
        global Framework.Domain construct(List<SObject> sObjectList) {
            return new FON_ProgramProfileTrigger(sObjectList);
        }
    }
    
    public override void beforeInsert(){
        Framework.Log.push(FON_ProgramProfileTrigger.class.getName(),'beforeInsert');
        //helper.setDefaults((ProgramApi__Program_Profile__c []) records);
        //helper.setTerms((ProgramApi__Program_Profile__c []) records);
        //FON_ProgramProfileService.setDefaults((ProgramApi__Program_Profile__c []) records);
        system.debug('BEFORE INSERT PP');
        setDefaults((List<ProgramApi__Program_Profile__c>) records);
        //FON_ProgramProfileService.setCreateStatus((ProgramApi__Program_Profile__c []) records);
        //List<ProgramApi__Program_Profile__c> npps = (List<ProgramApi__Program_Profile__c>) records;
        //system.debug('NEW Updated PP before insert' + npps[0].ProgramApi__Status__c);
        //FON_ProgramProfileService.setTerms((ProgramApi__Program_Profile__c []) records);
        Framework.Log.pop();
    }

    public override void afterInsert(){
        Framework.Log.push(FON_ProgramProfileTrigger.class.getName(),'afterInsert');
        //helper.setDefaults((ProgramApi__Program_Profile__c []) records);
        //helper.setTerms((ProgramApi__Program_Profile__c []) records);
        
        //FON_ProgramProfileService.setDefaults((ProgramApi__Program_Profile__c []) records);
        
        FON_ProgramProfileService.setTerms((ProgramApi__Program_Profile__c []) records);
        //FON_ProgramProfileService.setCreateStatus((ProgramApi__Program_Profile__c []) records);
        
        
        Framework.Log.pop();
    }

    public override void afterUpdate(Map<Id,SObject> oldMap){
        Framework.Log.push(FON_ProgramProfileTrigger.class.getName(),'afterUpdate');
        FON_ProgramProfileService.setBadge((ProgramApi__Program_Profile__c []) records, (Map<Id,ProgramApi__Program_Profile__c>) oldMap);
        //FON_ProgramProfileService.setStatus((ProgramApi__Program_Profile__c []) records, (Map<Id,ProgramApi__Program_Profile__c>) oldMap);
        //FON_ProgramProfileService.createNewPp((ProgramApi__Program_Profile__c []) records, (Map<Id,ProgramApi__Program_Profile__c>) oldMap);
        //FON_ProgramProfileService.setCreateStatus((ProgramApi__Program_Profile__c []) records);
        //FON_ProgramProfileService.validateTerms((ProgramApi__Program_Profile__c []) records);
        List<ProgramApi__Program_Profile__c> pps = (List<ProgramApi__Program_Profile__c>) records;
        
        
        
        List<Id> ppIds = new List<Id>();
        for (ProgramApi__Program_Profile__c pp : pps) {
            ppIds.add(pp.Id);
        }
    
        // Enqueue Queueable with retry support
        //if (!ppIds.isEmpty()) {
        //    System.enqueueJob(new FON_ProgramProfileValidateTermsQueueable(ppIds, 1), 1);
        //}
        
        // Create queueables
        Queueable[] jobs = new Queueable[] {
            new FON_ProgramProfileValidateTermsQueueable(ppIds)
        };
        FON_QueueableGatekeeper.enqueueIfFree(jobs, 0, 2);
        // Enqueue through Gatekeeper with 2-minute retry delay
        //System.enqueueJob(new FON_QueueableGatekeeper(jobs, 0, 2));
        
        Framework.Log.pop();
    }
    
    
    public static void setDefaults(List<ProgramApi__Program_Profile__c> records){

        Set<Id> ppIds = new Set<Id>();
        List<ProgramApi__Program_Profile__c> ppList = new List<ProgramApi__Program_Profile__c>();
        List<ProgramApi__Program_Term__c> ptList = new List<ProgramApi__Program_Term__c>();
        Set<Id> solIds = new Set<Id>();
        List<OrderApi__Sales_Order_Line__c> solList = new List<OrderApi__Sales_Order_Line__c>();
        Map<Id, Decimal> mapIDYear = new Map<Id, Decimal>();
        List<ProgramApi__Program_Profile__c> lstPPUpd = new List<ProgramApi__Program_Profile__c>();

        Set<Id> conIds = new Set<Id>();
        Set<Id> accIds = new Set<Id>();
        Map<Id,Integer> mapContactxNumProg = new Map<Id,Integer>();
        // get NCP program
        List<ProgramApi__Program__c> ncpProg = [Select Id FROM ProgramApi__Program__c WHERE Name = 'NCP' LIMIT 1];

        for(ProgramApi__Program_Profile__c pp : records){
            ppIds.add(pp.Id);
            system.debug('init set defaults pp '+pp.FON_Program_Name__c);
            ppList.add(pp);
            conIds.add(pp.ProgramApi__Contact__c);
            accIds.add(pp.ProgramApi__Account__c);
        }

		 system.debug('ppList '+ppList);
        for(ProgramApi__Program_Profile__c pp : ppList){
            solIds.add(pp.ProgramApi__SalesOrderLineId__c);
        }
		system.debug('solIDS '+solIds);
        if(solIds.size()>0){
            solList = [SELECT Id, OrderApi__Item__r.NCP_Exam_Year__c FROM OrderApi__Sales_Order_Line__c WHERE Id IN :solIds];
			system.debug('solList '+solList);
        }
        
        
        for(OrderApi__Sales_Order_Line__c sol : solList){
            if(!Test.isRunningTest()){ 
            	mapIDYear.put(sol.Id, sol.OrderApi__Item__r.NCP_Exam_Year__c);
            }else{
                mapIDYear.put(sol.Id, 2025);
            }
        }
		Date currentDate = system.today();
        
        List<ProgramApi__Program_Profile__c> ppsListAll = [SELECT Id, FON_Program_Start_Date__c, FON_Program_End_Date__c, ProgramApi__Account__c, ProgramApi__Contact__c  
                                                           FROM ProgramApi__Program_Profile__c 
                                                           WHERE ProgramApi__Account__c IN: accIds AND ProgramApi__Contact__c IN: conIds AND Id NOT IN: ppIds];
        
        Map<String, List<ProgramApi__Program_Profile__c>> mapAccContToPPList = new Map<String, List<ProgramApi__Program_Profile__c>>();
        if(ppsListAll.size()> 0){
            for(ProgramApi__Program_Profile__c pp : ppsListAll){
                String keyPP = String.valueOf(pp.ProgramApi__Account__c) + String.valueOf(pp.ProgramApi__Contact__c);
                if(mapAccContToPPList.containsKey(keyPP)){
                    mapAccContToPPList.get(keyPP).add(pp);
                }else{
                    mapAccContToPPList.put(keyPP, new List<ProgramApi__Program_Profile__c>{pp});
                }
            }
        }
        // check if user has current profile
        /*List<ProgramApi__Program_Profile__c> cppList = [
            SELECT Id,ProgramApi__Contact__c,
            ProgramApi__Program__r.Name,
            ProgramApi__SalesOrderLineId__c,
            FON_Program_Start_Date__c,
            FON_Program_End_Date__c,
            ProgramApi__Status__c,
            Renewed_on_New_Year__c,
            ProgramApi__Create_Maintenance_Term__c
            FROM ProgramApi__Program_Profile__c
            WHERE ProgramApi__Contact__c =: records[0].ProgramApi__Contact__c
        ];*/
        
        for(ProgramApi__Program_Profile__c pp : records){
            if(pp.ProgramApi__Program__c == ncpProg[0].Id){
                //Integer currentPf = mapContactxNumProg.get(pp.ProgramApi__Contact__c);
                
                //if(pp.ProgramApi__SalesOrderLineId__c != NULL && pp.ProgramApi__SalesOrderLineId__c != '') {
                    
                    // check for current profiles
                    String keyPP = String.valueOf(pp.ProgramApi__Account__c) + String.valueOf(pp.ProgramApi__Contact__c);
                    //List<ProgramApi__Program_Profile__c> currentProfiles = new List<ProgramApi__Program_Profile__c>();
                    //currentProfiles = mapAccContToPPList.get(keyPP);
                    List<ProgramApi__Program_Profile__c> currentProfiles =
                        mapAccContToPPList.get(keyPP) != null 
                        ? mapAccContToPPList.get(keyPP)
                        : new List<ProgramApi__Program_Profile__c>();
                    
                    /*if(pp.FON_Program_Start_Date__c == null){
                    	pp.FON_Program_Start_Date__c = Date.newInstance(currentDate.year(), 4, 1);
                    //}else if(pp.Renewed_on_New_Year__c==true){
                    }else{
                        pp.FON_Program_Start_Date__c = Date.newInstance(currentDate.year(), 1, 1);
                    }
                    pp.FON_Program_End_Date__c = Date.newInstance(currentDate.year() + 5, 12, 31);
                    */
    				if(currentProfiles.size()>0 ){
                        pp.FON_Program_Start_Date__c = Date.newInstance(integer.valueOf(pp.Exam_Year__c), 1, 1);
                        pp.FON_Program_End_Date__c = Date.newInstance(integer.valueOf(pp.Exam_Year__c) + 5, 12, 31);
                        pp.ProgramApi__Status__c = 'Maintenance';
                        pp.Registration_Origin__c = '';
                    }else{
                        pp.FON_Program_Start_Date__c = Date.newInstance(integer.valueOf(pp.Exam_Year__c), 4, 1);
                        pp.FON_Program_End_Date__c = Date.newInstance(integer.valueOf(pp.Exam_Year__c) + 5, 12, 31);
                        pp.ProgramApi__Status__c = 'On Track';
                        pp.Registration_Origin__c = 'New Registrant';
                    }
                    //pp.FON_Trainer_Name__c = 'set default';
                    
                    
                    
                    pp.Allowed_Credits__c = Decimal.valueOf(System.Label.Allowed_Credits_NCP);
                    pp.Allowed_Workshops__c = Decimal.valueOf(System.Label.Allowed_Workshops_NCP);
                    //pp.FON_Trainer_Name__c = 'from routing rule';
                    system.debug('new pp '+pp.FON_Program_Start_Date__c+' ---'+pp.FON_Program_End_Date__c);
                //}

            }
            system.debug('NEW BINSERT PP' + pp.ProgramApi__Status__c + pp);
        }

    }

}