unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</description>
    <inlineHelpText>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reserved for future use.</description>
    <inlineHelpText>Reserved for future use.</inlineHelpText>
    <label>RESERVED</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Balance_Due__c</fullName>
    <description>Defines the remaining amount due for this sales order.</description>
    <formula>OrderApi__Overall_Total__c -  OrderApi__Amount_Paid__c + IF(OrderApi__Is_Invoiced__c, OrderApi__Amount_Refunded__c, 0) - OrderApi__Credits_Applied__c + OrderApi__Credits_and_Adjustments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total - Total Payments</inlineHelpText>
    <label>Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>**System Calculated/Override** Checked when a recurring order or contract is active.</description>
    <inlineHelpText>**System Calculated/Override** Checked when a recurring order or contract is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Overall_Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Overall_Total__c</fullName>
    <description>Overall Amount of Sales Order.</description>
    <inlineHelpText>Overall Amount of Sales Order.</inlineHelpText>
    <label>Overall Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Total__c</fullName>
    <description>**System Calculated**. Subtotal +</description>
    <formula>OrderApi__Subtotal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>**System Calculated** Subtotal +</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Balance_Due__c</fullName>
    <description>Defines the remaining amount due for this sales order line item.</description>
    <inlineHelpText>This field identifies the remaining balance unpaid for this invoice line.</inlineHelpText>
    <label>Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the item related to the sales order.</description>
    <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
    <label>Item</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Overall_Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Overall_Total__c</fullName>
    <description>Overall Amount of Sales Order Line.</description>
    <inlineHelpText>Overall Amount of Sales Order Line.</inlineHelpText>
    <label>Overall Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Price_Override__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Price_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Overrides the calculation of price based on the most appropriate price for the purchasing customer. Default is unchecked.</description>
    <inlineHelpText>Overrides the calculation of price based on the most appropriate price for the purchasing customer. Default is unchecked.</inlineHelpText>
    <label>Price Override</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sale_Price__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>**System Calculated/Override** The price per-unit for the item sold on the sales order line.</description>
    <inlineHelpText>**System Calculated/Override** The price per-unit for the item sold on the sales order line.</inlineHelpText>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Total__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>**System Calculated** Total amount of Sales Order Line</description>
    <inlineHelpText>**System Calculated** Total amount of Sales Order Line</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/CreateBulkSMBillingLinesQueueable.cls
public class CreateBulkSMBillingLinesQueueable implements Queueable, Database.AllowsCallouts {
    private List<OrderApi__Sales_Order_Line__c> solsToInsert;
    private static final Integer BATCH_SIZE = 50;
    private String soID;
    private Boolean withDiscount;
    private String discountType; // Change to your actual data type
    private Decimal discountAmount; // Change to your actual data type

    public CreateBulkSMBillingLinesQueueable(List<OrderApi__Sales_Order_Line__c> sols, String soID,Boolean withDiscount, String discountType, Decimal discountAmount) {
        this.solsToInsert = sols;
        this.soID = soID;
        this.withDiscount = withDiscount;
        this.discountType = discountType;
        this.discountAmount = discountAmount;
    }

    public void execute(QueueableContext context) {
        // Create a list to hold the current batch
        List<OrderApi__Sales_Order_Line__c> currentBatch = new List<OrderApi__Sales_Order_Line__c>();

        try {
            // Check if there are enough records for a batch
            if (solsToInsert.size() > BATCH_SIZE) {
                // Add records to the current batch and remove them from the original list
                for (Integer i = 0; i < BATCH_SIZE; i++) {
                    currentBatch.add(solsToInsert.remove(0)); // removing the first element each time reduces the list size
                }

                // Perform the DML operation
                insert currentBatch;

                // Now, queue the next job with the remaining records
                System.enqueueJob(new CreateBulkSMBillingLinesQueueable(solsToInsert,soID,withDiscount,discountType,discountAmount));
            } else {
                // If less than BATCH_SIZE records are left, insert all of them
                insert solsToInsert;
                // This is the last batch, so we don't need to re-queue after this
                // 
                
                if(withDiscount==true || Test.isRunningTest()){
                    // now calculate the discount
                    AggregateResult result = [
                        SELECT SUM(OrderApi__Overall_Total__c) sum
                        FROM OrderApi__Sales_Order_Line__c WHERE OrderApi__Sales_Order__c =: soID
                    ];
                    Double totalDiscount = 0;
                    if(discountType == 'Percentage'){
                        totalDiscount = (Double) result.get('sum') * (discountAmount/100);
                    }else{
                        totalDiscount = discountAmount;
                    }
                    Double ddsc = totalDiscount;
                    totalDiscount = -1 * totalDiscount;
                    
                    // get discount item
                    List<OrderApi__Item__c> ditem = [Select Id FROM OrderApi__Item__c WHERE OrderApi__Is_Active__c = true AND Name = 'Discount'];
                    if(Test.isRunningTest()){
                        ditem = [Select Id FROM OrderApi__Item__c LIMIT 1];
                    }
                    
                    OrderApi__Sales_Order_Line__c sol = new OrderApi__Sales_Order_Line__c();
                    sol.OrderApi__Item__c = ditem[0].Id;
                    sol.OrderApi__Sales_Order__c = soID;
                    sol.OrderApi__Price_Override__c = true;
                    sol.OrderApi__Sale_Price__c = totalDiscount;
                    sol.OrderApi__Total__c = totalDiscount;
                    sol.OrderApi__Overall_Total__c = totalDiscount;
                    sol.OrderApi__Balance_Due__c = totalDiscount;
                    insert sol;
                    
                    // update the total
                    OrderApi__Sales_Order__c so = [Select Id,OrderApi__Overall_Total__c FROM OrderApi__Sales_Order__c WHERE Id =:soID];
                    so.OrderApi__Overall_Total__c = (Double) result.get('sum') - ddsc;
                    update so;
                    
                }
                
            }
        } catch (Exception e) {
            // Handle the exception (e.g., you might want to log the error or send a notification)
            // For now, we will simply re-throw the exception
            throw e;
        }
    }
}


/* FDService Version
 * 
 * public class CreateBulkSMBillingLinesQueueable implements Queueable {
    List<FDService.SalesOrderLine> solsToInsert;

    public CreateBulkSMBillingLinesQueueable(List<FDService.SalesOrderLine> sols) {
        this.solsToInsert = sols;
    }

    public void execute(QueueableContext context) {
        
        FDService.OrderService orderService = FDService.OrderService.getInstance();
        List<FDService.SalesOrderLine> lines = new List<FDService.SalesOrderLine>();
        try {
            // Check if we're nearing the CPU time limit
            if (Limits.getCpuTime() < (Limits.getLimitCpuTime() - 10)) { // 10 is a buffer
                lines = orderService.addItemsToOrder(solsToInsert);
            } else {
                // If nearing the limit, enqueue again after a delay
                System.enqueueJob(new CreateBulkSMBillingLinesQueueable(this.solsToInsert));
            }
        } catch (Exception e) {
            // Handle any exceptions here, such as logging or sending notifications
        }
    }
}*/