unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Is_Shipping_Rate__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Shipping_Rate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to create a Shipping Rate.</description>
    <inlineHelpText>Select the checkbox to create a Shipping Rate.</inlineHelpText>
    <label>Is Shipping Rate</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reserved for future use.</description>
    <inlineHelpText>Reserved for future use.</inlineHelpText>
    <label>RESERVED</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</description>
    <inlineHelpText>**System Calculated/Override** Link to the customer&#39;s contact record. Auto-populates with the related account&#39;s primary contact if not defined prior to entry.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Country__c</fullName>
    <description>The value of this field will be updated with the Account&#39;s Shipping Country or Contact&#39;s Mailing Country, based on &quot;Entity&quot; if not defined on record entry.</description>
    <inlineHelpText>The value of this field will be updated with the Account&#39;s Shipping Country or Contact&#39;s Mailing Country, based on &quot;Entity&quot; if not defined on record entry.</inlineHelpText>
    <label>Shipping Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Total__c</fullName>
    <description>**System Calculated**. Subtotal +</description>
    <formula>OrderApi__Subtotal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>**System Calculated** Subtotal +</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Account__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Contact__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
    <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Is_Shipping_Rate__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Shipping_Rate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines the Sales Order Line that is being used for shipping.</description>
    <inlineHelpText>Select the checkbox to have this Sales Order Line represent shipping.</inlineHelpText>
    <label>Is Shipping Rate</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the item related to the sales order.</description>
    <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
    <label>Item</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Quantity__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>**Conditionally Required** The quantity (number of units) of the item related to the sales order line. Required when an Item is linked that does not have &quot;Disable Price Rules&quot; checked. Default 1.</description>
    <inlineHelpText>**Conditionally Required** The quantity (number of units) of the item related to the sales order line. Required when an Item is linked that does not have &quot;Disable Price Rules&quot; checked. Default 1.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_City__c</fullName>
    <description>Optional shipping city for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping City&quot; field.</description>
    <inlineHelpText>Optional shipping city for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping City&quot; field.</inlineHelpText>
    <label>Shipping City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Country__c</fullName>
    <description>Optional shipping country for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Country&quot; field.</description>
    <inlineHelpText>Optional shipping country for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Country&quot; field.</inlineHelpText>
    <label>Shipping Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Postal_Code__c</fullName>
    <description>Optional shipping postal code for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &#39;&quot;Shipping Postal Code&quot; field.</description>
    <inlineHelpText>Optional shipping postal code for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &#39;&quot;Shipping Postal Code&quot; field.</inlineHelpText>
    <label>Shipping Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_State__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_State__c</fullName>
    <description>Optional shipping state for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping State&quot; field.</description>
    <inlineHelpText>Optional shipping state for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping State&quot; field.</inlineHelpText>
    <label>Shipping State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Shipping_Street__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Shipping_Street__c</fullName>
    <description>Optional shipping street for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Street&quot; field.</description>
    <inlineHelpText>Optional shipping street for the item&#39;s ordered on the order line. If left blank, the value of this field will be updated with the value of the parent order&#39;s &quot;Shipping Street&quot; field.</inlineHelpText>
    <label>Shipping Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Total__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>**System Calculated** Total amount of Sales Order Line</description>
    <inlineHelpText>**System Calculated** Total amount of Sales Order Line</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/AvalaraCheckoutService.cls
/**
 * AuraEnabled controller for the AvalaraCheckout Spark Plug component.
 * Handles UI concerns: checkout info, entity address management, and delegates tax calculation.
 */
public without sharing class AvalaraCheckoutService {

    public class TaxableItem {
        @AuraEnabled public String name;
        @AuraEnabled public Decimal quantity;
        @AuraEnabled public Decimal total;
    }

    public class CheckoutInfo {
        @AuraEnabled public List<TaxableItem> taxableItems;
        @AuraEnabled public String entityId;
        @AuraEnabled public String entityType;
        @AuraEnabled public String street;
        @AuraEnabled public String city;
        @AuraEnabled public String state;
        @AuraEnabled public String postalCode;
        @AuraEnabled public String country;
    }

    @AuraEnabled
    public static CheckoutInfo getCheckoutInfo(String encryptedSalesOrderId) {
        Id salesOrderId = resolveSalesOrderId(encryptedSalesOrderId);
        OrderApi__Sales_Order__c so = querySalesOrder(salesOrderId);

        CheckoutInfo info = new CheckoutInfo();
        info.taxableItems = buildTaxableItems(so.OrderApi__Sales_Order_Lines__r);
        populateEntityAddress(info, so);

        return info;
    }

    @AuraEnabled
    public static void updateEntityAddress(String encryptedSalesOrderId, String entityId, String entityType, Boolean saveForFuture, String street, String city, String state, String postalCode, String country) {
        if (saveForFuture) {
            updateEntity(entityId, entityType, street, city, state, postalCode, country);
        }

        Id salesOrderId = resolveSalesOrderId(encryptedSalesOrderId);
        update new OrderApi__Sales_Order__c(
            Id = salesOrderId,
            OrderApi__Shipping_Street__c = street,
            OrderApi__Shipping_City__c = city,
            OrderApi__Shipping_State__c = state,
            OrderApi__Shipping_Postal_Code__c = postalCode,
            OrderApi__Shipping_Country__c = country
        );
    }

    @AuraEnabled
    public static void calculateTax(String encryptedSalesOrderId) {
        Id salesOrderId = resolveSalesOrderId(encryptedSalesOrderId);
        AvalaraTaxCalculationService.calculateTax(salesOrderId);
    }

    // ─── Private Helpers ───

    private static List<TaxableItem> buildTaxableItems(List<OrderApi__Sales_Order_Line__c> lines) {
        List<TaxableItem> items = new List<TaxableItem>();

        if (lines == null) {
            return items;
        }

        for (OrderApi__Sales_Order_Line__c sol : lines) {
            TaxableItem item = new TaxableItem();
            item.name = sol.OrderApi__Item__r.Name;
            item.quantity = sol.OrderApi__Quantity__c;
            item.total = sol.OrderApi__Total__c;
            items.add(item);
        }

        return items;
    }

    private static void populateEntityAddress(CheckoutInfo info, OrderApi__Sales_Order__c so) {
        if (so.OrderApi__Contact__c != null) {
            Contact ct = [
                SELECT MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry
                FROM Contact
                WHERE Id = :so.OrderApi__Contact__c
                WITH SYSTEM_MODE
            ];
            info.entityId = ct.Id;
            info.entityType = 'Contact';
            info.street = ct.MailingStreet;
            info.city = ct.MailingCity;
            info.state = ct.MailingState;
            info.postalCode = ct.MailingPostalCode;
            info.country = ct.MailingCountry;
        } else if (so.OrderApi__Account__c != null) {
            Account acc = [
                SELECT ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, ShippingCountry
                FROM Account
                WHERE Id = :so.OrderApi__Account__c
                WITH SYSTEM_MODE
            ];
            info.entityId = acc.Id;
            info.entityType = 'Account';
            info.street = acc.ShippingStreet;
            info.city = acc.ShippingCity;
            info.state = acc.ShippingState;
            info.postalCode = acc.ShippingPostalCode;
            info.country = acc.ShippingCountry;
        }
    }

    private static void updateEntity(String entityId, String entityType, String street, String city, String state, String postalCode, String country) {
        if (entityType == 'Contact') {
            update new Contact(
                Id = entityId,
                MailingStreet = street,
                MailingCity = city,
                MailingState = state,
                MailingPostalCode = postalCode,
                MailingCountry = country
            );
        } else if (entityType == 'Account') {
            update new Account(
                Id = entityId,
                ShippingStreet = street,
                ShippingCity = city,
                ShippingState = state,
                ShippingPostalCode = postalCode,
                ShippingCountry = country
            );
        }
    }

    private static OrderApi__Sales_Order__c querySalesOrder(Id salesOrderId) {
        return [
            SELECT Id, OrderApi__Contact__c, OrderApi__Account__c,
                   (SELECT Id, OrderApi__Item__r.Name,
                           OrderApi__Quantity__c, OrderApi__Total__c
                    FROM OrderApi__Sales_Order_Lines__r
                    WHERE OrderApi__Item__r.Avalara_Tax__c != null
                      AND OrderApi__Is_Shipping_Rate__c = false)
            FROM OrderApi__Sales_Order__c
            WHERE Id = :salesOrderId
            WITH SYSTEM_MODE
        ];
    }

    private static Id resolveSalesOrderId(String encryptedSalesOrderId) {
        List<OrderApi__Sales_Order__c> salesOrders = [
            SELECT Id
            FROM OrderApi__Sales_Order__c
            WHERE OrderApi__Encrypted_Id__c = :encryptedSalesOrderId
            WITH SYSTEM_MODE
            LIMIT 1
        ];

        if (salesOrders.isEmpty()) {
            throw new AvalaraAuthProviderService.AvalaraException('Sales Order not found for encrypted ID.');
        }

        return salesOrders[0].Id;
    }

}