unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Is_Event__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Is_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <description>** System Calculated Override ** Enable event specific controls and features for this Item. Defaults to the value of the same field on the Item&#39;s related Item Class.</description>
    <inlineHelpText>** System Calculated Override ** Enable event specific controls and features for this Item. Defaults to the value of the same field on the Item&#39;s related Item Class.</inlineHelpText>
    <label>Is Event</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reserved for future use.</description>
    <inlineHelpText>Reserved for future use.</inlineHelpText>
    <label>RESERVED</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/ProgramApi__Program__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conditionally Required with Is Program Fee ** Defines the program for which a program profile is created as a result of purchasing/invoicing this item.</description>
    <inlineHelpText>Conditionally Required with Is Program Fee ** Defines the program for which a program profile is created as a result of purchasing/invoicing this item.</inlineHelpText>
    <label>Program</label>
    <referenceTo>ProgramApi__Program__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Receipt__c/OrderApi__Receipt__c.object-meta.xml
<CustomObject>
    <description>Receipts track Customer Payments and Refunds.</description>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Receipt__c/fields/OrderApi__Encrypted_Id__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Encrypted_Id__c</fullName>
    <description>This field shows this record&#39;s encrypted id used for external pages.</description>
    <inlineHelpText>This field shows this record&#39;s encrypted id used for external pages.</inlineHelpText>
    <label>Encrypted Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Receipt__c/fields/OrderApi__Receipt__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Caluclated** Lookup to the reciept for which you are refunding.</description>
    <inlineHelpText>**System Caluclated** Lookup to the reciept for which you are refunding.</inlineHelpText>
    <label>Receipt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OrderApi__Receipt__c.OrderApi__Is_Payment__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OrderApi__Receipt__c</referenceTo>
    <relationshipLabel>Refunds</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Receipt__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Link to related Sales Order.</description>
    <inlineHelpText>**System Calculated/Override** Link to related Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Receipt__c/fields/OrderApi__Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Total__c</fullName>
    <defaultValue>0</defaultValue>
    <description>**Conditionally Required** Receipt Total, required to post receipt to GL (Transactions).</description>
    <inlineHelpText>**Conditionally Required** Receipt Total, required to post receipt to GL (Transactions).</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Total__c</fullName>
    <description>**System Calculated**. Subtotal +</description>
    <formula>OrderApi__Subtotal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>**System Calculated** Subtotal +</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Item__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the item related to the sales order.</description>
    <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
    <label>Item</label>
    <referenceTo>OrderApi__Item__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Total__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>**System Calculated** Total amount of Sales Order Line</description>
    <inlineHelpText>**System Calculated** Total amount of Sales Order Line</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program__c/ProgramApi__Program__c.object-meta.xml
<CustomObject>
    <description>This object is used for the creation and management of programs.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/GetCYRILPCSparkPlugController.cls
global without sharing class GetCYRILPCSparkPlugController {
    @AuraEnabled
    public static Map<String,List<SObject>> getSalesOrder(String orderNumber) {
		Map<String,List<SObject>> sop = new Map<String,List<SObject>>();
        
        String sid;
        try{
            List<OrderApi__Sales_Order__c> so = [SELECT Id,Name,OrderApi__Total__c,OrderApi__Encrypted_Id__c FROM OrderApi__Sales_Order__c WHERE Name =:orderNumber];
            if(so != null && so.size() > 0) {
                sop.put('order',so);
                sid = so[0].Id;
            }else{
                List<OrderApi__Receipt__c> receiptList = [SELECT Id,OrderApi__Total__c,OrderApi__Encrypted_Id__c,OrderApi__Sales_Order__r.Id,OrderApi__Sales_Order__r.OrderApi__Encrypted_Id__c,OrderApi__Sales_Order__r.OrderApi__Total__c FROM OrderApi__Receipt__c WHERE Name =:orderNumber LIMIT 1];
                sop.put('receipt',receiptList);
                sid = receiptList[0].OrderApi__Sales_Order__r.Id;
            }
        } catch (ListException le) {
            System.debug('Receipt not found: '+le.getMessage());

        }
        
        
        
        
		
        
        // get line items
        List<OrderApi__Sales_Order_Line__c> sol = [SELECT Id,OrderApi__Item__r.Name,OrderApi__Item__r.OrderApi__Is_Event__c,OrderApi__Item__r.ProgramApi__Program__r.Id,OrderApi__Item__r.ProgramApi__Program__r.Name FROM OrderApi__Sales_Order_Line__c WHERE OrderApi__Sales_Order__c =:sid];
		sop.put('lines',sol);
        
        return sop;
    }
}