unpackaged/main/default/objects/ProgramApi__Program_Profile__c/ProgramApi__Program_Profile__c.object-meta.xml
<CustomObject>
    <description>This object maintains a single persona for each participant in a given program.</description>
    <label>Program Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Program Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Profile__c/fields/ProgramApi__Status__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Status__c</fullName>
    <description>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</description>
    <inlineHelpText>Identifies the participants program status; Maintenance identifies participants successfully completed program and have an active program term</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Track</fullName>
                <default>true</default>
                <label>On Track</label>
            </value>
            <value>
                <fullName>Cautionary</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending Revocation</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/FON_QueueableGatekeeperTest.cls
@IsTest
public class FON_QueueableGatekeeperTest {

    @IsTest
    static void testGatekeeperEnqueuesJobs() {

        // Prepare sample data
        ProgramApi__Program_Profile__c pp = new ProgramApi__Program_Profile__c(
            ProgramApi__Status__c = 'New'
        );
        insert pp;

        List<Id> ids = new List<Id>{ pp.Id };
        
        List<ProgramApi__Program_Profile__c> pps = new List<ProgramApi__Program_Profile__c>();
        pps.add(pp);

        // FIX: your queueables must be top-level classes
        Queueable job1 = new FON_ProgramProfileSetStatusQueueable(pps);
        Queueable job2 = new FON_ProgramProfileValidateTermsQueueable(ids);

        Queueable[] jobs = new Queueable[]{ job1, job2 };

        Test.startTest();
        System.enqueueJob(new FON_QueueableGatekeeper(jobs, 1, 1));
        Test.stopTest();


    }


    @IsTest
    static void testSchedulableCallsGatekeeper() {

        Queueable job = new FON_ProgramProfileSetStatusQueueable(null);

        Queueable[] jobs = new Queueable[]{ job };

        // Run once in test mode
        String cron = '0 0 0 1 1 ? 2050';

        Test.startTest();
        System.schedule(
            'Test_Gatekeeper_Sched',
            cron,
            new FON_GatekeeperSchedulable(jobs, 0, 1)
        );
        Test.stopTest();


    }



}