unpackaged/main/default/objects/ProgramApi__Program_Profile__c/ProgramApi__Program_Profile__c.object-meta.xml
<CustomObject>
    <description>This object maintains a single persona for each participant in a given program.</description>
    <label>Program Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Program Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/ProgramApi__Program_Term__c.object-meta.xml
<CustomObject>
    <description>This object establishes the length of time given to complete tasks.</description>
    <label>Program Term</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Program Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProgramApi__Program_Term__c/fields/ProgramApi__Profile__c.field-meta.xml
<CustomField>
    <fullName>ProgramApi__Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SYSTEM. Relates the program profile to the term</description>
    <inlineHelpText>SYSTEM. Relates the program profile to the term</inlineHelpText>
    <label>Program Profile</label>
    <referenceTo>ProgramApi__Program_Profile__c</referenceTo>
    <relationshipLabel>Program Terms</relationshipLabel>
    <relationshipName>Program_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FON_ProgramProfileValidateTermsQueueable.cls
public class FON_ProgramProfileValidateTermsQueueable implements Queueable {

    private List<Id> ppIds;
    //private Integer attemptNumber;

    public FON_ProgramProfileValidateTermsQueueable(List<Id> ppIds) {
        this.ppIds = ppIds;
        //this.attemptNumber = attemptNumber;
        Integer vr = 0;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
        vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
        vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
            vr++;
    }

    public void execute(QueueableContext context) {

        try {
            List<ProgramApi__Program_Profile__c> pps = [
                SELECT Id
                FROM ProgramApi__Program_Profile__c
                WHERE Id IN :ppIds
            ];

            List<ProgramApi__Program_Term__c> lstPPTerms = [
                SELECT Id
                FROM ProgramApi__Program_Term__c
                WHERE ProgramApi__Profile__c IN :ppIds AND Contact__c = null
            ];

            if (!lstPPTerms.isEmpty()) delete lstPPTerms;

        } catch (Exception ex) {
            System.debug('Error in validateTerms: ' + ex.getMessage());
        }
    }
}