unpackaged/main/default/objects/OrderApi__Business_Group__c/OrderApi__Business_Group__c.object-meta.xml
<CustomObject>
    <description>Separate groups or business entities to facilitate clear reporting on business lines and/or entities.</description>
    <label>Business Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Business_Group__c/fields/OrderApi__Description__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Description__c</fullName>
    <description>Briefly describe the ledger as you would like to see it on a report. (72 Chars. or less)</description>
    <inlineHelpText>Briefly describe the ledger as you would like to see it on a report. (72 Chars. or less)</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Business_Group__c/fields/OrderApi__Display_Name__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Display_Name__c</fullName>
    <description>** System Calculated Override ** The name that should be displayed when the Business Group is referenced on Invoices and other external pages and documents. Defaults to the &quot;Name&quot; defined for the Business Group.</description>
    <inlineHelpText>** System Calculated Override ** The name that should be displayed when the Business Group is referenced on Invoices and other external pages and documents. Defaults to the &quot;Name&quot; defined for the Business Group.</inlineHelpText>
    <label>Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Business_Group__c/fields/OrderApi__Email__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Email__c</fullName>
    <description>** System Calculated ** The email address to display to customers on Invoices and related documents.</description>
    <inlineHelpText>** System Calculated ** The email address to display to customers on Invoices and related documents.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/OrderApi__Item__c.object-meta.xml
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Business_Group__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Items can be related to Business Groups to separate business lines and/or legal entities on transactional (sales) and financial reports.</description>
    <inlineHelpText>Items can be related to Business Groups to separate business lines and/or legal entities on transactional (sales) and financial reports.</inlineHelpText>
    <label>Business Group</label>
    <referenceTo>OrderApi__Business_Group__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Description__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Description__c</fullName>
    <description>Product description.</description>
    <inlineHelpText>Product description.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Item__c/fields/OrderApi__Display_Name__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Display_Name__c</fullName>
    <description>** System Calculated Override ** The name of the Item as you would like it to display when published to customers. Defaults to the same value of the &quot;Item Name&quot; field.</description>
    <inlineHelpText>** System Calculated Override ** The name of the Item as you would like it to display when published to customers. Defaults to the same value of the &quot;Item Name&quot; field.</inlineHelpText>
    <label>Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/OrderApi__Sales_Order__c.object-meta.xml
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>OrderApi__Billing_City__c &amp;&#39;,&#39;&amp;&#39; &#39;&amp; OrderApi__Billing_State__c &amp;&#39; &#39;&amp; OrderApi__Billing_Postal_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>OrderApi__Contact__r.FirstName&amp;&#39; &#39;&amp;OrderApi__Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/FON_Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>FON_Billing_Type__c</fullName>
    <inlineHelpText>*System Generated* Based on value populated when creating the invoice. Can manually populate if needed.</inlineHelpText>
    <label>Billing Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <formula>&#39;E&#39;&amp;FON_Billing_Quarter__c&amp;FON_Invoice_Year__c&amp;
IF(FON_Invoice_Timing__c == &#39;Annual&#39;, &#39;A&#39;, &#39;Q&#39;)&amp;
IF(FON_Billing_Type__c == &#39;Deposit Based&#39;, &#39;D&#39;, &#39;i&#39;)&amp;
Auto_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice #</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/Invoice_Term__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Term__c</fullName>
    <formula>IF(Is_Sponsoring_Licensing_Invoice__c=true,
IF(NOT(ISBLANK(Custom_Coverage__c)),
Custom_Coverage__c,
Sponsored_Billing_Coverage__c
),
&#39;N/A&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coverage</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/Invoice_Total__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Total__c</fullName>
    <formula>OrderApi__Overall_Total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Billing_Street__c</fullName>
    <description>**System Calculated/Conditional** Billing Street derives from the Contact Mailing Street or the Account Billing Street when Calculate Billing Details is checked.</description>
    <inlineHelpText>**System Calculated/Conditional** Billing Street derives from the Contact Mailing Street or the Account Billing Street when Calculate Billing Details is checked.</inlineHelpText>
    <label>Billing Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Business_Group__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Link to the business group record - business groups will auto-populate if not defined on entry.</description>
    <inlineHelpText>**System Calculated/Override** Link to the business group record - business groups will auto-populate if not defined on entry.</inlineHelpText>
    <label>Business Group</label>
    <referenceTo>OrderApi__Business_Group__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Customer_Link__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Customer_Link__c</fullName>
    <description>**System Calculated** Link to the customer&#39;s record, controlled by the &quot;Entity&quot; field.</description>
    <formula>IF(ISPICKVAL(OrderApi__Entity__c,&quot;Account&quot;),HYPERLINK(&quot;/&quot; &amp; OrderApi__Account__r.Id, OrderApi__Account__r.Name), HYPERLINK(&quot;/&quot; &amp; OrderApi__Contact__r.Id, OrderApi__Contact__r.FirstName &amp; &quot; &quot; &amp; OrderApi__Contact__r.LastName))</formula>
    <inlineHelpText>**System Calculated** Link to the customer&#39;s record, controlled by the &quot;Entity&quot; field.</inlineHelpText>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Description__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Description__c</fullName>
    <description>Text field to capture information about the Sales Order.</description>
    <inlineHelpText>Internal facing descriptions will not appear and should not be included in customer-facing communications.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/OrderApi__Overall_Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Overall_Total__c</fullName>
    <description>Overall Amount of Sales Order.</description>
    <inlineHelpText>Overall Amount of Sales Order.</inlineHelpText>
    <label>Overall Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order__c/fields/PO_ID__c.field-meta.xml
<CustomField>
    <fullName>PO_ID__c</fullName>
    <formula>Sponsoring_Licensing_Account__r.Sponsored_Relationship2__r.PO_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PO ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/OrderApi__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Business_Group__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>**System Calculated/Override** Default value is mapped from the parent sales order. The Business Group controls what items are available to associate with the order line. If no value exists, all active items will be allowed to be associated.</description>
    <inlineHelpText>**System Calculated/Override** Default value is mapped from the parent sales order. The Business Group controls what items are available to associate with the order line. If no value exists, all active items will be allowed to be associated.</inlineHelpText>
    <label>Business Group</label>
    <referenceTo>OrderApi__Business_Group__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Overall_Total__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Overall_Total__c</fullName>
    <description>Overall Amount of Sales Order Line.</description>
    <inlineHelpText>Overall Amount of Sales Order Line.</inlineHelpText>
    <label>Overall Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/OrderApi__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Sales_Order__c</fullName>
    <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
    <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>OrderApi__Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/OrderApi__Sales_Order_Line__c/fields/PO_ID__c.field-meta.xml
<CustomField>
    <fullName>PO_ID__c</fullName>
    <formula>Sponsoring_Relationship__r.PO_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PO ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PagesApi__Site__c/PagesApi__Site__c.object-meta.xml
<CustomObject>
    <description>Sites are a collection of Pages published and hosted natively on the Force.com platform.</description>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PagesApi__Site__c/fields/OrderApi__Business_Group__c.field-meta.xml
<CustomField>
    <fullName>OrderApi__Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Group</label>
    <referenceTo>OrderApi__Business_Group__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PagesApi__Site__c/fields/PagesApi__Is_Default__c.field-meta.xml
<CustomField>
    <fullName>PagesApi__Is_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The default site for a given community. Only one site can be default for a community.</description>
    <inlineHelpText>The default site for a given community. Only one site can be default for a community.</inlineHelpText>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/GetSponsoredBillingInvoiceController.cls
global without sharing class GetSponsoredBillingInvoiceController {
    List<OrderApi__Sales_Order_Line__c> sol = new List<OrderApi__Sales_Order_Line__c>();
    OrderApi__Sales_Order__c so = new OrderApi__Sales_Order__c();
    OrderApi__Business_Group__c co = new OrderApi__Business_Group__c();
	OrderApi__Sales_Order_Line__c disc = new OrderApi__Sales_Order_Line__c();
    Decimal solTotal = 0;
    
    global GetSponsoredBillingInvoiceController() {
        String soID = Apexpages.currentPage().getparameters().get('id'); 
        //Apexpages.currentPage().getHeaders().put('content-disposition', 'attachment; filename=invoice-'+soID+'.pdf');
        
        so  = [Select Id,Name,Invoice_Number__c,PO_ID__c,OrderApi__Business_Group__r.Id,OrderApi__Description__c,Invoice_Term__c,Invoice_Total__c,OrderApi__Overall_Total__c,OrderApi__Customer_Link__c,Contact_Name__c,OrderApi__Billing_Street__c,Address__c,FON_Billing_Type__c from OrderApi__Sales_Order__c where Id =: soID];
        
        String bid;
        
        bid = so.OrderApi__Business_Group__r.Id;
        
        // Get site
        if(String.isBlank(bid) == true){
        	String siteId = Site.getSiteId();
        	bid = [SELECT OrderApi__Business_Group__r.Id FROM PagesApi__Site__c WHERE PagesApi__Is_Default__c = true LIMIT 1].OrderApi__Business_Group__r.Id;
        }
        co = [SELECT OrderApi__Display_Name__c,OrderApi__Email__c,OrderApi__Phone__c,OrderApi__Homepage_URL__c FROM OrderApi__Business_Group__c WHERE id = : bid];
        
       
        for (OrderApi__Sales_Order_Line__c a : [SELECT OrderApi__Item__c,Membership_Date__c,FON_Sponsored_Account__c,PO_ID__c,Primary_R_T__c,Invoice_Subscription__c,Annual_Dues__c,Amount_Invoiced__c,OrderApi__Overall_Total__c,Volume__c FROM OrderApi__Sales_Order_Line__c where OrderApi__Sales_Order__c =: soID AND OrderApi__Item__r.Name != 'Discount' ORDER BY FON_Sponsored_Account__c ASC]) {
            sol.add(a);
            solTotal = solTotal + a.OrderApi__Overall_Total__c;
        }
        
        List<OrderApi__Sales_Order_Line__c> discs = [SELECT OrderApi__Item__c,Membership_Date__c,FON_Sponsored_Account__c,PO_ID__c,Primary_R_T__c,Invoice_Subscription__c,Annual_Dues__c,Amount_Invoiced__c,OrderApi__Overall_Total__c,Volume__c FROM OrderApi__Sales_Order_Line__c where OrderApi__Sales_Order__c =: soID AND OrderApi__Item__r.Name = 'Discount' LIMIT 1];
        if(discs.size()>0){
            disc = discs[0];
        }
    }

    global List<OrderApi__Sales_Order_Line__c> getSOL() {
        return sol;
    }
    global OrderApi__Sales_Order__c getSO() {
        return so;
    }
    global OrderApi__Business_Group__c getCO() {
        return co;
    }
    global OrderApi__Sales_Order_Line__c getDISC() {
        return disc;
    }
    global Decimal getSOLTOTAL() {
        return solTotal;
    }
}